[IMP] CRM: Inactive lost leads
odoo/documentation pull request #10065
Opened 2024-07-03 18:15 UTC by pabr-odoo

Task: https://www.odoo.com/odoo/my-tasks/4013046

Adding as small note admonition explaining how to mark an inactive lead as lost.

2024-07-03 18:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10065.png)](https://mergebot.odoo.com/odoo/documentation/pull/10065)

2024-07-03 18:24 UTC, pabr-odoo commented
Hey @StraubCreative tagging you in for first review on this small addition when you get the chance. Thanks!

2024-07-08 19:11 UTC, StraubCreative requested changes
Hi @pabr-odoo 
Quick suggestion for you below, can you confirm please?
If correct, let's make any necessary changes and then we can pass to tech review, ty!

2024-07-08 19:11 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/lost_opportunities.rst
> +
>    Only *active* opportunities can be marked as *Won* or *Lost*.

Just confirmed in runbot— I don't think this is true, as I was able to mark an inactive lead as Lost.

>    The :guilabel:`Lost` button can now be used to mark the opportunity as lost.

The **Lost** button will only appear again if the opp is unarchived. Setting the prob % to 0 automatically marks it as lost.

```suggestion
   To mark an *inactive* (archived) opportunity as lost, set the :guilabel:`Probability` field to `0` percent.
```

2024-07-08 20:27 UTC, StraubCreative approved these changes
LGTM! 
@samueljlieber you're up for quick tech review, thanks!

2024-07-08 21:12 UTC, samueljlieber approved these changes
Thanks for this quick improvement PR @pabr-odoo, looks good to me 👍
..
@robodoo r+

2024-07-08 23:53 UTC, closed without merging