[MOV] ecommerce: moving page
odoo/documentation pull request #10227
Opened 2024-07-16 13:35 UTC by Donapi

2024-07-16 13:35 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10227.png)](https://mergebot.odoo.com/odoo/documentation/pull/10227)

2024-07-16 14:21 UTC, auva-odoo requested changes
Hi @Donapi! I noticed two small issues:
- There's a double h1 (see my comment in the review).
- It looks like the redirect from managing_products to products might have been missed.
I also suggest changing the PR name slightly to include the page you moved. Since you'll be moving a lot of pages while restructuring the commerce doc, this will help keep things organized better.
Thanks!

2024-07-16 14:21 UTC, auva-odoo commented on content/applications/websites/ecommerce/products.rst
>  ==================
Did you mean to remove this? There are currently 2 h1 in this rst ...

2024-07-16 14:53 UTC, ksc-odoo approved these changes
Apart from the one comment I left (which supported @auva-odoo 's original comment), this one looks ready to go. Approving now. 👍

2024-07-16 14:53 UTC, ksc-odoo commented on content/applications/websites/ecommerce/products.rst
>  ==================
```suggestion
Product management
==================
```
I agree with @auva-odoo ... this is how this header should be formatted in this case

2024-07-17 10:39 UTC, auva-odoo commented on redirects/17.0.txt
> +applications/websites/ecommerce/managing_products/products.rst applications/websites/ecommerce/products.rst
Sorry if I wasn't clear earlier: You need to add one for each of the sub-pages as well (catalog, variants, etc.)

2024-07-18 09:08 UTC, auva-odoo approved these changes
@robodoo r+

2024-07-18 11:30 UTC, closed without merging