[IMP] sms marketing: restructure/add cards/remove essen.
odoo/documentation pull request #10277
Opened 2024-07-19 16:21 UTC by ksc-odoo

In an effort to clean up the look (and feel) of the Marketing scope of applications, I am creating this PR to remove the 'essentials' and 'Pricing and FAQ' subsections , add intro content to the main SMS Marketing element on the toctree, add some linked cards to the main SMS documentation page (like Email Marketing, Events, etc.). 

Not only does this help everything appear uniform, but adds a much-needed level of organization and eases the navigability of the documentation.

And, just like the Events doc, I am *also* adding individual sections (w/ accompanying explanations and links) to the other pages in the scope.

**I PLAN ON UPDATING ALL CONTENT **AFTER** THIS PR (which sets up the new structure and layout)**
This PR is **purely** about structure and the addition of cards

PROJECT TASK: https://www.odoo.com/odoo/project/3835/tasks/4063869?cids=3

2024-07-19 16:22 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10277.png)](https://mergebot.odoo.com/odoo/documentation/pull/10277)

2024-07-19 16:34 UTC, ksc-odoo commented
Hey @Felicious -- this is ready for a quick Peer Review from you (whenever you get a chance). Thanks! 👍 🙏

2024-07-22 20:42 UTC, Felicious requested changes
It's great that you're doing the restructure for these SMS Marketing docs, @ksc-odoo !

While the rewrite is good, I found a couple outdated screenshots and opportunities to expand on existing fields. After you address those, tag me again and I'll be happy to look at the PR again!

2024-07-22 21:02 UTC, Felicious approved these changes
@ksc-odoo just let me know that this PR is purely just moving content around! Whoops! Since there are no build issues and the structure of the content looks good, approving this now :D

2024-07-23 21:17 UTC, ksc-odoo commented
Thank you SO MUCH for the insightful (and super helpful) feedback, @Felicious -- and, yes, as we discussed, this is purely a restructure doc -- and I will be tackling updates for the individual docs in the very near future. Also, thanks to your help, I made sure to add the necessary redirect to this PR, so everything *should* be good to go. 

@StraubCreative / @samueljlieber this is ready for a Final/Tech review, whenever you get a chance. Thanks! 🙏

2024-07-26 20:34 UTC, samueljlieber requested changes
Hi @ksc-odoo! Nice work on this restructure, I only have a couple comments! I know these are a big lift 💪

Also please update the commit message to be more succinct: 
`git commit --amend`
```
[REF] sms marketing: remove essentials and pricing
```
Requesting changes so I can  double check redirects, tag me for one more quick look!

Thank you!

2024-07-26 20:34 UTC, samueljlieber commented on content/applications/marketing/sms_marketing.rst
> +      Discover how to create and customize SMS marketing campaigns for any occassion with Odoo.
Typo
```suggestion
      Discover how to create and customize SMS marketing campaigns for any occasion with Odoo.
```

2024-07-26 20:34 UTC, samueljlieber commented on redirects/17.0.txt
> +applications/marketing/sms_marketing/essentials.rst applications/marketing/sms_marketing.rst 								  # /marketing/sms_marketing/essentials --> /marketing/sms_marketing
Need to add redirects for all moved and deleted files :)

Also please only use spaces, never tabs, for spacing and indenting in `.rst` and redirect `.txt` files :)
```suggestion
applications/marketing/sms_marketing/essentials.rst applications/marketing/sms_marketing.rst                                                              # /marketing/sms_marketing/essentials --> /marketing/sms_marketing
applications/marketing/sms_marketing/essentials/sms_essentials.rst applications/marketing/sms_marketing.rst                                               # /marketing/sms_marketing/essentials --> /marketing/sms_marketing
applications/marketing/sms_marketing/essentials/sms_campaign_settings.rst applications/marketing/sms_marketing.rst                                        # /marketing/sms_marketing/essentials --> /marketing/sms_marketing
applications/marketing/sms_marketing/essentials/mailing_lists_blacklists.rst applications/marketing/sms_marketing/mailing_lists_blacklists.rst            # /marketing/sms_marketing/essentials --> /marketing/sms_marketing
applications/marketing/sms_marketing/pricing.rst applications/marketing/sms_marketing/pricing_and_faq.rst                                                 # /marketing/sms_marketing/pricing --> /marketing/sms_marketing
applications/marketing/sms_marketing/pricing/pricing_and_faq.rst applications/marketing/sms_marketing/pricing_and_faq.rst                                 # /marketing/sms_marketing/pricing --> /marketing/sms_marketing
```

2024-08-01 22:23 UTC, ksc-odoo commented
I made those suggested adjustments, and *believe* 🤞 this one is now ready for another look from you, whenever you get a chance. Thanks for all the awesome help! 🙏 👍

2024-08-01 22:37 UTC, ksc-odoo commented
@samueljlieber just noticed I got a build error on this one, but I'm not quite sure how to resolve it. Any expert guidance or tips would be greatly appreciated (as always 🙏 )

2024-08-02 13:38 UTC, samueljlieber approved these changes
Hey @ksc-odoo, these redirects look good, just need to remove this line left over from a conflict. 

LMK if you have any questions! Thanks!
...
@robodoo delegate=ksc-odoo

2024-08-02 13:38 UTC, samueljlieber commented on redirects/17.0.txt
> +<<<<<<< HEAD
Somehow this ended up in the redirect file, likely left over from resolving a conflict :)
```suggestion
```

2024-08-02 15:05 UTC, ksc-odoo commented
@robodoo r+

2024-08-02 21:16 UTC, closed without merging