[ADD] Subscriptions: Wire transfer
odoo/documentation pull request #10276
Opened 2024-07-19 16:00 UTC by pabr-odoo

Task card: https://www.odoo.com/odoo/project/3835/tasks/4063978?cids=3

Adding a new document in subscriptions for the wire transfer payment provider. This is part of the larger ﻿[invoicing methods](https://github.com/odoo/project.task/4038566?cids=3)﻿ task for Subscriptions.

2024-07-19 16:01 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10276.png)](https://mergebot.odoo.com/odoo/documentation/pull/10276)

2024-07-19 16:20 UTC, pabr-odoo commented
Hey @Felicious this new doc is ready for first review whenever you get the chance. Thanks!

2024-07-20 01:01 UTC, Felicious approved these changes
Great job with this doc @pabr-odoo !

Your writing is clear, concise, and amazing! 😊 The flows worked perfectly. I just have a few minor suggestions for you to consider. Once you've had a look, feel free to pass it on to the next stage!

2024-07-22 19:16 UTC, pabr-odoo commented
Hey @ksc-odoo this is ready for final content review when you get the chance. Thanks!

2024-07-22 21:16 UTC, ksc-odoo requested changes
Hey there, @pabr-odoo -- just finished my Final Review of this PR. Nice work. Great attention to detail. There are a decent amount of comments/suggestions/feedback that require your attention, so if you could address those, and tag me again for another quick look -- that would be great. Thanks! 👍

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +the form.
Do you think it's worth mentioning that when Test Mode is selected, the method becomes 'Unpublished'?

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +   By default, the payment provider remains **unpublished** in test mode so that it is not visible
```suggestion
   By default, the payment provider remains :guilabel:`Unpublished` in :guilabel:`Test Mode`, so it is not visible
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +   It is recommended to use test mode on a duplicate or a test database to avoid potential issues
```suggestion
   It is recommended to use the :guilabel:`Test Mode` setting on a duplicate (or a test) database to avoid potential issues
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +With wire transfers :ref:`enabled and published <wire_transfer/configuration>`, customers will see
```suggestion
With wire transfers :ref:`enabled and published <wire_transfer/configuration>`, customers see
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +the purchase is confirmed, a sales order is created.
```suggestion
wire transfers as an available payment method at checkout when purchasing a product.

When this method is selected by a customer, they are shown the *Pending Message* set in the :ref:`wire
transfer configuration page <wire_transfer/configuration>` after confirming their purchase. Once
the purchase is confirmed, a sales order is created.
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +   received, *and* the order confirmed manually using the :guilabel:`Confirm` button on the sales
```suggestion
   received, *and* the order is confirmed manually, using the :guilabel:`Confirm` button on the sales
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +To begin processing the payment, navigate to :menuselection:`Sales app --> Orders --> Orders` and
```suggestion
To begin processing the payment, navigate to :menuselection:`Sales app --> Orders --> Orders`, and
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +Next, click the new :guilabel:`Create Invoice` button, then choose :guilabel:`Regular invoice` and
```suggestion
Next, click the new :guilabel:`Create Invoice` button, then choose :guilabel:`Regular invoice`, and
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +pop-up window is revealed with an email template configured and a PDF invoice attached.
```suggestion
pop-up window appears, with an email template configured, and a PDF invoice attached.
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +disappears and the :guilabel:`Send & Print` button turns gray to show the invoice has been sent.
```suggestion
disappears, and the :guilabel:`Send & Print` button turns gray to show the invoice has been sent.
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +click the corresponding sales order. A green :guilabel:`In Progress` banner appears in the
During my run-through, I wasn't seeing this 'In Progress' banner -- might be worth a quick double-check during your revisions.

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +Now click the :guilabel:`Register payment` button on the invoice page. A pop-up window titled
```suggestion
Next, click the :guilabel:`Register payment` button on the invoice page. A pop-up window titled,
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +:guilabel:`Register Payment` is revealed with options for selecting the type of payment. In the
```suggestion
:guilabel:`Register Payment` appears, with options for selecting the type of payment. In the
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +field to the right of :guilabel:`Journal`, type `Bank` or select it from the drop-down menu. Next,
```suggestion
:guilabel:`Journal` field, select :guilabel:`Bank` from the drop-down menu. Next,
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +set :guilabel:`Payment Method` to `Manual`. Ensure :guilabel:`Amount` and :guilabel:`Payment Date`
```suggestion
set the :guilabel:`Payment Method` to :guilabel:`Manual`. Ensure the :guilabel:`Amount` and :guilabel:`Payment Date`
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +The customer invoice is revealed with a green :guilabel:`In payment` banner in the upper-right
```suggestion
The customer invoice is revealed with a green :guilabel:`In Payment` banner in the upper-right
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +   be registered in Odoo by clicking the :guilabel:`Register Payment` button and creating the
```suggestion
   be registered in Odoo by clicking the :guilabel:`Register Payment` button, and creating the
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +   payment *before* clicking :guilabel:`Send & Print`. Now when an invoice is sent using the
```suggestion
   payment *before* clicking :guilabel:`Send & Print`. Now, when an invoice is sent using the
```

2024-07-22 21:16 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +   stating that the invoice is already paid.
```suggestion
   stating the invoice is already paid.
```

2024-07-24 22:03 UTC, pabr-odoo commented
Hey @ksc-odoo thanks so much for the thorough review. Just finished implementing your changes, so feel free to give it another look whenever you get the chance. Thank you!

2024-07-25 16:03 UTC, ksc-odoo approved these changes
hey @pabr-odoo -- great work on implementing those changes. Just a have a small collection of additional feedback that requires your attention. Once you make those necessary modifications, feel free to tag this for Tech Review. Thanks! 👍

2024-07-25 16:03 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +:guilabel:`Register Payment` appears, with options for selecting the type of payment. In the
```suggestion
:guilabel:`Register Payment`, appears with options for selecting the type of payment. In the
```

2024-07-25 16:03 UTC, ksc-odoo commented on content/applications/sales/subscriptions/payment_providers/wire_transfer.rst
> +   :guilabel:`Send & Print` button, a new line is automatically added to the invoice message
```suggestion
   :guilabel:`Send & Print` button, a new line is automatically added to the invoice message,
```

2024-07-25 16:20 UTC, pabr-odoo commented
Hey @StraubCreative this doc is ready for tech review whenever you get the chance. Thanks!

2024-07-26 21:14 UTC, samueljlieber requested changes
Hey @pabr-odoo! Amazing work documenting the wire transfer configuration, testing, and processing! 

Before I give a full review I want to discuss moving all of this content over to the existing **Finance > Online payments >** [Wire transfers](https://www.odoo.com/documentation/17.0/applications/finance/payment_providers/wire_transfer.html) documentation, since this content doesnt seem to be Subscriptions specific, but general to all online payments, is that correct?

If so, I think this content would fit better improving the existing doc, especially since there isnt much information there to being with. 

Let me know your thoughts, and @StraubCreative if you have any too, thank you!

2024-07-26 21:48 UTC, StraubCreative commented
> Let me know your thoughts, and @StraubCreative if you have any too, thank you!

I think it's worth a look on another PR simply to avoid scope creep, where we can pick/choose what content to merge into the other doc under Finance as a separate todo. For now since the current Task was brought up under the scope of Subscriptions, we can proceed with review + merge and then revisit after on a REF PR.

If you agree @samueljlieber please proceed with tech review or we can discuss. Ty either way for starting the convo 🤙

2024-07-29 16:02 UTC, samueljlieber approved these changes
Hi @pabr-odoo! I finished my technical review, and dont have many changes! Nice work on this PR :).

Approving with a couple updates to custom anchors just to stick to the convention. Thank you for your work!
.....
@robodoo delegate=pabr-odoo

2024-07-29 17:37 UTC, pabr-odoo commented
@robodoo r+

2024-07-29 19:38 UTC, closed without merging