[IMP] website: landing page
odoo/documentation pull request #10341
Opened 2024-07-25 12:34 UTC by masp-odoo

taskID-3710109

2024-07-25 12:35 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10341.png)](https://mergebot.odoo.com/odoo/documentation/pull/10341)

2024-08-02 06:55 UTC, auva-odoo requested changes
Hi @masp-odoo! After discussing this with Xavier, we think it would be best if the main application page included a brief introduction, followed by either very simple cards like this https://www.odoo.com/documentation/master/applications/finance/accounting.html or actual content when possible (which isn’t the case here). The goal should be to inform, not to sell the product, as that's covered on the app-specific pages on odoo.com. So, no marketing language —maybe just a tiny bit in the introduction to highlight key features, but always in an objective way (e.g., "user-friendly" is fine). I didn't add suggestions for changing the cards but it shouldn't take long I think.

I've added a few comments in my review as well 😊

Sorry about this! I wasn't sure which direction to take after our last conversation, as it's been a long, long time since someone reviewed or created a main application page. I definitely think we should do it for all pages, so we don't end up with "empty" TOC tree items or ugly-looking pages. Thank you for starting that process :slightly_smiling_face:

2024-08-02 06:55 UTC, auva-odoo commented on content/applications/websites/website.rst
> +:abbr:`SEO (Search Engine Optimization)`.
```suggestion
**Odoo Website** offers a user-friendly platform for creating and managing your website. It includes a variety of tools and features to help you design, publish, and maintain web pages without needing advanced technical skills. You can easily customize layouts, add multimedia content, and integrate with other Odoo apps to expand your website's functionality. 
```
You can of course tweak this, it was just easier for me to illustrate what we're aiming for using an example :slightly_smiling_face:

2024-08-02 06:55 UTC, auva-odoo commented on content/applications/websites/website.rst
> +   .. card:: Webdesign
```suggestion
   .. card:: Web design
```
Both options are correct, but since we've been using the two-word version, I suggest we stick with that.

2024-08-02 06:55 UTC, auva-odoo commented on content/applications/websites/website.rst
>  .. important::
I know you didn't change it but I don't think it needs to be an "important" admonition. It could be a note or a tip instead?

2024-08-06 07:59 UTC, masp-odoo commented
Dear @auva-odoo, thanks for your feedback! I updated it in this direction, what do you think?

2024-08-08 07:27 UTC, auva-odoo requested changes
@masp-odoo another little review as discussed :slightly_smiling_face: Let me know what you think!

2024-08-12 09:18 UTC, auva-odoo approved these changes
@robodoo r+

2024-08-12 10:59 UTC, closed without merging