[ADD] l10n_pe: eCommerce electronic invoicing
odoo/documentation pull request #10495
Opened 2024-07-31 23:13 UTC by gmz-odoo

- Add new section for **eCommerce Functionality starting Odoo17+**
- Section will be display after the “_Guía de entrega electrónica 2.0”_ menu with the similar hierarchy
- **Pictures** on shared folder: https://drive.google.com/drive/folders/1fDgPxJFOpesZrkE3TsaOytDIOT0OW9Cf?usp=sharing

2024-07-31 23:13 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10495.png)](https://mergebot.odoo.com/odoo/documentation/pull/10495)

2024-08-02 17:48 UTC, samueljlieber approved these changes
Hi @gmz-odoo! Thanks for your work on this PR! I went ahead and added some of the images you provides as well as made some technical revisions on the RST added in this PR.

I left some images out that I felt where unnecessary, to help cut down on the overall number of images in this document, as well we are trying to not use markup in images wherever possible :)

Please review and let me know if you have any additional changes! Thank you!
Built documentation for this PR: https://runbot163.odoo.com/runbot/static/build/66422323-17-0/logs/build/html/applications/finance/fiscal_localizations/peru.html#ecommerce-electronic-invoicing

2024-08-02 18:08 UTC, gmz-odoo commented
@samueljlieber 
AMAZING, I just had a look, and I think we are ready to go!
![image](https://github.com/user-attachments/assets/f57593f8-e009-47d9-9e2c-49f89007272e)

Thanks so much for your help =]

2024-08-08 14:03 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/peru.rst
> +enables the purchase to conclude in the corresponding electronic document.
```suggestion
enables the purchase to create the corresponding electronic document.
```

2024-08-08 14:05 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/peru.rst
> +and PDF directly from the portal view.
```suggestion
Once the invoice is validated with |SUNAT|, the user can download the :file:`.zip` with the CDR,
XML, and PDF directly from the portal view by clicking the :guilabel:`Download` button.
```

2024-08-08 14:19 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/peru.rst
> +and PDF directly from the portal view.
We're in the process of publishing new documentation guidelines, but one of the issues that we're implementing is to remove any markups from images. Also, we want the written documentation to be clear enough to stand on its own without screenshots, which it wasn't originally, but with the minor addition telling the user where to download the file, it should be clear enough to remove the screenshot.

2024-08-08 14:19 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/peru.rst
> +   :alt: Downloading electronic invoicing files from portal view.
```suggestion
```

2024-08-08 22:05 UTC, gmz-odoo commented
Hello team,

**_Thanks_** @dade-odoo for the improvements with Grammar and optimizing the structure as expected.

- In recap, if you consider that eliminating some screenshots is needed, I understand it.

- The idea of having them explicitly on the User Doc is because we just run into a lot of issues with Users not being as familiar with the Odoo interface  sometimes, so we wanted to make it extra clear to avoid time spent on tickets/calls for very basic use of fields, but it was with the aim of minimizing frequent questions/errors due clarity.

- Suggestions, changes and improvements made by @dade-odoo , look good to me, and I'll also consider it for some next sections to be added for this and other LATAM localizations.

Let me know if you happen to need anything else from my side, I appreciate your help with this task.

Cheers, happy MiniFriyayy  _(from the SF side)_
@samueljlieber

2024-08-13 14:33 UTC, samueljlieber commented
Thank you so much for your thorough review @dade-odoo! I implemented each of your suggestions in 8c5cd94. Thank you!

2024-08-27 12:50 UTC, dade-odoo approved these changes
Hey @gmz-odoo and @samueljlieber sorry for the delay! I was OOO. Looks great, passing on to the final review :)

2024-08-29 09:44 UTC, auva-odoo requested changes
Hello @gmz-odoo @samueljlieber thank you for your work on this! @gmz-odoo, I noticed that most configurations are already covered in the eCommerce documentation. To avoid duplicate content, we usually reference existing documentation rather than repeat it. Localization docs should focus on what's unique to that localization (or what isn't mentioned elsewhere in the documentation) since they're already quite extensive. I've added some suggestions in my review to adjust the PR accordingly. Thank you!

2024-08-30 11:34 UTC, auva-odoo commented
@robodoo r+

2024-08-31 12:14 UTC, robodoo commented
@gmz-odoo @auva-odoo staging failed: ci/runbot on bf8909d64710d8b5ce55c72316b44de291842e35 (view more at https://runbot.odoo.com/runbot/build/67586874)

2024-09-02 06:32 UTC, auva-odoo commented
@robodoo retry

2024-09-02 08:22 UTC, closed without merging