[IMP] CRM: update multiple sales teams doc
odoo/documentation pull request #1056
Opened 2021-07-02 22:22 UTC by vpk-odoo

Associated task: https://www.odoo.com/web#id=2588786&action=333&active_id=3835&model=project.task&view_type=form&cids=3&menu_id=4720

2022-04-26 23:17 UTC, meng-odoo requested changes
@StraubCreative Hi Zach! I made tons of changes to VPK's content on this doc, especially since you suggested I edit to make it shorter/clearer/more concise. Please let me know if you have any questions/comments about my changes below :) Thanks

2022-04-26 23:17 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +choose a color for your team as well as access the team configuration template.
Editing this entire paragraph for brevity.

`Clicking on the three dots in the corner of a tile opens a navigational menu that lets you quickly view documents or reports, create new quotations or opportunities, pick a color for this team, or access its configuration page.`

2022-04-26 23:17 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +take you directly to that team’s pipeline without having to access the Sales menu.
Editing this entire paragraph for brevity and accuracy.

`Clicking on the **Pipeline** button brings you directly to that team's CRM pipeline.`

2022-04-27 22:33 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +day period.
Yea reformatting entire block is fine. Made small grammar change from `30 day period` to `30-day period` (with hyphen).

2022-04-27 22:56 UTC, robodoo commented
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

2022-04-27 22:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1056).

2022-04-27 23:00 UTC, StraubCreative commented
Hi @meng-odoo 

Good first pass 👍  
I made all of the change requests you asked for which you can see in commit [8824706](https://github.com/odoo/documentation/commit/88247063f8867c403468aab6969df185a5937ae4)

For next round of review, I highly suggest reworking the tense and tone for the whole document, namely:
- there are a number of instances where verb tense is in _continuous_ present, where I think it would be more ideal to write in the _simple_ present instead (e.g. lines 56 and line 64, _clicking_ vs. _click_). While continuous present is _technically_ correct, I’d argue that this tense makes for more clunky sentence structures that don’t clearly communicate direct paths of action ([guidelines reference on tense]( https://www.odoo.com/documentation/15.0/contributing/documentation/content_guidelines.html#grammatical-tenses))
- there’s a lot of 2nd person familiar pronouns in this doc (e.g. you, your)…can we clean these up a bit so it sounds less accusatory and more instructional? We’ll especially want to remove these in headings per [guidelines on headings](https://www.odoo.com/documentation/15.0/contributing/documentation/content_guidelines.html#titles-and-headings).

Looking forward to your thoughts and further improvements as you see fit!

2022-04-28 01:46 UTC, meng-odoo requested changes
@StraubCreative Hi Zac! Thanks for your feedback on my first review--I'll keep all of that in mind when writing my future reviews as well.

I think this one makes a lot of improvements :) Please let me know if you have any more suggestions.

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +monthly revenue targets they need to achieve.
Removing "you" and improving wording

`Set a *Domain* to assign leads/opportunities to this Sales Team based on specific filters, such as country, language, or campaign. Set an *Invoicing Target* if this team has specific monthly revenue goals.`

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +Add members to your Sales Team
Removing "you"

`Add members to a Sales Team`

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +maximum number of leads that they can be assigned in a 30-day period.
Removing "you" and improving wording/tense

`To add team members, click **Add** under the Assignment tab when editing the Sales Team's configuration page. Select a salesperson from the dropdown menu or create new salesperson. Set a maximum number of leads that can be assigned to this salesperson in a 30-day period to ensure that they do not overwork.`

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +easily check all of the pipelines they need access to.
Removing "you" and improving wording

`One person can be added as a team member or Team Leader to multiple Sales Teams, allowing them to
access all of the pipelines that they need to.`

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +To view your Sales Team dashboard, go to :menuselection:`CRM --> Configuration --> Sales Teams`. Any
Removing "you"

`To view the Sales Team dashboard, go to :menuselection:CRM --> Configuration --> Sales Teams. Any`

Please note that I removed the backticks around the menuselection items in my corrected quote.

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +Clicking on the three dots in the corner of a tile opens a navigational menu that lets you quickly
Improving tense

`Click on the three dots in the corner of a tile to open a navigational menu that lets you quickly`

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +Clicking on the **Pipeline** button brings you directly to that team's CRM pipeline.
Improving tense

`Click on the **Pipeline** button to go directly to that team's CRM pipeline.`

2022-04-28 01:46 UTC, meng-odoo commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +To create a new *Sales Team*, go to :menuselection:`CRM --> Configuration --> Sales Teams` then
I don't think this instance of "Sales Team" needs to be italicized. Let's italicize it once at the very beginning for emphasis/understanding, then leave it unitalicized but capitalized in the rest of the doc.

`To create a new Sales Team, go to :menuselection:CRM --> Configuration --> Sales Teams then`

Please note that I removed the backticks around the menuselection items in my corrected quote.

2022-04-29 20:02 UTC, StraubCreative commented
@meng-odoo 
Second pass changes were great! Doc sounds a lot more confident, instructional, and easier to read imo.
Please find your change requests on latest commit [e8d2765](https://github.com/odoo/documentation/commit/e8d2765440336f589ab3e3961f58f85adfa28269) and let me know if we need anything else, otherwise we can pass over to Doc Review :)

2022-05-05 00:17 UTC, meng-odoo approved these changes
@StraubCreative Thanks Zac! Everything looks good to me. I'll go ahead and tag Doc Review :)

2022-05-05 08:20 UTC, AntoineVDV approved these changes
Perfect! :ok_hand: 

@robodoo r+

2022-05-05 09:00 UTC, robodoo commented
Because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2022-05-05 09:27 UTC, AntoineVDV commented
@meng-odoo @StraubCreative could you just squash the two commits into one so that the PR can be merged?

2022-05-06 17:50 UTC, StraubCreative commented
> @meng-odoo @StraubCreative could you just squash the two commits into one so that the PR can be merged?

Should be good to go @AntoineVDV 🚀

2022-05-09 09:26 UTC, closed without merging