[FIX] bill_configuration.rst: remove paragraph talking about routings…
odoo/documentation pull request #1057
Opened 2021-07-05 04:33 UTC by Danisan

[FIX] bill_configuration.rst: remove paragraph talking about routings. Replace it with operations.
Add timer and add locking quantities section.
Add images with configuration options.

2021-07-09 13:09 UTC, jcs-odoo requested changes
@Lau-Odoo can you do a review please?
Also, is this only for v14?

a few points about the images already:
- the resolution of the images is way too high. You could shrink to 50%
- [compress them with pngquant](https://www.odoo.com/documentation/14.0/contributing/documentation.html#pngquant)
- [use alt tags](https://www.odoo.com/documentation/14.0/contributing/documentation/content_guidelines.html#alt-tags)
- put them in the right [media folder] (https://www.odoo.com/documentation/14.0/contributing/documentation/content_guidelines.html#media-files) and name the files with words rather than numbers. (you could also move the old media files in this doc to the new media folder
- [align the indentation](https://www.odoo.com/documentation/14.0/contributing/documentation/rst_guidelines.html#be-consistent-with-indentation) of for the images options

Also:
- [break the lien at 100th character](https://www.odoo.com/documentation/14.0/contributing/documentation/rst_guidelines.html#start-a-new-line-before-the-100th-character)

2022-04-13 23:27 UTC, weka-odoo requested changes

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +Adding the timer to work orders
Title is misleading - the timer is already a feature of the work orders, not something you can add on?

Maybe change to "Timing your work orders"

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +Adding the timer to work orders
Adding a timer to work orders

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +You can add a timer to your work orders. This consists of tree buttons that
"You can time your work orders using buttons that allow you to start, pause, or block each operation. Using these buttons will register the duration of each operation in real time."

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +You can add a timer to your work orders. This consists of tree buttons that
"The timer consists of three buttons that allow you to start, pause, or block each operation and registers the real duration of each operation.

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +You will also see the timer, in the manufacturing orders, when clicking the
not sure if this sentence is necessary

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +You will also see the timer, in the manufacturing orders, when clicking the
not sure if this sentence is necessary

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +Enabling this option, you can define that manufacturing orders are locked by
Make sure to mention how/where to enable this option. 

i.e. "You can lock quantities to consume under Configuration > Settings.  Enabling this option will prevent manufacturing users from modifying quantities of components to consume."

2022-04-13 23:27 UTC, weka-odoo commented on content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
> +Enabling this option, you can define that manufacturing orders are locked by
Make sure to mention how/where to enable this option. 

i.e. "You can lock quantities to consume under Configuration > Settings.  Enabling this option will prevent manufacturing users from modifying quantities of components to consume."

2023-05-10 05:16 UTC, jcs-odoo commented
Hi,

I'm closing this old pull request as I see this file has been updated several times since then.

cc @Felicious @brse-odoo @hojo-odoo If this may be of interest for you, feel free to reopen this PR.

Thanks and have a good day!

2023-05-10 05:16 UTC, closed without merging