[FIX] remove vantiv integration
odoo/documentation pull request #10828
Opened 2024-08-21 16:02 UTC by dikd-odoo

2024-08-21 16:03 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10828.png)](https://mergebot.odoo.com/odoo/documentation/pull/10828)

2024-08-21 18:06 UTC, dikd-odoo commented
Hi @samueljlieber this PR is ready for technical review, when you have a chance! This is the revised master PR from #10429 and #10426 to remove the Vantiv POS terminal from 17.5+. Thank you again for your help on this!

2024-08-28 15:31 UTC, samueljlieber requested changes
Hi @dikd-odoo! 
Thank you for re-opening this PR on master! I have just a couple quick technical fixes, and we should be good to go!

Please correct the following and tag me once more for another quick look. Thank you!

Please update the commit message to follow [the convention](https://github.com/odoo/documentation/blob/master/commit_template.txt) (missing the app/module)
Can use: `git commit --amend`
```
[IMP] pos: remove vantiv integration
```

Thank you for your work!

2024-08-28 15:31 UTC, samueljlieber commented on content/applications/sales/point_of_sale/payment_methods/terminals/payment-terminals.png
Please reduce this image width to be at or below 933px, as well as please compress this image with pngquant :)

2024-08-28 15:31 UTC, samueljlieber commented on redirects/17.0.txt
> +applications/sales/point_of_sale/payment_methods/terminals/vantiv.rst applications/sales/point_of_sale/payment_methods/terminals.rst		#remove vantiv integration
Nitpick for the redirect comment :) I suggest we stick with the existing convention of describing the redirect using arrows
```suggestion
applications/sales/point_of_sale/payment_methods/terminals/vantiv.rst applications/sales/point_of_sale/payment_methods/terminals.rst		# terminals/vantiv --> terminals
```

2024-08-28 17:50 UTC, dikd-odoo commented
Hi @samueljlieber thank you so much for your review and also helping me with merge conflicts! I implemented your changes, this is ready for another look when you have a chance. Thanks again!

2024-08-29 10:50 UTC, closed without merging