[ADD] l10n_in_reports: add profit and loss report (India)
odoo/documentation pull request #10866
Opened 2024-08-29 06:08 UTC by nash-odoo

In this PR, added the profit and loss report with opening and closing stock.

**task**-4143190

2024-08-29 06:09 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/10866.png)](https://mergebot.odoo.com/odoo/documentation/pull/10866)

2024-08-29 11:16 UTC, dade-odoo requested changes
Hey @nash-odoo thanks for the addition! Just a few minor capitalization/formatting comments. Once they're resolved I'll pass you on to the final review and r+ :)

2024-08-29 11:16 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/india.rst
> +This is a :guilabel:`Profit & Loss` report that displays the balances for **Opening Stock** and
```suggestion
This is a :guilabel:`Profit and Loss` report that displays the balances for **Opening Stock** and
```

2024-08-29 11:16 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/india.rst
> +Cost of Goods (i.e Opening Stock + Purchases During the Period - Closing Stock).
```suggestion
**Closing Stock**. It helps users using Continental accounting to accurately determine the cost of
goods (i.e :guilabel:`Opening Stock` + purchases during the period - :guilabel:`Closing Stock`).
```

2024-08-29 12:02 UTC, dade-odoo approved these changes

2024-08-29 14:07 UTC, auva-odoo requested changes
Hi @nash-odoo thank you for your work! It looks like the PNG file wasn’t compressed. Could you please take care of that when you get a chance? Thanks!

2024-08-30 05:07 UTC, nash-odoo commented
Hi @auva-odoo, I compressed the image.
Thanks for the review :blush:

2024-08-30 06:04 UTC, auva-odoo approved these changes
Thank you @nash-odoo! You can r+ whenever you're ready :slightly_smiling_face: 
@robodoo delegate+

2024-08-30 06:23 UTC, nash-odoo commented
@robodoo r+

2024-08-30 09:07 UTC, closed without merging