[IMP] accounting: cash register page in POS
odoo/documentation pull request #11038
Opened 2024-09-17 09:45 UTC by afma-odoo

task-3721929

2024-09-17 09:45 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11038.png)](https://mergebot.odoo.com/odoo/documentation/pull/11038)

2024-09-18 06:45 UTC, auva-odoo requested changes
Just a small suggestion @afma-odoo :slightly_smiling_face:

2024-09-18 06:45 UTC, auva-odoo commented on content/applications/sales/point_of_sale.rst
> +your screen.
```suggestion
To add or take out cash to/from the register, click :guilabel:`Cash In/Out` on the upper left side of
the screen.
```

2024-09-18 07:15 UTC, afma-odoo commented on content/applications/sales/point_of_sale.rst
> +your screen.
@auva-odoo Thanks for the advice 😊

2024-09-18 09:25 UTC, auva-odoo approved these changes
@robodoo r+

2024-09-18 11:34 UTC, closed without merging