18.0 add worldline documentation edm
odoo/documentation pull request #11070
Opened 2024-09-23 14:53 UTC by Demesmaeker

[ADD] payment_providers/worldline

New payment provider, it's features, and how to set it up

task-3499275

See also:
- https://github.com/odoo/odoo/pull/175194

2024-09-23 14:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11070.png)](https://mergebot.odoo.com/odoo/documentation/pull/11070)

2024-10-08 11:25 UTC, auva-odoo requested changes
Hi @Demesmaeker thank you for your work on this! I've added some comments and suggestions to help clarify the documentation and align it with other payment provider docs like Razorpay and APS. 
Also, correct me if I'm wrong, but should we retarget this PR to 18? That might also resolve the ci/minimal check issue I think? Don't hesitate if you have any questions (or if you'd prefer I do the changes myself). Thanks again!

2024-10-08 11:25 UTC, auva-odoo commented on content/applications/finance/payment_providers/worldline.rst
> +.. _worldline/worldline:
I would change the name of this anchor to something more specific, e.g.,:
```suggestion
.. _worldline/API-user:
```

2024-10-08 11:25 UTC, auva-odoo commented on content/applications/finance/payment_providers/worldline.rst
> +
I would add an anchor here so we can use it in the Odoo section

2024-10-08 11:25 UTC, auva-odoo commented on content/applications/finance/payment_providers/worldline.rst
> +these to set up your provider.
```suggestion
#. Go to :menuselection:`Developer --> Webhooks` and click on :guilabel:`Generate webhook keys`. Copy the :guilabel:`Webhook ID` and the associated :guilabel:`Secret webhook key` and save them for later.
```

2024-10-08 11:25 UTC, auva-odoo commented on content/applications/finance/payment_providers/worldline.rst
> +replaced by your database: `https://<example>/payment/worldline/webhook`.
Is this absolutely necessary? If so I would rephrase to make that clear (to me "you can" could be interpreted as "it's optional"):
```suggestion
#. Click :guilabel:`Add webhook endpoint`, enter your Odoo database's URL followed by `/payment/worldline/webhook` in the :guilabel:`Endpoint url` field, and :guilabel:`Confirm`. For example: `https://example.odoo.com/payment/worldline/webhook`.

```

2024-10-08 11:25 UTC, auva-odoo commented on content/applications/finance/payment_providers/worldline.rst
> +portal <worldline/worldline>`.
```suggestion
To set up Worldline in Odoo:
#. :ref:`Navigate to the payment provider Worldline <payment_providers/add_new>` and change its state to :guilabel:`Enabled`. 
#. In the :guilabel:`Credentials` tab, enter the :guilabel:`PSPID` of your Worldline account and fill in the :guilabel:`API Key`, :guilabel:`API Secret`, :guilabel:`Webhook Key`, and :guilabel:`Webhook Secret` with the values you saved at the step :ref:`Set up Worldline for Odoo <add the new anchor here>`. 
#. Configure the rest of the options to your liking.
```

2024-10-08 12:27 UTC, Demesmaeker reviewed
Hello @auva-odoo 
I rebased. I opened that PR before the freeze, knowing it would happen before we could merge, thus the branch name and wrong target. ^^

I push the changes I could, feel free to change and push after me, I only did the basis so that nothing would be openly wrong according to the code, but I might not be the clearest documentation wise '^^

2024-10-08 12:27 UTC, Demesmaeker commented on content/applications/finance/payment_providers/worldline.rst
> +
I don't know, there might be one, but not sure what we should put here instead '^^

2024-10-08 12:27 UTC, Demesmaeker commented on content/applications/finance/payment_providers/worldline.rst
> +:guilabel:`New User`. The following fields must be configured:
I used your suggestion with a general link =]

2024-10-08 13:07 UTC, AntoineVDV commented on content/applications/finance/payment_providers/worldline.rst
> +`Worldline <https://worldline.com/>`_, is a France-based company and the world's number 4 payments
```suggestion
`Worldline <https://worldline.com/>`_, is a France-based company and the world's number four payments
```

2024-10-08 13:07 UTC, AntoineVDV commented on content/applications/finance/payment_providers/worldline.rst
> +   - Specify a :guilabel:`UserID, `User's name, E-mail address`, and :guilabel:`Timezone` of your
Missing guilabels.

2024-10-08 13:07 UTC, AntoineVDV commented on content/applications/finance/payment_providers/worldline.rst
> +   - Enable :guilabel:`Special user for API`.
Make it a numbered list too.

2024-10-08 13:29 UTC, AntoineVDV approved these changes

2024-10-08 16:52 UTC, auva-odoo commented on content/applications/finance/payment_providers/worldline.rst
> +
@AntoineVDV any ideas here?

2024-10-09 15:18 UTC, AntoineVDV commented on content/applications/finance/payment_providers/worldline.rst
> +
I don't see the point in including this link; users who read the current documentation will already have a Worldline account.

2024-10-10 07:19 UTC, auva-odoo approved these changes
@robodoo r+

2024-10-10 10:01 UTC, closed without merging