[ADD] payment_providers: Nuvei
odoo/documentation pull request #11157
Opened 2024-10-08 21:36 UTC by andg-odoo

Documentation for Nuvei payment provider.

task-4172642

See also:
- https://github.com/odoo/odoo/pull/181459

2024-10-08 21:36 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11157.png)](https://mergebot.odoo.com/odoo/documentation/pull/11157)

2025-02-10 09:01 UTC, auva-odoo requested changes
Hello @andg-odoo and thank you for your work! I added a few comments and suggestions; feel free to reach out if you have any questions. (Apologies in advance if any of them are inaccurate; I wasn’t able to test the configuration myself, so it was a bit challenging.)

2025-02-12 00:22 UTC, andg-odoo commented
@auva-odoo Thanks for the review, I agree with you on all cases, and have updated the documentation as requested.

2025-02-14 11:51 UTC, auva-odoo approved these changes
Thank you for the changes @andg-odoo, I force-pushed a few additional (minor) ones, I hope you don't mind. Thanks again!

2025-02-14 16:26 UTC, andg-odoo commented
Thanks for the once over @auva-odoo, we were considering adding a table to the page showing what payment methods Nuvei supports in what specific countries, would something like this (Either top or bottom) fit the style: 
![image](https://github.com/user-attachments/assets/32a3e94c-c74f-4d56-b74b-d92f54940c00)


I'll try and get that written up today and push it.

2025-02-25 08:12 UTC, auva-odoo requested changes
Thanks for the update @andg-odoo! I added some suggestions for improvement.

2025-02-25 08:12 UTC, auva-odoo commented on content/applications/finance/payment_providers/nuvei.rst
> +====================
```suggestion
Payment methods
===============
```
I think you meant payment methods instead of providers? 
(And we use [sentence case in headings](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html))

2025-02-25 08:12 UTC, auva-odoo commented on content/applications/finance/payment_providers/nuvei.rst
> +listed below:
```suggestion
Most Nuvei payment methods are **region-specific**. The supported payment methods for each country are listed below:
```

2025-02-25 17:34 UTC, andg-odoo commented
@auva-odoo Thanks for the review, I have made the two adjustments.

2025-03-07 07:50 UTC, auva-odoo approved these changes
Thanks for the changes @andg-odoo ! 

@robodoo delegate+

2025-03-07 10:51 UTC, AntoineVDV commented on content/applications/finance/payment_providers/nuvei.rst
> +   Key` fields with the information saved at the step :ref:`payment_providers/nuvei/dashboard`.
I don't know if it's super relevant, but I'd swap these two steps, as switching to the "enabled" state marks required the fields to fill at step 2.

2025-03-07 19:10 UTC, andg-odoo commented on content/applications/finance/payment_providers/nuvei.rst
> +   Key` fields with the information saved at the step :ref:`payment_providers/nuvei/dashboard`.
Ordering swapped!

2025-03-17 09:51 UTC, AntoineVDV commented
@robodoo r+

2025-03-17 10:00 UTC, robodoo commented
@andg-odoo @AntoineVDV linked pull request(s) odoo/odoo#181459 not ready. Linked PRs are not staged until all of them are ready.

2025-03-17 15:15 UTC, closed without merging