[IMP]l10n_br: IAP Free Credits Clarification
odoo/documentation pull request #11216
Opened 2024-10-16 21:12 UTC by vbe-odoo

Odoo gives users 500 free IAP credits when they start with Odoo in BR in production databases. This is an important information that was not clarified.

2024-10-16 21:12 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11216.png)](https://mergebot.odoo.com/odoo/documentation/pull/11216)

2024-10-16 21:15 UTC, vbe-odoo commented
@samueljlieber not sure if you can help with this, or maybe pinging someone who can review this change?
Thanks!
cc' @ingo-odoo

2024-10-16 21:21 UTC, samueljlieber approved these changes
Looks good to me @vbe-odoo, approving with a small commit message update!

@odoo/localizations-doc-review this should be a quick one :)

2024-10-16 21:24 UTC, vbe-odoo commented
> Looks good to me @vbe-odoo, approving with a small commit message update!
> 
> @odoo/localizations-doc-review this should be a quick one :)

Great! Thanks for the quick reply and for adding the change!

2024-10-16 21:58 UTC, vbe-odoo commented
@samueljlieber please wait until my notice to move forward with this, we are checking internally the qty of free credits, sorry!

2024-10-17 11:32 UTC, dade-odoo requested changes
Hi @vbe-odoo , thanks for the addition! Can we make it a little more specific? Does each new database receive 500 free credits? Each new Brazilian company? Each new user?
I suspect it's by database, in which case I would suggest:

> On creation, new databases receive 500 free credits.

This avoids the unnecessary "you" and is more precise. Let me know if you have any questions, and take a minute to check out our newly updated [documentation guidelines](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html) whenever you have a chance :)

2024-10-17 23:18 UTC, vbe-odoo commented
> Hi @vbe-odoo , thanks for the addition! Can we make it a little more specific? Does each new database receive 500 free credits? Each new Brazilian company? Each new user? I suspect it's by database, in which case I would suggest:
> 
> > On creation, new databases receive 500 free credits.
> 
> This avoids the unnecessary "you" and is more precise. Let me know if you have any questions, and take a minute to check out our newly updated [documentation guidelines](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html) whenever you have a chance :)

Totally agree with you.
We've confirmed this information, and it is correct.
This is good to go/review/etc.

Thanks!
cc' @dade-odoo @samueljlieber

2024-10-21 07:45 UTC, dade-odoo approved these changes
Thanks @vbe-odoo @samueljlieber - looks good to me :)

2024-10-21 09:58 UTC, xpl-odoo commented
@robodoo r+

2024-10-21 13:19 UTC, robodoo commented
@vbe-odoo @xpl-odoo staging failed: ci/runbot on ab58cadfacfea143fa3e443ad368f5500406314a (view more at https://runbot.odoo.com/runbot/build/69649393)

2024-10-21 13:27 UTC, samueljlieber commented
@robodoo retry

2024-10-21 16:04 UTC, closed without merging