[FIX] l10n_de: Fix second broken GoBD link
odoo/documentation pull request #11263
Opened 2024-10-22 14:14 UTC by dade-odoo

There were two broken links originally, one of which was fixed by PR#10074. This commit will remove the first link entirely and fix the second link, as suggested by TSB.

task-4088554

2024-10-22 14:14 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11263.png)](https://mergebot.odoo.com/odoo/documentation/pull/11263)

2024-10-22 15:50 UTC, xpl-odoo requested changes
You will need to fix the `ci/documentation` error first:
![image](https://github.com/user-attachments/assets/28b7c3f4-c6b6-4eb2-ad69-ec9a80e3393f)
If the error isn't clear: it means the same hypertext (or explicit target name) doesn't point to the same hyperlink. So you need to change one of the two hypertext so they match :)

@robodoo delegate+

2024-10-23 07:18 UTC, dade-odoo commented
@xpl-odoo oops, my mistake. Should be fixed now.

2024-10-24 08:26 UTC, xpl-odoo commented
@robodoo r+

2024-10-24 09:37 UTC, closed without merging