[IMP] sales: update settings navigation for multi address
odoo/documentation pull request #11442
Opened 2024-11-21 23:43 UTC by dikd-odoo

Updated Sales app documentation on utilizing multiple customer addresses from [outdated] Sales app > Configuration > Settings to [updated] Accounting > Configuration > Settings.

Task: https://www.odoo.com/odoo/my-tasks/4293822

2024-11-21 23:43 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11442.png)](https://mergebot.odoo.com/odoo/documentation/pull/11442)

2024-11-21 23:55 UTC, dikd-odoo commented
Hi @benderliz this PR is ready for a peer review, when you have a chance. Thank you!

2024-11-22 19:13 UTC, benderliz approved these changes
@dikd-odoo I think this is a fair change! :D

2024-11-22 23:48 UTC, dikd-odoo commented
Thank you @benderliz! 

Hi @ksc-odoo this PR is ready for a final review, when you have a chance. Thank you!

2024-11-26 19:04 UTC, ksc-odoo approved these changes
Hey @dikd-odoo -- just reviewed this PR. Nice job on this quick fix. Left an adjustment that requires your attention, to ensure the navigation is as accurate as possible. If you have any questions, don't hesitate to reach out. Once you implement the adjustment, feel free to tag this for Tech Review. Thanks! 👍

2024-11-26 19:04 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
>  next to :guilabel:`Customer Addresses`, and click :guilabel:`Save`.
```suggestion
To properly utilize multiple addresses in Odoo, go to :menuselection:`Accounting app --> Configuration
--> Settings`, and scroll down to the :guilabel:`Customer Invoices` heading. Then, tick the checkbox
next to :guilabel:`Customer Addresses`, and click :guilabel:`Save`.
```

2024-11-26 23:24 UTC, dikd-odoo commented
Hi @ksc-odoo thank you for the edits and review!

Hello @samueljlieber this PR is ready for technical review, when you have a chance. Thank you!

2024-11-27 15:53 UTC, samueljlieber requested changes
Hi @dikd-odoo, these changes look good, however the original task states this applies to all versions from 16. Can you please retarget this PR to 16.0 before I review?

Thanks!

2024-11-27 18:07 UTC, samueljlieber commented
https://github.com/odoo/documentation/commit/d8658ed56d8d08ed06733330aa4c04b94b997cb4 re-targeted the PR on 16.0 and will FWP to master

2024-11-27 18:17 UTC, samueljlieber approved these changes
Thanks @dikd-odoo, looks good to me!
..
@robodoo r+

2024-11-27 19:21 UTC, closed without merging