[IMP] ecommerce: shipping
odoo/documentation pull request #11455
Opened 2024-11-26 14:41 UTC by Donapi

taskid-4016678

2024-12-02 10:06 UTC, auva-odoo requested changes
@Donapi don't hesistate if you have questions regarding my comments/suggestions. Also, I know this is not your scope but I would still use this opportunity to add a link to the Bpost documentation in a the table in [this doc](https://www.odoo.com/documentation/master/applications/inventory_and_mrp/inventory/shipping_receiving/setup_configuration/third_party_shipper.html) (they probably just forgot to do it). 
Thank you!

2024-12-02 10:06 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/shipping.rst
> +carriers.
(if we add a Pick up in store section (see my other comments), it might be worth it to mention it as well.

2024-12-03 14:38 UTC, Donapi commented on content/applications/websites/ecommerce/checkout_payment_shipping/shipping.rst
> +communication, tracking, and shipping processes.
I updated this sentence. From my understanding, the shipping processes are automated from the third-party carrier side, and we don't have to cover how it works in detail. Let me know if you disagree, and let me know what you expect :)

2024-12-10 09:24 UTC, auva-odoo requested changes

2024-12-17 11:47 UTC, auva-odoo approved these changes
@robodoo r+

2024-12-17 16:28 UTC, closed without merging