[DOC] tours
odoo/documentation pull request #11467
Opened 2024-11-27 13:17 UTC by bastien-ipb

2024-11-27 17:20 UTC, AntoineVDV requested changes

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +   :align: center
Actually I don't think that you need to add (and maintain) an image just for that:

```suggestion
The main purpose of the onboarding tours is to guide the user. They can all be started in their sequence order by toggling the :guilabel:`Onboarding` option in the user menu.
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +    |               └── your_tour.js
Alternatively:
```suggestion
    ├── static/src/js/tours/your_tour.js
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +   - :ref:`testing/javascript/test`
```suggestion
The javascript part is the same as for ref:`the test tour <testing/javascript/test>`.
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +- **rainbow_man_message**: Optional, will show the message in the
```suggestion
- `name`: Required, the name must be the same as the one in the
  javascript registry.
- `sequence`: Optional, will determine the order to execute the
  onboarding tours, If no ``sequence``, has a default value of 1000.
- `url`: Optional, the url where to start the tour. If no ``url``,
  take the url from the registry.
- `rainbow_man_message`: Optional, will show the message in the
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +  onboarding tours, If no ``sequence``, has a default value of 1000.
```suggestion
- **sequence**: Optional; determines the order to execute the
  onboarding tours. Defaults to 1000.
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +  the field and write nothing as value.
Same as for `sequence`

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +The main purpose of the onboarding tours is to guide the user. They can be started with the
Considering that you have a "Running onboardng tours" section, I would remove "The main purpose of the onboarding tours is to guide the user." completely and move the rest in that section.

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +In this view you'll get all the onboarding tours and you can execute them by clicking on `onboarding` or `testing`.
With moving the intro here in mind:
```suggestion
You can run specific onboarding tours by going to the :menuselection:`Settings --> Technical --> User Interface --> Tours` and clicking on :guilabel:`Onboarding` or :guilabel:`Testing`.
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +In this view you'll get all the onboarding tours and you can execute them by clicking on `onboarding` or `testing`.
Given that this explanation is straightforward, I think that the second image should be removed too.

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +be exported to javascript file, ready to be put in your module.
```suggestion
You can also create tours easily with the tour recorder. To do so, click on :guilabel:`Record` on the
onboarding tours view. When started, this tool will record all your interactions in Odoo.

The created tours are flagged in the onboarding tours view as **Custom**. These tours can also
be exported to a javascript file, ready to be put in your module.
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +Running onboarding tour
```suggestion
Running onboarding tours
```

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +*************************
I think it's fine as "Run via browser" considering it's a nested section.

2024-11-27 17:20 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> -.. image:: testing/tours.png
Remove the image as well.

2024-12-03 16:22 UTC, AntoineVDV approved these changes
@robodoo delegate+

2024-12-03 16:22 UTC, AntoineVDV commented on content/developer/reference/backend/testing.rst
> +The javascript part is the same as for ref: `the test tour <testing/javascript/test>`.
Broken ref
```suggestion
The javascript part is the same as for :ref:`the test tour <testing/javascript/test>`.
```

2024-12-10 08:30 UTC, bastien-ipb commented
@robodoo r+

2024-12-10 10:03 UTC, closed without merging