[IMP] Update documentation with neutralize command line options
odoo/documentation pull request #11478
Opened 2024-11-28 08:14 UTC by cgsmith

Fixes #11477

2024-11-28 08:14 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11478.png)](https://mergebot.odoo.com/odoo/documentation/pull/11478)

2024-11-28 11:48 UTC, Julien00859 requested changes
The neutralise command is part of Odoo since 16.0, could you make your changes on that branch please? We have a bot that'll take care of forwarding the changes to all following versions :)

I can do that for you if you want.

2024-11-28 11:48 UTC, Julien00859 commented on content/developer/reference/cli.rst
> +   $ odoo-bin neutralize -d odoo
```suggestion
   $ odoo-bin --addons-path <PATH,...>  neutralize -d <database>
```

2024-11-28 11:48 UTC, Julien00859 commented on content/developer/reference/cli.rst
> +.. option:: -d
```suggestion
.. option:: -d <database, --database <database>
```

2024-12-03 12:25 UTC, cgsmith commented
I will have some time to do this tomorrow when on a plane.

2025-02-21 15:44 UTC, Julien00859 approved these changes
Hello @cgsmith I took the liberty to squash the commits and change the commit title to match our guidelines :)

@xpl-odoo greened :)

2025-02-21 15:50 UTC, Julien00859 commented
> [Julien00859](https://github.com/Julien00859) [force-pushed](https://github.com/odoo/documentation/compare/87dbb20b2a1821866e1adefd4727513b5f7ccdcd..331f745e8d9d943b60d54c4bdf9388601c582998)

Made the blanks and line-length consistent with the rest of the file

2025-02-21 16:49 UTC, AntoineVDV commented on content/administration/neutralized_database.rst
> +
Not necessary since the `:doc:` role is used, and not recommended either.
```suggestion
```

2025-02-21 16:49 UTC, AntoineVDV commented on content/developer/reference/cli.rst
> +   :doc:`Neutralized Database <../../administration/neutralized_database>`
Better let the page title be displayed here.
```suggestion
   :doc:`../../administration/neutralized_database`
```

2025-02-25 07:35 UTC, cgsmith commented
@AntoineVDV updated! Thanks!

2025-02-25 09:04 UTC, AntoineVDV approved these changes
Thanks for the changes!

@robodoo r+ squash

2025-02-25 09:04 UTC, robodoo commented
Merge method set to squash.

2025-02-25 11:45 UTC, closed without merging

2025-03-05 13:19 UTC, Xavier-Do commented
@robodoo fw=skipci

2025-03-05 13:19 UTC, robodoo commented
Not waiting for CI to create followup forward-ports.