[ADD] point_of_sale: documentation for urbanPiper Integration
odoo/documentation pull request #11496
Opened 2024-12-02 12:17 UTC by meji-odoo

In this commit:
===
- Added detailed documentation on configuring online food delivery using UrbanPiper integration.
- Provides step-by-step guidance for setting up the system.

task-4263288

2024-12-02 12:17 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11496.png)](https://mergebot.odoo.com/odoo/documentation/pull/11496)

2024-12-31 12:19 UTC, xpl-odoo requested changes
Sorry for not being able to provide more detailed feedback and not being more thorough, that's a very quick review :)

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +   and Point of Sale :guilabel:`Available on Food Delivery`.
The last part of the instruction isn't clear

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +Sync Menu
```suggestion
Sync menu
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. Go to :ref:`POS settings <configuration/settings>` and find the Food Delivery Connector.
```suggestion
#. Go to :ref:`POS settings <configuration/settings>` and scroll down the :guilabel:`Food Delivery Connector`.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +      After successfully syncing the menu, a success notification will appear. Below the
```suggestion
      After successfully syncing the menu, a notification will appear. Below the
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. Log-in in `Go to the Locations <https://atlas.urbanpiper.com/locations>`_ tab.
```suggestion
#. `Go to the Locations tab <https://atlas.urbanpiper.com/locations>`_ of your Atlas account.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. Click on the location you want to activate, then press the :guilabel:`Request to Go Live` button.
```suggestion
#. Click on the location you want to activate, then press the :guilabel:`Request to go Live` button.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. Select the platform(s) you want to activate and press Next.
```suggestion
#. Select the platform(s) you want to activate and press :guilabel:`Next`.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. Now, configure the platform’s parameters, such as Platform ID and Platform URL, to establish the
```suggestion
#. Configure the platform’s parameters, such as :guilabel:`Platform ID` and :guilabel:`Platform URL`, to establish the
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. When someone places an order via any food delivery platform :guilabel:`i.e. Zomato, UberEats`,
```suggestion
#. When someone places an order via any food delivery platform (e.g., Zomato, UberEats),
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +   you will be notified with sound and a notification. To view the order, simply click on
```suggestion
   you will be notified with a sound and text notification. To view the order, click
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +   "Review Order" and you will be redirected to the orders page.
```suggestion
   :guilabel:`Review Orders` and you will be redirected to the orders page.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +   for :guilabel:`New, Ongoing, and Done`.
```suggestion
   for :guilabel:`New`, :guilabel:`Ongoing`, and :guilabel:`Done`.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +        is for food-ready orders.
```suggestion
        The :guilabel:`New` button indicates placed orders, :guilabel:`Ongoing` is for acknowledged orders, and :guilabel:`Done`
        is for food-ready orders.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +   display is configured.
```suggestion
#. The order will be displayed on the preparation display if the kitchen
   display is configured.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. When the order is ready, simply click :guilabel:`Mark as ready`, and the order status changes
```suggestion
#. When the order is ready, click :guilabel:`Mark as ready`, and the order status changes
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. In some cases, the shop/restaurant may want to cancel an order. In this case, click on
```suggestion
#. In some cases, the shop/restaurant may want to cancel an order. In this case, click 
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +   :guilabel:`Reject`, and a pop-up will appear like below.
```suggestion
   :guilabel:`Reject`, and a will pop-up appear.
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +        "JustEat", and "HungerStation" do not support order rejection. Ensure to follow the
```suggestion
        order, Swiggy customer support will contact the restaurant. Similarly, Deliveroo,
        JustEat, and HungerStation do not support order rejection. Ensure to follow the
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +   :guilabel:`Assoc. platform(s)` column, click on any provider and review the status of that
```suggestion
   :guilabel:`Assoc. platform(s)` column, select any provider and review the status of that
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +Order Flow
```suggestion
Order flow
```

2024-12-31 12:19 UTC, xpl-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +#. Additionally, there is a cart button in the navbar. Clicking this button will give you options
```suggestion
#. Additionally, there is a cart button in the navbar. Clicking this button gives you options
```
"gives you options" isn't clear? "_The number of orders at each stage is displayed_" or something like that?

2025-01-01 10:27 UTC, meji-odoo commented
@xpl-odoo 
Thanks for the review.
I have resolve your comments.

>Are there plans to add other platforms like UrbanPiper? Even if there are, this page is currently useless, so I suggest removing it and putting the UrbanPiper page's content at this level.
Also, I would move it under the [Restaurant features](http://runbot144.odoo.com/runbot/static/build/72248647-18-0/logs/build/html/applications/sales/point_of_sale/restaurant.html) section.

For this comment I have ask to PO in task.

Thanks :)

2025-01-16 09:05 UTC, meji-odoo commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +
> I don't know if that's correct, but if you can create an account from Odoo, than it deserves to be a tip:

Filling out this form does not create an account; it only adds the data to the survey form. After this, a series of procedures are followed. The account is created by Odoo, not by the customer. The customer only receives the login credentials after completing this form.

2025-01-22 11:31 UTC, LoredanaLrpz commented on content/applications/sales/point_of_sale/online_food_delivery/urban_piper.rst
> +
Ok, in that case it's even more important than just a tip, I've put it as a step

2025-01-22 15:45 UTC, LoredanaLrpz commented
@robodoo r+

2025-01-23 02:57 UTC, closed without merging