[ADD] project/dashboard: this is a new doc about project dashboard
odoo/documentation pull request #11533
Opened 2024-12-05 11:54 UTC by zulu-odoo

task-id 4384333

2024-12-05 11:54 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11533.png)](https://mergebot.odoo.com/odoo/documentation/pull/11533)

2025-01-02 07:50 UTC, auva-odoo requested changes
Hello @zulu-odoo great job on the structure and explanations in this doc! Here are some general remarks in addition to my suggestions:
- Should we document this for 17.0 instead of 18.0 (from what I could see, only the option's name in the vertical ellipsis's menu changes and we could easily change that in the fw-port)?
- I think it would be useful to add a short explanation in the introduction regarding what's on the left vs what's on the right on the project dashboard (after you explain how to access it for example)?
- I would add links/refs to the relevant docs for the different smart buttons where possible (e.g., Tasks, Documents, Planned, etc.)
- Should we also mention other information on the dashboard, such as Sales, Profitability, Budgets, Milestones, etc.?

Thank you!

2025-01-02 07:50 UTC, auva-odoo commented on content/applications/services/project/project_dashboard.rst
> +    project’s tasks over time.
```suggestion
  - :guilabel:`Burndown Chart`: click the smart button to access a :doc:`report </applications/essentials/reporting>` on the status of the
    project’s tasks over time.
```

2025-01-02 07:50 UTC, auva-odoo commented on content/applications/services/project/project_dashboard.rst
> +    timesheets and shifts.
```suggestion
  - :guilabel:`Timesheets and Planning`: click the smart button to access a :doc:`report </applications/essentials/reporting>` on the project’s
    timesheets and shifts.
```

2025-01-03 12:10 UTC, zulu-odoo commented on content/applications/services/project/project_dashboard.rst
> +(:guilabel:`⋮`), and select :guilabel:`Dashboard`.
I don't see why not, thank you for the suggestion! Added :)

2025-01-03 12:21 UTC, zulu-odoo commented on content/applications/services/project/project_dashboard.rst
> +   :doc:`Odoo Reporting <../../../applications/essentials/reporting>`
Moved, but let's double check if it's in the right place now!

2025-01-10 13:33 UTC, zulu-odoo commented on content/applications/services/project/project_dashboard.rst
> +    current information on aspects such as profitability, budget, milestones, etc.
not really yet, I'm working on a doc (or TWO) about billable projects and profitability!

2025-01-10 13:49 UTC, zulu-odoo commented on content/applications/services/project/project_dashboard.rst
> +    Click the smart button to access the Kanban view of the project.
I removed it!

2025-01-10 13:49 UTC, zulu-odoo commented on content/applications/services/project/project_dashboard.rst
> +- Totals smart buttons:
It absolutely was not intended, thank you for catching it! Restructured the doc so it's not an issue anymore.

2025-01-10 15:09 UTC, auva-odoo approved these changes
Thank you very much for the changes @zulu-odoo ! :slightly_smiling_face: I force-pushed a few minor changes (like removing commas and adding refs) and added a few things in the Budgets and Milestones section. Could please check those two sections to make sure everything is correct and complete? Then you can r+ whenever you're ready!

Thanks again!

@robodoo delegate+

2025-01-13 07:35 UTC, zulu-odoo commented
@robo-odoo r+

2025-01-13 08:39 UTC, zulu-odoo commented
@robodoo r+

2025-01-13 12:05 UTC, closed without merging