[NEW] Project: Create a new page about task dependencies
odoo/documentation pull request #11572
Opened 2024-12-12 10:13 UTC by guga-odoo

2024-12-12 10:13 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11572.png)](https://mergebot.odoo.com/odoo/documentation/pull/11572)

2024-12-12 17:19 UTC, auva-odoo requested changes
Hi @guga-odoo thank you for your work! 
- I think we could document this feature for the 17.0 version (i.e., rebase the branch) and make the few required changes for 18.0 on the fw-port branch (we can do it together!)
- I suggested quite a few changes structure-wise and I’m not sure I explained them clearly. If anything is confusing, please don’t hesitate to reach out—it’ll be easier to clarify in person! :sweat_smile:

2024-12-20 09:12 UTC, guga-odoo commented on content/applications/services/project/tasks/task_dependencies.rst
> +  you hover your mouse over it.
AJU told me the interface will soon change and the arrow buttons will disappear. I'll update this page once the updated interface is live.

2024-12-31 07:36 UTC, auva-odoo requested changes
Hi @guga-odoo, I have a few more comments, but I suggest we rebase your branch to 17.0 first (we'll do it together, let me know when you're ready!).

2024-12-31 07:36 UTC, auva-odoo commented on content/applications/services/project/tasks/task_dependencies.rst
> +To enable task dependencies in Projects, go to :menuselection:`Project --> Configuration -->
```suggestion
To enable task dependencies in projects, go to :menuselection:`Project --> Configuration -->
```

2024-12-31 07:36 UTC, auva-odoo commented on content/applications/services/project/tasks/task_dependencies.rst
> +(:guilabel:`save`) icon.
```suggestion
Settings`, enable :guilabel:`Task Dependencies`, and click :guilabel:`Save`).
```

2024-12-31 07:36 UTC, auva-odoo commented on content/applications/services/project/tasks/task_dependencies.rst
> +the predecessor task, click the :guilabel:`Blocking Tasks` smart button.
```suggestion
:guilabel:`Blocked by` tab, click :guilabel:`Add a line`. Click :guilabel:`View` to access the predecessor task. To access the successor tasks from
the predecessor task, click the :guilabel:`Blocking Tasks` smart button.
```
(becomes "Blocked Tasks" in 18.0)

2024-12-31 07:36 UTC, auva-odoo commented on content/applications/services/project/tasks/task_dependencies.rst
> +will appear, indicating the dependency from the predecessor task to the successor.
```suggestion
click one of the dots that appear around it. Drag and drop the dot onto the successor task. An arrow appears, indicating the dependency from the predecessor task to the successor.
```

2024-12-31 07:36 UTC, auva-odoo commented on content/applications/services/project/tasks/task_dependencies.rst
> +  you hover your mouse over it.
```suggestion
To remove a task dependency, proceed as follows:
- From the task form, go to the **Blocked by** tab and click the :icon:`fa-times` button.
- From Gantt view, click the red :guilabel:`X` button that appears at the center of the arrow when
  you hover your mouse over it.
```

2024-12-31 09:06 UTC, guga-odoo commented
Created new branch in 17.0 https://github.com/odoo/documentation/pull/11657

2024-12-31 09:06 UTC, closed without merging