[l10n_ec][V18][ADD] Expense Reimbursements.rst
odoo/documentation pull request #11581
Opened 2024-12-12 23:22 UTC by danielacanez

Add new section Expense Reimbursement
Content based on V18

- Images Folder : https://drive.google.com/drive/u/1/folders/1XldxZ-7F8I96C4OEivSzcXkDb7SG7Vaa

Reference for expected section to be added: 
https://docs.google.com/document/d/1yq-AXZ-TTSuJ4PpZ_BTHxIKCQZcQPHP9XAfpFodP74k/edit?tab=t.0

2024-12-12 23:22 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11581.png)](https://mergebot.odoo.com/odoo/documentation/pull/11581)

2024-12-12 23:23 UTC, danielacanez commented
FYI @vbe-odoo

2024-12-12 23:27 UTC, danielacanez commented
Hello! @samueljlieber I'm the new Loc Expert for Ecuador. I requested a new section to be added, please let me know if we need changes.
Regards:)

2024-12-13 14:28 UTC, samueljlieber commented
Hi @danielacanez! Great to meet you, and welcome! Thank you for sending this PR over, I will review with @benderliz 🙂

2024-12-18 00:03 UTC, benderliz commented
Hi @danielacanez, thanks for sending Sam and I this PR! :)

I made a number of edits to the existing text and newly added sections. Most of my fixes were for [RST conventions](https://www.odoo.com/documentation/16.0/contributing/documentation/rst_guidelines.html#nested-lists), wording (for example, we try to avoid the use of "you" in our documentation), and clarity (I added a lot of navigation instructions at the beginning of sections so users know where they should be when they're updating fields). 

Before this PR can move forward, **we will need new images without any markup (such as the purple/red boxes).** This is a newer formatting convention that we are trying to adhere to.

**Can you upload the new images to [this Google drive folder](https://drive.google.com/drive/u/0/folders/1XldxZ-7F8I96C4OEivSzcXkDb7SG7Vaa)?** There will need to be new images throughout the doc, since the UI was updated in 18.0. The titles should stay the same as the original images. 

Once new images have been taken, I can compress them and add them officially to the documentation.

Thank you so much, and please let me know if there are any questions!

2024-12-18 22:21 UTC, danielacanez commented
> Hi @danielacanez, thanks for sending Sam and I this PR! :)
> 
> I made a number of edits to the existing text and newly added sections. Most of my fixes were for [RST conventions](https://www.odoo.com/documentation/16.0/contributing/documentation/rst_guidelines.html#nested-lists), wording (for example, we try to avoid the use of "you" in our documentation), and clarity (I added a lot of navigation instructions at the beginning of sections so users know where they should be when they're updating fields).
> 
> Before this PR can move forward, **we will need new images without any markup (such as the purple/red boxes).** This is a newer formatting convention that we are trying to adhere to.
> 
> **Can you upload the new images to [this Google drive folder](https://drive.google.com/drive/u/0/folders/1XldxZ-7F8I96C4OEivSzcXkDb7SG7Vaa)?** There will need to be new images throughout the doc, since the UI was updated in 18.0. The titles should stay the same as the original images.
> 
> Once new images have been taken, I can compress them and add them officially to the documentation.
> 
> Thank you so much, and please let me know if there are any questions!

2024-12-18 22:25 UTC, danielacanez commented
Hii! @benderliz 
Thank you for your feedback :) 
I uploaded the images without markups in the folder, please let me know if I need to change something else.
Happy holidays!

2024-12-30 19:50 UTC, benderliz commented
Hi @danielacanez! I have added a [new commit](https://github.com/odoo/documentation/pull/11581/commits/926442562d475046bfe197cd629d4847ff43eb8b) for this PR, with all of the new screenshots compressed and uploaded. I think this is ready for review from your side! Please let me know how else I can help 😄

2024-12-30 19:50 UTC, benderliz approved these changes

2024-12-30 21:01 UTC, danielacanez commented
> Hi @danielacanez! I have added a [new commit](https://github.com/odoo/documentation/pull/11581/commits/926442562d475046bfe197cd629d4847ff43eb8b) for this PR, with all of the new screenshots compressed and uploaded. I think this is ready for review from your side! Please let me know how else I can help 😄

Hi @benderliz ! Everything looks great from my side! Thank you :)

2025-01-02 18:45 UTC, samueljlieber approved these changes
Hi @danielacanez (and @benderliz) thank you so much for your work on this PR to improve the Ecuador localization documentation! 

The new section, **Expense reimbursement**, looks good to me! We did improve the rest of the doc as well because some supporting sections (Purchase Documents, Vendor bills, Purchase liquidation, Purchase withholding, etc.) needed to be updated along with this new section.

I made [a commit](https://github.com/odoo/documentation/commit/7e27c8bdbdd401aaee0e9f1d655543ba948959b3) to fix a couple RST syntax issues, improve list formatting, add more seealso links, and handle images.

I also updated the commit message to follow [the convention](https://github.com/odoo/documentation/blob/18.0/commit_template.txt).

As is, this PR looks good to me, so I am passing it over to @odoo/localizations-doc-review for a final review! 

Thanks @danielacanez, and please let @benderliz or me know if you have any questions or additional edits in the meantime :)

2025-01-17 11:00 UTC, afma-odoo requested changes
Hi @samueljlieber!
Thanks a lot for the considerable work on this page.
I added comments/suggestions, mostly trying to simplify and write in a more straightforward way.
Please let me know if you have any questions. Thanks!

2025-02-11 21:24 UTC, samueljlieber commented
Hi @danielacanez, thank you for the nudge– I will make a commit as soon as possible addressing @afma-odoo's [feedback](https://github.com/odoo/documentation/pull/11581#pullrequestreview-2549550345), and Ill reach out to you with any questions!

2025-02-12 15:54 UTC, samueljlieber commented
Hi @afma-odoo, thank you for your thorough review! I implemented all of your suggestions in https://github.com/odoo/documentation/commit/eb71cea063b8fe88bd9285f48e63f2798567bbda :)

2025-02-13 15:28 UTC, afma-odoo requested changes
Hi @samueljlieber! Thanks a lot for the update. Since this revision is quite important, I have a few more suggestions. For technical reasons, I can't add a suggestion about the "website-checkout-form" image (in the eCommerce workflow section), but I don't think the image is necessary.
Feel free to contact me if you have any questions,
Thank you!

2025-02-13 15:28 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +validated. Make sure to specify the relevant product with the correct taxes for a partial refund.
If the Partial Refund/Full Refund/Full refund and new draft invoice options are not available, then this part should be updated.

2025-02-13 16:11 UTC, samueljlieber commented
https://github.com/odoo/documentation/commit/7723d2e56e69468fa2eb9230e1cf2e4c79c93be4 Implemented all of the unresolved suggestions from [AFMAs review](https://github.com/odoo/documentation/pull/11581#pullrequestreview-2614910381).

@danielacanez can you please help me with these two remaining suggestions?
1. https://github.com/odoo/documentation/pull/11581#discussion_r1954550033
2. https://github.com/odoo/documentation/pull/11581#discussion_r1954705962

2025-02-14 15:59 UTC, danielacanez commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +Then, click :guilabel:`Reverse`.
Hello AMFA, you're correct, we have this change in version 18. I'll work on updating this new version.

2025-02-14 19:41 UTC, danielacanez commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +validated. Make sure to specify the relevant product with the correct taxes for a partial refund.
Hello @afma-odoo i will make these changes next week for 18v. 
Thank you for your feedback

2025-03-03 19:07 UTC, danielacanez commented
Hi! @samueljlieber 
I want to follow up on this new section.
Thank you so much!

2025-03-04 17:16 UTC, samueljlieber commented
Hi @afma-odoo, Daniela and I addressed your remaining suggestions in https://github.com/odoo/documentation/commit/19cac2bf4a88147e83995ff569f783876a3e2e08 to update the **Customer credit notes** section. 

This is ready for another look, TIA!

2025-03-06 15:33 UTC, afma-odoo requested changes
Hi! Thank you @danielacanez & @samueljlieber for these changes 😉
I only have a few suggestions, just let me know if you have any questions.
Thank you!

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
>  - :guilabel:`Reason`: type the reason for the credit note.
```suggestion
- :guilabel:`Reason`: Type the reason for the credit note.
```

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +- :guilabel:`Reversal date`: set the date for the reversal.
```suggestion
- :guilabel:`Journal`: Select the journal for the reversal.
- :guilabel:`Document Type`: By default, :guilabel:`(04) Credit Note` is selected.
- :guilabel:`Reversal date`: Set the date for the reversal.
```

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +and select :guilabel:`Create Debit Note`.
```suggestion
and select :guilabel:`Create Debit Note`. Then, complete the following information in the 
:guilabel:`Create Debit Note` window
```

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +- :guilabel:`Debit note date`: Select the :guilabel:`specific` options.
```suggestion
- :guilabel:`Debit note date`: Set the debit note date.
```

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
>  The :guilabel:`Customer debit note` is an electronic document that, when validated, is sent to SRI.
```suggestion
The :ref:`customer debit note <accounting/issue-debit-note>` is an electronic document that, when validated, is sent to SRI.
```

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +   :ref:`Issue a customer debit note <accounting/issue-debit-note>`
As I added this info as a :ref: markup at the beginning of the section, it's no longer needed here.
```suggestion
```

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +  entered once, and then the sequence will be automatically assigned for the next documents.
```suggestion
- :guilabel:`Document number`: Enter the document number (sequence). This must only be entered once,
  and the sequence will automatically be assigned for the next documents.
```

2025-03-06 15:33 UTC, afma-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
I don't think this "Introduction" heading is needed, the page could start with line 8.
```suggestion
```

2025-03-10 07:48 UTC, afma-odoo approved these changes
@samueljlieber Thank you again for the changes!
I approve it and add the be-doc-review for the next step ;) 
Thanks for updating the page 🙂

2025-03-11 21:47 UTC, danielacanez commented on content/applications/finance/fiscal_localizations/ecuador.rst
>  Configuration
Hello! @auva-odoo 
Thank you for your feedback, I agree with your suggestions.
For your questions, I'm able to see the payment providers on a database Ecuadorian company, please let me know if you are referring to the following:
![2025-03-11_14-43](https://github.com/user-attachments/assets/a824961a-12e4-408a-8a82-6ea1056e3e72)
![2025-03-11_14-43_1](https://github.com/user-attachments/assets/01e8f151-67a4-4eff-a9f8-a342dccfea56)

For online payments, it's important to Ecuador to specify the SRI payment method field on the payment methods setting, it's the only thing that you need different from the rest of the localizations. 
![image](https://github.com/user-attachments/assets/f2b62b28-660e-4b48-b235-77ff7ea5a8b4)

Please let me know if you have more questions.
Regards!

2025-03-12 07:34 UTC, auva-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
>  Configuration
@danielacanez Thanks for the quick reply! That makes sense—it must have been the databases I was testing on. Appreciate the clarification! My suggestion still stands then :slightly_smiling_face: .

2025-03-12 13:27 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +- :ref:`Vendor Bills <l10n_ec/vendor-bills>`
I think we can remove this line, I am not sure why it is included either :)

2025-03-12 13:31 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +As part of the localization module, taxes are automatically created with its configuration and
```suggestion
The localization module automatically creates and configures taxes. If new taxes need to be created,
it is recommended to base them on the configuration of the existing ones.
```

2025-03-12 13:57 UTC, samueljlieber commented
Thank you @auva-odoo for your helpful suggestions, I've addressed them in https://github.com/odoo/documentation/commit/f3afa158674a19d843012d8d8c9aeb0e21bbe4c9 :)

2025-03-12 14:26 UTC, auva-odoo approved these changes
Thank you @samueljlieber ! :hugs: 

@robodoo r+

2025-03-12 19:54 UTC, closed without merging