[IMP] accounting: update payment matching feature
odoo/documentation pull request #11607
Opened 2024-12-19 10:34 UTC by afma-odoo

task-3518648

2024-12-19 10:34 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11607.png)](https://mergebot.odoo.com/odoo/documentation/pull/11607)

2024-12-31 09:32 UTC, auva-odoo requested changes
Thank you for your work @afma-odoo! I only have a few minor comments/suggestions (and one question as well) :slightly_smiling_face:

2024-12-31 09:32 UTC, auva-odoo commented on content/applications/finance/accounting/payments.rst
>  this specific customer or vendor. To match it with the invoice or bill, click :guilabel:`ADD`
```suggestion
this specific customer or vendor. To match it with the invoice or bill, click :guilabel:`Add`
```

2024-12-31 09:32 UTC, auva-odoo commented on content/applications/finance/accounting/payments.rst
> +:doc:`bank transactions <bank/transactions>`.
```suggestion
Invoices and bills are automatically matched to their corresponding payments and are then marked as
:guilabel:`In payment` until they are :doc:`reconciled <bank/reconciliation>` with their corresponding
:doc:`bank transactions <bank/transactions>`.
```

2024-12-31 09:32 UTC, auva-odoo commented on content/applications/finance/accounting/payments.rst
> +credit notes or refunds are marked as :guilabel:`Paid`.
```suggestion
The invoices or bills are then marked as :guilabel:`In payment` until they are :doc:`reconciled
<bank/reconciliation>` with the corresponding :doc:`bank transactions <bank/transactions>`. The
credit notes or refunds are marked as :guilabel:`Paid`.
```

2024-12-31 09:32 UTC, auva-odoo commented on content/applications/finance/accounting/payments.rst
> +<bank/transactions>` line to finalize the payment workflow and mark the invoice or bill as
```suggestion
next step is :doc:`reconciling <bank/reconciliation>` it with the related :doc:`bank transaction
<bank/transactions>` line to finalize the payment workflow and mark the invoice or bill as
```

2025-01-06 10:04 UTC, afma-odoo commented on content/applications/finance/accounting/payments.rst
>  this specific customer or vendor. To match it with the invoice or bill, click :guilabel:`ADD`
@auva-odoo Ooopsie! 😳☺️

2025-01-27 09:14 UTC, dade-odoo requested changes
Great job on this one @afma-odoo - a few more minor things (including from aspects of the doc that weren't yours, sorry :sweat_smile: ) and one bigger structural change in the auto-reconciling section. Let me know if you have any questions!

2025-01-27 09:14 UTC, dade-odoo commented on content/applications/finance/accounting/payments.rst
> +Using the Auto-reconcile tool
Can we change this to "Matching payments" instead? I think it's important to explain the auto-reconciliation feature like you did here, but they can also be matched manually, which isn't covered at all. Matching payments is the larger topic here, and the auto-reconcile feature is a more specific subject within that.

2025-01-27 09:14 UTC, dade-odoo commented on content/applications/finance/accounting/payments.rst
> +#. In the :guilabel:`Journal Items to reconcile` list view, click :guilabel:`Auto-Reconcile` next to
Here, explain how to select individual items from the list view and use the "Reconcile" button. Then in a lower section you can keep this and the following steps to explain how to use the Auto-reconcile feature

2025-01-27 09:14 UTC, dade-odoo commented on content/applications/finance/accounting/payments.rst
>  :doc:`reconciliation <bank/reconciliation>`. They are also useful when depositing :doc:`checks
Just below this, can we change "SEPA payments" to be more localization neutral? "for generating bank payment files such as SEPA or NACHA" would name the two biggest ones and imply that there are others :)

2025-01-27 09:54 UTC, afma-odoo commented on content/applications/finance/accounting/payments.rst
> +bill. Then, the payment is :doc:`reconciled <bank/reconciliation>` with the bank transactions.
Yes, indeed, thank you for catching that nuance! ;)

2025-01-27 12:52 UTC, afma-odoo commented on content/applications/finance/accounting/payments.rst
> +Using the Auto-reconcile tool
You're right, I forgot the more "general" way to do it 😅

2025-01-27 13:41 UTC, afma-odoo commented
@dade-odoo Thanks for the review, I updated the page accordingly ;)

2025-01-27 13:50 UTC, dade-odoo approved these changes
One ref to add and one note about future versions - great work on this!

2025-01-27 13:50 UTC, dade-odoo commented on content/applications/finance/accounting/payments.rst
> +#. In the :guilabel:`Find Entries to Reconcile Automatically` window, set the :guilabel:`Reconcile`
Be aware that the name of this window changes in 18 :)

2025-01-27 13:50 UTC, dade-odoo commented on content/applications/finance/accounting/payments.rst
> +<payments/pay_sepa>` or NACHA. To do so, go to :menuselection:`Accounting --> Customers --> Batch
Let's link to the NACHA section in the US localization:
https://www.odoo.com/documentation/17.0/applications/finance/fiscal_localizations/united_states.html#send-payments-nacha-files

2025-01-27 14:07 UTC, afma-odoo commented on content/applications/finance/accounting/payments.rst
> +#. In the :guilabel:`Find Entries to Reconcile Automatically` window, set the :guilabel:`Reconcile`
I will 👍

2025-01-27 14:07 UTC, afma-odoo commented on content/applications/finance/accounting/payments.rst
> +<payments/pay_sepa>` or NACHA. To do so, go to :menuselection:`Accounting --> Customers --> Batch
I knew there should be a ref somewhere I could use, but I didn't think about loc pages 😛 Thanks!

2025-01-28 14:10 UTC, auva-odoo requested changes
Great work @afma-odoo, I only have a few minor suggestions :slightly_smiling_face: and thank you @dade-odoo for the first review!

2025-01-28 15:26 UTC, afma-odoo commented on content/applications/finance/accounting/payments.rst
> +:menuselection:`Action --> Create Batch Payment`.
You're right, thanks! I updated a bit because the information needed some corrections too :)

2025-01-28 15:30 UTC, afma-odoo commented on content/applications/finance/accounting/reporting/year_end.rst
> +    any open vendor bills and customer invoices with their payments. While this step is optional, it
I think this comment is part of the year_end page 😅

2025-01-29 10:21 UTC, afma-odoo commented
@auva-odoo Thanks for the review! I just don't think the last comment is meant for this page 😉

2025-01-29 10:54 UTC, auva-odoo commented on content/applications/finance/accounting/reporting/year_end.rst
> +    any open vendor bills and customer invoices with their payments. While this step is optional, it
It is! I think I came accross this section it because you modified the ref on line 65 of this file?

2025-01-29 11:27 UTC, afma-odoo commented on content/applications/finance/accounting/reporting/year_end.rst
> +    any open vendor bills and customer invoices with their payments. While this step is optional, it
Ooops, you're right ☺️

2025-01-30 06:42 UTC, auva-odoo approved these changes
Thanks for the changes @afma-odoo ! I just pushed a tiny changes because I made a mistake in one of my suggestions (line 161 of the payments.rst file). Great work on this!

@robodoo r+

2025-01-30 07:56 UTC, closed without merging