[IMP] ecommerce: checkout
odoo/documentation pull request #11635
Opened 2024-12-23 14:36 UTC by Donapi

taskid-4392415

2024-12-23 14:36 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/11635.png)](https://mergebot.odoo.com/odoo/documentation/pull/11635)

2025-01-06 13:36 UTC, AntoineVDV commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
>  Express checkout
We should not use the term "express checkout" for the "buy now" feature. Express checkout refers to the express payment methods such as Apple Pay and Google Pay that can be displayed on the cart page, enabling the customer to skip entirely the Delivery and Payment checkout steps.

2025-01-10 08:41 UTC, auva-odoo requested changes
Hello @Donapi thank you for work on this PR. I think it would benefit from a bit more work and some additional testing of the features to ensure everything is accurate and complete. I left comments and suggestions to help with that in my review.
Also, are you planning to create another PR for 17.0? All other recent ecommerce doc updates have been done on 17.0 so far and it would be great to see this page updated there as well. Most of this PR's content would be valid for 17.0 as well (with a few exceptions, such as the eCommerce access setting (available from 17.4) that could be changed/added in the fw-port).

2025-01-21 11:57 UTC, auva-odoo requested changes
@Donapi Could you please rebase this PR onto 17.0 (as mentioned in my original comment) and then take note of the options (I mentioned them in my review comments) that are only available on 18.0 (or maybe even 17.2/17.4, I didn't check but I think it might be worth clooking into) to add them on the fw-port branch(es). Thank you.

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +accommodate business requirements.
I don't think the last sentence is necessary as it's implied in the previous one (and the fields' labels)

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +customer information via an online :ref:`form <website/dynamic_content/form>`.
```suggestion
You can add an :guilabel:`Extra Info` step in the checkout process to collect additional
customer information via an online form.
```
I would actually add the ref later (see my comment on line 121)

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +:guilabel:`Continue Checkout to proceed` to the next step.
I don't understand why this paragraph is in this section (and this sounds a bit chatgpt-y to me)

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +
I would add a small sentence to specifically mention the fact that you you can adapt the form, with this ref: <website/dynamic_content/form>`.

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +   methods, which helps diagnose potential availability issues on the payment form.
```suggestion
   Click the :icon:`fa-bug` :guilabel:`bug` icon to display an
   :ref:`availability <payment_providers/availability>` report for payment providers and payment
   methods, which helps diagnose potential availability issues on the payment form.
```

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +===============
I think this section would actually make more sense before the different steps as the checkout policy impacts the whole process?

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +  confirmation email to track their order;
```suggestion
- :guilabel:`Optional`: Customers can check out as guests and register later via the order
  confirmation email to track their order.
```

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout.rst
> +======================
And maybe this section should remain right under the Checkout policy section? (see my comment on line 157-158)

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/checkout/checkout-wishlist.png
(only for 18.0)

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/ecommerce_management/customer_accounts.rst
> +   :ref:`sign in/up at checkout <ecommerce/checkout/policy>` option allows for accounts creation.
```suggestion
   :ref:`sign in/up at checkout <ecommerce/checkout/policy>` option allows for account creation.
```

2025-01-21 11:57 UTC, auva-odoo commented on content/applications/websites/ecommerce/products/catalog.rst
> +   account.
```suggestion
   Go to :menuselection:`Website --> Configuration --> Settings`, scroll down to the :guilabel:`Privacy`
   section to restrict :guilabel:`Ecommerce Access` to logged-in users and/or enable
   :guilabel:`Shared Customer Accounts` to allow access to all websites with a single
   account.
```
- see my original comment on original lines 12-15
- I think if you enable the option, you allow access to all webistes with a single account so it doesn't make sense to mention "disallow"?
- The two options are not mutually exclusive --> and/or
- The Ecommerce access setting is also only valid for 18.0

2025-01-30 14:22 UTC, auva-odoo approved these changes
@robodoo r+

2025-01-30 19:10 UTC, robodoo commented
@donapi @auva-odoo staging failed: ci/runbot on bbc3b6ca19a174c4d027b981f8521e4cefa7672d (view more at https://runbot.odoo.com/runbot/build/74227852)

2025-01-31 07:32 UTC, auva-odoo commented
@robodoo retry

2025-01-31 10:37 UTC, closed without merging