JS domain style customisation
odoo/documentation pull request #1206
Opened 2021-10-22 08:13 UTC by SimonGenin

2021-11-02 13:20 UTC, edi-odoo requested changes
We could later place this inside style.scss

2021-11-02 13:20 UTC, edi-odoo commented on static/css/js.css
> +    border: 2px solid #00A09D;
`border: 2px solid #017e84;`

2021-11-02 13:20 UTC, edi-odoo commented on static/css/js.css
> +    padding: 16px;
`1rem`
(prefer `rem` values)

2021-11-02 13:20 UTC, edi-odoo commented on static/css/js.css
> +    color: black;
`color: #212529`

2021-11-02 13:20 UTC, edi-odoo commented on static/css/js.css
> +    border-radius: 4px;
`border-radius: .25rem;`

2021-11-03 09:02 UTC, SimonGenin commented
@Feyensv Changes applied :)

2021-11-03 09:10 UTC, Feyensv commented
@robodoo delegate+

2021-11-03 09:13 UTC, SimonGenin commented
@robodoo r+

2021-11-03 09:24 UTC, closed without merging