Correct version from 13.0 to 15.0
odoo/documentation pull request #1242
Opened 2021-10-30 15:42 UTC by StanvanHoorn

Correct version from 13.0 to 15.0

2021-10-30 15:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1242).

2021-12-10 07:52 UTC, d-fence requested changes
Nice catch of those poor forgotten documentation lines.
Can you change your commit message so that it conforms to the [guidelines](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#tag-and-module-name)

It should looks like
`[FIX] install: update versions`

2021-12-10 07:52 UTC, d-fence commented on content/administration/install/install.rst
> +Odoo 15.0 'deb' package currently supports `Debian Buster`_, `Ubuntu 18.04`_ or above.
```suggestion
Odoo 15.0 'deb' package currently supports `Debian 11 (Bullseye)`_, `Ubuntu 20.04 (Focal)`_ or above.
```

2021-12-10 07:52 UTC, d-fence commented on content/administration/install/install.rst
> +Odoo 15.0 'rpm' package supports Fedora 30.
```suggestion
Odoo 15.0 'rpm' package supports Fedora 34.
```

2021-12-11 16:02 UTC, StanvanHoorn commented
Done!

2021-12-13 10:35 UTC, Xavier-Do commented
Also, you may need to rebase your branch if you want to push again, it is a little outdated.

2021-12-13 10:37 UTC, Xavier-Do commented
Build is red:


```
/data/build/documentation/content/administration/install/install.rst:110: WARNING: Unknown target name: "debian 11 (bullseye)".
/data/build/documentation/content/administration/install/install.rst:110: WARNING: Unknown target name: "ubuntu 20.04 (focal)".
```

2021-12-13 10:44 UTC, d-fence requested changes

2021-12-13 10:44 UTC, d-fence commented on content/administration/install/install.rst
> +Odoo 15.0 'deb' package currently supports `Debian 11 (Bullseye)`_, `Ubuntu 20.04 (Focal)`_ or above.
Sorry, I forgot to mention that you also have to change the references accordingly in lines 755 and 759 hence the warnings.

2021-12-13 13:34 UTC, jcs-odoo commented
Having a quick look at this.
Can you squash both commits and have a commit message such as the following, please? 
[FIX] install/maintain: update versions in "Installing Odoo"

Here is the [documentation's commit message template](https://github.com/odoo/documentation/blob/15.0/commit_template.txt).

Well... now that I see it, basically what @d-fence  wrote :D 

Thanks!

2021-12-17 16:33 UTC, jcs-odoo commented
I believe this would solve the issue #1304

2022-02-09 15:59 UTC, AntoineVDV approved these changes
@robodoo delegate=jcs-odoo

2022-02-09 16:09 UTC, closed without merging