[FIX] account: fix bank account advanced configuration's description.
odoo/documentation pull request #1324
Opened 2021-11-18 08:53 UTC by casp-odoo

The doc mentioned an option that does not exist anymore to modify an existing bank account (Accounting --> Configuration --> Bank Accounts).

The method described here is available in this 15.0 (dashboard -> account's journal --> ... --> Configuration)

Also updated the example image.

2021-11-18 08:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1324).

2021-12-10 15:51 UTC, chiaraprattico requested changes

2021-12-10 15:51 UTC, chiaraprattico commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +Click on the three dots of the account's journal, then on *Configuration*.
```suggestion
To edit an existing bank account, go to the **Accounting dashboard**.
Click on the three dots of the account's journal, then on **Configuration**.
```

2021-12-10 15:51 UTC, chiaraprattico commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +to this account's Journal.
As you used minuscule before, you can keep it like that throughout the whole document.
```suggestion
to this account's journal.
```

2021-12-13 15:51 UTC, jcs-odoo commented
Thanks for your contribution @casp-odoo and @chiaraprattico !

While this would certainly help if some readers can't find how to edit a bank account, it mostly revealed a few things about the whole page:

- the bank mechanism changed in v14.0 --> the modifications should target 14.0 and not 15.0 but we should recreate a new PR rather than changing the base of this PR as this would ping all code owners on this repo)
- Odoo doesn't have bank accounts fields anymore but rather journals with the "bank" type. A lot on this page is then wrong as it describes a different mechanism.
- We obviously lack documentation about journals as well
- If the rest of the page was up to date, then explaining that we have to open the journal's settings for advanced settings would then be redundant with the rest of the page.

Modifying just this small part would then leave the readers with a mostly outdated page with a bit that is "kind of up to date" which could be even more confusing.

But also:
- the screenshot would need to be compressed with pngquant (see our [content guidelines](https://www.odoo.com/documentation/14.0/contributing/documentation/content_guidelines.html#images))

For now, I prefer to close this Pull Request and create a new task to update this page completely.
https://www.odoo.com/web#menu_id=4720&cids=1&action=333&active_id=3835&model=project.task&view_type=form&id=2713580

Thank you!
Jonathan

2021-12-13 15:51 UTC, closed without merging