Update SIX integration doc to match Odoo 15.0
odoo/documentation pull request #1331
Opened 2021-11-22 17:59 UTC by TwioTech

My colleague and I spent quite some time before we found out that the SIX integration works well. I hope this change in the documentation will help a lot of people. Thanks!

2021-11-22 17:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1331).

2021-12-10 10:04 UTC, LoredanaLrpz approved these changes
Thank you for your contribution, 
I took the liberty to make some changes 

Have a nice day

2021-12-10 10:25 UTC, jcs-odoo approved these changes

2021-12-10 13:41 UTC, AntoineVDV requested changes
I guess that it's better if you handle this change yourself @LoredanaLrpz :)

2021-12-10 13:41 UTC, AntoineVDV commented on content/applications/sales/point_of_sale/payment/six.rst
> +field, then enter your payment terminal IP address.
- Create -> create
- Don't start a new line unless you've reached the 100th character.
- Start a new line before you reach the 100th character.

```rst
Back in :menuselection:`Point of Sale --> Configuration --> Payment Methods`, create a new payment
method for SIX, select the appropriate journal, select *SIX* in the **Use a Payment Terminal**
field, then enter your payment terminal IP address.
```

2021-12-15 11:03 UTC, AntoineVDV approved these changes
@robodoo r+

2021-12-15 11:07 UTC, closed without merging