[ADD] general/payment_acquirers: add doc on Ogone Webhook Setup
odoo/documentation pull request #1348
Opened 2021-12-03 10:31 UTC by Demesmaeker

task-2703230

2021-12-03 10:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1348).

2021-12-13 07:58 UTC, LoredanaLrpz requested changes
Hey @Demesmaeker, 
Thanks for this doc, it's really well done, I've made some suggestions, tell me what you think :)

Have a great day,

2021-12-13 08:40 UTC, Demesmaeker commented
Thanks @LoredanaLrpz 
Nice suggestions, I pushed them :)

2022-01-03 09:30 UTC, LoredanaLrpz approved these changes

2022-01-03 09:51 UTC, AntoineVDV approved these changes
@robodoo r+

2022-01-03 09:55 UTC, closed without merging