[IMP] legal: german translation of enterprise agreement
odoo/documentation pull request #1445
Opened 2021-12-21 13:07 UTC by frfa1993

I added an updated German translation for the German enterprise agreement and I edited the main legal .rst to add the corresponding PDF file.

2021-12-21 13:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1445).

2021-12-22 15:21 UTC, jcs-odoo requested changes
Hello @frfa1993 
Thanks for this PR!

As discussed previously with @AntoineVDV , please add white lines between each command. This includes headings and paragraphs.

Also, we'll have to rebase your branch onto 14.0 and create a new PR to change the target of the PR.

Thanks

2021-12-22 15:21 UTC, jcs-odoo commented on content/legal/terms/i18n/enterprise_de.rst
> +Während der Laufzeit dieser Vereinbarung kann der Kunde eine unbegrenzte Anzahl von kostenlosen
```suggestion
4.5 Support-Dienste
-------------------

Umfang
++++++

Während der Laufzeit dieser Vereinbarung kann der Kunde eine unbegrenzte Anzahl von kostenlosen
```

2021-12-22 15:21 UTC, jcs-odoo commented on content/legal/terms/i18n/enterprise_de.rst
>  .. _upgrade_odoo_de:
```suggestion
4.3 Upgrade-Dienste
-------------------

.. _upgrade_odoo_de:

```

2021-12-28 09:11 UTC, frfa1993 commented
Backported in #1453

2021-12-28 09:11 UTC, closed without merging