[ADD] Accounting: new page about intrastat
odoo/documentation pull request #1472
Opened 2022-01-20 11:59 UTC by chiaraprattico

Task-id 2721400

https://www.odoo.com/web#id=2721400&menu_id=4720&cids=1&action=333&active_id=3835&model=project.task&view_type=form

2022-01-20 12:00 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1472).

2022-01-20 15:05 UTC, jcs-odoo requested changes
Hi @chiaraprattico :)

Nice one for your first doc PR!

This page isn't covering everything about Intrastat, but we'll update it later. What matter now is the last section on this page.

Please re-request a review from me once you've updated your branch.

Cheers,
Jonathan

2022-01-20 15:05 UTC, jcs-odoo commented on content/applications/finance/accounting/reporting/declarations/intrastat.rst
> +Once the Intrastat has been activated you are able to choose the *Incoterm* values.
```suggestion
Once the Intrastat has been activated you are able to choose the **Default incoterm**.
```

2022-01-20 15:05 UTC, jcs-odoo commented on content/applications/finance/accounting/reporting/declarations/intrastat.rst
> +   <general/upgrade>` ``account_intrastat`` to add the new transaction codes and :ref:`install
```suggestion
   <general/upgrade>` the ``account_intrastat`` module to add the new transaction codes and :ref:`install
```

2022-01-21 14:12 UTC, jcs-odoo requested changes
Small changes

2022-01-21 14:12 UTC, jcs-odoo commented on content/applications/finance/accounting/reporting/declarations/intrastat.rst
> +   All transactions recorded after this date have to follow the new system’s rules.
Break the line at 100th character
```suggestion
   As of January 1, 2022, the reporting requirements have changed. One main modification concerns
   the transactions codes which are now switching to a 2-digits format. All transactions recorded
   after this date have to follow the new system’s rules.
```

2022-01-21 14:12 UTC, jcs-odoo commented on content/applications/finance/accounting/reporting/declarations/intrastat.rst
> +Once the Intrastat has been activated you are able to choose the **Default incoterm**.
- why the three ``` ?
- line break at 100th character

```suggestion
Go to :menuselection:`Accounting --> Settings --> Customer Invoices`, then enable **Intrastat** and
*Save*. Once the Intrastat has been activated you are able to choose the **Default incoterm**.
```

2022-01-21 15:10 UTC, jcs-odoo approved these changes
Good job for your first PR :)
I now can request a review from @odoo/doc-review . Either they merge it themselves or they'll delegate you the rights to do so and you'll be able to merge the PR yourself, including the fw-port PR as well.

2022-01-21 15:23 UTC, Feyensv commented on content/applications/finance/accounting/reporting/declarations/intrastat.rst
> +   the transactions codes which are now switching to a 2-digits format. All transactions recorded
```suggestion
   the transaction codes which are now switching to a 2-digits format. All transactions recorded
```

2022-01-21 15:23 UTC, Feyensv commented on content/applications/finance/accounting/reporting/declarations/intrastat.rst
> +of the goods traded with other EU countries.
```suggestion
about the goods traded with other EU countries.
```

2022-01-21 15:43 UTC, Feyensv approved these changes
@robodoo r+

2022-01-21 15:48 UTC, closed without merging