[IMP] buckaroo: provide steps to set up a webhook
odoo/documentation pull request #1481
Opened 2022-01-24 16:47 UTC by AntoineVDV

task-2692127

2022-01-24 16:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1481).

2022-01-27 10:40 UTC, LoredanaLrpz requested changes
I've made some suggestions to be more consistent in the way we tell "what to do" and then "where to do it" but overall it looks clear to me 

I'm still thinking of how to improve the general reading of these pages, working on it :)

2022-01-27 10:40 UTC, LoredanaLrpz commented on content/applications/general/payment_acquirers/buckaroo.rst
> +     URL followed by `/payment/buckaroo/webhook`.
```suggestion
#. | Enter your Odoo database URL followed by `/payment/buckaroo/webhook` in both the **Push URI 
     Success** and **Push URI Failure** text fields
```

2022-01-27 10:40 UTC, LoredanaLrpz commented on content/applications/general/payment_acquirers/buckaroo.rst
> +#. In the **Delayed and Push responses** section, check **Enable Push Response**.
```suggestion
#. Check **Enable Push Response** in the **Delayed and Push responses** section.
```

2022-01-27 10:58 UTC, LoredanaLrpz approved these changes

2022-01-31 15:51 UTC, AntoineVDV commented
@robodoo r+

2022-01-31 15:58 UTC, closed without merging