[IMP] odoo_sh doc update
odoo/documentation pull request #1597
Opened 2022-02-16 08:32 UTC by sts-odoo

2022-02-16 08:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1597).

2022-02-21 11:11 UTC, jcs-odoo requested changes
Hello @sts-odoo 
Thanks for the pr :)

- please add a redirection in redirects.txt (root folder)
  add this at line 250
  `administration/odoo_sh/advanced/frequent_technical_questions.rst administration/odoo_sh/advanced/scheduled_actions.rst   # frequent_technical_questions -> scheduled_actions`
- make sure to break the line at the 100th character (see [rst guidelines](https://www.odoo.com/documentation/15.0/contributing/documentation/rst_guidelines.html#start-a-new-line-before-the-100th-character))

2022-02-21 11:11 UTC, jcs-odoo commented on content/administration/odoo_sh/advanced/scheduled_actions.rst
> +On the Odoo.sh platform, we cannot guarantee an exact running time for scheduled actions.
- list
- phrasing suggestions 
- some English mistakes

```suggestion
- The delay between a scheduled task's next execution date and the actual triggering depends on many
  parameters and can be delayed according to the state of the execution pool of the shared server.
-  Scheduled actions on staging branches are executed less often than production build.
- The platform will deactivate scheduled actions that repeatedly time out.
- If the execution time of a scheduled action is business-critical, then we recommend using a
  dedicated server as the scheduled actions timeout can be modified in the project settings.
- We cannot guarantee an exact running time for scheduled actions on the Odoo.sh platform.
```

2022-02-21 11:11 UTC, jcs-odoo commented on content/administration/odoo_sh/advanced/submodules.rst
> +This symlink has to be done within your github repository. Do not try to create the symlink wth the container.
- note
- cap letters GitHub
- typo ("with")

```suggestion

.. note::
   This symlink has to be done within your GitHub repository. Do not try to create the symlink
   with the container.```

2022-02-21 11:11 UTC, jcs-odoo commented on content/administration/odoo_sh/getting_started/create.rst
> +</administration/maintain/supported_versions>` of Odoo. The branch will automatically switch to the Odoo version of the database.
present tense
https://www.odoo.com/documentation/15.0/contributing/documentation/content_guidelines.html#grammatical-tenses

2022-02-21 12:35 UTC, jcs-odoo requested changes
There are still a few minor changes required.

Thanks!

2022-02-21 12:35 UTC, jcs-odoo commented on content/administration/odoo_sh/advanced/scheduled_actions.rst
> +.. _odoosh-advanced-scheduled_actions:
can you apply this as well if possible?
It's not a guideline but it's to remain consistent with all the newly added ref anchors.

2022-02-21 12:35 UTC, jcs-odoo commented on content/administration/odoo_sh/advanced/scheduled_actions.rst
> +worker" bound to every Odoo.sh instance.
- 100th character line break. see our [rst guidelines]([url](https://www.odoo.com/documentation/15.0/contributing/documentation/rst_guidelines.html#start-a-new-line-before-the-100th-character))

```suggestion
On Odoo.sh, cron jobs and incoming mails are handled by a specific worker that is not accounted in
the workers on your subscription. It is a kind of "hidden free worker" bound to every Odoo.sh
instance.
```

2022-02-21 12:35 UTC, jcs-odoo commented on content/administration/odoo_sh/advanced/scheduled_actions.rst
> +* We cannot guarantee an exact running time for scheduled actions on the Odoo.sh platform.
- not a guideline either but we'd rather use `-` for lists, for consistency of the code
- present tense for general truths.

```suggestion
- The delay between a scheduled task's next execution date and the actual triggering depends on many
  parameters and can be delayed according to the state of the execution pool of the shared server.
- Scheduled actions on staging branches are executed less often than production build.
- The platform deactivates scheduled actions that repeatedly time out.
- If the execution time of a scheduled action is business-critical, then we recommend using a
  dedicated server as the scheduled actions timeout can be modified in the project settings.
- We cannot guarantee an exact running time for scheduled actions on the Odoo.sh platform.
```

2022-02-21 14:42 UTC, jcs-odoo approved these changes

2022-02-21 17:32 UTC, AntoineVDV approved these changes
@robodoo r+

2022-02-21 17:37 UTC, closed without merging