Add Note about how to access Detailed Operations
odoo/documentation pull request #1639
Opened 2022-02-25 21:51 UTC by ray-odoo

User tripped up due to the creation of a second warehouse enabling Storage Locations and changing the workflow.

https://www.odoo.com/forum/help-1/inventory-receipt-in-second-warehouse-199962

2022-02-25 21:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1639).

2022-03-09 22:38 UTC, ray-odoo commented
@jcs-odoo what's the process here to get this reviewed? Do I just add you as a reviewer? Someone else? zst told me he wasn't supposed to be in the Inventory Doc Review group and he was the only member when that group was added as a reviewer.

Also, how are you? Taking care of things at the farms?

2022-03-10 09:33 UTC, jcs-odoo requested changes
Hello Ray!

I'm doing well, thanks! What about you?

Usually, people who aren't in the team of reviewers anymore should 1) add the new responsible 2) leave the team. We can't edit teams in which we are not, so I can't update it for everyone.
I'll see with Martin, who has more access rights, if he can update these teams just once to have a fresh start, and I'll send an email to all writers to explain the process :)

Anyway, bookmark this [doc that maps each app with its responsible](https://docs.google.com/spreadsheets/d/18QSSwvAVjla5WiAPr78Jdtr3A8LD8s8K_n8NT4BAxAE/) (content is in the last column). Here you see that @sdr-odoo and jorc (I can't find his GitHub account... meaning I can't ask Martin to update the team either) should be the reviewers.

Once the reviewer approves the changes, they ping the team **odoo/doc-review** so they can merge the content safely.

It's a small PR, so here is my review :)

- I believe this PR should have targeted 13.0 instead of 15.0 since the doc is the same in all versions, and I believe your addition is valid for all versions.
  - in general, please check back to which version your changes can be applied. 
  - We can't retarget the PR directly (or it pings all teams of reviewers). You have then to create a new PR, close this one, and mention the new one in it. 
- about the note, see the comment directly in the text.

If you agree with my suggestion, then I or @sdr-odoo can do the new PR for you this time :)

Have a good one!

Jonathan

2022-03-10 09:33 UTC, jcs-odoo commented on content/applications/inventory_and_mrp/inventory/management/incoming/one_step.rst
> +where you are storing the received product(s).
- [RST cheat sheet: notes admonitions](https://www.odoo.com/documentation/13.0/contributing/documentation/rst_cheat_sheet.html#note)
- RST guidelines: break the line at the 100th character
- not documented yet but we'll use `guilabel` for elements that are part of the interface (fields names, buttons, views etc)

Does this suggestion seem good to you?
```suggestion
.. note::
   If you have :guilabel:`Storage Locations` activated, you can click the hamburger menu next to 
   the :guilabel:`Done quantity` to specify the location(s) where you are storing the received
   product(s).
```

2022-03-10 10:01 UTC, jcs-odoo commented
Oh and I forgot something:
The title of the commit (and the PR) should be something like this:

`[IMP] inventory: add note about detailed operations in one_step.rst`

2022-03-30 09:29 UTC, robodoo commented
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

2022-03-30 09:42 UTC, jcs-odoo commented
Hi @ray-odoo :)
I hope you're well. I just went with my suggested changes and backported this in 13.0 with the PR #1772 
So I close this one but the content is going to be merged with the other PR :)

2022-03-30 09:42 UTC, closed without merging