Update ocr.rst
odoo/documentation pull request #1653
Opened 2022-03-04 19:49 UTC by ray-odoo

Add link to try the OCR service, cleanup copy.

2022-03-04 19:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1653).

2022-03-07 07:58 UTC, chiaraprattico commented on content/applications/finance/accounting/payables/supplier_bills/ocr.rst
> +should be processed automatically (use the OCR service every time) or manually (on demand).
```suggestion
should be processed automatically ( with the OCR ) or manually.
```

2022-03-07 10:43 UTC, jcs-odoo requested changes
Thanks for the PR @ray-odoo !

This PR should target 13.0 instead of 15.0, but we have to recreate a new PR for this. (so don't worry if you see we close this one :) )

@chiaraprattico , we'll do this together today and apply your suggestion at the same time.

2022-03-07 12:18 UTC, chiaraprattico commented
Created the update PR in #1655

2022-03-07 12:18 UTC, closed without merging