[IMP] amazon: explain how to use a carrier
odoo/documentation pull request #1750
Opened 2022-03-28 07:52 UTC by Demesmaeker

In case of an unsupported carrier or a self Delivery, Odoo won't block
the user to use the Amazon connector, but explanation were needed for
these cases.

task-2804907

see also:
- https://github.com/odoo/odoo/pull/82772
- https://github.com/odoo/enterprise/pull/23504

2022-03-28 07:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1750).

2022-04-21 21:42 UTC, meng-odoo requested changes
@Demesmaeker Hi! Thanks for your contribution here. I'm just requesting a small wording change before we make the approval. Thanks :)

2022-04-21 21:42 UTC, meng-odoo commented on content/applications/sales/sales/amazon_connector/manage.rst
> +     about any typo, as Amazon wouldn't recognize it.
Small change to this sentence to make it present tense and sound a little smoother:

`about typos, as Amazon won't recognize them.`

2022-05-06 13:19 UTC, Demesmaeker commented
@meng-odoo Hello! Thanks for your feedback, the change is done. =]

2022-05-07 00:35 UTC, meng-odoo approved these changes
Hi @Demesmaeker! Thanks for making those changes. Everything looks great. I'll go ahead and push this to the next step in the review process.

2022-05-09 07:53 UTC, AntoineVDV approved these changes
@robodoo r+

2022-05-09 09:40 UTC, closed without merging