[IMP] accounting: update the follow-up information
odoo/documentation pull request #1834
Opened 2022-04-14 11:32 UTC by Donapi

Task ID: 2735445

2022-04-14 11:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1834).

2022-04-28 15:06 UTC, aim-odoo requested changes
@Donapi review done ;)

2022-04-28 15:06 UTC, aim-odoo commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +them as good, normal, or bad debtors on the follow-up reports. Just click on the button next to the
```suggestion
them as good, normal, or bad debtor on the follow-up report. Just click on the bullet next to the
```

2022-04-28 15:06 UTC, aim-odoo commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +To make your follow-up process more manageable, you can send reminder emails in batches from your
```suggestion
To make your follow-up process even smoother, you can send reminder emails in batches from the
```

2022-04-28 15:06 UTC, aim-odoo commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +Send reminders in batch
```suggestion
Send reminders in batches
```

2022-04-28 15:06 UTC, aim-odoo commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +Follow-up Reports page. Select all the reports you would like to process, click on Action, and then
```suggestion
Follow-up Reports page. Select all the reports you would like to process, click on the *Action* gear icon, and select
```

2022-04-28 15:06 UTC, aim-odoo commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +on Process Follow-ups.
```suggestion
*Process Follow-ups*.
```

2022-04-29 05:54 UTC, Donapi commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +automatically send a reminder by checking the *Auto Execute* option
Sentence updated as follow: Depending on the number of overdue days you set in the *Follow-up Action* form, you can plan to print a letter, send an email, an SMS message, or a letter to follow up with your customer. It is
also possible to automatically send a reminder by enabling the *Auto Execute* option.

2022-04-29 06:34 UTC, Donapi commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +   * The contact information available on the invoice or on the contact is used to send the
The contact information available on the invoice or on the contact form is used for? 
"used to send the reminder." isn't correct?

2022-04-29 06:37 UTC, Donapi commented
Thanks for your review @aim-odoo !

2022-05-12 13:49 UTC, Donapi commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> -    :align: center
I no longer see it...

2022-05-13 07:47 UTC, Donapi commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +Follow-up Reports
Le terme est en majuscule dans Odoo... 
![image](https://user-images.githubusercontent.com/85342080/168236287-f53be2ac-3b00-4ffb-bc64-ea643abc8ff8.png)

2022-05-13 07:47 UTC, Donapi commented on content/applications/finance/accounting/receivables/customer_payments/followup.rst
> +Follow-up Reports
du coup, majuscule ou minuscule? :)

2022-05-23 13:39 UTC, jcs-odoo approved these changes

2022-05-23 13:42 UTC, jcs-odoo commented
Ping me once you've fixed the conflicts with the old images' paths.

2022-05-24 11:39 UTC, AntoineVDV approved these changes
@robodoo r+

2022-05-24 12:29 UTC, closed without merging