[FIX] sales: fix typo
odoo/documentation pull request #1886
Opened 2022-04-28 12:08 UTC by alpa-odoo

critarias -> criterias

2022-04-28 12:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1886).

2022-04-29 18:23 UTC, meng-odoo requested changes
@alpa-odoo Hi! Thanks for finding this typo. The correct word is actually "criteria" (it's already plural without the "s" at the end). Let's just fix that tiny detail before approving :)

2022-04-29 18:23 UTC, meng-odoo commented on content/applications/sales/sales/products_prices/prices/pricing.rst
> +You can set several criterias to use a specific price: periods, min. sold quantity (meet a minimum order quantity and get a price break), etc.
```suggestion
You can set several criteria to use a specific price: periods, min. sold quantity (meet a minimum order quantity and get a price break), etc.
```

2022-04-29 22:00 UTC, meng-odoo approved these changes
Hi @alpa-odoo Thanks for making that change! Everything looks good. I'll move this to the next stage in the review process.

2022-05-02 09:01 UTC, Feyensv requested changes
Please squash the commits into one commit with a clear title (like the PR one) :)

2022-05-02 13:42 UTC, AntoineVDV approved these changes
@robodoo r+

2022-05-02 15:36 UTC, closed without merging