Fix a typo: user menu registry example
odoo/documentation pull request #1975
Opened 2022-05-10 13:13 UTC by beshoynabeih

fix errors in javascript code example.

2022-05-10 13:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/1975).

2022-05-11 11:38 UTC, brboi requested changes
It's nice you spotted this typo.
Thank you for helping us improve the user documentation of Odoo!

Can you please make the requested change?

2022-05-11 11:38 UTC, brboi commented on content/developer/reference/frontend/registries.rst
> +    })
```suggestion
        };
    });
```

2022-05-13 20:39 UTC, beshoynabeih commented on content/developer/reference/frontend/registries.rst
> +    })
sure, I did it.

2022-05-16 08:48 UTC, beshoynabeih commented
@brboi should I do anything else to merge my request?

2022-05-16 11:36 UTC, brboi commented
> @brboi should I do anything else to merge my request?

There is one last step required: a validation from @odoo/doc-review

😉

2022-05-16 12:24 UTC, AntoineVDV requested changes
Hello @beshoynabeih, could you please squash your commits into one so we can proceed with the merge? :)
Ideally, the commit title would be something like `[FIX] developer/frontend: typo in the user menu registry example`.

2022-05-17 06:40 UTC, AntoineVDV commented
> @AntoineVDV I did the squash could you please check you

@beshoynabeih As you can see [here](https://github.com/odoo/documentation/pull/1975/commits) your pull request counts 5 commits. After squashing the commits into one, it should only have a single commit.

2022-05-19 09:16 UTC, beshoynabeih commented
@AntoineVDV thank you for helping. now it is one commit

2022-05-19 09:46 UTC, AntoineVDV approved these changes
Good, thank you!

@robodoo r+

2022-05-19 12:22 UTC, closed without merging