Thomasdeleval putaways removal
odoo/documentation pull request #2002
Opened 2022-05-13 14:15 UTC by thomasdeleval

added the new features of V15 for putaways and removal strategies

2022-05-13 14:16 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2002).

2022-05-16 07:54 UTC, jirocha requested changes
Please check line 21, towards the end, there is an error near the end. Thank you Thomas :)

2022-05-16 07:54 UTC, jirocha commented on content/applications/inventory_and_mrp/inventory/routes/strategies/putaway.rst
> +In some cases, like for a retail shop storing vegetables and fruits, we have to store products in different locations depending on several fatctors like
Error near the end of the line 21 "fatctors"

2022-08-30 12:48 UTC, jcs-odoo commented
@StraubCreative moved this PR's content to another PR #2556 .
I close this one to avoid duplicates and to clean the list.

2022-08-30 12:48 UTC, closed without merging