[ADD] websites: add plausible.io Dashboard documentation
odoo/documentation pull request #2007
Opened 2022-05-17 17:08 UTC by JKE-be

2022-05-17 17:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2007).

2022-05-17 17:13 UTC, JKE-be commented
![_home_odoo_src_odoo_documentation__build_html_applications_websites_website_optimize_plausible html](https://user-images.githubusercontent.com/4848797/168871936-b5cc47d5-45dc-4607-9a19-cb5fa4ce270f.png)

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +=======================================================
```suggestion
=====================================================
How to track your website's traffic with Plausible.io
=====================================================
```

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +- `Create a Plausible.io account <https://plausible.io/register/>`__ if   you don't have any.
```suggestion
- `Create a Plausible.io account <https://plausible.io/register/>`__ if you don't have any.
```

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +- `Create your website <https://plausible.io/sites/new/>`__ and `Start collecting data`  if it is not already done.
```suggestion
- `Create your website <https://plausible.io/sites/new/>`__ and `Start collecting data` if it is not already done.
```

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +        :align: center
```suggestion
    .. image:: media/plausible_cog.png
       :align: center
```

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +        :align: center
```suggestion
    .. image:: media/plausible_new_sharedlink.png
       :align: center
```

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +        :align: center
```suggestion
    .. image:: media/plausible_create_sharedlink.png
       :align: center
```

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +        :align: center
```suggestion
    .. image:: media/plausible_copy_sharedlink.png
       :align: center
```

2022-05-18 06:39 UTC, Lau-Odoo commented on content/applications/websites/website/optimize/plausible.rst
> +        :align: center
```suggestion
    .. image:: media/plausible_paste_sharedlink.png
       :align: center
```

2022-05-18 09:38 UTC, Lau-Odoo approved these changes

2022-05-18 12:34 UTC, rdeodoo requested changes
Damn, cool!
Thanks for writting it

2022-05-18 12:34 UTC, rdeodoo commented on content/applications/websites/website/optimize/plausible.rst
> +- Go through the `list of yours websites <https://plausible.io/sites/>`__ and click on the gear wheel.
```suggestion
- Go through the `list of your websites <https://plausible.io/sites/>`__ and click on the gear icon.
```

2022-05-18 12:34 UTC, rdeodoo commented on content/applications/websites/website/optimize/plausible.rst
> +.. note:: What's about the Goal ?
```suggestion
.. note:: What about the Goal?
```
(and maybe just `What about Plausible Goal(s)`?)

2022-05-18 12:34 UTC, rdeodoo commented on content/applications/websites/website/optimize/plausible.rst
> +.. note:: You are on the Odoo Saas Platform ?
```suggestion
.. note:: You are on the Odoo Saas Platform?
```

2022-05-18 15:11 UTC, rdeodoo approved these changes
@robodoo r+

2022-05-18 15:12 UTC, robodoo commented
I'm sorry, @rdeodoo. I'm afraid I can't do that.

2022-05-18 15:13 UTC, JKE-be commented
@robodoo r+

it has been approved by 2 reviewers already

2022-05-18 15:13 UTC, robodoo commented
I'm sorry, @JKE-be. You can't review+.

2022-05-18 19:28 UTC, closed without merging