[ADD] payment: update SIX screenshots
odoo/documentation pull request #2008
Opened 2022-05-17 17:38 UTC by mivu-odoo

If merged, this will update the screenshot for the "Connect a SIX Payment Terminal to your PoS" doc. In Odoo v14.0, the "Use a Payment Terminal" field only has "Six" as an option, not "Six without IoT Box." The new screenshot reflects this change and I also rewrote the step to reflect this change.

I also added alt text to the images, fixed the image file names, and fixed the image file folder name.

Related issue: https://github.com/odoo/documentation/issues/954

2022-05-17 17:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2008).

2022-05-17 22:42 UTC, StraubCreative requested changes
@mivu-odoo 

The changes you made here were great 🎉 

I like that you cleaned up the lines that were breaking too early before the 100th char along with the wording/flow edits you made which were spot on. Nice job renaming the image files too so they were more contextual to what the images communicate.

Just a couple small revisions below:
• remove extra backtick (`) in line 19
• add another `:guilabel:` on line 20
• would reduce resolution of the image you added by about 50%

2022-05-17 22:42 UTC, StraubCreative commented on content/applications/sales/point_of_sale/payment/six.rst
> +:guilabel:`Apps`, remove the *Apps* filter, and search for *POS Six*.
Add `:guilabel:` for clickable UI filter.

```suggestion
:guilabel:`Apps`, remove the :guilabel:'Apps' filter, and search for *POS Six*.
```

2022-05-17 22:42 UTC, StraubCreative commented on content/applications/sales/point_of_sale/payment/six.rst
> +First, make sure that the :guilabel:`POS Six`` module is installed. For this, go to
Remove extra backtick after `POS Six`
```suggestion
First, make sure that the :guilabel:`POS Six` module is installed. For this, go to
```

2022-05-17 22:42 UTC, StraubCreative commented on content/applications/sales/point_of_sale/payment/six.rst
> +.. image:: six/new-payment-method-six.png
The file size is fine but you'll probably get dinged for 4k resolution during technical review.
Would reduce file width by about 50% if you can to around tablet breakpoint of ~787px (as opposed to 1500+ pixels"

2022-05-18 07:09 UTC, LoredanaLrpz approved these changes
It seems fine :).
 
Thank you for this PR and the review @mivu-odoo and @StraubCreative. However, if any changes are needed regarding the pos pages, create a task so the person in charge will do it. 
If you're wondering who's in charge of what app, please refer to this [doc](https://docs.google.com/spreadsheets/d/18QSSwvAVjla5WiAPr78Jdtr3A8LD8s8K_n8NT4BAxAE/edit#gid=1664672763).

I wish you both a nice day,

2022-05-18 17:32 UTC, mivu-odoo commented
> It seems fine :).
> 
> Thank you for this PR and the review @mivu-odoo and @StraubCreative. However, if any changes are needed regarding the pos pages, create a task so the person in charge will do it. If you're wondering who's in charge of what app, please refer to this [doc](https://docs.google.com/spreadsheets/d/18QSSwvAVjla5WiAPr78Jdtr3A8LD8s8K_n8NT4BAxAE/edit#gid=1664672763).
> 
> I wish you both a nice day,

Hi @LoredanaLrpz ! 

I'm sorry, it was my mistake. I'm in charge of IoT Box and I forgot that payment terminals were a category separate from IoT Box. Would you like to take over the PR from here, or do you want me to make the changes that @StraubCreative requested and close this PR?

2022-05-20 19:45 UTC, mivu-odoo commented
Got permission from Loredana (lrpz) to continue with this PR, despite it not being in my app scope (thank you!)

2022-05-20 20:38 UTC, mivu-odoo reviewed
Hi @StraubCreative !

Thank you for the review. I made the following changes:

- Line 19: Deleted the extra backtick after `POS Six`
- Line 20: Added a `:guilabel:` to `Apps` filter
- Line 30: Updated the screenshot for `new-payment-method.png` so that it's smaller

Please let me know if there's anything else that needs work. Thank you :-)

2022-05-24 22:20 UTC, StraubCreative approved these changes
Looks good to me!
On to DR :)

2022-05-25 08:50 UTC, AntoineVDV approved these changes
@robodoo r+ squash

2022-05-25 08:51 UTC, robodoo commented
Merge method set to squash

2022-05-25 09:43 UTC, closed without merging