[IMP] base: Qweb add `t-cache` and `t-nocache` directive
odoo/documentation pull request #2056
Opened 2022-05-20 08:59 UTC by Gorash

related with: https://github.com/odoo/odoo/pull/88276

2022-05-31 12:27 UTC, robodoo commented
I'm sorry, @VincentSchippefilt. I'm afraid I can't do that.

2022-06-03 10:58 UTC, Julien00859 approved these changes
Review done verbally, we know there are still rooms for improvement but this it the best we have right now and we are [under pressure](https://youtu.be/a01QQZyl-_I) to merge.

2022-06-03 12:24 UTC, AntoineVDV requested changes
Since this PR is blocking the freeze, I only reviewed its technical aspects and didn't pay much attention to the content itself. The latter would however need to be proofread someday to fix the grammar and phrasing, eventually on the occasion of a full rewrite of the page.

@robodoo delegate+

While you're at it, could you please update the message commit to be relevant to the documentation repository? Something like: `[IMP] qweb: document 't-cache' and 't-nocache' directives`.

2022-06-03 12:24 UTC, AntoineVDV commented on content/developer/reference/frontend/qweb.rst
> +        returns etree object, ref
A blank line is required in order for the method to render correctly.
```suggestion
.. py:method:: render(template_name, values, load, **options)

    :func:`load(ref)`
        returns etree object, ref
```

2022-06-03 12:47 UTC, AntoineVDV commented
@robodoo r+

2022-06-03 12:53 UTC, AntoineVDV commented
@robodoo squash

2022-06-03 12:54 UTC, robodoo commented
Merge method set to squash

2022-06-03 12:55 UTC, Gorash commented
robodoo r+

2022-06-03 12:55 UTC, robodoo commented
I'm sorry, @Gorash. This PR is already reviewed, reviewing it again is useless.

2022-06-03 13:00 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#27582, odoo/odoo#88276 not ready. Linked PRs are not staged until all of them are ready.

2022-06-03 15:38 UTC, closed without merging