[IMP] maintain: process for odoo.sh to odoo online
odoo/documentation pull request #2133
Opened 2022-06-02 08:45 UTC by jaae-odoo

https://www.odoo.com/web#id=2870122&cids=1&model=project.task&view_type=form

2022-06-02 08:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2133).

2022-06-02 13:10 UTC, LoredanaLrpz commented on content/administration/maintain/hosting_changes.rst
> +   - When (and in which timezone) you want the database to be up and running (see note below)
I took off the parenthesis -just bc I don't like it here and think it looks better as a note- (same with see as note)
```suggestion
   - Which user(s) will be the administrator(s)
   - When (and in which timezone) you want the database to be up and running
```

2022-06-02 13:11 UTC, LoredanaLrpz commented on content/administration/maintain/hosting_changes.rst
> +   - In which region you want to be hosted (select the one closest to your users to reduce latency):
I took off the parenthesis and put it as a note below
```suggestion
   - In which region you want to be hosted:
```

2022-06-02 13:15 UTC, LoredanaLrpz commented on content/administration/maintain/hosting_changes.rst
> +#.  **If you have time constraints, contact us earlier to schedule the transfer.**
+ indentation problem

```suggestion
#. **If you have time constraints, contact us earlier to schedule the transfer.**
```

Also, I wouldn't put this as a mandatory step, but in the note instead.

>>>> I guess you just put it this way to stay consistent with the top of the page, though, so maybe just leave it, or change the whole page MOUHAHAHAHHAHA

2022-06-02 14:46 UTC, LoredanaLrpz approved these changes

2022-06-02 16:04 UTC, jcs-odoo requested changes
@toaa-odoo @LoredanaLrpz 
Nicely done! It looks great :) 
Just some full stops missing

2022-06-02 16:04 UTC, jcs-odoo commented on content/administration/maintain/hosting_changes.rst
> +   - The URL you want to use for your database (e.g.: `example.odoo.com`)
```suggestion
   - The URL you want to use for your database (e.g., `example.odoo.com`)
```

2022-06-03 09:23 UTC, jcs-odoo approved these changes

2022-06-03 10:28 UTC, Feyensv commented
@robodoo r+

2022-06-03 10:29 UTC, Feyensv approved these changes

2022-06-03 11:15 UTC, closed without merging