[IMP] core: additionnal country db for geoip
odoo/documentation pull request #2151
Opened 2022-06-03 11:11 UTC by Julien00859

Task: 2848206

2022-06-03 11:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2151).

2022-06-03 11:15 UTC, Julien00859 commented
We found a way to include the doc commit in the batch :)

2022-06-03 12:46 UTC, AntoineVDV reviewed
Content review for `content/developer/misc/other/cmdline.rst` only. @odoo/website-doc-review please reset my request for review when the PR is ready for technical review ;)

2022-06-03 12:46 UTC, AntoineVDV commented on content/developer/misc/other/cmdline.rst
> +   Absolute path to the country GeoIP database file.
As per maxmind.com nomenclature.
```suggestion
   Absolute path to the GeoIP City database file.

.. option:: --geoip-country-db <path>

   Absolute path to the GeoIP Country database file.
```

2022-06-14 06:58 UTC, Lau-Odoo requested changes
- Please, adapt the number of "=" symbols to your title length.
- Only one commit per PR please :)

2022-06-14 07:09 UTC, Lau-Odoo approved these changes

2022-06-14 11:24 UTC, AntoineVDV requested changes

2022-06-14 11:24 UTC, AntoineVDV commented on content/applications/websites/website/publish/on-premise_geo-ip-installation.rst
> +   called ``GeoLite2-City.mmdb`` and ``GeoLite2-Country.mmdb``
We have a task to highlight file names differently so let's start flagging them with the `file` role already :)
```suggestion
   called :file:`GeoLite2-City.mmdb` and file:`GeoLite2-Country.mmdb`
```

2022-06-14 11:24 UTC, AntoineVDV commented on content/applications/websites/website/publish/on-premise_geo-ip-installation.rst
> +2. Move the files to the folder ``/usr/share/GeoIP/``
```suggestion
2. Move the files to the folder :file:`/usr/share/GeoIP/`
```

2022-06-14 11:24 UTC, AntoineVDV commented on content/applications/websites/website/publish/on-premise_geo-ip-installation.rst
> +   If you don't want to locate the geoip database in ``/usr/share/GeoIP/``, use the
```suggestion
   If you don't want to locate the geoip database in :file:`/usr/share/GeoIP/`, use the
```

2022-06-14 11:24 UTC, AntoineVDV commented on content/applications/websites/website/publish/on-premise_geo-ip-installation.rst
> +2. Move the files to the folder ``/usr/share/GeoIP/``
```suggestion
2. Move the files to the folder ``/usr/share/GeoIP/``.
```

2022-06-14 11:24 UTC, AntoineVDV commented on content/applications/websites/website/publish/on-premise_geo-ip-installation.rst
> +        mv ~/Downloads/GeoLite2-Country.mmdb /usr/share/GeoIP/
While you're at it, remove the extra indentation space before each of these lines that makes item 2. behave as a quote block. You'll also need to add an extra blank line after item 2.
```suggestion

   .. code-block:: bash

       mv ~/Downloads/GeoLite2-City.mmdb /usr/share/GeoIP/
       mv ~/Downloads/GeoLite2-Country.mmdb /usr/share/GeoIP/
```

2022-06-14 11:24 UTC, AntoineVDV commented on content/applications/websites/website/publish/on-premise_geo-ip-installation.rst
> +4. Save and refresh the page.
```suggestion
#. Save and refresh the page.
```
You'll most like need to properly indent the code block above to correctly align it with item 3. as it's currently misaligned.

2022-07-15 15:13 UTC, AntoineVDV requested changes

2022-07-15 15:13 UTC, AntoineVDV commented on content/applications/websites/website/publish/on-premise_geo-ip-installation.rst
> +        mv ~/Downloads/GeoLite2-Country.mmdb /usr/share/GeoIP/
See https://github.com/odoo/documentation/pull/2151#discussion_r896691507
![image](https://user-images.githubusercontent.com/15896813/179252389-43cf065e-12c3-48bc-b3b9-7d4f18b2970f.png)
```suggestion
   .. code-block:: bash

       mv ~/Downloads/GeoLite2-City.mmdb /usr/share/GeoIP/
       mv ~/Downloads/GeoLite2-Country.mmdb /usr/share/GeoIP/
```

2022-07-18 06:06 UTC, AntoineVDV approved these changes
@robodoo r+

2022-07-18 07:00 UTC, robodoo commented
Linked pull request(s) odoo/enterprise#27399, odoo/odoo#91337 not ready. Linked PRs are not staged until all of them are ready.

2022-12-14 14:01 UTC, AntoineVDV commented
@Julien00859 anything worth checking?

2022-12-14 14:38 UTC, Julien00859 commented
Nothing changed, it was just a rebase, thank for asking :)

2023-01-03 12:09 UTC, Julien00859 commented
@robodoo r+

2023-01-03 13:19 UTC, closed without merging