[FIX] Update epos_ssc.rst
odoo/documentation pull request #2180
Opened 2022-06-10 10:02 UTC by lse-odoo

Because of a recent Chrome security update, a lot of customers using peripheral devices (printers, ...) will have to follow this doc.

Therefore, I followed the doc and did the flow on my side. 

I modified 'Copy to file' to 'Export' and 'Trusted Root Certification Authorities' to 'Authorities' in order to have the exact same terms as in Chrome (I guess they updated their terms at some point).

2022-06-10 10:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2180).

2022-06-10 10:10 UTC, lse-odoo commented
@qle-odoo 
I did change the branch name for LMA and it looks like it was the issue for the check not being passed. Could you review it please ?

2022-06-10 11:11 UTC, qle-odoo approved these changes
@robodoo r+

2022-06-10 11:11 UTC, robodoo commented
I'm sorry, @qle-odoo. I'm afraid I can't do that.

2022-06-10 11:12 UTC, qle-odoo commented
@lse-odoo sorry i can't merge documentation
@LoredanaLrpz

2022-06-10 12:35 UTC, LoredanaLrpz approved these changes

2022-06-10 12:42 UTC, Feyensv approved these changes
@robodoo r+
(are you sure this change is not needed in the 13.0 documentation ?)

2022-06-10 12:44 UTC, Feyensv commented
@robodoo squash

2022-06-10 12:45 UTC, qle-odoo commented
> @robodoo r+ (are you sure this change is not needed in the 13.0 documentation ?)

No ePos in 13.0 so no doc...

2022-06-10 12:46 UTC, LoredanaLrpz commented
please, wait before merging I approved too fast

2022-06-10 12:49 UTC, Feyensv commented
@robodoo r-

2022-06-10 12:50 UTC, Feyensv commented
> please, wait before merging I approved too fast

If you're speaking of the commit message & title, with the 'squash' method, the merge commit will use the PR title & message ;).

2022-06-10 12:53 UTC, LoredanaLrpz requested changes
hello @lse-odoo , sorry I approved but didn't check the characters, I've made suggestions then I'll approve that PR :D

2022-06-10 12:53 UTC, LoredanaLrpz commented on content/applications/sales/point_of_sale/overview/epos_ssc.rst
> +Go to the *Details* tab and click on **Export**. Select X.509 in base 64 and save it.
```suggestion
Go to the :guilabel:`Details` tab and click on :guilabel:`Export`. Select X.509 in base 64 and save 
it.
```

2022-06-10 12:53 UTC, LoredanaLrpz commented on content/applications/sales/point_of_sale/overview/epos_ssc.rst
>  your previous file. Accept all warnings and restart your browser.
```suggestion
Go to the :guilabel:`Authorities` tab and click on :guilabel:`Import` and select your previous file. 
Accept all warnings and restart your browser.
```

2022-06-15 18:14 UTC, LoredanaLrpz approved these changes
@lse-odoo looks good to me :) ! Thank you =D

2022-06-16 09:11 UTC, Feyensv commented
@robodoo r+

2022-06-16 10:35 UTC, closed without merging