[IMP] accounting: adding a tip
odoo/documentation pull request #2238
Opened 2022-06-16 12:51 UTC by Donapi

https://www.odoo.com/web#id=2868642&cids=1&model=project.task&view_type=form

2022-06-16 12:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2238).

2022-06-16 13:17 UTC, xpl-odoo approved these changes
I would have phrased the last part of the sentence this way - but it's fine either way :)
_the invoice or bill's status is directly set to "paid"_

2022-06-20 13:13 UTC, jcs-odoo requested changes

2022-06-20 13:13 UTC, jcs-odoo commented on content/applications/finance/accounting/bank/setup/outstanding_accounts.rst
> +   is registered, the invoice or bill's status is directly set to "paid".
guilabel :)

2022-06-20 13:14 UTC, jcs-odoo commented
@Donapi Isn't this true in 14.0 as well?

2022-06-24 12:05 UTC, jcs-odoo commented
@robodoo r+

2022-06-24 12:28 UTC, jcs-odoo approved these changes

2022-06-24 14:07 UTC, closed without merging