[IMP] discuss: custom ICE server list optional
odoo/documentation pull request #2240
Opened 2022-06-17 00:47 UTC by mivu-odoo

This will edit the "Define a list of custom ICE servers" section in the
"Configure ICE servers with Twilio" v15.0 user doc. I added a line to
mention that defining a list of custom ICE servers is an optional step,
as Odoo only uses this list as a fallback if Twilio is not configured or
is not working at any given moment.

Fixes PR #1994
Closes Odoo Task [2882679](https://www.odoo.com/web#id=2882679&cids=3&model=project.task&view_type=form)

2022-06-17 00:48 UTC, mivu-odoo commented
Also, ignore the branch name, tired brain did this right after doing a PR for Helpdesk. The branch name incorrectly says "helpdesk" when it should be "discuss" lol

2022-06-17 00:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2240).

2022-06-17 00:50 UTC, mivu-odoo commented
@StraubCreative when you have the chance, can you review this? I only did a small content change as per Francisco Pinto Schröder (frps)'s feedback on the linked Odoo Task. Thank you!

2022-06-18 18:27 UTC, StraubCreative commented
> @StraubCreative when you have the chance, can you review this? I only did a small content change as per Francisco Pinto Schröder (frps)'s feedback on the linked Odoo Task. Thank you!

@samueljlieber this one too please :)

2022-06-21 19:38 UTC, samueljlieber requested changes
Overall this looks great - I just found a few sentences that exceeded 100 characters.  See my suggestions below!
- Line 19 needs to break before 'number.'
- Line 21 needs to break before 'questions:'
- Line 50 needs to break before ':guilabel:`Account SID`'

2022-06-27 18:45 UTC, mivu-odoo commented
Hello @samueljlieber !
Thank you for catching the lines that went over 100 characters! I went in and fixed those instances. Let me know if there's anything else I need to do :-)

2022-06-28 13:14 UTC, samueljlieber approved these changes
Hi @mivu-odoo! These changes look good to me 👍

2022-06-29 07:10 UTC, AntoineVDV approved these changes
@robodoo r+

2022-06-29 08:33 UTC, closed without merging