[IMP] developer/howtos: Add missing information about debug mode
odoo/documentation pull request #2286
Opened 2022-06-23 15:03 UTC by chevalierv

In chapter 3 of the developer core training, one is asked to click on a
button that is only shown in debug mode but there is no indication about
this mode in this chapter.

2022-06-23 15:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2286).

2022-06-23 15:27 UTC, Feyensv commented on content/developer/howtos/rdtraining/03_newapp.rst
> +   <https://www.odoo.com/documentation/user/general/developer_mode/activate.html>`_ as explained in
Nope :red_circle:

2022-06-24 14:05 UTC, AntoineVDV requested changes

2022-06-24 14:05 UTC, AntoineVDV commented on content/developer/howtos/rdtraining/03_newapp.rst
> +   Remind to enable :doc:`debug mode </applications/general/developer_mode/activate>` as explained in the previous
```suggestion
   Remember to enable the :ref:`developer mode <developer-mode>` as explained in the previous
```

2022-06-24 14:05 UTC, AntoineVDV commented on content/developer/howtos/rdtraining/03_newapp.rst
> +   chapter. You won't see the `Update Apps List` button if you don't.
```suggestion
   chapter. You won't see the :guilabel:`Update Apps List` button otherwise.
```

2022-06-24 14:55 UTC, AntoineVDV approved these changes
@robodoo r+

2022-06-24 16:38 UTC, closed without merging