[FIX] sale_amazon: fix information displayed
odoo/documentation pull request #2366
Opened 2022-07-01 14:47 UTC by Demesmaeker

Both carrier name and tracking reference are now displayed to the
customer, even when using the carrie `Self Delivery`

task-2900803

2022-07-01 14:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2366).

2022-07-05 22:39 UTC, meng-odoo requested changes
Hi @Demesmaeker, thanks for updating this doc! I made a small wording change to clarify where the carrier and tracking reference are displayed, but please let me know if it's incorrect.

2022-07-05 22:39 UTC, meng-odoo commented on content/applications/sales/sales/amazon_connector/manage.rst
> +     as the tracking reference are then displayed.
Small wording change for clarification.
```suggestion
   - Keep in mind that the customer is notified by email about the delivery, and the carrier and tracking reference are displayed in the email to the customer.
```

2022-07-06 18:13 UTC, meng-odoo approved these changes
Hi @Demesmaeker, the changes look perfect, thank you! I'll go ahead and tag technical review.

2022-07-07 08:29 UTC, AntoineVDV approved these changes
@robodoo r+

2022-07-07 09:30 UTC, closed without merging