15.0 bank accounts
odoo/documentation pull request #2417
Opened 2022-07-07 14:24 UTC by Donapi

[task 2607774](https://www.odoo.com/web#id=2607774&cids=1&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form)

2022-07-07 14:24 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2417).

2022-07-08 11:17 UTC, Donapi commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +   :alt: Bank journals are displayed on the Accounting Dashboard and contain actions buttons
here we don't mean parameters, it's really the actions, ie: 1 bill to pay

2022-07-08 11:26 UTC, xpl-odoo requested changes
Don't forget to `make html` - that's why you failed the documentation check (if you click on it, you will see the error _No "build succeeded." found in logs._)

2022-07-08 11:26 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +The :guilabel:`Bank Feeds` can be selected from the bank journal. 3 options are possibles:
```suggestion
:guilabel:`Bank Feeds` can be selected from the bank journal. Three options are available:
```
Numbers from zero to nine are usually spelled out. Always spell out numbers when they start a sentence.

2022-07-08 11:26 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +- :guilabel:`Automated Bank Synchronization`
```suggestion
- :guilabel:`Undefined yet`, which should be selected when you don’t know yet if you will sync your bank account
  with your database or not.
- :guilabel:`Import (CAMT, CODA, CSV, OFX, QIF)`, which should be used if you want to import your bank
  statements using a different format.
- :guilabel:`Automated Bank Synchronization`
```
It feels weird that you don't explain the last point, even if obvious.

2022-07-08 11:29 UTC, Donapi commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +If you need to **edit your bank account details**, click on the :guilabel:`Account number`. A new
no you really have to click on the bank account 
![image](https://user-images.githubusercontent.com/85342080/177983887-bdb2b995-a4b2-473d-b31c-d617ed03891c.png)
![image](https://user-images.githubusercontent.com/85342080/177983948-151f1c12-43e0-4522-96e6-e2a70b65d80c.png)

2022-07-08 11:49 UTC, Donapi commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
>  your database, you may also configure your bank account manually.
I updated as per most of your comments

2022-07-08 12:01 UTC, Donapi commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> -  transactions linked to this bank account or create a new one by clicking on *Create and Edit*.
Not sure it is really needed to describe those fields, and a short description of the fields is available when moving the computer mouse over it.

2022-07-08 12:58 UTC, Donapi commented
@xpl-odoo @toaa-odoo Thanks for your review guys!

2022-07-14 14:36 UTC, xpl-odoo approved these changes
Very small comments/suggestions, but it's good to go otherwise :)

2022-07-14 14:36 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +- :guilabel:`Undefined yet`, which should be selected when you don’t know yet if you will synchronize your
Line break after 100 characters

2022-07-14 14:36 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +   :doc:`../../bank/feeds/bank_synchronization`.
```suggestion
   :doc:`../../bank/feeds/bank_synchronization`
```
Not a sentence, full stop isn't needed

2022-07-14 14:36 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +A default bank journal is available and can be used to configure your bank account, by going to
```suggestion
A default bank journal is available and can be used to configure your bank account by going to
```
No comma

2022-07-14 14:36 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +:guilabel:`Bank journals` are displayed by default on the :guilabel:`Accounting Dashboard` in
```suggestion
:guilabel:`Bank journals` are displayed by default on the :guilabel:`Accounting Dashboard` in
```
Do `Bank journals` appear on the UI? (just asking, if not, no guilabel ;))

2022-08-03 08:15 UTC, toaa-odoo approved these changes

2022-10-26 15:14 UTC, jcs-odoo requested changes
Hello @Donapi @toaa-odoo and @xpl-odoo 

At last, I review it :D 
Thanks for the improvements.

I think you can improve the structure, though.

Currently, you have first a heading that says "create a new bank account" where the first instruction is actually to edit the existing one. Next heading (different level) explains how to "edit an existing account". And both headings contain content that is valid both for creation and editing.

I suggest you have a single heading for all that content, and sub-headings for all the different topics: bank account number, bank feeds, ... but also the suspense account, profit/loss accounts, currency. That's the kind of info that is useful in the documentation
+ links to related pages (currencies, outstanding accounts etc) 
Speaking of outstanding accounts, other tabs are still part of the bank configuration. But you can have that in separate docs if you prefer.

technical

- there are two commits. It looks like you intended to have only one. You squash them together (`git rebase -i 15.0` and `squash` the second commit instead of `pick`)
- The PR name isn't correct (there is a way to squash commits when we merge, and the resulting commit takes the name of the PR)
- filenames don't follow the [media files guidelines](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html#media-files)
  - hyphens `-` instead of underscores `_`
  - no need to rewrite the prefix bank-accounts in the filename since it's already in the folder name
-

2022-10-27 15:50 UTC, jcs-odoo approved these changes
Hi @Donapi 

I made a few changes and additions to your commit.
Mostly to move your content around without changing it, but also to add some links, a note in the intro, and a short section on how to add a cash journal.

[You can review my changes here](https://github.com/odoo/documentation/compare/9bf4ff8081ec9c2f766c85b4dcb366aafefad54f..98676d937fa6afbcd1560af43b07b19ce51479d1), but it looks heavier than it really is, since moving some paragraphs to another place looks like changing a lot of content.

Have a good day and thanks for the PR :)

2022-10-28 09:10 UTC, jcs-odoo commented on content/applications/finance/accounting/bank/setup/bank_accounts.rst
> +   - :doc:`../../bank/feeds/bank_synchronization`
Agreed!

2022-10-28 09:15 UTC, jcs-odoo commented
@robodoo r+

2022-10-28 10:54 UTC, closed without merging