[IMP] content/developer/webservices
odoo/documentation pull request #2481
Opened 2022-07-14 11:42 UTC by Julien00859

It is hard to find and learn about RPC in Odoo, users hardly know about
JSON-RPC as the only place where we talk about it in deep down in the
*How to make a Module* tutorial.

In the commit, we isolated the tutorial about RPC in a dedicated file,
that file is better referenced thanks to cross-references in some others
places that are talking about RPC

Task: 2884559

Rebased to 15.0 from master #2427

2022-07-14 11:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2481).

2022-07-14 11:44 UTC, robodoo commented
I'm sorry, @Julien00859. You can't method=rebase-ff.

2022-07-14 12:43 UTC, AntoineVDV requested changes

2022-07-14 12:43 UTC, AntoineVDV commented on content/developer/api/external_api.rst
> +.. warning::
This is not exactly a warning; more like an important note.
```suggestion
.. important::
```

2022-07-14 12:43 UTC, AntoineVDV commented on content/developer/api/external_api.rst
> +.. warning::
Also I'd swap it with the `seealso`.

2022-07-14 12:43 UTC, AntoineVDV commented on content/developer/api/external_api.rst
> +   for installation steps.
```suggestion
   Starting with PHP8, the XML-RPC extension may not be available by default.
   Check out the `manual <https://www.php.net/manual/en/xmlrpc.installation.php>`_
   for the installation steps.
```

2022-07-14 18:36 UTC, AntoineVDV commented
@robodoo r+ rebase-ff

2022-09-13 17:11 UTC, jcs-odoo commented
It looks like this r+ didn't go through...
@AntoineVDV @Julien00859

2022-09-14 08:25 UTC, AntoineVDV commented
@robodoo r+ rebase-ff

2022-09-14 08:26 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-09-14 09:30 UTC, closed without merging