[IMP] accounting: update and improve the cash basis taxes documentation
odoo/documentation pull request #2500
Opened 2022-07-19 08:26 UTC by Donapi

[ID: 2381690](https://www.odoo.com/web#id=2381690&cids=1&model=project.task&view_type=form)

2022-07-19 12:00 UTC, chiaraprattico requested changes
Nice doc,  just some aspects could be clearer.

2022-07-19 12:00 UTC, chiaraprattico commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +basis method is mandatory in some countries and under some conditions.
Cash basis taxes are due when the payment is made, as opposed to standard taxes that are due when
the invoice is confirmed. Reporting your income and expenses to the government based on the cash
basis method is mandatory in some countries and under some conditions.

2022-07-19 12:00 UTC, chiaraprattico commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +:guilabel:`Short Code` that displays the journal entries of this journal.
Maybe add " save" in the end?

2022-08-08 08:43 UTC, Donapi commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +correct tax reports in Odoo with accurate base tax amounts.
yes, correct!

2022-10-21 15:16 UTC, xpl-odoo reviewed
Quelques petits changements :)

2022-10-21 15:16 UTC, xpl-odoo commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +correct tax reports in Odoo with accurate base tax amounts.
```suggestion
The journal items :guilabel:`Income account` vs. :guilabel:`Income account` are neutral, but they are needed to ensure
correct tax reports in Odoo with accurate base tax amounts.
```

2022-10-24 07:33 UTC, Donapi commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +:guilabel:`Based on Payment`, so the tax is due as soon as the payment of the invoice is received.
What they should do depends on their needs. Here, I explained they should select Based on Payment so the tax is due when the payment is received. Not sure to understand your point :)

2022-10-26 11:17 UTC, xpl-odoo commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +:guilabel:`Based on Payment`, so the tax is due as soon as the payment of the invoice is received.
Reading the doc, I had the feeling we **had** to select **Based on Payment** to make the feature work as intended. If it's just a possibility, I would either:

- specify what both options do. Something like: _If the tax should due as soon as the payment is received, select Based on Payment. If it should be due as soon as the invoice is validated, select Based on Invoice_)
- or make it clear it's an example: _For example, select Based on Payment, so the tax..._

2022-10-26 11:20 UTC, xpl-odoo commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +the sales of a product that costs 1.000$, with a cash basis tax of 15%.
Missed one: comma instead of a period used as the separator 1.000 -> 1,000

2022-10-26 11:22 UTC, xpl-odoo commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +| Receivable $1.150          |                            |
Comma instead of a period as the separator 1.150 -> 1,150

2022-10-26 11:26 UTC, xpl-odoo commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +The following entries are created in your accounting and the tax report is currently empty.
According to Grammarly:
![image](https://user-images.githubusercontent.com/70884563/198014270-77533a12-2495-46c7-9862-bf1faed4cdcb.png)
I would follow Grammarly's suggestion on this one, but feel free to leave it out ;)

2022-10-26 11:34 UTC, xpl-odoo approved these changes
Check my comments to address a couple of small things. I already approve the PR though so it goes faster ;)

2022-10-26 13:17 UTC, chiaraprattico commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +:guilabel:`Based on Payment`, so the tax is due as soon as the payment of the invoice is received.
I guess based on payments is enough as the doc is specifically Cash basis, maybe a note can be added saying that for "normal" tax there is the "based on invoice".

2022-10-27 06:58 UTC, Donapi commented on content/applications/finance/accounting/taxation/taxes/cash_basis_taxes.rst
> +:guilabel:`Based on Payment`, so the tax is due as soon as the payment of the invoice is received.
It is explained in the first paragraph of this doc: "Cash basis taxes are due when the payment is made, as opposed to standard taxes that are due when the invoice is confirmed." So I think it's ok to only mention what applies to cash basis taxes.

2022-10-27 07:10 UTC, chiaraprattico approved these changes

2022-10-28 08:43 UTC, AntoineVDV approved these changes
@robodoo r+

2022-10-28 09:49 UTC, closed without merging