[FIX] odoo_sh: change img who explain storage space
odoo/documentation pull request #2582
Opened 2022-08-10 15:18 UTC by roussieau

The image that explains the storage in odoo.sh is outdated. 

https://www.odoo.com/web#id=2948233&cids=1&menu_id=4720&action=333&active_id=1105&model=project.task&view_type=form

2022-08-10 15:19 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2582).

2022-08-16 15:43 UTC, amigrave commented
@robodoo r+

2022-08-16 15:43 UTC, robodoo commented
I'm sorry, @amigrave. I'm afraid I can't do that.

2022-08-18 05:32 UTC, Lau-Odoo approved these changes

2022-08-18 06:57 UTC, jcs-odoo requested changes
Hello @roussieau 

Thanks for your contribution to the doc.

- Image files must be compressed with pngquant (see [content guidelines: images](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html#images))
- you target 15.0 on this PR which is probably a mistake, considering the page is the same from 13.0. To change the target of the PR, please set it as a draft before you do this change, otherwise, all codeowners of this repo would get a notification.

Thanks :)

@amigrave you can't r+ on this repo I'm afraid. Nothing to do, though. Once a PR is ready for review, the right codeowners get notified.

@Lau-Odoo you must check if images are compressed and make sure the target is right before you approve a PR.

2022-08-18 13:41 UTC, closed without merging

2022-08-18 13:42 UTC, roussieau commented
I opened a new PR that targets the 13.0 with the compressed image. #2607