[IMP] accounting: updated chart of accounts v15
odoo/documentation pull request #2657
Opened 2022-09-01 12:01 UTC by toaa-odoo

Creating account groups part was outdated.

task id: 2950820

2022-09-02 07:23 UTC, chiaraprattico approved these changes

2022-09-19 19:35 UTC, toaa-odoo commented
@jcs-odoo kind reminder if you have time

2022-09-20 14:42 UTC, jcs-odoo requested changes
Hello @toaa-odoo and @chiaraprattico (Chiara, pay attention to the comment about the dev mode, it's important to check this as a reviewer too).

since you're updating the page, here are some elements that could be updated as well.

- replace `*` list marks with `-` instead
- rename old image files (hyphens instead of underscores and no numbering)

Also, I think these changes can be applied from 14.0, even if your new screenshot isn't exactly the same, that's okay :)

2022-09-28 12:45 UTC, toaa-odoo commented
@jcs-odoo It's the PR with which we had issues and had to turn into a draft, and force-push, and then make it ready. I don't think it was merged yet ?

2022-11-09 14:13 UTC, toaa-odoo commented on content/applications/finance/accounting/getting_started/initial_configuration/chart_of_accounts.rst
> +the payment. Therefore, the account used to record credit card payments needs to be configured as
Yes, you should work in accounting

2022-11-09 14:20 UTC, toaa-odoo commented
@xpl-odoo Could you have a (final) look ? :)

2022-11-10 08:05 UTC, toaa-odoo commented on content/applications/finance/accounting/getting_started/initial_configuration/chart_of_accounts.rst
> +   intended for rare and advanced use cases.
Done! Pinging doc-review

2022-11-10 10:32 UTC, AntoineVDV requested changes

2022-11-10 10:32 UTC, AntoineVDV commented on content/applications/finance/accounting/getting_started/initial_configuration/chart_of_accounts.rst
> +app-->Reporting-->Trial Balance`, then open the :guilabel:`Options` menu and select
Broken markup
![image](https://user-images.githubusercontent.com/15896813/201067492-cb603f75-3fb2-42ba-b4fe-68852226f319.png)

```suggestion
app --> Reporting --> Trial Balance`, then open the :guilabel:`Options` menu and select
```

2022-11-10 10:38 UTC, toaa-odoo commented on content/applications/finance/accounting/getting_started/initial_configuration/chart_of_accounts.rst
> +app-->Reporting-->Trial Balance`, then open the :guilabel:`Options` menu and select
Fixed

2022-11-10 13:01 UTC, AntoineVDV approved these changes
@robodoo r+

2022-11-10 13:48 UTC, closed without merging