[IMP] extensions/spoilers: add an extension for spoilers
odoo/documentation pull request #2837
Opened 2022-10-21 13:40 UTC by AntoineVDV

It is often needed in developer tutorials to show excerpts of code for examples and solutions. This takes quite some page space and, for the latter, it is not always desired to show the final code result right after the exercise objective.

This commit adds a spoiler feature to the documentation to allow hiding content until the reader wants to display it.

The feature relies on the new `.. spoiler:: Button label` directive.

task-3036845

2022-10-21 13:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2837).

2022-10-24 12:52 UTC, jcs-odoo requested changes

2022-10-24 13:09 UTC, AntoineVDV commented on content/contributing/documentation/rst_cheat_sheet.rst
> +          .. spoiler:: Answer to the Ultimate Question of Life, the Universe, and Everything
Yes, but it's not the content (that is `42`) but the button's label

I could change it, but this is actually a good usage of directive labels, and that'd require options like `:button-label: something somethin`.

2022-10-24 13:12 UTC, jcs-odoo commented on content/contributing/documentation/rst_cheat_sheet.rst
> +          .. spoiler:: Answer to the Ultimate Question of Life, the Universe, and Everything
Ah okay sorry I didn't check the render.

2022-10-24 13:12 UTC, jcs-odoo approved these changes

2022-10-28 09:28 UTC, AntoineVDV commented
@robodoo r+ rebase-ff

2022-10-28 09:29 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2022-10-28 10:17 UTC, closed without merging