[IMP] accounting: fiscal year
odoo/documentation pull request #2850
Opened 2022-10-25 13:16 UTC by chiaraprattico

taskid: 2823858

2022-10-25 13:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2850).

2022-10-31 13:51 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +ensure that your accounting is correct, up to date, and accurate:
up-to-date

2022-10-31 13:52 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +- Make sure you have fully reconciled your **bank account(s)** up to year end and confirm that your
year-end

2022-10-31 14:02 UTC, Donapi requested changes

2022-10-31 14:08 UTC, Donapi requested changes

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +During this process, it is good practice to set the **Lock date for Non-Advisers** to the last day
:guilabel:?

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +During this process, it is good practice to set the **Lock date for Non-Advisers** to the last day
add the path to set the lock date?

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +   On this screen, you also have a field :guilabel: `all users Lock date`. This lock date will
guilabel didn't work

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +   The all journal entries lock date prevents journal entry creation or modification prior the
```suggestion
   The "all journal entries" lock date prevents journal entry creation or modification prior the
```

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +There is no need to do a specific year end closing entry in order to close out your Profit and Loss
```suggestion
There is no need to do a specific year-end closing entry to close out your Profit and Loss
```

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +**Income Statement**, the beginning date will correspond with the beginning of the **Fiscal Year**
```suggestion
**Income Statement**, the beginning date corresponds with the beginning of the **Fiscal Year**
```

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +**Current Year Earnings**, you should set the **Lock Date** to the last day of the fiscal year.
guilabel?

2022-10-31 14:08 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +**Balance Sheet** is correctly reporting a 0 balance.
guilabel?

2022-11-04 12:54 UTC, Donapi requested changes

2022-11-04 12:54 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +ensure that your accounting is correct, up-to-date, and accurate:
```suggestion
Before going ahead with closing a fiscal year,  a few steps should be taken to
ensure that your accounting is correct, up-to-date, and accurate:
```

2022-11-04 12:54 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +-  Book all the :guilabel:`Depreciation` and :guilabel:`Deferred Revenues`.
general comments: add "see also" in this section or hyperlinks, to link to the related document pages?

2022-11-04 12:54 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +auditing the books.
I would maybe add this as an important note

2022-11-04 12:54 UTC, Donapi commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +the :guilabel:`Income Statement`, the beginning date will correspond with the beginning of the
```suggestion
the :guilabel:`Income Statement`, the beginning date corresponds with the beginning of the
```

2023-02-16 09:58 UTC, xpl-odoo commented
Hi @chiaraprattico!
Is there a reason why this PR is on hold? If it's currently "blocked" for some reason, you can put it in draft - or close if the PR is now irrelevant somehow. If you need a review, you know what to do 😉 
(just trying to clean up the pipeline a tiny bit)

2023-03-31 15:12 UTC, xpl-odoo requested changes
I'm going to push some changes myself.

- I removed most guilabels as you aren't referring to elements on screens (you aren't giving precise instructions to follow here, but more describing the general conceptual process).

- I added links to other docs where I could. Could you check if there are other/better links that could be added? It may be necessary to create `:ref:` on other pages first.

- The year-end checklist is something you do before closing the year, no? Maybe that could be mentioned in the heading somehow.

2023-03-31 15:12 UTC, xpl-odoo commented on content/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.rst
> +  This lock date is reversible and can be removed.
I can't find this field, and the description seems very similar to the **lock date for non-advisers** field, right? I removed it for now.

2023-05-25 10:21 UTC, xpl-odoo commented
@chiaraprattico Do you think this PR can be merged as it is?
I can either r+, put in draft, or close the PR - let me know what you prefer 😃

2023-05-25 10:42 UTC, jcs-odoo commented
info for the forward-port: this file moved in 15.0, and the other fiscal_year.rst file about the configuration was deleted and its content was merged into this page. If needed I can help with the resolution of the conflicts.
(I haven't read the content of this pr)

2023-06-23 14:06 UTC, xpl-odoo commented
@chiaraprattico @jcs-odoo merge or trash?

2025-02-10 06:40 UTC, robodoo commented
@chiaraprattico the target branch '14.0' has been disabled, you may want to close this PR.

2025-02-10 08:20 UTC, closed without merging