14.0 batch sdd chpr
odoo/documentation pull request #2867
Opened 2022-10-27 14:48 UTC by chiaraprattico

2022-11-03 07:39 UTC, toaa-odoo requested changes
Great PR! Just a small suggestion, you wrote both XML and .XML, it's best to be consistent throughout :)

2022-11-03 07:39 UTC, toaa-odoo commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
>  Clicking on **Close** updates the mandate’s end day to the current day. This means that invoices
```suggestion
Clicking on :guilabel:`Close` updates the mandate’s end day to the current day. This means that invoices
```

2022-11-03 07:39 UTC, toaa-odoo commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +Direct Debit mandates are closed automatically after their **End Date**. If this field is left
```suggestion
Direct Debit mandates are closed automatically after their :guilabel:`End Date`. If this field is left
```

2022-11-03 07:39 UTC, toaa-odoo commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
>     required by the SEPA customer-to-bank Implementation Guidelines, which ensures compatibility with
```suggestion
   required by the SEPA customer-to-bank `implementation guidelines <https://www.europeanpaymentscouncil.eu/document-library/implementation-guidelines/sepa-credit-transfer-customer-psp-implementation>`_, which ensures compatibility with
```

2022-11-03 07:39 UTC, toaa-odoo commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +To do so go to :menuselection:`Customers --> Payments`, select the needed payments and then click on
```suggestion
To do so, go to :menuselection:`Customers --> Payments`, select the needed payments, then click on
```

2022-11-03 07:39 UTC, toaa-odoo commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +:guilabel:`Action` and finally :guilabel:`Create a batch Payment`. Once you click on
```suggestion
:guilabel:`Action`, and finally :guilabel:`Create a batch Payment`. Once you click on
```

2022-11-04 13:05 UTC, toaa-odoo approved these changes

2022-11-08 12:13 UTC, AntoineVDV requested changes

2022-11-08 13:43 UTC, chiaraprattico commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +You can record customer mandates in Odoo, and generate `.xml` files containing pending payments made
Not necessarily but it's to be consistent with what's on odoo dbs

2022-11-08 14:53 UTC, AntoineVDV commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +You can record customer mandates in Odoo, and generate `.xml` files containing pending payments made
Oh god.

2022-11-08 15:00 UTC, AntoineVDV requested changes

2022-11-08 15:00 UTC, AntoineVDV commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +The :abbr:`SDD` Mandate is the document that your customers sign to authorize you to collect
Abbreviations must follow [this format](https://www.odoo.com/documentation/master/contributing/documentation/rst_cheat_sheet.html#abbreviations) to work.

2022-11-08 15:00 UTC, AntoineVDV commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +click on :guilabel:`Create`, and fill out the form.
Like this:
```suggestion
To create a new mandate, go to :menuselection:`Accounting app --> Customers -->
Direct Debit Mandates`, click on :guilabel:`Create`, and fill out the form.
```

2022-11-08 15:00 UTC, AntoineVDV commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +Export the PDF file by clicking on :guilabel:`Print`. It is then up to your customer to sign this
Also, don't force a line break in RST when you don't intend to break the line in HTML.

2022-11-08 15:00 UTC, AntoineVDV commented on content/applications/finance/accounting/receivables/customer_payments/batch_sdd.rst
> +     <https://www.europeanpaymentscouncil.eu/document-library/implementation-guidelines/sepa-credit-transfer-inter-psp-implementation-guidelines>`_
This should probably be written somewhere, but the guideline is to always have exactly 1 blank line at the end of each file. That's true for many languages (not only RST). This helps editors highlight the code correctly.
```suggestion
     <https://www.europeanpaymentscouncil.eu/document-library/implementation-guidelines/sepa-credit-transfer-inter-psp-implementation-guidelines>`_

```

2022-11-09 10:02 UTC, AntoineVDV commented
Hello @chiaraprattico, https://github.com/odoo/documentation/pull/2867#discussion_r1016741618 is still unresolved, and unresolved https://github.com/odoo/documentation/pull/2867#discussion_r1016743140 because the change was not applied.

2022-11-25 09:18 UTC, AntoineVDV approved these changes
@robodoo r+

2022-11-25 10:31 UTC, closed without merging