[ADD] accounting: provide information on the tax carryover feature
odoo/documentation pull request #2889
Opened 2022-10-31 12:57 UTC by Donapi

2022-10-31 12:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2889).

2022-11-02 08:38 UTC, chiaraprattico requested changes

2022-11-02 08:38 UTC, chiaraprattico commented on content/applications/finance/accounting/reporting/overview/tax_carryover.rst
> +transferred from period to period (for example, because the total of the line is negative).
It has been created to meet the legal requirements of specific locations, where amounts must be transferred from period to period (for instance, when the total of a line is negative).

2022-11-02 08:38 UTC, chiaraprattico commented on content/applications/finance/accounting/reporting/overview/tax_carryover.rst
> +Italy. There is no specific configuration required.
The feature is activated by default in countries where it is required, such as Belgium, France, and
Italy. There is no specific configuration required.

2022-11-02 08:38 UTC, chiaraprattico commented on content/applications/finance/accounting/reporting/overview/tax_carryover.rst
> +   :alt: pop-up message stating the amount will be carried over to the next period
Not sure this last image is compressed , also not sure about the previous ones. As well as not sure if the zoom is 100% --> should be 110%

2022-11-02 08:38 UTC, chiaraprattico commented on content/applications/finance/accounting/reporting/overview/tax_carryover.rst
> +period based on the existing transactions and the carryover from the previous period.
At the time of the tax closing period, the tax report shows that the amount was carried over from the
previous period. It also indicates the amount that will be carried over to this line in the next
period based on the existing transactions and the carryover from the previous period.

2022-11-04 08:01 UTC, chiaraprattico approved these changes

2022-11-14 14:39 UTC, Donapi commented on content/applications/finance/accounting/reporting/overview/tax_carryover.rst
> +.. image:: tax_carryover/pop-up.png
on my side it looks ok... last time you told me my screenshots were too small :D we can check together at the office if needed!

2022-11-14 14:39 UTC, Donapi commented on content/applications/finance/accounting/reporting/overview/tax_carryover.rst
> +.. image:: tax_carryover/tax-return.png
same feedback than before :)

2022-11-15 09:32 UTC, AntoineVDV approved these changes
@robodoo r+

2022-11-15 10:43 UTC, closed without merging