[IMP] ecommerce: updated build product page
odoo/documentation pull request #2903
Opened 2022-11-04 12:45 UTC by toaa-odoo

Updated build product page. Forward to 15.0

taskid:

2022-11-04 12:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2903).

2022-11-08 13:47 UTC, LoredanaLrpz requested changes
Hello there @toaa-odoo !
Here are my suggestions :)

2022-11-09 14:27 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
Woops

2022-11-09 14:29 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
> +- From the front-end, by clicking on :menuselection:`+ New --> Product`;
I added a note anyways

2022-11-09 14:33 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
> +quality and explicit images.
good quality and explicit images is correct, no "-". Perhaps Grammarly suggested you something different?

2022-11-09 14:37 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
> +- :guilabel:`Can be Rented`: the product can be rented by the customer for a select period;
Good catch

2022-11-09 14:54 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
> +   to display a product in only two of them.
I changed the note a bit, let me know if it's clearer.

2022-11-09 15:03 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
> +**all product pages**. The **HTML** is stored on the **QWeb** view.
It might be 15+ only, I removed that part

2022-11-09 15:03 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
> +.. image:: product_page/ecommerce-building-blocks.png
Removed with the previous part

2022-11-09 15:08 UTC, toaa-odoo commented on content/applications/websites/ecommerce/getting_started/product_page.rst
> +backend --> Configuration --> Settings --> Products`.
Well, back-end and front-end or not the same thing. Front-end is the part where you see the shop, etc. Back-end is where you can do all the configuration, settings, etc. The customer never sees the back-end.

2022-11-15 08:23 UTC, LoredanaLrpz approved these changes

2023-03-24 13:34 UTC, closed without merging