[FIX] deploy: wsgi application entrypoint moved
odoo/documentation pull request #2927
Opened 2022-11-09 11:57 UTC by Julien00859

The wsgi application entrypoint moved during the httpocalypse. Some clients don't use the odoo builtin wsgi server and have troubles upgrading from 15.0 to 16.0 because the `odoo.service.wsgi_server` module doesn't exist anymore.

https://github.com/odoo/odoo/pull/105434

2022-11-09 11:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2927).

2022-11-09 12:29 UTC, Gorash approved these changes

2022-11-14 13:01 UTC, Julien00859 commented
@robodoo r+

2022-11-14 13:02 UTC, robodoo commented
I'm sorry, @Julien00859: you can't review+.

2022-11-14 13:19 UTC, Feyensv approved these changes
@robodoo r+

2022-11-14 13:26 UTC, AntoineVDV commented
@robodoo r-

2022-11-14 13:33 UTC, AntoineVDV requested changes
Hello, I really don't think this is the place to mention a path change that is not referenced in the paragraphs above. I feel like this is a bandage for a missing deprecation warning, an upgrade changelog, or similar.

The user documentation should neither be formatted as a changelog nor dispense upgrade advises. Instead, we should rather keep it factual and up-to-date: on a given version (here 15.3), this deployment guide should give the required steps, no more no less.

2022-11-14 13:56 UTC, Julien00859 commented
We restored the `wsgi_server` module with its `application` function with a deprecation warning. The deprecation warning replaces the `versionchanged` of this PR

2022-11-14 13:56 UTC, closed without merging