[IMP] accounting: checks payment
odoo/documentation pull request #2934
Opened 2022-11-10 14:23 UTC by chiaraprattico

2022-11-14 09:49 UTC, jaae-odoo requested changes
Hey, just a few minor typos, nothing else to add :)

2022-11-14 09:49 UTC, jaae-odoo commented on content/applications/finance/accounting/payables/pay/check.rst
> +sent to suppliers with actual bank statements.
```suggestion
Once you decide to pay a supplier bill, you can select to pay by check. You can then print all the
registered payments by check. Finally, the bank reconciliation process will match the checks you
sent to suppliers with actual bank statements.
```

2022-11-14 09:49 UTC, jaae-odoo commented on content/applications/finance/accounting/payables/pay/check.rst
> +In the :guilabel:`Outgoing Payments` tab, add :guilabel:`Checks` as a payment method.
```suggestion
The first necessary step to pay by check is to activate the setting. To do so, go to
:menuselection:`Accounting app --> Configuration --> Checks`, there you can activate the payment
method as well as set up the :guilabel:`Check Layout`.
Once you have activated the setting, you must also activate the payment method on related bank
journals. Go to :menuselection:`Accounting dashboard --> Bank Journal --> drop-down menu (⋮) -->
Configuration`.
In the :guilabel:`Outgoing Payments` tab, add :guilabel:`Checks` as a payment method.
```

2022-11-14 09:49 UTC, jaae-odoo commented on content/applications/finance/accounting/payables/pay/check.rst
> +   checks.
```suggestion
.. note::
   Some countries require specific modules to print checks; such modules may be installed by
   default. For instance the :guilabel:`U.S. Check Printing` module is required to print U.S.
   checks.
```

2022-11-14 09:49 UTC, jaae-odoo commented on content/applications/finance/accounting/payables/pay/check.rst
> +to print the checks reconciled.
```suggestion
On your :guilabel:`Accounting Dashboard` in the :guilabel:`Bank Journal`, you can see the
number of checks registered. By clicking on :guilabel:`Checks to print` you have got the possibility
to print the reconciled checks.
```

2022-11-15 10:32 UTC, jaae-odoo approved these changes

2022-11-15 10:39 UTC, jaae-odoo approved these changes

2022-12-01 11:44 UTC, xpl-odoo approved these changes

2022-12-01 15:47 UTC, AntoineVDV approved these changes
@robodoo r+

2022-12-01 17:54 UTC, closed without merging