[IMP] payment_providers,stripe: rename payment icon to payment method
odoo/documentation pull request #2955
Opened 2022-11-15 15:22 UTC by anko-odoo

task-2882564

Changing every occurrence of Payment Icon to Payment Method.

2022-11-15 15:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/2955).

2022-11-17 08:23 UTC, toaa-odoo requested changes
Just a small change, because the sentence was a bit confusing :)

2022-11-17 08:23 UTC, toaa-odoo commented on content/applications/finance/payment_providers.rst
> +**Displayed as** field and which credit card icons to display under the **Supported Payment Methods**
```suggestion
**Displayed as** field, and the supported credit card icons displayed under the **Supported Payment Methods**
```

2022-11-17 14:34 UTC, anko-odoo commented on content/applications/finance/payment_providers.rst
> +**Displayed as** field and which credit card icons to display under the **Supported Payment Methods**
Done :)

2022-11-21 16:51 UTC, chevalierv approved these changes
LGTM :+1:

2022-11-22 07:22 UTC, toaa-odoo approved these changes
LGTM 2

2023-01-17 15:48 UTC, AntoineVDV approved these changes
@robodoo r+

2023-01-17 16:00 UTC, robodoo commented
@anko-odoo @AntoineVDV linked pull request(s) odoo/odoo#105678, odoo/upgrade#4029 not ready. Linked PRs are not staged until all of them are ready.

2023-01-18 16:00 UTC, robodoo commented
@anko-odoo @AntoineVDV linked pull request(s) odoo/upgrade#4029 not ready. Linked PRs are not staged until all of them are ready.

2023-01-20 18:56 UTC, closed without merging