[ADD] Spreadsheet/Reporting/Search
odoo/documentation pull request #3000
Opened 2022-11-21 16:26 UTC by xpl-odoo

Task ID: 3053800

2022-11-21 16:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3000).

2022-12-09 12:25 UTC, xpl-odoo commented
@AntoineVDV After discussing with @jcs-odoo, we figured it would be better to create two additional pages under `/general/`, namely **Search and filter records** and **Reporting** rather than include that information directly under Spreadsheet.
Learning about filtering and using the "dynamic" reporting views is important for configuring pivots and graphs before inserting them in a spreadsheet. Yet, the information was quite general and could benefit other apps, hence the move (and adaptation) to the Miscellaneous section; at least until we find a better place in a potential future revision of the structure.

Note: we also moved the Spreadsheet section under the `/finance/` to respect the odoo.com app menu (although Spreadsheet is actually inside the Documents app page), so the codeowner check is failing.

2022-12-09 14:15 UTC, AntoineVDV commented
@xpl-odoo It's not a problem if the check is red until the final tech review. It's actually less work for me as your last comment can attest :p

2023-02-08 12:48 UTC, LoredanaLrpz requested changes
Hey @xpl-odoo , there you go :)
Please ask me anything tomorrow if needed (or if you want to think about the structure together)

2023-02-08 12:48 UTC, LoredanaLrpz commented on content/applications/general/search.rst
> +   If the records should *only* match one of several conditions, click :guilabel:`Add a condition`
I've noted an inconsistency between "click" and "click on", I don't mind if it differs from one page to another, but I feel like it's weird to switch on the same page

2023-02-13 13:36 UTC, xpl-odoo commented on content/applications/finance/spreadsheet.rst
> +   :alt: Spreadsheet main UI elements
Indeed, the original image wasn't looking great. I took your 4th design as a basis for the new version, thanks a lot for the suggestions :)

2023-02-13 13:46 UTC, xpl-odoo commented on content/applications/finance/spreadsheet/insert.rst
> +Where you need to click depends on the element:
I think the sentence wasn't really necessary. I removed it.

2023-02-13 13:54 UTC, xpl-odoo commented on content/applications/finance.rst
> +    finance/spreadsheet
I already had this discussion with @jcs-odoo and we decided to put it under finance, so I'm leaving it there.

Note, you can create spreadsheets from anywhere using the "insert in spreadsheet" button. Now to manage them, you need to open Documents first.

2023-02-13 15:14 UTC, xpl-odoo commented on content/applications/finance/spreadsheet/insert.rst
> +   Data --> Refresh all data`.
I will get rid of the menuselection then
![image](https://user-images.githubusercontent.com/70884563/218493811-a954854c-c468-426b-804e-f558b0fe6d06.png)

2023-02-13 15:40 UTC, xpl-odoo commented on content/applications/finance/spreadsheet/insert.rst
> +would be added.
Indeed, some clarifications were in order ;)

2023-02-13 16:09 UTC, xpl-odoo commented on content/applications/general/reporting.rst
> +
I think it's interesting to see the same report evolves across different examples that build upon the previous ones.

2023-02-15 12:44 UTC, xpl-odoo commented on content/applications/general/reporting.rst
> +<search/group>` depending on the dimension you want to analyze. A typical default group is *Date >
The default isn't always _Date > Month_, but I could say "By default, the data is _often_ grouped by..."

2023-02-15 13:00 UTC, xpl-odoo commented on content/applications/general/reporting.rst
> +
I agree it might be a bit image intensive, but I feel it helps understand/find where to click.

2023-02-15 13:22 UTC, xpl-odoo commented on content/applications/general/reporting.rst
> +**preconfigured groups**. To remove one, click the minus button (:guilabel:`➖`).
I agree. But grouping measures applies to both graph and pivot views, so I felt it was important to mention grouping at this stage already. I go more in depth regarding grouping for the pivot view.

2023-02-15 13:23 UTC, xpl-odoo commented on content/applications/general/reporting.rst
> +
Since it applies to both the graph and pivot views, I don't go into too many details here.

2023-02-15 13:28 UTC, xpl-odoo commented on content/applications/general/search.rst
> +   On the Sales Analysis report, only records at the sales order stage are selected by default.
I know, but I sometimes ignore Grammarly. As it's an example, I think starting with the context (i.e., on the sales analysis report)

2023-02-15 13:34 UTC, xpl-odoo commented on content/applications/general/search.rst
> +   a divider, a thin horizontal line), the records can match *any* condition to be included.
I rephrased - the sentence was indeed a bit "heavy"

2023-02-23 13:26 UTC, AntoineVDV approved these changes
@robodoo r+

2023-02-23 14:37 UTC, closed without merging