[IMP] documentation: legal page design
odoo/documentation pull request #3058
Opened 2022-12-01 10:08 UTC by morm-odoo

Prior to this commit, the terms and conditions were displayed in a table with all the languages and it was not practical for the futur, with many more languages.

2022-12-01 10:09 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3058).

2022-12-01 11:04 UTC, AntoineVDV requested changes
Looking good! Just a few things to change. :point_down:

2022-12-01 16:05 UTC, AntoineVDV requested changes

2022-12-01 16:05 UTC, AntoineVDV commented on extensions/odoo_theme/layout_templates/legal.html
> +                                <a class="btn btn-primary" target="_blank" href="{{ enterprise_agreement_path }}" role="button">{{ _("Read") }}</a>
```suggestion
                            <a class="btn btn-primary" target="_blank" href="{{ enterprise_agreement_path }}" role="button">{{ _("Read") }}</a>
```

2022-12-01 16:05 UTC, AntoineVDV commented on extensions/odoo_theme/layout_templates/legal.html
> +                            </a>
```suggestion
                                <a class="btn btn-light text-primary" target="_blank" href="legal/terms/partnership.html">
                                    English
                                </a>
```

2022-12-01 16:05 UTC, AntoineVDV commented on extensions/odoo_theme/layout_templates/legal.html
> +                            </a>
```suggestion
                                <a class="btn btn-light text-primary" target="_blank" href="legal/terms/terms_of_sale.html">
                                    English
                                </a>
```

2022-12-01 16:05 UTC, AntoineVDV commented on extensions/odoo_theme/layout_templates/legal.html
> +                            {%- set enterprise_agreement_path = 'legal/terms/i18n/enterprise_%s.html' % language_code %}
The path for documents in English is `legal/terms/enterprise.html`. Clicking on Read in English leads to a 404.

2022-12-01 16:05 UTC, AntoineVDV commented on extensions/odoo_theme/layout_templates/legal.html
> +                    <a class="fn-backref" href="#id1">1</a>
Clicking on this breaks the [1] in the card:

![image](https://user-images.githubusercontent.com/15896813/205101301-72cd8c23-2933-4329-959c-0882691f1c6a.png)

2022-12-01 16:23 UTC, morm-odoo commented on extensions/odoo_theme/layout_templates/legal.html
> +                                <a class="btn btn-light text-primary" target="_blank" href="legal/terms/enterprise.html">
It's on target blank in the current design, should I change it?

2022-12-01 16:24 UTC, AntoineVDV commented on extensions/odoo_theme/layout_templates/legal.html
> +                                <a class="btn btn-light text-primary" target="_blank" href="legal/terms/enterprise.html">
I didn't check the design but, in the doc, internal links are usually not target blank. So I guess yes

2022-12-02 14:23 UTC, AntoineVDV approved these changes

2022-12-07 09:26 UTC, AntoineVDV reviewed
@robodoo r+

2022-12-07 10:27 UTC, closed without merging