Update portal.rst
odoo/documentation pull request #3137
Opened 2022-12-07 17:23 UTC by ray-odoo

Removed old and probably not needed image of the dashboard showing the Contacts App

2022-12-07 17:24 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3137).

2022-12-08 08:58 UTC, AntoineVDV commented
Hi @odoo/sales-doc-review, could you handle this PR?

2022-12-13 22:45 UTC, meng-odoo approved these changes
Hi @ray-odoo, thanks for making this change! Looks good to me, so I'll go ahead and approve.

Hi @StraubCreative, please proceed with technical review. It looks like some code checks were unsuccessful. Thanks!

2022-12-26 01:51 UTC, StraubCreative commented
@AntoineVDV or @Feyensv can I have a hand with this? 

I tried doing a `git reset --hard 16.0` with a `git cherry-pick` on top of it and I'm still getting CI errors even though I'm not seeing any build errors locally with `make`. The details of the CI errors also don't make any sense to me, as this branch _should_ be an exact replica of `16.0` with only one commit ahead...

Is this one of those instances where it's better to start fresh with a new feature branch/PR and cherry-pick on top of it?

Thanks in advance for any advice/help 🙏

2022-12-26 02:10 UTC, StraubCreative commented
@meng-odoo quick follow up.

Kicking this back to you as there's much to update/clean-up:

- 2nd-person familiar you/your language instead of third-person instructional
- gendered pronouns instead of third-person neutral
- generic image filenames
- images too big, out of date, and/or not in HD
- missing `:alt:` text
- missing `:guilabel:` tags
- 100th character formatting
- typos, grammar, and wording
- high image:copy ratio (which suggests more detailed written content could be added here, although I could be mistaken!)
- etc.

I went ahead and added `:guilabel:` tags where I saw fit, formatted for 100th char, cleaned up a couple typos, and added `:alt:` text but the content needs a decent lift to get it up to Guidelines standards.

Please give it a look and tag @mivu-odoo for CR when you're done. Ty 🙏

2022-12-27 09:13 UTC, AntoineVDV commented
@StraubCreative The runbot believed that the branch still had a `master` base because that'd the first base it saw.
![image](https://user-images.githubusercontent.com/15896813/209642839-025080fd-3af1-44ca-a6b5-3bf0699b45b1.png)

One way to fix this is to change the target branch of the PR from `16.0` to `master`, then from `master` to `16.0`.

2023-01-06 18:11 UTC, StraubCreative commented
`portal.rst` rebuild on [87a5c33](https://github.com/odoo/documentation/pull/3137/commits/87a5c33ded9eaa7ffbf36b433a3199816bedbdac): addressed all outstanding items in [this comment](https://github.com/odoo/documentation/pull/3137#issuecomment-1364814394) and updated screenshots as well using a `14.0` runbot instance.

This rewrite would serve better as a base for all versions of Odoo that we're actively maintaining (v14-16), and we can open future PRs to address any version-specific differences or additional features.

I'll reset the commit history and change the target branch to `14.0` in the next commit.

cc: @meng-odoo @ray-odoo 

Also, wondering--
Wouldn't this doc be better served in **Miscellaneous** section of the documentation, given that it touches so many different app scopes beyond Sales? Wdyt @jcs-odoo ?

2023-01-06 20:42 UTC, meng-odoo requested changes
Hey @StraubCreative! I just found a couple small typos to fix whenever you push the next commit. Thanks :)

2023-01-06 20:42 UTC, meng-odoo commented on content/applications/sales/sales/advanced/portal.rst
> +Some common use cases for providing portal access include allowing customers to read/view any/all
The two consecutive slashes were a little confusing to read
```suggestion
Some common use cases for providing portal access include allowing customers to read/view any or all
```

2023-01-06 20:42 UTC, meng-odoo commented on content/applications/sales/sales/advanced/portal.rst
> +the :guilabel:`Action`` drop-down menu located at the top-center of the interface.
Deleting an extra `
```suggestion
the :guilabel:`Action` drop-down menu located at the top-center of the interface.
```

2023-01-06 20:42 UTC, meng-odoo commented on content/applications/sales/sales/advanced/portal.rst
> +   :guilabel:`In Portal` column and clicking `Apply`.
Adding a guilabel
```suggestion
   :guilabel:`In Portal` column and clicking :guilabel:`Apply`.
```

2023-01-06 20:58 UTC, StraubCreative commented
Thanks for catching those @meng-odoo 🙏 
All CRs were addressed on [4beb0da](https://github.com/odoo/documentation/pull/3137/commits/4beb0da8edd150ad7c95a4f42be451af6e55c30c). Can you take another look, please?

If all good can move on to final content review with Michelle 🚀

2023-01-07 02:48 UTC, meng-odoo approved these changes
@StraubCreative looks good!
@mivu-odoo this is ready for final review :)

2023-01-13 00:52 UTC, StraubCreative commented
Changed target branch to `14.0` so we can FWP the doc rewrite up to `16.0`
Reset + cherry-picked on [04dcbe0](https://github.com/odoo/documentation/pull/3137/commits/04dcbe0e52555ce4cacd434431ac6fa9e2e20391). 
All CI checks pass.

Approving content and moving to @odoo/doc-review 👍

2023-01-13 00:53 UTC, StraubCreative approved these changes

2023-01-16 08:46 UTC, AntoineVDV approved these changes
Delegating so you can merge the fwp PRs.

@robodoo delegate=StraubCreative

2023-01-16 18:04 UTC, StraubCreative commented
@robodoo r+

2023-01-16 19:10 UTC, closed without merging