[IMP] payment acquirers: multi-company use
odoo/documentation pull request #3150
Opened 2022-12-08 12:01 UTC by toaa-odoo

Added a paragraph on users wishing to use the same payment provider across multiple companies.

taskid: 3095103

2022-12-08 12:02 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3150).

2022-12-08 17:15 UTC, jcs-odoo requested changes
Do not fw-port it as is up to master, as you indicated, since the content isn't the same from 16 (no create button from the main payment acquirers view, no save button, and mostly, "payment acquirers" is named "payment providers"

Also, I tried this in 16.0 and 15.0, and I get an error message when trying to replicate the flow, when saving the duplicated acquirer. No error message on 14.0, though

![image](https://user-images.githubusercontent.com/46810843/206515417-5505a151-cd96-4deb-bb1d-e51c35f676e2.png)

Any insight on this, @AntoineVDV ?

2022-12-08 17:15 UTC, jcs-odoo commented on content/applications/finance/payment_acquirers.rst
> +go to :menuselection:`Configuration --> Payments: Payment Acquirers` and select the payment acquirer
1st step is to be on the "main" company, first, I think.

2022-12-09 08:50 UTC, toaa-odoo commented
> Do not fw-port it as is up to master, as you indicated, since the content isn't the same from 16 (no create button from the main payment acquirers view, no save button, and mostly, "payment acquirers" is named "payment providers"
> 
> Also, I tried this in 16.0 and 15.0, and I get an error message when trying to replicate the flow, when saving the duplicated acquirer. No error message on 14.0, though
> 
> ![image](https://user-images.githubusercontent.com/46810843/206515417-5505a151-cd96-4deb-bb1d-e51c35f676e2.png)
> 
> Any insight on this, @AntoineVDV ?

My bad, I thought it would just conflict and I could adapt to the versions above

2022-12-09 10:04 UTC, AntoineVDV commented
> Do not fw-port it as is up to master, as you indicated, since the content isn't the same from 16 (no create button from the main payment acquirers view, no save button, and mostly, "payment acquirers" is named "payment providers"
> 
> Also, I tried this in 16.0 and 15.0, and I get an error message when trying to replicate the flow, when saving the duplicated acquirer. No error message on 14.0, though
> 
> ![image](https://user-images.githubusercontent.com/46810843/206515417-5505a151-cd96-4deb-bb1d-e51c35f676e2.png)
> 
> Any insight on this, @AntoineVDV ?

That's how the company switcher is designed to "work" starting Odoo 15. :roll_eyes: 
It's not related to payment. When duplicating company-dependent records, you must be careful to switch your companies at the right moment...

2022-12-09 10:54 UTC, toaa-odoo commented
> > Do not fw-port it as is up to master, as you indicated, since the content isn't the same from 16 (no create button from the main payment acquirers view, no save button, and mostly, "payment acquirers" is named "payment providers"
> > Also, I tried this in 16.0 and 15.0, and I get an error message when trying to replicate the flow, when saving the duplicated acquirer. No error message on 14.0, though
> > ![image](https://user-images.githubusercontent.com/46810843/206515417-5505a151-cd96-4deb-bb1d-e51c35f676e2.png)
> > Any insight on this, @AntoineVDV ?
> 
> That's how the company switcher is designed to "work" starting Odoo 15. roll_eyes It's not related to payment. When duplicating company-dependent records, you must be careful to switch your companies at the right moment...

So what does is it mean for this PR? They can only duplicate the payment provider at the very beginning ?

2022-12-12 09:32 UTC, jcs-odoo approved these changes
@toaa-odoo after this is merged in 14.0, you can then update first in 15.0, (if needed) and then in 16.0. Please ping me on these branches for review once you've updated them.

Cheers :)

2022-12-13 09:15 UTC, AntoineVDV approved these changes
@robodoo r+

2022-12-13 10:06 UTC, closed without merging