[ADD] eCommerce: add to cart page
odoo/documentation pull request #3175
Opened 2022-12-09 15:41 UTC by toaa-odoo

Adding add to cart page to the eCommerce section.

taskid:

2022-12-09 15:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3175).

2022-12-15 12:15 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +   those without.
Fair point :)

2022-12-15 12:28 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +  (instant checkout).
No changes in your suggestion, so as discussed I'm assuming it is a mistake :)

2022-12-16 09:28 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +**add-to-cart** button.
Changed it up a bit

2022-12-16 10:22 UTC, chiaraprattico approved these changes

2022-12-28 14:19 UTC, xpl-odoo requested changes

2022-12-28 14:19 UTC, xpl-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +To add it, go on the **product page** of your choice, click :menuselection:`Edit --> Blocks` and
You can add it to any page.

2022-12-28 14:19 UTC, xpl-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +You can enable the :guilabel:`Buy Now` button to instantly take the customer to **checkout** instead
```suggestion
You can enable the 'Buy Now' button to instantly take the customer to **checkout** instead
```

2022-12-28 14:19 UTC, xpl-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +:menuselection:`Configuration --> Settings --> Shop - Checkout Process` and tick
```suggestion
:menuselection:`Website --> Configuration --> Settings --> Shop - Checkout Process` and tick
```

2022-12-28 14:19 UTC, xpl-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +portal. To do so, go to :menuselection:`Configuration --> Settings --> Shop - Checkout Process` and
```suggestion
portal. To do so, go to :menuselection:`Website --> Configuration --> Settings --> Shop - Checkout Process` and
```

2022-12-28 14:19 UTC, xpl-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +enable :guilabel:`Re-order From Portal`. Customers can find the :guilabel:`Re-order` button on their
```suggestion
enable :guilabel:`Re-order From Portal`. Customers can find the :guilabel:`Order Again` button on their
```

2022-12-29 10:22 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +Add to cart
I'm not sure I understand what you mean here. There's a new eCommerce structure, and it includes a checkout section :) : https://docs.google.com/spreadsheets/d/1O7Jg4T8kPE0HaLw-3YDjaj54MMk957-9akBFaSNKQA0/edit#gid=0

2022-12-29 10:33 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +Hide the 'Add to Cart' button
Good suggestion

2022-12-29 11:33 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +URL**.
True

2022-12-29 11:41 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +   for those without.
It is intended for eCommerces that only sell B2B and not B2C, therefore actually choosing who can buy on their website by granting them portal access through a selection (from what I understood from the smartclass)

2022-12-29 11:42 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +   for those without.
Same comment as above

2022-12-29 11:51 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +To add it, go on the **product page** of your choice, click :menuselection:`Edit --> Blocks` and
Reworded

2022-12-29 12:01 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +Custom 'Add to Cart' button
I changed it to "Customizable" which defines better what the button really is about, however if you have any suggestions, lmk as I don't know how else to name a button can be modified by the user.

2022-12-29 12:11 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +   for those without.
See explanation above, and I added a todo:: for when the doc containing the mandatory sign up" is published

2022-12-29 12:30 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +
Relevant comment, I removed the first note.

2022-12-29 12:45 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +increase the number of 'buy' options for customers.
Great suggestion

2022-12-29 13:05 UTC, toaa-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +Process`, and select one of the three options under the :guilabel:`Add to Cart` section.
I like the way you did it better

2023-01-12 11:31 UTC, xpl-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +To do so, go to :menuselection:`Website app --> Configuration --> Settings --> Shop - Products` and
```suggestion
To do so, go to :menuselection:`Website --> Configuration --> Settings --> Shop - Products` and
```
It's not necessary to mention "app" - discussed that with Jon previously.

2023-01-12 11:31 UTC, xpl-odoo commented on content/applications/websites/ecommerce/checkout_payment_shipping/cart.rst
> +Custom 'Add to Cart' button
You can customize default/standard add to cart buttons as well, so I felt talking about "additional" buttons might have been clearer

2023-01-13 07:30 UTC, toaa-odoo commented
Do *not* merge yet. To be included in mega PR for new eCommerce structure

2023-02-02 16:10 UTC, AntoineVDV approved these changes
@robodoo delegate+

2023-02-07 10:25 UTC, toaa-odoo commented
@robodoo r+

2023-02-07 11:53 UTC, closed without merging