[IMP][CSS] Clean up of the SCSS code
odoo/documentation pull request #3225
Opened 2022-12-21 14:56 UTC by edi-odoo

In order to reduce the size of our css files:
Some unused or repeated code was found and removed. 
Variables have been cleaned up, the way the admonitions (alerts) were created has been modified,

Expanding the use of BS variables in order to reduce repeated code and to stay consistent in the general design.
Sphinx was updated which made some changes in the DOM, breaking some of the CSS: 
the literals for example, these have been fixed in this PR.
The font sizes were breaking the typescale, this has been fixed by modifying the typescale
rather than hardcoding font sizes.

2022-12-21 14:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3225).

2022-12-21 17:00 UTC, AntoineVDV reviewed
Looking good! :+1: 

I have a few remarks in addition to the review comments, but some are just for double-checking if a change is intended:
- The bar and texts were darker. The footer too.
  ![image](https://user-images.githubusercontent.com/15896813/208951251-73c79231-363b-4a9c-9bf4-1dbbad5eded9.png)
- Generally speaking, it's good that (almost) all admonitions follow the same style now, but some (e.g., exercise) are maybe too dark and their content hard to read.
  ![image](https://user-images.githubusercontent.com/15896813/208955276-b0b09920-e8cf-4c3e-b2e5-e904d6fb46a1.png)
- Literals are in bold now. I don't think they should. This is a bit weird on technical pages with a lot of literals.
  ![image](https://user-images.githubusercontent.com/15896813/208953520-0fda5816-edf0-43b8-a027-d98828538f0b.png)
- I like that h3/h4 are now more easily distinguishable from regular text, but I feel like h4 look even bolder than h3. `<h3>Bulleted list</h3><h4>Bulleted list</h4>` :point_down: 
  ![image](https://user-images.githubusercontent.com/15896813/208954035-3e4e0fe6-83ff-4c7c-b66d-c85d839bfe50.png)
- Open question, should spoilers have the same style as exercises since they are used together?
  ![image](https://user-images.githubusercontent.com/15896813/208955461-a4db08e1-b2ff-4a12-934d-a705489cb67f.png)
- There should be no highlight on spoilers' buttons.
  ![image](https://user-images.githubusercontent.com/15896813/208955654-6d765c69-8b05-4989-ad69-0a0b8ba9ee92.png)
- The close button on modals moved to the left.
  ![image](https://user-images.githubusercontent.com/15896813/208958133-90dd8c0b-d891-4c67-b22a-123898c5ac7d.png)
- We lost the indentation on /developer/api/extract_api.html#request-body
  ![image](https://user-images.githubusercontent.com/15896813/208961291-09db2d8a-9199-4752-bf84-a17729e87676.png)
- In /developer/cli.html, other generic literals are now grey instead of white with a yellow border, but `odoo` still has the yellow border.
  ![image](https://user-images.githubusercontent.com/15896813/208961694-5ec32c71-6092-482a-97ac-83841f072c32.png)

2022-12-21 17:00 UTC, AntoineVDV commented on extensions/odoo_theme/translator.py
> +# The alert classes have been replaced by default BS classes to reduce number of scss lines.
Don't write changelogs in the code. It won't mean anything to new readers :wink: 
```suggestion
```

2022-12-21 17:00 UTC, AntoineVDV commented on extensions/odoo_theme/translator.py
>  }
```suggestion
}  # Map admonitions to Bootstrap alert classes.
```

2022-12-21 17:00 UTC, AntoineVDV commented on extensions/odoo_theme/static/js/layout.js
> +                           <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
```suggestion
                               <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
```

2022-12-21 17:00 UTC, AntoineVDV commented on extensions/odoo_theme/static/style.scss
> -.o_image_modal {
Shouldn't the class be removed too?

2022-12-21 17:14 UTC, stefanorigano requested changes
Thanks @edi-odoo , some notes in the code. Some suggestions:
- you can remove legacy browser's prefixes in _mixins.scss and probably the mixins themselves since rules like `transform-origin` are widespread across all browsers nowadays 
- looks no all `fw_*` class is used except `fw_medium`

2022-12-21 17:14 UTC, stefanorigano commented on extensions/odoo_theme/static/style.scss
> +                    content: '#{$i-note}';
you can define css variables in the main selector and then apply the customization by class (better inside a loop)... something like:

```scss
.alert {
    > .alert-title:before, > h3:before {
        content: var(--o-alert-icon, #{$i-default-icon});
    }
    
    // [.. smthg similar for borders]
    
    &.alert-success {
        --o-alert-icon: #{$i-whatever};
        --o-alert-border-color: #{$o-color-xhatever}
    }
}



```

2022-12-21 17:14 UTC, stefanorigano commented on extensions/odoo_theme/static/style.scss
> +                @include o_code;
typo?
 
```suggestion
                @include o-code;
```

2022-12-22 09:02 UTC, edi-odoo commented on extensions/odoo_theme/static/scss/bootstrap_overridden.scss
> +$theme-colors: (
Do you mean $theme-colors?

2022-12-22 10:22 UTC, edi-odoo commented on extensions/odoo_theme/static/scss/bootstrap_overridden.scss
> +$theme-colors: (
I've changed all the colors of theme-colors and added new ones.

2022-12-22 10:27 UTC, edi-odoo commented on extensions/odoo_theme/static/scss/bootstrap_overridden.scss
> +$theme-colors: (
Indeed I just realised I can inject the `"tip":        $primary,` instead. Duh!

2023-01-03 15:58 UTC, AntoineVDV commented
@robodoo r+ merge

2023-01-03 15:59 UTC, robodoo commented
Merge method set to merge directly, using the PR as merge commit message.

2023-01-03 16:41 UTC, merged