[IMP] sales: menuselection fix
odoo/documentation pull request #3282
Opened 2023-01-04 01:04 UTC by meng-odoo

Fixed a menuselection error and deleted instances of second-person pov
Closes task [3116083](https://www.odoo.com/web#id=3116083&cids=3&model=project.task&view_type=form)

2023-01-04 01:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3282).

2023-01-23 20:30 UTC, meng-odoo commented
@StraubCreative this is ready for your review.

2023-02-03 04:30 UTC, StraubCreative requested changes
Hi @meng-odoo 

Good PR. Short and sweet and the RST's clean 👍 

I had only two comments:
- `sales-team-creation.png` might be just a touch too big (at ~1300px)
- `Sales Teams` is not a proper noun so I wouldn't capitalize it except when: 
    - first introducing it as a term/feature in the overview, and 
    - whenever we're calling attention to a UI element that's called `Sales Teams`

I highlighted a couple instances below, however there are much more throughout the doc. 
Can you take a look?

2023-02-03 04:30 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
>  Create a new Sales Team
Would use [sentence case](https://www.odoo.com/documentation/15.0/contributing/documentation/content_guidelines.html#titles-and-headings) here, just like the H1.
```suggestion
Create a new sales team
```

2023-02-03 04:30 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
>  :guilabel:`Create`.
`Sales Team` doesn't need to be capitalized here, as it was already introduced as a term in the overview and it's not a proper noun.
```suggestion
To create a new sales team in Odoo, go to :menuselection:`CRM --> Configuration --> Sales Teams`
then click :guilabel:`Create`.
```

2023-02-03 04:30 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +for this Sales Team every time a message is sent to that unique email address. Choose whether to
Lowercase
```suggestion
for this sales team every time a message is sent to that unique email address. Choose whether to
```

2023-02-03 04:30 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
>  Set a :guilabel:`Domain` to assign leads/opportunities to this Sales Team based on specific
```suggestion
Set a :guilabel:`Domain` to assign leads/opportunities to this sales team based on specific
```

2023-02-03 04:30 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
>  Sales Team dashboard
```suggestion
Sales team dashboard
```

2023-02-07 21:57 UTC, meng-odoo commented
Hi @StraubCreative, I fixed the capitalization of "sales team" throughout the doc as requested. I also realized that all of the screenshots were of v14, so I updated all of them to v15. This is ready for your final review.

This PR should be forward-ported to v16 documentation, please. (We can leave v14 alone, there is no menuselection error in that doc.)

Thanks

2023-03-28 21:49 UTC, StraubCreative approved these changes
Hi @meng-odoo 👋 
Approving with a couple quick changes I'll push up momentarily.
Thank you!

2023-03-28 21:49 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
> +team's configuration page. Select a salesperson from the dropdown menu or create new salesperson.
Compound modifier gets a hyphen.
```suggestion
team's configuration page. Select a salesperson from the drop-down menu or create new salesperson.
```

2023-03-28 21:49 UTC, StraubCreative commented on content/applications/sales/crm/pipeline/multi_sales_team.rst
>  .. image:: multi_sales_team/sales-team-overview.png
Resize + compress

2023-03-28 21:54 UTC, StraubCreative commented
@robodoo r+

2023-03-28 22:56 UTC, closed without merging