[IMP] toctrees: redesign and new card component
odoo/documentation pull request #3326
Opened 2023-01-12 17:12 UTC by mano-odoo

The goal of this commit is to propose a first step towards a new `.. card::` directive for the toctrees. This is a first design proposition for this new card component in raw html for the fallback page `howtos.rst`

The long term objective is to redesign the toctrees by implementing card components, clearer toctree list design and custom html pages.

Related to task-3059229

2023-01-12 17:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3326).

2023-01-18 12:46 UTC, edi-odoo requested changes

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +                <p class="card-text text-dark fw-normal">Learn the most important parts of the Odoo development framework to create your own modules with  and for Odoo in this step-by-step tutorial c
```suggestion
                <p class="card-text text-dark fw-normal">Learn the most important parts of the Odoo development framework to create your own modules with and for Odoo in this step-by-step tutorial crafted for newcomers and any other individual curious about Odoo development.</p>
```

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +              <p class="card-text text-dark fw-normal">Build your first website modules with Odoo</p>
```suggestion
              <p class="card-text text-dark fw-normal">Build your first website modules with Odoo.</p>
```

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +              <p class="card-text text-dark fw-normal">Learn how to build your own Odoo modules</p>
```suggestion
              <p class="card-text text-dark fw-normal">Learn how to build your own Odoo modules.</p>
```

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +              <p class="card-text text-dark fw-normal">Learn more about Odoo's embedded profiler of code.</p>
```suggestion
              <p class="card-text text-dark fw-normal">Learn more about Odoo's embedded code profiler.</p>
```

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +              <p class="card-text text-dark fw-normal">Access information from multiple companies but also to create/edit records in a multi-company environment
```suggestion
              <p class="card-text text-dark fw-normal">See how to manage multiple companies and create/edit records in a multi-company environment.
```

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +        <a class="o_toctree_card" href="howtos/company.html">
Wrong URL

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +        <a class="o_toctree_card" href="howtos/company.html">
Wrong URL

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +        <a class="o_toctree_card" href="howtos/company.html">
Wrong URL

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +        <a class="o_toctree_card" href="howtos/company.html">
Wrong URL

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +              <p class="card-text text-dark fw-normal">Build a localization module, bank operation model and create dynamic report</p>
```suggestion
              <p class="card-text text-dark fw-normal">Read how to build a localization module, create bank operation models and dynamic reports.</p>
```

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +              <p class="card-text text-dark fw-normal">Implicit and explicit export of translatable term</p>
```suggestion
              <p class="card-text text-dark fw-normal">See how to provide translation abilities to your module.</p>
```

2023-01-18 12:46 UTC, edi-odoo commented on extensions/odoo_theme/static/style.scss
> +    transition: all 200ms;
```suggestion
```

2023-01-18 12:46 UTC, edi-odoo commented on extensions/odoo_theme/static/style.scss
> +
```suggestion

    .card {
        transition: all 200ms;
    }
```

2023-01-18 12:46 UTC, edi-odoo commented on content/developer/howtos.rst
> +    <div class="row mb-5 center">
```suggestion
    <div class="row mb-4 center">
```

2023-01-25 14:21 UTC, AntoineVDV approved these changes
@robodoo r+

2023-01-25 15:53 UTC, closed without merging