[IMP] sign: secured authentication info added
odoo/documentation pull request #3430
Opened 2023-01-27 13:49 UTC by Donapi

[ID: 3084552](https://www.odoo.com/web#id=3084552&cids=1&model=project.task&view_type=form)

2023-01-27 13:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3430).

2023-02-14 07:48 UTC, LoredanaLrpz requested changes
hello @Donapi , there you have it :)

2023-02-14 07:48 UTC, LoredanaLrpz commented on content/applications/finance/sign.rst
> +:guilabel:`Send`. A page pops up, select the customer, and click :guilabel:`Send`.
Not sure about "previous", but here's what I'd suggest
```suggestion
Go to the document to sign and add a field that has the previous role attributed, such as the
:guilabel:`Signature` field, and click :guilabel:`Send`. A page pops up, select the customer, and
click :guilabel:`Send`.
```

2023-02-14 07:48 UTC, LoredanaLrpz commented on content/applications/finance/sign.rst
> +:guilabel:`Identify with itsme®`.
```suggestion
Go to :menuselection:`Sign --> Configuration --> Settings` and enable :guilabel:`Identify with
itsme®`.
```

2023-02-14 07:48 UTC, LoredanaLrpz commented on content/applications/finance/sign.rst
> +:guilabel:`Extra Authentication Step` column for the role, and select :guilabel:`Via itsme®`.
```suggestion
Then, go to :menuselection:`Sign --> Configuration --> Roles`. Click in the :guilabel:`Extra
Authentication Step` column for the role, and select :guilabel:`Via itsme®`.
```

2023-02-14 07:48 UTC, LoredanaLrpz commented on content/applications/finance/sign.rst
> +:guilabel:`customer (identified with itsme®)`, and click :guilabel:`Validate` and :guilabel:`Send`.
That sentence contains a lot of "and" here's what I'd suggest:
```suggestion
Go to the document that needs to be signed and add the :guilabel:`Signature` field. Switch the role
to :guilabel:`customer (identified with itsme®)`, click :guilabel:`Validate`, and :guilabel:`Send`.
```

2023-02-14 07:48 UTC, LoredanaLrpz commented on content/applications/finance/sign.rst
> +The person signing the document fills in the :guilabel:`Signature` field and then click
```suggestion
The person signing the document fills in the :guilabel:`Signature` field and clicks
```

2023-02-15 09:01 UTC, LoredanaLrpz reviewed
Hey @Donapi , the PR is great, I'll approve it as soon as the pictures issue is fixed =)
Have a nice one!

2023-02-16 08:01 UTC, LoredanaLrpz approved these changes

2023-02-16 08:39 UTC, AntoineVDV approved these changes
@robodoo r+

2023-02-16 10:03 UTC, closed without merging