[IMP] inventory: update owned_stock
odoo/documentation pull request #3600
Opened 2023-02-16 16:33 UTC by brse-odoo

Performed complete rewrite for Inventory document: owned_stock.rst.

- Added new sections to document, including:
- Receiving consignment stock
- Selling consignment stock
- Consignment stock in inventory reports 

-Added all new screenshots and updated/elaborated on general information

- Cleaned up RST, including:
-Fixed 100th character line breaks
-Fixed indentations
-Fixed typos and improved grammar

2023-02-16 16:34 UTC, brse-odoo commented
Hi @StraubCreative, this is ready for your review whenever you have the chance. Thank you!

2023-02-16 16:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3600).

2023-02-28 18:10 UTC, brse-odoo commented
Hi @ksc-odoo  -- when you have a chance, can you please review this doc? Thanks in advance for your help on this!

2023-02-28 18:11 UTC, brse-odoo commented
Sending through a peer review stage before sending to final/technical review.

2023-02-28 19:48 UTC, ksc-odoo reviewed
@brse-odoo Alrighty - this one is ready for you to take a look at! Great job...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +Consignment: Buy and Sell Stock Without Owning It
Consignment: Buy and sell stock without owning it

*need to consider the capitalization rules

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +in their warehouses without having to buy those items up front. This is called **Consignment**.
...in their warehouses, without having to buy those items up front.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +This is a great way for suppliers to launch new products and easily get them out to their
This is a great way for suppliers to launch new products, and easily get them to their customers. It's also a great way for the company storing the products (the consignee) to earn something back for their efforts. Consignees can even charge a fee for the convenience of storing products they don't actually own.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +Receive and Store Consignment Stock
Receive (and store) consignment stock

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +With the *Consignment* feature enabled, consignment stock can now be received into a warehouse.
With the :guilabel:`Consignment` feature enabled, consignment stock can now be received into a warehouse.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +To receive, store, and sell consignment stock, the *Consignment* feature needs to be enabled. To
...the :guilabel:`Consignment` feature...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +From the Inventory main dashboard, click into the :guilabel:`Receipts` section. Then, click
From the main Inventory dashboard,...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +    :guilabel:`Receive From` and :guilabel:`Assign Owner` field must match each other.
...field must match.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +Sell and Deliver Consignment Stock
Sell and deliver consignment stock

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +**Quotations** overview, click :guilabel:`New`.
:guilabel:`Quotations` overview, ...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +    stock received into and stored in the warheouse.
The :guilabel:`Customer` *must* be different from the :guilabel:`Vendor` that supplied the consignment stock received  (and stored) in the warehouse.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +has been filled out, :guilabel:`Confirm`.
..., click :guilabel:`Confirm`.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +delivered and invoiced for.
...delivered and invoices can be sent.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +Traceability and Reporting of Consignment Stock
Traceability and reporting of consignment stock

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +inventory reports, go to :menuselection:`Inventory --> Reporting`, and choose a report to view.
Although consignment stock is owned by the vendor who supplied it, and not by the company storing
it in their warehouse, consignment products will *still* appear in certain inventory reports. 

To find inventory reports, go to :menuselection:`Inventory --> Reporting`, and choose a report to view.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +    in the **Stock Valuation** report, and have no impact on the consignee's inventory valuation.
...in the :guilabel:`Stock Valuation` report, ...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +**Stock** Report
Is there a reason behind the "**"?

Could "Stock report" work instead? Just a thought...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +To view the **Stock** report, go to :menuselection:`Inventory --> Reporting --> Stock`. From this
same question re: "**"

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +report, information about all stock on-hand can be seen. For consignment products, the information
...report, all information about on-hand stock can be seen.

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +any replenishment rules are listed; its **Locations** are available; and its :guilabel:`Forecasted`
...its :guilabel:`Locations` are available...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +**Locations** Report
Same question re: "**"

Locations report

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +To view the **Locations** report, go to :menuselection:`Inventory --> Reporting --> Locations`.
To view the :guilabel:`Locations` report,...

2023-02-28 19:48 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +From this report, the **Locations** of all stock on-hand are displayed, as well as the quantities
From this report, the :guilabel:`Locations` of all stock on-hand are displayed, in addition to the quantities per location.

2023-03-02 15:02 UTC, brse-odoo commented
Hi @tiku-odoo  -- when you have a chance, this doc is ready for its 2nd peer review. Thanks in advance for your help on this!

2023-03-07 19:15 UTC, tiku-odoo reviewed
Awesome work @brse-odoo! I've made a couple of suggestions, other than that looks good to go to final review. Looking forward to seeing this published. 

Thanks,
Tim 👍

2023-03-09 14:46 UTC, brse-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +in their warehouse, without having to buy those items up front. This is called *Consignment*.
Nice catch. I didn't even consider how this could be confusing but definitely works to change it here.

2023-03-09 14:57 UTC, brse-odoo commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +of its product moves can be reviewed; any replenishment rules are listed; and its
Me neither. I've removed this.

2023-03-09 15:49 UTC, brse-odoo commented
Hi @StraubCreative, this PR has passed the peer review stage and is ready for your final review whenever you have a chance. Thank you!

2023-03-24 16:44 UTC, samueljlieber requested changes
Hey @brse-odoo, great job on this doc! I've made some technical changes which you can see below. Just some minor adjustments to line breaking and admonition blocks 🙂. Im implementing the changes in a commit after this review.

2023-03-24 16:44 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +*Consignment*.
lowercase *consignment*

2023-03-24 16:44 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +set the :guilabel:`Quantity`, and any other pertinent product details. Once everything has been
can break line later at *set*

2023-03-24 16:44 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +    the :guilabel:`drop-down menu` and click :guilabel:`Apply`.
can break line later at *the*

2023-03-24 16:45 UTC, samueljlieber commented
Implemented [technical changes](https://github.com/odoo/documentation/pull/3600#pullrequestreview-1357034942) in https://github.com/odoo/documentation/commit/57a5f12f0286bb204f388903012e3883f5ee971d.

2023-03-29 16:41 UTC, samueljlieber approved these changes

2023-04-07 22:29 UTC, StraubCreative requested changes
Hi @brse-odoo 

This was a really well written doc. Nice work.
Props to the review team too ✨ 

The CRs I have below mostly revolve around `guilabel` use and some small wording adjustments...small stuff.

I'm pushing up the revisions in a second commit so you can view them locally if you like (otherwise you can see the adjustments here on the GH UI under the **Files** tab).

Please let me know if you approve these changes or list your dissent on any of the comments below. 
- If you approve, I can squash/merge right away. Just indicate so in a comment and @tag me. 
- If you have further changes you'd like to make, then pull down an updated copy of the PR to your machine using `git pull --rebase`, make your changes on a third commit, squash all of the commits into one, rebase, and push back up and tag me for another review.

Thanks and let me know if you have any questions or need a hand 🙂

2023-04-07 22:29 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +consignment products, the information in this report is the same as any other product: the history
To better fit the guilabel use here, slight rewording.
```suggestion
To view all information about on-hand stock moves, navigate to the the :guilabel:`Product Moves`
dashboard by going to :menuselection:`Inventory --> Reporting --> Product Moves`. For consignment
products, the information in this report is the same as any other product: the history
```

2023-04-07 22:29 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +   :guilabel:`drop-down menu` and click :guilabel:`Apply`.
Guilabel use, wording.
```suggestion
.. tip::
   To view a consignment product's moves by ownership, select the :guilabel:`Group By` filter,
   choose the :guilabel:`Add Custom Group` parameter, and then select :guilabel:`From Owner`, and
   :guilabel:`Apply` to finish.
```

2023-04-07 22:29 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/misc/owned_stock.rst
> +products in the first place.
Very small adjustment to justify a clearer `guilabel` use
```suggestion
View the :guilabel:`Stock On Hand` dashboard by navigating to :menuselection:`Inventory -->
Reporting --> Inventory Report`. From this report, the :guilabel:`Locations` of all stock on-hand
are displayed, in addition to the quantities per location. For consigment products, the
:guilabel:`Owner` column will be populated with the owner of those products, or the original vendor
who supplied the products in the first place.
```

2023-04-12 19:51 UTC, brse-odoo commented
Hi @StraubCreative, thanks for reviewing this! I looked over all the changes and approve of them! I'm all set.

2023-04-12 20:51 UTC, StraubCreative commented
[8962868](https://github.com/odoo/documentation/pull/3600/commits/89628686f63e952318ec2756b622788993d1e37c): squashed + rebased.
All checks pass ✅ 

@robodoo r+

2023-04-12 20:51 UTC, StraubCreative approved these changes

2023-04-12 21:33 UTC, closed without merging