[IMP] inventory: update integrating_landed_costs
odoo/documentation pull request #3686
Opened 2023-02-27 16:54 UTC by brse-odoo

This PR is a **targeted revision** for **V14.0 only**.

Performed complete rewrite for Inventory document: integrating_landed_costs.rst

-Added new sections to document
-Fixed and replaced all screenshots
-Removed use of 2nd person
-Reworked example flow in doc

Cleaned up RST, including:
-Fixed 100th character line breaks
-Fixed indentations
-Fixed typos and improved grammar

2023-02-27 16:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3686).

2023-02-27 16:55 UTC, brse-odoo commented
@StraubCreative, this is ready for your review whenever you have a chance. Thank you!

2023-03-28 19:00 UTC, samueljlieber requested changes
Hi @brse-odoo 👋 Ive made some technical changes on this doc, stated below for your review. I will be pushing these changes in a second commit for your approval, once approved I will squash the commits, rebase, and push them back up for final review.

This doc is written very well, my only changes were on 2 things:

1. :guilabel: use on general terms like "landed costs", "vender bills", and "inventory valuation"
2. Indenting within admonition blocks.

Please let me know if you approve of these changes and Ill forward this onto final review. Thank you 🙂

2023-03-29 15:33 UTC, brse-odoo commented
> Hi @brse-odoo 👋 Ive made some technical changes on this doc, stated below for your review. I will be pushing these changes in a second commit for your approval, once approved I will squash the commits, rebase, and push them back up for final review.
> 
> This doc is written very well, my only changes were on 2 things:
> 
> 1. :guilabel: use on general terms like "landed costs", "vender bills", and "inventory valuation"
> 2. Indenting within admonition blocks.
> 
> Please let me know if you approve of these changes and Ill forward this onto final review. Thank you 🙂

Hi @samueljlieber, thanks for completing the technical review and implementing these changes! Everything looks good to me and you have my approval on the changes.

2023-04-12 21:08 UTC, samueljlieber commented
Hi @brse-odoo, thanks for approving 🙂 I squashed the changes and rebased in https://github.com/odoo/documentation/commit/a825b6a33664dc54b4d42b83480458290abcfc65.

All set for your final review @StraubCreative 😎

2023-04-12 21:08 UTC, samueljlieber approved these changes

2023-04-17 18:42 UTC, brse-odoo commented
Hi @odoo/us-doc-review, this PR could use a content review whenever one of you has a chance. Thank you!

**Sending through a content review check before sending to zst for final review. Will squash commits/rebase/push up changes and re-request final review when ready.**

2023-04-27 18:32 UTC, ksc-odoo reviewed
Hey @brse-odoo just finished a peer review of this doc, but I ran into some issues near the end of the flow. If you could give those steps a quick "double-check" that would be great. If I made an error along the way, or if a change was made, just let me know and I'll happily give this another try. Just let me know ... Other than that - great work!

2023-04-27 18:32 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +as well as the :guilabel:`Additional Landed Cost` that changed the original purchase order.
I can see these columns (Original Value and New Value), but everything under the Valuation Adjustments tab is blank. I've made sure to use a FIFO product, etc., but perhaps I did something incorrect along the way? It's worth looking into - and I'm happy to give this workflow another try if something needs to be corrected/adjusted.

2023-04-27 18:32 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +vendor bill (via the breadcrumbs).
When I attempted to click 'Validate' I got the following error message: You cannot apply landed costs on the chosen Transfers(s). Landed costs can only be applied for products with FIFO or average costing method.

However, I made sure that FIFO was applied to the Product Category that was applied to BOTH: the product initially added to the RfQ & to the Service Type 'Landed Cost' product added during the Vendor Bill Draft page section. So, perhaps this is a bug? Did I misunderstand a step along the way? Worth looking into either way.

2023-04-27 18:32 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +Payment`.
Was unable to reach this portion, as the above steps caused an error pop-up.

2023-05-05 00:11 UTC, StraubCreative requested changes
Hi @brse-odoo 
Please fix all of the 100th character line break issues and tag me again for another review.
These should have not made it past technical review 😉 
Thank you.

cc: @samueljlieber

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +Then, click the :guilabel:`Purchase` tab, and under the :guilabel:`Landed Costs` section, select
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +Clicking the blank field beside :guilabel:`Default Split Method` reveals a drop-down menu. From
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +   Depending on the landed cost of each shipment, the price of a landed cost product can change
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +:guilabel:`Done` quantities. Then, navigate back to the initial :abbr:`PO (purchase order)` (via
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +landed cost product to the vendor bill. And, since this product was specifically created as a
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +Once all the necessary information on the bill has been filled out, click
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +Additionally, an expenses :guilabel:`Account` (located in the :guilabel:`Additional Costs` tab)
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +To see how the landed costs affect the items on the :abbr:`PO (purchase order)`, click the
100th character

2023-05-05 00:11 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/reporting/integrating_landed_costs.rst
> +:guilabel:`Additional Landed Cost` that was added to change the original
100th character

2023-06-26 15:21 UTC, brse-odoo commented
Removed file `product_variants` in latest commit `4731e2e` to resolve merge conflicts/ci check failures. Pushed up changes and will review doc once more before sending to review.

2023-06-26 18:23 UTC, brse-odoo commented
Hi @StraubCreative this PR is ready for final review when you have the chance, thank you 👍

2023-06-27 23:09 UTC, StraubCreative approved these changes
Hi @brse-odoo 
Good PR. 
Approving with comments for you to address.
When you're done, you can run the merge command.
Thanks!

@fw-bot ignore
@robodoo delegate=brse-odoo

2023-07-31 20:08 UTC, closed without merging