[IMP] mail plugins: add instructions to gmail plugin
odoo/documentation pull request #3695
Opened 2023-02-28 21:24 UTC by meng-odoo

Added instructions to the Gmail Plugin doc for Odoo on-premise users

2023-02-28 21:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3695).

2023-02-28 21:30 UTC, meng-odoo commented
Hi @StraubCreative, this is ready for your review.

2023-03-01 07:25 UTC, jcs-odoo commented
Hi @meng-odoo  :)
You can link issues and branches in their "development" section above the "notifications" section.
This way, the issue will be closed once this PR is merged.

2023-03-01 09:20 UTC, AntoineVDV commented
> Hi @meng-odoo :) You can link issues and branches in their "development" section above the "notifications" section. This way, the issue will be closed once this PR is merged.

I don't think that it'll work because robodoo closes (red) PRs instead of merging (purple) them. It's still interesting which issues are linked to the PR, though.

2023-03-28 19:21 UTC, samueljlieber requested changes
Hi @meng-odoo 👋 Ive done a technical review of the changes on this doc and I'm approving them once I make my commit as the changes are very minor. Then I will tag it for final review.

I just added `.md` to the :guilabel:README for completeness, fixed one line that broke early, and resized two images that were over 768px wide. 

Thank you 🙂

2023-03-28 19:21 UTC, samueljlieber commented on content/applications/productivity/mail_plugins/gmail.rst
> +instructions in the :guilabel:`README` file to push the Gmail Plugin files as a Google Project.
:guilabel:README.md for completeness

2023-03-28 19:26 UTC, samueljlieber commented
Implemented technical changes in https://github.com/odoo/documentation/commit/62aa895781474ff0df4ccdd881f6fb7cd1572077, and sending to final review with @StraubCreative 🙂

2023-03-28 19:26 UTC, samueljlieber approved these changes

2023-03-28 22:01 UTC, StraubCreative approved these changes
Looks good @meng-odoo 👍

2023-03-28 22:01 UTC, StraubCreative commented on content/applications/productivity/mail_plugins/gmail.rst
>  After that, share the Google Project with the Gmail account that the user wishes to connect to
100th char
```suggestion
After that, share the Google Project with the Gmail account that the user wishes to connect to Odoo.
```

2023-03-28 22:11 UTC, StraubCreative commented
Small update in [646d600](https://github.com/odoo/documentation/pull/3695/commits/646d6002883cc8c2940636699355c42f3f9d74dd). All checks pass 👍 

@robodoo r+

2023-03-28 23:58 UTC, closed without merging