[IMP] eCommerce: ewallets/giftcards section
odoo/documentation pull request #3739
Opened 2023-03-03 10:36 UTC by toaa-odoo

Adding ewallets/giftcards section to the eCommerce doc. Forward to master.

taskid: 3215674

2023-03-03 10:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3739).

2023-03-03 12:50 UTC, chiaraprattico requested changes

2023-03-03 12:50 UTC, chiaraprattico commented on content/applications/websites/ecommerce/checkout_payment_shipping/payments.rst
> +**Shop - Products** section, enable :menuselection:`Discounts, Loyalty & Gift Card`.
When checking out, customers can pay with an **eWallet** or **gift cards**. To enable these, go to :menuselection:`Website --> Configuration --> Settings`, and in **Shop-Products** section, enable :menuselection:`Discounts, Loyalty & Gift Card`.

2023-03-07 10:25 UTC, chiaraprattico approved these changes

2023-03-07 11:31 UTC, jcs-odoo approved these changes
@robodoo r+

2023-03-07 12:46 UTC, closed without merging