[IMP] accounting: updating bank transactions creation
odoo/documentation pull request #3760
Opened 2023-03-07 14:07 UTC by chiaraprattico

taskid 3204835

2023-03-07 14:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3760).

2023-03-09 10:26 UTC, Donapi requested changes
Hi Chiara, please find some suggestions :) we can review them together if you want.

2023-03-09 10:26 UTC, Donapi commented on content/applications/finance/accounting/bank/feeds/bank_statements.rst
> +automated. However, if you do not want to use it or if your bank is not yet supported, other
```suggestion
With :doc:`bank synchronization <bank_synchronization>`, the process is
automated. However, if you do not want to use it or if your bank is not yet supported, other
```

2023-03-09 10:26 UTC, Donapi commented on content/applications/finance/accounting/bank/feeds/bank_statements.rst
>  - Import the bank statement files delivered by your bank;
- Import bank statement files;
- Register bank transactions manually.
- --> I would take the title of the sections below and add custom anchors.

2023-03-09 10:26 UTC, Donapi commented on content/applications/finance/accounting/bank/feeds/bank_statements.rst
> +the :guilabel:`Bank` journal, or click on the drop-down menu (:guilabel:`⋮`) button and then on
```suggestion
To import a file, go to the :guilabel:`Accounting Dashboard` and in the
the :guilabel:`Bank` journal, click on :guilabel:`Import Statement`. 
```

2023-03-09 10:26 UTC, Donapi commented on content/applications/finance/accounting/bank/feeds/bank_statements.rst
>  Next, select the file you want to import and click on :guilabel:`Upload`.
I don't see the "upload" option. I would just say "Next, select and upload the file you want".

2023-03-09 10:26 UTC, Donapi commented on content/applications/finance/accounting/bank/feeds/bank_statements.rst
> +file before importing it.
```suggestion
After setting the necessary formatting options and mapping the needed
columns, you have the possibility to make a :guilabel:`Test` or you can directly :guilabel:`Import` your bank statement files.
```

2023-03-10 12:45 UTC, Donapi approved these changes
Good work Chiara!

2023-03-13 13:48 UTC, xpl-odoo approved these changes
One spelling mistake and a couple of suggestions to shorten the text.
Otherwise, already approved ;)

2023-03-13 13:48 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/feeds/bank_statements.rst
> +files.
```suggestion
After setting the necessary formatting options and mapping the needed columns, you can
make a :guilabel:`Test` or directly :guilabel:`Import` your bank statement
files.
```
Suggestion to shorten/simplify

2023-03-13 13:48 UTC, xpl-odoo commented on content/applications/finance/accounting/bank/feeds/bank_statements.rst
> +Next, select the file you want to import and upload it.
```suggestion
Next, select the file and upload it.
```
Suggestion to shorten/simplify

2023-03-15 12:14 UTC, jcs-odoo requested changes
@xpl-odoo @chiaraprattico 
I think we're missing Odoo 16's new paradigm:
Bank statements are not the focus anymore, while bank transactions are.
(It is even renamed "import transactions" from Odoo 16.2 :) )
![image](https://user-images.githubusercontent.com/46810843/225305500-7746fe33-9eaa-4e92-b5e9-115d5dd93ad2.png)


It's true that we can still import bank statements manually, and all transactions would be part of a "statement" in Odoo too. Otherwise, I think the whole doc should be about "bank transactions" (also the title and filename).

2023-03-27 09:41 UTC, jcs-odoo approved these changes
@robodoo r+

2023-03-27 09:44 UTC, jcs-odoo commented
@robodoo r-

2023-03-27 10:03 UTC, jcs-odoo commented
@robodoo r+

2023-03-27 11:35 UTC, closed without merging