[IMP] sales: update customer addresses
odoo/documentation pull request #3784
Opened 2023-03-09 19:34 UTC by meng-odoo

Updated this doc for Odoo 16, and rewrote it for clarity and brevity. Replaced images, and fixed image names and alt descriptions.
Closes task #[3152071](https://www.odoo.com/web#id=3152071&cids=3&model=project.task&view_type=form) and Issue #[3693](https://github.com/odoo/documentation/issues/3693)

2023-03-09 19:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3784).

2023-03-09 19:36 UTC, meng-odoo commented
@StraubCreative this is ready for your review

2023-03-09 19:44 UTC, StraubCreative commented
@ksc-odoo can you plz take a look at this doc? Any improvements y'all can tackle before it gets to me will improve likelihood of quick merge. TIA!

2023-03-09 19:55 UTC, ksc-odoo reviewed
hey @meng-odoo - I just did a quick review of your updates to this doc (per ZST's instructions). Just a few minor modifications to consider before passing it along to @StraubCreative for final review. Great job!!!

2023-03-09 19:55 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +:menuselection:`Invoicing > Configuration > Settings` if the Accounting app is not installed.
Activate the :guilabel:`Customer Addresses` feature in the settings. 

If the :guilabel:`Accounting` app is installed, the :guilabel:`Customer Addresses` feature is located in :menuselection:`Accounting > Configuration > Settings`.

If the :guilabel:`Accounting` app is *not* installed, the :guilabel:`Customer Addresses` feature is located in
:menuselection:`Invoicing > Configuration > Settings`.

2023-03-09 19:55 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +With Odoo Sales, customers can use different addresses for delivery and invoicing.
With :guilabel:`Odoo Sales`, ...

2023-03-09 19:55 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +Addresses` tab, click :guilabel:`Add`.
Navigate to the :guilabel:`Contacts` application (or to :menuselection:`Sales > Orders >
Customers`), and click on a customer to open their contact form. 

Under the :guilabel:`Contacts & Addresses` tab, click :guilabel:`Add`.

2023-03-09 19:55 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +immediately input another one.
Enter the address information. Then, click :guilabel:`Save & Close` to save the address, and close
the :guilabel:`Create Contact` window.

Or, click :guilabel:`Save & New` to save this address, and immediately input another one.

2023-03-09 19:55 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +Address` will autopopulate according to the customer’s contact form.
When a customer is added to a quotation, the :guilabel:`Invoice Address` and :guilabel:`Delivery
Address` will autopopulate (according to the customer’s contact form).

2023-03-09 19:55 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +the quotation by clicking on the :guilabel:`Internal link` button next to the address line.
The :guilabel:`Invoice Address` and :guilabel:`Delivery Address` can also be edited directly from
the quotation, by clicking on the :guilabel:`Internal link` button next to the address line.

2023-03-09 19:57 UTC, ksc-odoo commented
> @ksc-odoo can you plz take a look at this doc? Any improvements y'all can tackle before it gets to me will improve likelihood of quick merge. TIA!

@StraubCreative done deal. just a few small things to adjust and then it should be good to go. Let me know if there's anything else you need from me. Thanks!

2023-03-09 21:09 UTC, meng-odoo commented
Thanks for the review @ksc-odoo! I've incorporated your suggestions on the latest commit.
@StraubCreative this is ready for you.

2023-03-29 01:04 UTC, StraubCreative requested changes
Hi @meng-odoo 
Couple change requests here.
I like that the doc is simple and provides clear + linear instruction, however I think we can be more specific in some spots. See comments below.

2023-03-29 01:04 UTC, StraubCreative commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +Address` will autopopulate according to the customer’s contact form.
Slightly more specific
```suggestion
Address` fields will autopopulate according to the values that were added on the customer's contact
form.
```

2023-03-29 01:04 UTC, StraubCreative commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +the quotation, by clicking on the :guilabel:`Internal link` button next to the address line.
Seems like the doc ends a little prematurely. It's not quite clear what the outcome (dare I say, "wow" moment) is. Now that these addresses are configured, what now? What outcome is produced?

2023-04-27 21:25 UTC, meng-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +With :guilabel:`Odoo Sales`, customers can use different addresses for delivery and invoicing.
By "customers" I actually meant customers in the Contacts app, not the Odoo user. Clarified in the latest version.

2023-04-27 22:38 UTC, meng-odoo commented
@StraubCreative whoops we never finalized this. I incorporated your changes in the latest commit. If you want to go ahead and merge, we can add this to Q1 deliverables :)

2023-04-28 00:42 UTC, StraubCreative approved these changes
LGTM. Short and sweet 🙂 

@robodoo r+

2023-04-28 02:26 UTC, closed without merging