Information about bank synchronization with Enable Banking.
odoo/documentation pull request #3799
Opened 2023-03-10 15:34 UTC by oskarenablebanking

Hi. Im oskar from Enable Banking. We are being contacted often by Odoo users with questions about issues / authentication with Enable Banking. Im making this pull request so things would be clearer to Odoo users. Could this also be added to master?
Is there something I should improve?

2023-03-10 15:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3799).

2023-03-13 09:12 UTC, FlorianGilbert requested changes
Not a real review, need to have a review from doc team

2023-03-13 09:12 UTC, FlorianGilbert commented on content/applications/finance/accounting/bank/feeds/enablebanking.rst
> +-------------------------------------------------------------------
```suggestion
I have an error with authorization
-------------------------------------------------
```

2023-03-13 09:12 UTC, FlorianGilbert commented on content/applications/finance/accounting/bank/feeds/enablebanking.rst
> +-------------------------------------------------------------------
```suggestion
Im seeing duplicate transactions
-----------------------------------------------
```
Probably we have to change the name of this part

2023-03-14 10:53 UTC, chiaraprattico commented
Hi @oskarenablebanking, thanks for your contribution. I'm putting this in draft as I will be checking about the content and form of your PR.

2023-03-24 12:51 UTC, oskarenablebanking reviewed
updated

2023-03-24 16:02 UTC, chiaraprattico commented
Hi @oskarenablebanking, I took your work and started a new branch to finalize the content and upload it online. So I'll close your branch, you can see updates here https://github.com/odoo/documentation/pull/3858.

Thanks!

2023-03-24 16:02 UTC, closed without merging