[REF] surveys: remove overview folder
odoo/documentation pull request #3803
Opened 2023-03-10 19:46 UTC by samueljlieber

Task: [#3189711](https://www.odoo.com/web#id=3189711&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form)

Targets: 14.0, 15.0, & 16.0

This PR removes the **Overview** folder in Surveys because it is an extra single folder to click through to get to the child pages.

Redirects added for all moved files.

2023-03-10 19:47 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3803).

2023-03-10 20:00 UTC, samueljlieber commented
Update in https://github.com/odoo/documentation/commit/5a065b07dce8ddab21346e1cf14f5c50652bd9d4:
- overview.rst --> surveys.rst redirect fixed

2023-03-30 17:40 UTC, ksc-odoo approved these changes

2023-04-25 20:34 UTC, samueljlieber commented
Fixed conflict on `redirect.txt` in https://github.com/odoo/documentation/commit/46835ba3b025c8fd37bb3b484eb1f06b2b24d4d6. @StraubCreative ready for your review 🙂

2023-04-26 01:38 UTC, StraubCreative requested changes
hi @samueljlieber 
Very quick edit which I'll push up in a sec and merge.
Thanks for getting to this so quickly!

2023-04-26 01:38 UTC, StraubCreative commented on content/applications/marketing/surveys.rst
>  :show-toc:
Would delete these too.
Structure it just like events so the top level menu link is a non-indexed page.

2023-04-26 02:08 UTC, StraubCreative approved these changes
@robodoo r+

2023-04-26 02:48 UTC, closed without merging