14.0 inventory add create second warehouse hojo
odoo/documentation pull request #3842
Opened 2023-03-16 20:19 UTC by hojo-odoo

This PR adds a new doc detailing how to create and configure a second warehouse, and add existing inventory to it.

2023-03-16 20:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/3842).

2023-03-16 20:21 UTC, hojo-odoo commented
Hey @StraubCreative,

This PR is ready for review.

Thanks,
hojo

2023-03-23 02:13 UTC, StraubCreative requested changes
Hi @hojo-odoo 

Couple quick CRs below.

For the media file names, these [need hyphens](https://www.odoo.com/documentation/15.0/contributing/documentation/content_guidelines.html#media-files) (-), not underscores (_) between the keyword values. For the IA config and NW config screenshots, think we can use more descriptive/real-life values for **Inventory Reference** and **Warehouse** name too.
e.g.
- Warehouse: San Francisco Fulfillment Center / Short Name: SF1
- Inventory Reference: SF1 Initial Inventory Count

2023-03-23 02:13 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/warehouses/create_a_second_warehouse.rst
> +  warehouse and any locations within it that inventory will be added to
Suggestion
```suggestion
- :guilabel:`Locations`: the location(s) where the inventory is stored; include the new warehouse
  and any locations within it that inventory will be added to
```

2023-03-23 02:13 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/warehouses/create_a_second_warehouse.rst
> +- :guilabel:`Location`: the location where the product is stored; this can be the new warehouse or a
Which location: the _old_ location where the stock was previously before being shifted to the new warehouse, or the _new_ location inside the additional warehouse?

2023-03-23 02:13 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/warehouses/create_a_second_warehouse.rst
> +- :guilabel:`On Hand`: the total number of the product stored in the location for which inventory is
Word choice
```suggestion
- :guilabel:`On Hand`: the total quantity of the product stored in the location for which inventory is
```

2023-03-23 02:13 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/warehouses/create_a_second_warehouse.rst
> +products added will appear in the inventory of the new warehouse.
Can break the tag
```suggestion
After adding all the products already stored in the new warehouse, click :guilabel:`Validate
Inventory` to complete the inventory adjustment. The values in the :guilabel:`On Hand` column will
update to reflect those in the :guilabel:`Counted` column and the products added will appear in the
inventory of the new warehouse.
```

2023-03-23 02:14 UTC, StraubCreative commented
Last thing quick:
We'll need to change the commit message both in git and here on GH so it follows the naming convention.
Can show you tomorrow 🙂

2023-04-04 21:45 UTC, StraubCreative commented
@StraubCreative 
Pretty sure PR is g2g, however we'll need to solve merge conflicts from #3967 first otherwise we'll run into more conflicts on FWPs.

2023-05-01 22:14 UTC, StraubCreative approved these changes
Hi @hojo-odoo thanks for making the edits and waiting for the other PR to merge first.

Updates on [68baa81](https://github.com/odoo/documentation/pull/3842/commits/68baa81eb36d4187fa4b55702f32a93d9a02445e): 
- renamed all images with hyphens (instead of underscores), updated RST
- CI check error (100th char break on line 43)

All checks pass ✅ 

@robodoo r+

2023-05-01 22:53 UTC, closed without merging

2023-05-03 05:03 UTC, jcs-odoo reviewed
Hi @hojo-odoo and @StraubCreative !

small (and late) comment about the title:
It's usually best not to use verbs in the main title and certainly not in the RST filename unless they're very specific. Verbs such as "manage" are noisy in the toc tree as they could be written on all pages. Imagine a left menu full of "create, manage, how to". It's just harder to navigate.
About "create", it's often not only about creating something but also its configuration etc.

https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html#titles-and-headings

If you plan to rename the RST filename, no need to add a redirection, as it's just been created.

Have a good day/evening :)

2023-05-03 17:52 UTC, StraubCreative commented
> 

Ah, that makes a lot of sense thanks for the advice @jcs-odoo 🙏 
@samueljlieber @hojo-odoo we can do a quick [FIX] PR to rename this file. Should be easy merge 🙂