[ADD] Employees: adding overview doc larm
odoo/documentation pull request #4038
Opened 2023-04-05 20:30 UTC by larm-odoo

Created a new Employees app section under HR and added the first new doc to this, the overview.

2023-04-05 20:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4038).

2023-04-19 13:55 UTC, jcs-odoo commented on content/applications/hr/employees.rst
> +:show-toc:
If you move your content to this page, no need for any of these options now.
```suggestion
```

However, if you add sub-pages, you'll need this:
```suggestion
:show-content:
:show-toc:
```

2023-04-21 16:05 UTC, hojo-odoo requested changes

2023-04-21 16:05 UTC, hojo-odoo commented on content/applications/hr/employees/employees_overview.rst
> +regarding their attendance can be done here.
Rephrase
```suggestion
The :guilabel:`Employee Presence` report shows how many employees are currently working or absent,
along with the options for managing :guilabel:`Time Off Requests`. Information on how to contact the employee via text or email is also located here.
```

2023-04-21 16:05 UTC, hojo-odoo commented on content/applications/hr/employees/employees_overview.rst
> +with metrics achieved.
Word choice
```suggestion
including metrics achieved.
```

2023-04-21 16:05 UTC, hojo-odoo commented on content/applications/hr/employees/employees_overview.rst
> +detail, as well as create and manage contract templates, to more easily handle new recruits. Gamify
Rephrase
```suggestion
job positions and departments are created and managed. From here, it is possible to create onboarding and offboarding plans in detail, as well as create and manage contract templates to more easily handle new recruits.
```

2023-10-26 21:01 UTC, larm-odoo commented
This overview was written when I first started writing the HR docs. There were no docs, so I started with these overviews. In the end, this was not the right path to take. Now, I have many HR docs written and published- all very thorough and detailed, so these are no longer needed. Closing this PR, along with the other 3 original "overview:" HR docs created at the same time.

2023-10-26 21:01 UTC, closed without merging