Update different_addresses.rst
odoo/documentation pull request #4083
Opened 2023-04-09 14:37 UTC by ahmedeali

the customer addresses feature is not in the settings of the sales app of v 16
its now part of the settings of the Invoicing app

2023-04-09 14:38 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4083).

2023-04-17 21:04 UTC, ksc-odoo reviewed
Just finished my peer review. Think its ready for a technical review, @samueljlieber

2023-04-17 21:04 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/different_addresses.rst
> +Go to :menuselection:`Invoicing --> Configuration --> Settings` and activate the **Customer Addresses**
Go to :menuselection:`Accounting app --> Configuration --> Settings` and scroll down to the :guilabel:`Customer Invoices` section. Then, check the box next to :guilabel:`Customer Addresses`, and click :guilabel:`Save`.

2023-04-18 17:41 UTC, StraubCreative requested changes
Hi @ahmedeali 👋 
Quick edit below. 
After that I think we're good to merge, thanks! 👍 

cc: @samueljlieber

2023-04-21 23:52 UTC, StraubCreative commented
Hi @ahmedeali or @samueljlieber 
Can you make the last edit here so we can close this PR out for you? 😉 
Thanks!

2023-04-24 13:28 UTC, samueljlieber commented
Implemented @StraubCreative [suggested edit](https://github.com/odoo/documentation/pull/4083#pullrequestreview-1390631016) in https://github.com/odoo/documentation/commit/95ef3dc96f9d4af08513987a1953d4969ed7b7d3.

2023-05-05 00:48 UTC, StraubCreative commented
@samueljlieber please fix the merge conflict. Afterwards can send to me immediately for quick merge (assuming everything else is g2g), thanks!

2023-05-08 19:33 UTC, samueljlieber commented
Resolved merge conflict in https://github.com/odoo/documentation/commit/2d55d20922eecb07ff29a450ebfbca93911cf8f4 due to https://github.com/odoo/documentation/commit/07249080ca4a7e47582792f5c93543fdb5a2f92f where this doc `different_addresses.rst` was updated, it appears the changes in this PR were covered in that commit, but I prefer the formatting in this PR (using the Note admonition block). Up to your discretion @StraubCreative to merge :)

2023-05-08 19:33 UTC, samueljlieber commented
Resolved merge conflict in https://github.com/odoo/documentation/commit/2d55d20922eecb07ff29a450ebfbca93911cf8f4 due to https://github.com/odoo/documentation/commit/07249080ca4a7e47582792f5c93543fdb5a2f92f where this doc `different_addresses.rst` was updated, it appears the changes in this PR were covered in that commit, but I prefer the formatting in this PR (using the Note admonition block). Up to your discretion @StraubCreative to merge :)

2023-05-09 16:23 UTC, StraubCreative approved these changes
@robodoo r+

2023-05-09 17:39 UTC, closed without merging