[IMP] accounting/electronic_invoicing: adapt to new Send & Print
odoo/documentation pull request #4152
Opened 2023-04-13 14:17 UTC by JulienVR

From saas-16.2, the choice of the format can be made from the partner form view (for the formats present in `account_edi_ubl_cii` only). And the attachment are generated during the Send & Print fow.

PR to select the EDI format based on the partner:
https://github.com/odoo/odoo/pull/115934

PR refactoring the Send & Print flow:
https://github.com/odoo/odoo/pull/111857

2023-04-13 14:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4152).

2023-04-14 08:40 UTC, jcs-odoo commented
I'll do the rebase #4155 will have been fw-ported to 16.2 .
Thanks already for the review/update, @toaa-odoo  :)

2023-04-14 08:50 UTC, JulienVR commented
> I'll do the rebase #4155 will have been fw-ported to 16.2 . Thanks already for the review/update, @toaa-odoo :)

I'll do it, I'm going to make some change again in a few minutes :D

2023-04-14 12:21 UTC, chiaraprattico requested changes

2023-04-14 12:21 UTC, chiaraprattico commented on content/applications/finance/accounting/receivables/customer_invoices/electronic_invoicing.rst
> +Electronic invoice generation
Generating an E-invoice

2023-04-14 12:22 UTC, chiaraprattico commented on content/applications/finance/accounting/receivables/customer_invoices/electronic_invoicing.rst
> +Use the :guilabel:`Send & Print` wizard on invoices to select the documents to be generated.
I'd say button instead of wizard

2023-04-14 14:06 UTC, JulienVR commented on content/applications/finance/accounting/receivables/customer_invoices/electronic_invoicing.rst
> +Select customer-specific electronic invoicing formats from the customer form view, in the Accounting tab.
Why would you go to the company view ? The formats are to be selected from the partners, not from the company 🤔. When we click on the "Send and Print" button, the format displayed is the one of the partner on the invoice/vendor bill. So it's not related on the company.

2023-04-14 14:32 UTC, chiaraprattico commented on content/applications/finance/accounting/receivables/customer_invoices/electronic_invoicing.rst
> +Select customer-specific electronic invoicing formats from the customer form view, in the Accounting tab.
My bad, I actually was thinking of the company info but indeed for the customer I'd still say:
Customer-specific electronic invoicing formats are available by going to :menuselection:Accounting --> Customers --> Customers'. Once in the company view, in the :guilabel:Accounting` tab the specific electronic format can be chosen.

2023-04-14 14:33 UTC, chiaraprattico commented on content/applications/finance/accounting/receivables/customer_invoices/electronic_invoicing.rst
> +Select customer-specific electronic invoicing formats from the customer form view, in the Accounting tab.
We always specify the path instead of just saying in the customer view even though it might be pretty obvious

2023-04-14 14:33 UTC, chiaraprattico approved these changes

2023-04-18 16:36 UTC, jcs-odoo commented
Not sure why GitHub is so slow to update the pr with the current branch: it still doesn't take the last push into account. I'll try one last amend + force-push for today.

2023-04-18 16:41 UTC, jcs-odoo approved these changes
@robodoo r+

2023-04-18 18:27 UTC, closed without merging