16.0 accesssettings lrpz
odoo/documentation pull request #4212
Opened 2023-04-19 15:55 UTC by LoredanaLrpz

task ID: 3256407

These commits:
- overview --> general features
- move getting started configuration content into general features
- add payment methods page with the configuration content
- move the payment terminals page under payment methods
- change getting started to sessions and update content

2023-04-19 15:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4212).

2023-04-20 09:41 UTC, AntoineVDV approved these changes

2023-04-22 07:33 UTC, jcs-odoo commented
Some of these changes seem to be for master (future saas-16.3) and not for 16.0
Restructuration of the toctree in #4226

2023-04-22 07:33 UTC, jcs-odoo requested changes
Some of these changes seem to be for master (future saas-16.3) and not for 16.0
Restructuration of the toctree in https://github.com/odoo/documentation/pull/4226

2023-04-22 16:42 UTC, jcs-odoo commented
merged in #4242

2023-04-22 16:42 UTC, closed without merging