[IMP] Update rst for target_audiences.rst (v14)
odoo/documentation pull request #4321
Opened 2023-05-02 17:56 UTC by ksc-odoo

made necessary RST formatting changes based on decisions made during the Writer's Workshop meeting

2023-05-02 17:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4321).

2023-05-03 21:06 UTC, samueljlieber requested changes
Hi @ksc-odoo 👋
I've made some technical changes, please review them below and let me know if you approve or have any changes. I will push these changes up after this review. 🙂

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +icon.
```suggestion
Keep the second portion of the filter equation on the default :guilabel:`🟰 (equal sign)` icon.
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +the equation.
```suggestion
Add another node to this filter by clicking the :guilabel:`➕ (plus sign)` icon to the right of the
equation.
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
>  (or search for) :guilabel:`Stage` from the field drop-down menu.
Can break this line later
```suggestion
the default :guilabel:`ID` from the first portion of the second filter equation, and scroll down (or
search for) :guilabel:`Stage` from the field drop-down menu.
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +Once again, leave the second portion of the filter equation on :guilabel:` 🟰 ` (equal sign)`.
```suggestion
Once again, leave the second portion of the filter equation on :guilabel:`🟰 (equal sign)` icon.

```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +While in Edit mode on a campaign template form (by clicking the :guilabel:`Edit` button), select
```suggestion
While in *Edit mode* on a campaign template form (by clicking the :guilabel:`Edit` button), select
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +Click the the default :guilabel:` 🟰 ` (equal sign)` in the second portion of the filter equation.
```suggestion
Click the default :guilabel:`🟰 (equal sign)` icon in the second portion of the filter equation.
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +of the equation.
```suggestion
Then, add another node to this filter by clicking the :guilabel:`➕ (plus sign)` icon to the right of
the equation.
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +same drop-down menu, select :guilabel:`Name`.
Line needs to break sooner
```suggestion
and scroll down (or search for) :guilabel:`Event Ticket` from the field drop-down menu. Then, in
that same drop-down menu, select :guilabel:`Name`.
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +Once again, click the the default :guilabel:` 🟰 ` (equal sign)` in the second portion of the filter
```suggestion
Once again, click the default :guilabel:`🟰 (equal sign)` icon in the second portion of the filter
```

2023-05-03 21:06 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/target_audience.rst
> +the event ticket type for this sample filter.
```suggestion
Lastly, in the third (and final) portion of the second filter equation, which is blank, type in the
name of the ticket type that should be used for the filter. In this case, :guilabel:`Standard` is
the name of the event ticket type for this sample filter.
```

2023-05-03 21:08 UTC, samueljlieber commented
Implemented my [technical changes](https://github.com/odoo/documentation/pull/4321#pullrequestreview-1411840359) in https://github.com/odoo/documentation/commit/d9609f563aa2e41a063122e24544a783ec2beb0c.

2023-05-04 14:53 UTC, samueljlieber approved these changes

2023-05-04 14:53 UTC, samueljlieber commented
Hi @StraubCreative this PR is ready for your review!

2023-06-06 15:20 UTC, samueljlieber commented
Rebased to latest and fixed 2 early line breaks in https://github.com/odoo/documentation/commit/442ba9eb7159abce044e2dd39dc07799f2d6d038 :)

2023-06-14 21:50 UTC, StraubCreative approved these changes
LGTM. Thanks all 🙂 

@robodoo r+

2023-06-14 22:00 UTC, ksc-odoo commented
> LGTM. Thanks all 🙂
> 
> @robodoo r+

Anything I need to do?

2023-06-14 22:12 UTC, robodoo commented
@ksc-odoo @StraubCreative staging failed: ci/runbot on a15491ec32ed71128a7ff8cca95e5e4de306768e (view more at https://runbot.odoo.com/runbot/build/45392020)

2023-06-15 13:22 UTC, StraubCreative commented
@robodoo -

2023-06-15 14:59 UTC, closed without merging