[IMP] 14.0 workflow_activities.rst - Format fixes
odoo/documentation pull request #4322
Opened 2023-05-02 18:40 UTC by ksc-odoo

added necessary RST formatting adjustments to adhere to decisions made during recent Writer's Workshop meeting

2023-05-02 18:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4322).

2023-05-03 21:44 UTC, samueljlieber requested changes
Hi @ksc-odoo please see my technical changes below and let me know if you approve or have any changes 🙂 I will push these changes up after this review.

2023-05-03 21:44 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/workflow_activities.rst
> +To get started, navigate to the bottom of a marketing automation campaign detail form,  and click
```suggestion
To get started, navigate to the bottom of a marketing automation campaign detail form, and click
```

2023-05-03 21:44 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/workflow_activities.rst
> +There is also the option to add a *Child Activity* by clicking :guilabel:`Add child activity`,
No need to capitalize _child activity_
```suggestion
There is also the option to add a *child activity* by clicking :guilabel:`Add child activity`,
```

2023-05-03 21:44 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/workflow_activities.rst
> +it, which is also known as its *Parent Activity*.
```suggestion
Child activities are sub-activities that are connected to (and triggered by) the activity above it,
which is also known as its *parent activity*.
```

2023-05-03 21:44 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/getting_started/workflow_activities.rst
> +indented position beneath its parent activity.
```suggestion
Once a trigger is selected, the user can configure the child activity (it has the same configuration
options as a regular activity), and click :guilabel:`Save & Close` to finish creating the child
activity, which will then be displayed in the :guilabel:`Workflow` section, in a slightly indented
position beneath its parent activity.
```

2023-05-03 21:46 UTC, samueljlieber commented
Implemented my [technical changes](https://github.com/odoo/documentation/pull/4322#pullrequestreview-1411925297) in https://github.com/odoo/documentation/pull/4322#pullrequestreview-1411925297.

2023-05-03 21:47 UTC, ksc-odoo commented
> Hi @ksc-odoo please see my technical changes below and let me know if you approve or have any changes 🙂 I will push these changes up after this review.

@samueljlieber everything looks good to me - thanks again for the always-awesome reviews!

2023-05-04 14:54 UTC, samueljlieber commented
Hi @StraubCreative this PR is ready for your review!

2023-06-15 13:28 UTC, StraubCreative approved these changes
Seems good. Thanks all 👍

2023-06-15 15:59 UTC, closed without merging