OWL DateTimePicker + dates unification
odoo/documentation pull request #4330
Opened 2023-05-03 15:02 UTC by Arcasias

# Owl DateTimePicker (documentation)

This PR introduces a date picker OWL component meant to handle the
following use-cases:
- date picker
- date & time picker
- date range picker
- date & time range picker

Basically, this component is the union of the two previous third-party
libraries handling these cases: TempusDominus and DateRangePicker.

## New components introduced:

* The main addition of this commit is the `DateTimePicker` itself which
handles the display and interactions of the calendar and time pickers.
> see @web/core/datetime/datetime_picker

* The picker can then be coupled to an input using the
`useDateTimePicker` hook. The purpose of this hook is to handle events
on a given input element and syncronize its value to a date picker it
will spawn in a popover.
> see @web/core/datetime/datetime_hook

* Lastly, a simple `DateTimeInput` component will render an input and
call the hook mentioned above to handle it. This component is
effectively replacing the previous DatePicker and DateTimePicker
components (note that it does not handle range values).
> see @web/core/datetime/datetime_input

## Date range declarations in views

Another noticeable change of this commit is the definition of daterange
fields in views:

- Previously, the arch would have to define both fields
and bind them via their options, while also adding an arrow between
inputs or other forms of connection.

- In the new implementation, only the start date field must be declared,
and a date range can be spawned by providing an `end_date_field` in its
options.

Example:
```xml
<field
    name="start_datetime"
    widget="daterange"
    options="{'end_date_field': 'end_datetime'}"
/>
```

## ⚠️ Added limitations

- this new way of declaring date ranges means that templates have been
revised to declare one field tag instead of two. This means that list
views using date ranges have lost the ability to be sorted on their end
date fields.

> Justification: the current use cases have been reviewed and it has
been decided that it was not needed to sort on the end date on the
affected list views.

> Workaround: drop the date range and declare both fields as simple date
pickers (i.e. without the end_date_field option).

- all modifiers applied to a field using a date range will be copied and
applied to the end date field. There is no way to define modifiers
specific to one field or the other.

> Justification: there was no use case where one of the two fields
needed specific modifiers.

> Workaround: same as the previous point: split the range into 2 simple
date picker fields.

## Additional notes:

- the `widget="daterange"` is not mandatory in form views, but is required
in list views because only fields with explicit widgets will not be
rendered as simple <span> elements. The date range feature will be
available as soon as an end_date_field is specified.

- as the end date field is not explicitly defined in the view anymore,
any modifier depending on it need to have it defined as invisible
somewhere in the arch.

## Links
- Community PR: https://github.com/odoo/odoo/pull/112171
- Enterprise PR: https://github.com/odoo/enterprise/pull/38569
- Task ID: [3121497](https://www.odoo.com/web#id=3121497&cids=1&menu_id=4720&action=333&active_id=133&model=project.task&view_type=form)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2023-05-03 15:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4330).

2023-06-30 10:17 UTC, fdardenne approved these changes

2023-06-30 10:19 UTC, fdardenne commented
I've rebuilt the runbot build to see the result in live.
It is now red, don't know why: I launch a rebuild

2023-06-30 12:56 UTC, AntoineVDV requested changes
Hello, I started a new batch of builds with an automatic rebase to fix the red CIs, but you'll have to rebase manually before pushing.

2023-06-30 12:56 UTC, AntoineVDV commented on content/developer/reference/frontend/javascript_reference.rst
> +      <field name="datefield" options="{'min_date': 'today', 'max_date': '2023-12-31'}" />
Indent this code-block and the second one below to make them part of the bullet points.
```suggestion
    .. code-block:: xml

        <field name="datefield" options="{'min_date': 'today', 'max_date': '2023-12-31'}" />
```

2023-06-30 12:56 UTC, AntoineVDV commented on content/developer/reference/frontend/javascript_reference.rst
>  date (FieldDate)
Define anchors to reference from other fields.
```suggestion
.. _reference/javascript_reference/field_date:

date (FieldDate)
```

2023-06-30 12:56 UTC, AntoineVDV commented on content/developer/reference/frontend/javascript_reference.rst
> +  - see FieldDate options
Reference the new anchor(s).
```suggestion
  - see :ref:`FieldDate <reference/javascript_reference/field_date>` options
```

2023-06-30 12:56 UTC, AntoineVDV commented on content/developer/reference/frontend/javascript_reference.rst
> +    Accepted values are: SQL-formatted dates (yyyy-MM-dd HH:mm:ss) or *today*.
Markup at least the technical terms/formats as literals (and, optionally, the values too, or in bold) for better clarity.
```suggestion
  - `min_date`/`max_date`: sets limit dates for accepted values. By default, the earliest
    accepted date is **1000-01-01** and the latest is **9999-12-31**.
    Accepted values are: SQL-formatted dates (`yyyy-MM-dd HH:mm:ss`) or **today**.
```

2023-06-30 12:56 UTC, AntoineVDV commented on content/developer/reference/frontend/javascript_reference.rst
> +  - Supported field types: *date*
```suggestion
  - Supported field types: `date`
```

2023-06-30 12:56 UTC, AntoineVDV commented on content/developer/reference/frontend/javascript_reference.rst
> +  - warn_future: displays a warning if the value is in the future (based on today).
```suggestion
  - `warn_future`: displays a warning if the value is in the future (based on today).
```

2023-07-03 11:06 UTC, AntoineVDV commented
> I noticed that some of the changes you requested would actually break consistency with the overall "style" of the fields' doc. Do you want me to apply your remarks to all other fields or should I stick to the original notation?

@Arcasias Hello, some of my suggestions are indeed not in line with some parts of that page, but they follow the style we try to progressively apply to the documentation as a whole. Like in odoo/odoo, the recommendation to follow the existing style in odoo/documentation only holds if the existing content has been somewhat recently revamped; otherwise, we're just expanding the bad style elsewhere. :sweat_smile: 
In the end, the decision is yours, as it's essentially a matter of "taste".

@Arcasias Hello, some of my suggestions are indeed not in line with some parts of that page, but they follow the style we try to progressively implement in the documentation as a whole. Like in odoo/odoo, the recommendation to follow the existing style in odoo/documentation only holds if the existing content has been somewhat recently revamped; otherwise, we're just spreading the bad style elsewhere. :sweat_smile: 
In the end, the decision is yours, as it's essentially a matter of "taste".

2023-07-03 13:46 UTC, AntoineVDV approved these changes
Even better :ok_hand: 

@robodoo r+ rebase-ff

2023-07-03 13:47 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-07-04 00:12 UTC, closed without merging