[IMP] subscriptions: update subscription plans
odoo/documentation pull request #4343
Opened 2023-05-04 21:02 UTC by meng-odoo

Update to the emergency subscriptions update for Odoo 16 (eliminating subscription templates from Odoo 15).
Related to task #[3222232](https://www.odoo.com/web#id=3222232&menu_id=4720&cids=3&action=333&active_id=3835&model=project.task&view_type=form)

2023-05-04 21:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4343).

2023-05-05 16:49 UTC, hojo-odoo requested changes
Hey @meng-odoo,

Great job on this! Most of my comments are pretty minor. Make sure to decapitalize all of the words that follow a colon.

Thanks,
hojo

2023-05-05 16:49 UTC, hojo-odoo commented on content/applications/sales/subscriptions/plans.rst
> +- The name of the plan: Enter a name for the subscription plan at the top of the page.
```suggestion
- Title: Enter a name for the subscription plan at the top of the page.
```

2023-05-05 16:49 UTC, hojo-odoo commented on content/applications/sales/subscriptions/plans.rst
> +  paying for the quotation. Enable both to leave the choice to the customer. Enable neither to only
```suggestion
  paying for the quotation. Enable both to leave the choice up to the customer. Enable neither to only
```

2023-05-05 16:49 UTC, hojo-odoo commented on content/applications/sales/subscriptions/plans.rst
> +Selecting a :guilabel:`Recurrence` turns the quotation template into a subscription plan and enables
```suggestion
Selecting a :guilabel:`Recurrence` period turns the quotation template into a subscription plan and enables
```

2023-05-05 16:49 UTC, hojo-odoo commented on content/applications/sales/subscriptions/plans.rst
> +All subscription orders will appear on the *Subscriptions* dashboard regardless of whether they were
Same as above.

2023-05-08 21:15 UTC, meng-odoo commented
Thanks for your review @hojo-odoo! FYI I followed all of the colons with a complete sentence so that they could properly be in sentence case (have a capitalized first letter).

Hi @samueljlieber, this is ready for technical review.

2023-05-09 20:18 UTC, samueljlieber requested changes
Hi @meng-odoo 👋 I made just a couple of technical suggestion on this PR, please review them below and let me know if you have any questions. 

Note on images: Since were improving this doc, can you please resize the images used in `plans.rst` to be a maximum of 933px wide, ideally 768px wide. 

Thank you! 🙏

2023-05-09 20:18 UTC, samueljlieber commented on content/applications/sales/subscriptions/plans.rst
> +    determines the amount of time after which the subscription will automatically end.
early 100th char line break

2023-05-09 20:18 UTC, samueljlieber commented on content/applications/sales/subscriptions/plans.rst
> +  *past* the due date are automatically closed.
early 100th char line break

2023-05-10 23:41 UTC, meng-odoo commented
Thank you @samueljlieber! I incorporated your edits (and added an image while I was at it) in the latest commit. Requesting your review again just in case :)

2023-05-15 14:23 UTC, samueljlieber approved these changes
Hi @meng-odoo! This PR is good to go 🚀 great job! @StraubCreative sending this to you for final review!

2023-05-22 18:51 UTC, closed without merging