[ADD] Inventory: Add Replenish on order (MTO)
odoo/documentation pull request #4406
Opened 2023-05-10 22:07 UTC by hojo-odoo

This PR adds a new doc for the Inventory app detailing how to use the Replenish on Order (MTO) route. 

This doc expands upon the information in the MTO subsection of the [How to select the right replenishment strategy](https://www.odoo.com/documentation/14.0/applications/inventory_and_mrp/inventory/management/products/strategies.html) doc, which also contains subsections about replenishment rules and the Replenishment page. Two additional docs will be pushed regarding those topics, at which point the "How to select the right replenishment strategy" doc will be deleted.

2023-05-10 22:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4406).

2023-05-11 18:36 UTC, ksc-odoo reviewed
@hojo-odoo just finished reviewing this doc. Fantastic job. Just a few minor adjustments, but it should be good to go after that. If you have any questions or need clarification on anything, just let me know. Once again, great work! 👍

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +:guilabel:`Save` to save the Bill of Materials.
```suggestion
If the product is manufactured, click the :guilabel:`Bill of Materials` smart button at the top of
the screen, then click :guilabel:`Create` on the :guilabel:`Bill of Materials` page to configure a
new Bill of Materials for the product. Doing so reveals a blank Bill of Materials form.

On the blank Bill of Materials form, add the components used to manufacture the product under the
:guilabel:`Components` tab. In the along with the :guilabel:`Operations` tab, add operations
required for the manufacturing workflow, by clicking :guilabel:`Add a line`, and entering in the
necessary information in the :guilabel:`Create Operations` pop-up.

Then, click :guilabel:`Save & Close` to save and return to the Bill of Materials form, or
:guilabel:`Save & New` to save and immediately create another operation on a fresh
:guilabel:`Create Operations` pop-up.

Lastly, when all necessary configurations are complete, click :guilabel:`Save` to save the Bill of
Materials.
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +=========================================
```suggestion
Fulfill sales order with MTO route
==================================
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +=========================================
```suggestion
Fulfill sales order with MTO route
==================================
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +selected, then a Purchase Order will be created upon confirmation of a Sales Order.
```suggestion
After configuring a product to use the MTO route, a replenishment order is created for it every
time a Sales Order including that specific product is confirmed. The type of order created depends
on the second route selected, in addition to MTO.

For example, if *Buy* was the second route selected on the product form, then a Purchase Order is
created upon confirmation of a Sales Order.
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +   hand to fulfill the Sales Order without buying or manufacturing additional units of it.
```suggestion
   When the MTO route is enabled for a product, a Replenishment Order is always created upon
   confirmation of a Sales Order. This is the case even if there is enough stock of the product
   on-hand to fulfill the Sales Order, without buying or manufacturing additional units of it.
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +then click :guilabel:`Create` to create a new Quotation.
```suggestion
While the MTO route can be used in unison with a variety of other routes, the *Buy* route
is used as the example for this workflow. Begin by navigating to the :menuselection:`Sales` app,
then click :guilabel:`Create`, which reveals a blank Quotation form.
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +routes. Click :guilabel:`Confirm` and the Quotation will be turned into a Sales Order.
```suggestion
On the blank Quotation form, add a :guilabel:`Customer`, then click :guilabel:`Add a product` under
the :guilabel:`Order Lines` tab, and enter a product that has been configured to use the *MTO* and
*Buy* routes. Then, click :guilabel:`Confirm`, and the Quotation is turned into a Sales Order.
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +click it to register them into inventory.
```suggestion
A :guilabel:`Purchase` smart button appears in the top-right corner of the Sales Order. Clicking it
reveals the Request for Quotation associated with that specific Sales Order.

Click :guilabel:`Confirm Order` to confirm the Request for Quotation, and turn it into a Purchase
Order. Doing so reveals a green :guilabel:`Receive Products` button at the top of the Purchase
Order. Click that button once the products are received to register them into inventory.
```

2023-05-11 18:36 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +the customer, click :guilabel:`Validate` to confirm the delivery.
```suggestion
Return to the Sales Order by clicking the :guilabel:`SO` breadcrumb, or by navigating to
:menuselection:`Sales app --> Orders --> Orders` and selecting the desired Sales Order.

Then, click the :guilabel:`Delivery` smart button in the top-right of the order to be taken to the
Delivery Order. Once the products have been shipped to the customer, click :guilabel:`Validate` to
confirm the delivery.
```

2023-05-11 18:36 UTC, ksc-odoo reviewed
@hojo-odoo just finished reviewing this doc. Fantastic job. Just a few minor adjustments, but it should be good to go after that. If you have any questions or need clarification on anything, just let me know. Once again, great work! 👍

2023-06-23 12:12 UTC, samueljlieber requested changes
Hi @hojo-odoo ✌️ great job with this new doc! It is looking really great, I have just a few technical changes– most are removing capitalization from general industry terms. 

You will a suggestion for adding abbreviation shorthands, let me know if you have any questions on that!

Thank you for the continued hard work on this PR 🙏

2023-06-23 12:12 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +route selected in addition to MTO.
Adding abbreviations and no caps on _sales order_
```suggestion
After configuring a product to use the |MTO| route, a replenishment order is created for it every
time a sales order including the product is confirmed. The type of order created depends on the
second route selected in addition to |MTO|.
```

2023-06-23 12:12 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +confirmation of a Sales Order.
Remove caps
```suggestion
For example, if *Buy* was the second route selected, then a purchase order is created upon
confirmation of a sales order.
```

2023-06-23 21:00 UTC, hojo-odoo commented
Hey @samueljlieber,

This should be ready for Zach too. I addressed all of your comments.

Thanks,
hojo

2023-06-26 15:37 UTC, samueljlieber approved these changes
Hi @hojo-odoo great job with this PR! It is looking great to me 🙂 I am approving now but please make the changes below before passing to final review!

2023-06-26 15:37 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +Fulfill a Sales Order using the MTO route
No caps needed on _sales order_
```suggestion
Fulfill a sales order using the MTO route
```

2023-07-01 03:35 UTC, StraubCreative approved these changes
Looks good @hojo-odoo 

On future versions I think it would be valuable to also include an MTO + Manufacture route section with a full walk-through of managing an MTO-manufactured product.

This should get us started though, as it's immediately useful for customers 😉 
Don't forget to update 16.0 with new UI screenshots and remove "save" and/or "edit" language where necessary.

@robodoo r+

2023-07-01 03:35 UTC, StraubCreative commented on content/applications/inventory_and_mrp/inventory/management/products/mto.rst
> +.. |BOM| replace:: :abbr:`BOM (bill of materials)`
This is how we've been formatting the capitalization of these acronyms.
```suggestion
.. |MTO| replace:: :abbr:`MTO (Make to Order)`
.. |RFQ| replace:: :abbr:`RFQ (Request for Quotation)`
.. |BOM| replace:: :abbr:`BoM (Bill of Materials)`
```

2023-07-01 04:40 UTC, closed without merging