[IMP] accounting: default_taxes.rst - Changes on invoices
odoo/documentation pull request #4421
Opened 2023-05-12 09:03 UTC by gawa-odoo

Since https://github.com/odoo/odoo/pull/115222, a new line on an invoice won't have the default sales tax put on by default. If there are no taxes on the product, the account or from predictive, the tax will stay empty Its use has been restricted back to the tax put on new products. It is still used in Accounting Firms mode, as we don't want people to have to input the product when quick encoding.

task-3045026

2023-05-12 09:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4421).

2023-05-12 10:55 UTC, chiaraprattico requested changes
Hello, thanks for this one. I made a few suggestions. You can find more information about adding images to a doc over here https://www.odoo.com/documentation/15.0/contributing/documentation/rst_cheat_sheet.html#images

2023-05-12 10:55 UTC, chiaraprattico commented on content/applications/finance/accounting/taxation/taxes/default_taxes.rst
> +.. image:: default_taxes/default-taxes-product.png
For a better resolution, please take the screenshot with 110% zoom (or more if needed). Also, the file should always be compressed, if there are any irrelevant parts, it's better to crop them ( for example, here the internal note field at the bottom can be left out so we can focus on what matters).

2023-05-12 10:55 UTC, chiaraprattico commented on content/applications/finance/accounting/taxation/taxes/default_taxes.rst
> +It is also used to prefill the **Taxes** field with when you add a new line on an invoice in Accounting Firms mode.
**Default Taxes** define which :doc:`taxes <taxes>` are automatically selected when creating a new product.
They also used to prefill the :guilabel:`Taxes` field when adding a new line on an invoice in Accounting Firms mode.

2023-05-16 07:46 UTC, chiaraprattico approved these changes

2023-05-16 12:11 UTC, jcs-odoo commented
oh no, this is going one of the many conflicts with the restructure :'(

2023-05-16 12:26 UTC, gawa-odoo commented
> oh no, this is going one of the many conflicts with the restructure :'(

I don't know what the restructure is about, but I don't mind waiting to rebase and merge it afterwards. I mainly wanted to do it to not forget about this change.

2023-05-16 12:39 UTC, jcs-odoo commented
> > oh no, this is going one of the many conflicts with the restructure :'(
> 
> I don't know what the restructure is about, but I don't mind waiting to rebase and merge it afterwards. I mainly wanted to do it to not forget about this change.

Haha! No, no worries @gawa-odoo go ahead and merge this whenever needed!

Here is our attempt at improving the structure of the accounting documentation.
https://github.com/odoo/documentation/pull/4422

2023-05-24 13:28 UTC, jcs-odoo approved these changes
@robodoo r+

2023-05-24 19:26 UTC, closed without merging