[IMP] sales: updated get signature for validation doc for RST formatting
odoo/documentation pull request #4460
Opened 2023-05-17 18:01 UTC by ksc-odoo

updated RST formatting and compressed images (added additional image, as well) to the "get signature for validation" sales doc for v14 - but should be forward-ported to 15, 16 (and minor modifications and adjustments will be made to those versions in the future)

Project Task: https://www.odoo.com/web#id=3330435&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2023-05-17 18:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4460).

2023-06-13 18:10 UTC, hojo-odoo commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +   :guilabel:`Confirmation` tab.
This conditional doesn't make sense. It reads like you're saying that the Online Signature feature is found on the Confirmation tab IF the reader is familiar with the quote template documentation. I think you can remove the intro entirely. See below.
```suggestion
   The :guilabel:`Online Signature` feature for each quotation template is found under the
   :guilabel:`Confirmation` tab.
```

2023-06-13 18:10 UTC, hojo-odoo commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +on the quotation. When clicked, clients have the option to draw a signature, automatically fill in
```suggestion
on the quotation. When clicked, clients have the option to draw a signature, fill in
```

2023-06-21 19:21 UTC, samueljlieber requested changes
Hi @ksc-odoo, nice job! I have just a couple of changes needed, let me know when this PR is ready for another look!

2023-06-21 19:21 UTC, samueljlieber commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +:guilabel:`Save` button in the top-left corner.
Early line break
```suggestion
Settings`, scroll to the :guilabel:`Quotations & Orders` heading, and activate the :guilabel:`Online
Signature` feature by checking the box beside it, and clicking the :guilabel:`Save` button in the
top-left corner.
```

2023-06-21 19:21 UTC, samueljlieber commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +To activate the *Online Signature* feature, go to :menuselection:`Sales app --> Configuration -->
No need to capitalize *online signature*
```suggestion
To activate the *online signature* feature, go to :menuselection:`Sales app --> Configuration -->
```

2023-06-21 19:21 UTC, samueljlieber commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +   :alt: How to enable online signature on Odoo Sales.
All three following images have the same alt text, its best for each to be descriptive and unique.
```suggestion
   :alt: How to enable online signature in Odoo Sales settings.
```

2023-06-21 19:21 UTC, samueljlieber commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +      :alt: How to enable online signature on Odoo Sales.
```suggestion
      :alt: How to enable online signature on a quotation template.
```

2023-06-21 19:21 UTC, samueljlieber commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +      :alt: How to enable online signature on Odoo Sales.
```suggestion
      :alt: How to enable online signature on standard quotations.
```

2023-06-22 17:14 UTC, ksc-odoo commented
> Hi @ksc-odoo, nice job! I have just a couple of changes needed, let me know when this PR is ready for another look!

Alrighty, @samueljlieber - this is ready for another quick review, whenever you get a chance. Thanks! 👍

2023-06-26 14:34 UTC, samueljlieber approved these changes
Hi @ksc-odoo this PR looks great! Approving now and sending to final review. @StraubCreative this should be a quick merge 🙂

2023-07-31 22:10 UTC, meng-odoo requested changes
Hi @ksc-odoo, this doc looks great! I just had a few tiny changes before we merge. Thanks!

2023-07-31 22:10 UTC, meng-odoo commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +   The :guilabel:`Online Signature` feature for each quotation template is found under the
Changing the sentence structure slightly to mirror the following sentence and draw the comparison more clearly.
```suggestion
   On quotation templates, the :guilabel:`Online Signature` feature is located under the
```

2023-07-31 22:10 UTC, meng-odoo commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +and confirmed, a delivery order is automatically created.
```suggestion
and confirmed, a delivery order is automatically created (if the Odoo *Inventory* app is installed).
```

2023-07-31 22:10 UTC, meng-odoo commented on content/applications/sales/sales/send_quotations/get_signature_to_validate.rst
> +on the quotation. When clicked, clients have the option to draw a signature, fill in the field with
```suggestion
on the quotation in the online customer portal. When clicked, clients have the option to draw a signature, fill in the field with
```

2023-07-31 23:08 UTC, ksc-odoo commented
> Hi @ksc-odoo, this doc looks great! I just had a few tiny changes before we merge. Thanks!

@meng-odoo Alrighty - just made all those suggested edits. Thanks for the super-helpful feedback! If there's anything else you need me to do with this doc - just let me know. If not, feel free to merge! Thanks again 👍

2023-08-01 17:22 UTC, meng-odoo commented
@samueljlieber There were only very tiny changes to this PR, but could you please do another quick review before we merge? Thanks so much :)

2023-08-02 13:38 UTC, samueljlieber approved these changes
Hi @ksc-odoo this PR looks good to me! Nice job 🙂 

@StraubCreative ready for merge 👍 and can be FWP to 15.0 & 16.0.

2023-08-05 00:42 UTC, StraubCreative approved these changes
Short and sweet, nice job @ksc-odoo 👍 
Approving with two small comments which can optionally be addressed later

@robodoo r+

2023-08-05 01:35 UTC, closed without merging