[ADD] accounting: add Singapore localisations
odoo/documentation pull request #4565
Opened 2023-05-30 12:34 UTC by tong-odoo

Impacted versions:

- saas-16.4 or above

This commit improve below features:

- Singapore accounting documentation
- PayNow QR code documentation

task-3130633

2023-05-30 12:35 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4565).

2023-05-31 07:08 UTC, toaa-odoo approved these changes

2023-06-12 15:28 UTC, jcs-odoo requested changes
Hello,

Thanks for your contribution to the documentation! :)

I just want to double-check the version we should target for these two commits?
I see the support for HK FPS was made in 16.3, and not for the next 16.4 freeze, and I couldn't find any paynow task.

Thank you :)

2023-06-12 15:28 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/singapore.rst
> +   :alt: "QR Codes" feature activated
not necessary, in my opinion

2023-06-12 15:28 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/singapore.rst
> +.. note::
important note, maybe? If not, you can group the next note with this one, in a bullet list
```suggestion
.. important::
```

2023-06-12 15:28 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/singapore.rst
> +   :align: center
you can delete all the centered alignment
```suggestion
```

2023-06-13 01:30 UTC, vin-odoo commented
@jcs-odoo Howdy :smile: 
It does have to target master, it is linked to this bundle => https://runbot.odoo.com/runbot/bundle/master-l10n-sg-tong-16306
and this task => https://www.odoo.com/web#id=3130633&cids=5&menu_id=4720&action=333&active_id=1822&model=project.task&view_type=form

It adds pay now as a payment QR code for SG, and at the same time refactors the recent HK payment QR to move some things in the generic module that is shared with the SG one (and some others in the future).
So the 16.3 version of the doc is still valid for 16.3, and it has to change for 16.4

2023-06-13 01:58 UTC, tong-odoo commented on content/applications/finance/fiscal_localizations/singapore.rst
> +Go to :menuselection:`Accounting --> Configuration --> Settings`. Under the :guilabel:`Customer
Right now i only see EMV format in APAC region. Not sure if I will encounter more

2023-06-13 01:59 UTC, tong-odoo commented on content/applications/finance/fiscal_localizations/hong_kong.rst
> +Value` field depending on the type you chose.
The update only applied to 16.4. In 16.3, it stays the same.

2023-06-13 01:59 UTC, tong-odoo commented on content/applications/finance/fiscal_localizations/singapore.rst
> +
sure.

2023-06-13 11:03 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-06-13 12:01 UTC, robodoo commented
@tong-odoo @jcs-odoo linked pull request(s) odoo/upgrade#4727 not ready. Linked PRs are not staged until all of them are ready.

2023-06-15 16:51 UTC, closed without merging