[ADD] Incoterms doc
odoo/documentation pull request #4572
Opened 2023-05-31 12:48 UTC by toaa-odoo

Seperating Incoterms section from "Intrastat" doc to make it a stand alone documentation.

task-3305222

2023-05-31 12:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4572).

2023-06-01 09:07 UTC, dade-odoo requested changes
Hi Tom!

Great PR - I made a few comments about the structure and the need to include instructions on how to create additional Incoterms.

Also, Loredana and I both agree that Reporting isn't the best section for Incoterms. Perhaps Customer invoices instead?

2023-06-01 13:12 UTC, toaa-odoo commented
@dade-odoo Thanks for your review! I addressed the few points you mentioned. As for the location of the doc, Jon put Intrastat here, and since he wanted to split from Incoterms, I figured it should be in the same place

2023-06-01 14:19 UTC, jcs-odoo reviewed
Looks good

- change commit message and pr title:

2023-06-01 14:35 UTC, jcs-odoo requested changes
Hey @toaa-odoo and @dade-odoo 

Looks good :)
Please change the commit message and pr title: `[ADD] accounting: incoterms`

Also, now that I read this intro, I don't think it belongs to the reporting section. I guess it is mostly useful for customer invoices to define the responsibility of the customer.  wdyt?

Cheers, Jonathan

2023-06-01 14:35 UTC, jcs-odoo commented on content/applications/finance/accounting/reporting/incoterms.rst
> +---------------------
I'd make this a h2 level, instead of h3

```suggestion
.. _incoterms/default:

Default Incoterm rule
=====================
```

2023-06-01 14:35 UTC, jcs-odoo commented on content/applications/finance/accounting/reporting/incoterms.rst
> +=============
It's not really a configuration. You rather define an Incoterm for a document. "define an incoterm"? or maybe even no heading ^^

2023-06-02 08:35 UTC, jcs-odoo approved these changes
@robodoo r+

2023-06-02 10:20 UTC, closed without merging