[IMP] accounting: OSS report
odoo/documentation pull request #4615
Opened 2023-06-02 12:05 UTC by toaa-odoo

Added a section on where to find OSS reports and how to export them

task-3305037

2023-06-02 12:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4615).

2023-06-06 07:45 UTC, LoredanaLrpz requested changes
Hey @toaa-odoo , as usual, a great work. Here are my suggestions, mostly to avoid "repetitions in ideas" - we can have a call to discuss it if you want to :)

2023-06-06 11:39 UTC, toaa-odoo commented on content/applications/finance/accounting/taxes/eu_distance_selling.rst
> +Summary`, and select either :guilabel:`OSS Sales` or :guilabel:`OSS Imports`. Once selected, click
Thanks for the notification!

2023-06-06 14:47 UTC, LoredanaLrpz approved these changes
Hey @toaa-odoo , I just have one last suggestion, but I'm approving this PR
Cheers!

2023-06-09 11:16 UTC, jcs-odoo requested changes
Hi @toaa-odoo and @LoredanaLrpz 

In addition to my comments, you can also remove the centered alignment of the images if you'd like.

Cheers :)

2023-06-09 16:05 UTC, jcs-odoo commented
@robodoo r+

2023-06-09 17:55 UTC, closed without merging