[IMP] Adyen: Update directions for setting the URLs
odoo/documentation pull request #4634
Opened 2023-06-06 14:53 UTC by auva-odoo

task-3338125

2023-06-06 14:54 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4634).

2023-06-06 15:45 UTC, AntoineVDV requested changes
LGTM, but I think we should also provide the test URLs now and not in another task, as we first discussed. The reason is that, in the previous API URLs page, Adyen listed the test URLs, which allowed users to follow the same configuration steps in both live and test environments.

2023-06-07 08:59 UTC, zulu-odoo requested changes
Hellooo,
Just two tiny things, I leave it up to you to decide if they're valid or not :)
Thank youuu

2023-06-07 09:09 UTC, auva-odoo commented on content/applications/finance/payment_acquirers/adyen.rst
>  Be careful to copy your API key as you'll not be allowed to get it later without generating a new
You're right, but I will take care of this in another PR when I review the structure of the whole page (it needs a lot of TLC) :-)

2023-06-07 09:09 UTC, auva-odoo commented on content/applications/finance/payment_acquirers/adyen.rst
> +#. In Odoo, :ref:`navigate to the payment acquirer Adyen <payment_acquirers/add_new>`.
It's still "payment acquirers" in v15 but I will have to change it for v16 :-)

2023-06-07 09:13 UTC, zulu-odoo approved these changes

2023-06-07 13:33 UTC, AntoineVDV approved these changes
@robodoo r+

2023-06-07 15:48 UTC, closed without merging