[IMP] Expenses: making targeted edits for v 15
odoo/documentation pull request #4701
Opened 2023-06-09 19:00 UTC by larm-odoo

Needed to edit the pushed new Expenses doc that was sent to v 15  and make edits for the V15 document ONLY.

2023-06-14 15:15 UTC, samueljlieber commented
Implemented [my technical changes](https://github.com/odoo/documentation/pull/4701#pullrequestreview-1478070068) in https://github.com/odoo/documentation/commit/30b6209c1f4fd978666269e0584a4685f20c7af1. @StraubCreative this PR is ready for your final review, and this PR **should not be FWP to 16.0**.

2023-06-14 15:15 UTC, samueljlieber approved these changes

2023-06-20 21:09 UTC, StraubCreative requested changes
Hi @larm-odoo 
Looks pretty good here too.
I have a couple of suggestions below.
Overall, double-check singular vs. plural t/o the doc please. I pointed out a couple spots where there was a mismatch, but not all.

2023-06-20 21:09 UTC, StraubCreative commented on content/applications/finance/expenses.rst
> +:guilabel:`Expenes` smart button appears in the top right, listing the number of expenses on the
```suggestion
:guilabel:`Expenes` smart button appears in the top-right corner, listing the number of expenses on the
```

2023-06-20 21:09 UTC, StraubCreative commented on content/applications/finance/expenses.rst
> +leaving only the :guilabel:`My Team` filter active.
suggestion to join the sentences and remove the **X**
```suggestion
Team`. This presents all the reports to approve for the manager's team. Manager's can easily view
*all* reports for their team by simply clicking the removing the :guilabel:`To Approve` filter in
the :guilabel:`Search...` bar,leaving only the :guilabel:`My Team` filter active.
```

2023-06-20 21:09 UTC, StraubCreative commented on content/applications/finance/expenses.rst
> +   :guilabel:`Add Followers`.
This whole section reads more as a **tip**, actually.
Also would start it like this:
`If more information is needed, such as a missing receipt, communication is  easy from the`

2023-06-20 21:09 UTC, StraubCreative commented on content/applications/finance/expenses.rst
> +order can then be invoiced, thus invoicing the customer for the expense.
Reads clunky. Can you give this section another look?

2023-06-20 21:09 UTC, StraubCreative commented on content/applications/finance/expenses.rst
> +:guilabel:`Analytic Account` the expense will be posted to. After the expense(s) are created, the
We introduce the instruction using expense (singular), so grammar should match accordingly.
```suggestion
:guilabel:`Analytic Account` the expense will be posted to. After the expense(s) is created, the
```

2023-06-20 21:09 UTC, StraubCreative commented on content/applications/finance/expenses.rst
> +Order)` is **only** updated *after the journal entries are posted*, and the expenses now appear on
mistmatch between singular and plural in this section
```suggestion
Order)` is **only** updated *after the journal entries are posted*, and the expense(s) now appear on
```

2023-06-21 20:06 UTC, larm-odoo commented
All ready for you, @StraubCreative. I changed up a few sections for the singular/plural issue (the "posting journal entries" was a sneaky one, I caught those!)  I also did some general clean up here and there as I saw more items (tense, switched the order of a sentence around, etc). I think it's good to go!

2023-06-21 22:11 UTC, StraubCreative requested changes
Hi @larm-odoo looks good, just one quick tag to look at.

As well, before we merge can you delete unused images in the file's media folder, please?
Example: `create-new-expense.png`

I think after that we can merge. Tag me again when we're ready :)

2023-06-21 22:11 UTC, StraubCreative commented on content/applications/finance/expenses.rst
> +First, in the main *Expenses* app dashboard view (this view can also be accessed from
Yea menuselection could work or we could mimic what we did for 16 and do a gui here.

2023-06-22 16:25 UTC, StraubCreative approved these changes
@fw-bot ignore
@robodoo r+

2023-06-22 18:11 UTC, robodoo commented
@larm-odoo @StraubCreative staging failed: ci/runbot on 391003569013df53bd10ef9757f4ab392edf6057 (view more at https://runbot.odoo.com/runbot/build/46867680)

2023-06-22 18:44 UTC, StraubCreative commented
@robodoo retry

2023-06-22 19:17 UTC, robodoo commented
@larm-odoo @StraubCreative staging failed: ci/runbot on 0d2457a24ac0880de739f28b9a02eac7aaa0e547 (view more at https://runbot.odoo.com/runbot/build/46868684)

2023-06-22 21:01 UTC, StraubCreative commented
@robodoo retry

2023-06-22 21:37 UTC, robodoo commented
@larm-odoo @StraubCreative staging failed: ci/runbot on 21e7e247217a34debe56cbd092e2ee93183e0b95 (view more at https://runbot.odoo.com/runbot/build/46890662)

2023-06-23 06:01 UTC, d-fence commented
@robodoo retry
The non-related failing test in design-theme is now disabled.

2023-06-23 06:58 UTC, closed without merging