[IMP] website: "pages" page
odoo/documentation pull request #4871
Opened 2023-06-23 11:15 UTC by toaa-odoo

Adding a documentation on "pages" within the already existing "page" toctree

task-3383323

2023-06-23 11:16 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4871).

2023-07-28 09:27 UTC, LoredanaLrpz requested changes
Hey, @auva-odoo , great work overall =D
Here's my review 
_Please note that I usually don't check the count of characters when I make suggestions x)_

Also, don't forget to change the commit msg since you co-authored the PR 
--> commit --amend and write
`Co-authored-by: Toaa <toaa@odoo.com>`
`Co-authored-by: Auva <auva@odoo.com>`

2023-07-28 09:27 UTC, LoredanaLrpz commented on content/applications/websites/website/pages.rst
> +   and enable :guilabel:`Redirect Old URL`.
You can seperate at any "space". Here's the only suggestion for which I checked the number of characters x) 
```suggestion
.. note::
   A record is added automatically everytime you :ref:`modify a page's URL
   <website/page_properties>` and enable :guilabel:`Redirect Old URL`.
```

2023-07-28 09:27 UTC, LoredanaLrpz commented on content/applications/websites/website/pages.rst
> +     or :ref:`deleted <website/delete-page>`.
Same as above :)
```suggestion
   - 404, 301 and 302 redirections only work if the original page has been :ref:`unpublished
     <website/un-publish-page>` or :ref:`deleted <website/delete-page>`.
```

2023-07-31 06:39 UTC, auva-odoo commented on content/applications/websites/website/pages.rst
> +#. Once you have updated the links (or set up a :ref:`redirection <website/URL-redirection>`),
You're right! I used your suggestion, but changed it slightly :)

2023-07-31 06:40 UTC, auva-odoo commented on content/applications/websites/website/pages.rst
> +- :guilabel:`URL from`: Enter the URL to be redirected (e.g., `/about-the-company`) or search for
They are only listed when you select the 308 redirection type. We can have a look together :)

2023-08-03 13:41 UTC, xpl-odoo requested changes
Nice job Audrey/Tom! :) Don't hesitate to ask questions regarding my suggestions or challenge them ;)

2023-08-03 13:41 UTC, xpl-odoo commented on content/applications/websites/website/pages.rst
> +   :ref:`redirection <website/URL-redirection>` for the page's URL.
```suggestion
```
Not necessary, given it's already covered by points 2. and 3.

2023-08-03 13:41 UTC, xpl-odoo commented on content/applications/websites/website/pages.rst
> +To access existing URL redirections for your website and create new ones, :doc:`activate the
```suggestion
To access existing URL redirections and create new ones, :doc:`activate the
```

2023-08-03 13:41 UTC, xpl-odoo commented on content/applications/websites/website/pages.rst
> +   A record is added automatically everytime you :ref:`modify a page's URL
```suggestion
   A record is added automatically every time you :ref:`modify a page's URL
```

2023-08-03 13:41 UTC, xpl-odoo commented on content/applications/websites/website/pages.rst
> +URL redirects
Does this apply to all page types (forum, blog, etc?)
If so, consider moving that part of the documentation to another page or specify this.

2023-08-03 13:41 UTC, xpl-odoo commented on content/applications/websites/website/pages.rst
> +- :guilabel:`Sequence`: to define the order in which redirections are performed, e.g. in the case of
```suggestion
- :guilabel:`Sequence`: to define the order in which redirections are performed, e.g., in the case of
```

2023-08-03 13:41 UTC, xpl-odoo commented on content/applications/websites/website/pages.rst
> +   - `Redirects and Google Search <https://developers.google.com/search/docs/crawling-indexing/301-redirects>`_
```suggestion
   - `Google documentation on redirects and search <https://developers.google.com/search/docs/crawling-indexing/301-redirects>`_
```

2023-08-07 07:00 UTC, xpl-odoo approved these changes
@robodoo delegate+

2023-08-07 07:21 UTC, auva-odoo commented
@robodoo r+

2023-08-07 07:21 UTC, robodoo commented
I'm sorry, @auva-odoo. I'm afraid I can't do that.

2023-08-07 07:45 UTC, xpl-odoo commented
@robodoo r+

2023-08-07 08:43 UTC, closed without merging