[IMP] accounting: AU rebrands Keypay to Employment Hero
odoo/documentation pull request #4876
Opened 2023-06-26 06:58 UTC by tong-odoo

Impacted Versions:

- 16.0 or above

task-3250954

2023-06-26 06:59 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/4876).

2023-06-27 09:08 UTC, toaa-odoo approved these changes

2023-06-27 09:09 UTC, toaa-odoo commented
> Impacted Versions:
> 
> * 16.0 or above
> 
> [task-3250954](https://www.odoo.com/web#view_type=form&model=project.task&id=3250954)

All good to me, and I guess you meant 16.0 *and* above ;)

2023-06-27 09:59 UTC, jcs-odoo requested changes
Hi @tong-odoo and @toaa-odoo 

Content-wise, I think the text needs to be adapted as well since we have to retrieve the codes from the employmenthero portal, and not from keypay anymore. Since it's still named keypay in Odoo's UI, we could also add an explication note for the readers, to avoid confusion.

Also, the images haven't been compressed with pngquant yet.

Thanks :)

2023-07-03 12:32 UTC, jcs-odoo approved these changes
@robodoo r+

2023-07-03 13:26 UTC, closed without merging