[IMP] Inventory: updated images and removed edit and save directions
odoo/documentation pull request #4879
Opened 2023-06-26 14:33 UTC by larm-odoo

Updated images to 16, removed mentions of saving and editing buttons when not needed.

2023-06-26 22:43 UTC, meng-odoo approved these changes
Hi @larm-odoo! It looks like this doc as a whole was updated recently, and you've just made small changes for v16 in this PR, correct? Your recent changes look good to me.

My only note would be that a couple of the longer images (replenishment-report-dashboard.png & rfq-source-document.png) come out pretty blurry. You may want to consider showing a smaller portion of the page, or adjusting the window size to make the page shorter width-wise? But I'll approve and let you/Sam decide what's best here :)

2023-06-27 13:12 UTC, larm-odoo commented
Thanks @meng-odoo - you are correct, I just did the 14.0 version, so 15 an 16 just had a coupe sentences removed/updated and the images updated (you'll see there's another one for 15.0 in Github). I keep having issues with my big/text heavy/wide images, so I will defer to @samueljlieber for his thoughts on that. Thanks for the review!

2023-06-27 15:29 UTC, samueljlieber requested changes
Hi @larm-odoo 👋 these changes look great except for two images that are too blurry. I left some suggestions for retaking them as well as example images of what I was able to capture with some tweaking. Once these images are fixed tag me again for another look and let me know if you have any questions 🙂 thank you!

2023-06-27 15:29 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/products/strategies/replenishment-report-dashboard.png
This images is too hard to read with the text size and compression. It could be retaken as such to remove the page title and sidebar, as well as zooming in the page a bit, and squishing some columns. Here is a retaken & compressed image:

![Screenshot 2023-06-27 at 11 02 46 AM](https://github.com/odoo/documentation/assets/36018073/f318cffc-5a13-4bba-9956-d478f5c15422)

2023-06-27 15:29 UTC, samueljlieber commented on content/applications/inventory_and_mrp/inventory/management/products/strategies/rfq-source-document.png
This image is also difficult to see. It can be retaken to be more legible by zooming in, hiding some columns, and resizing the window. Here is a retaken and compressed image:

![Screenshot 2023-06-27 at 11 20 33 AM 2](https://github.com/odoo/documentation/assets/36018073/de44bd3f-779f-4f17-9d48-b647771bb9c7)

2023-06-29 14:45 UTC, larm-odoo commented
Thanks @samueljlieber ! I redid the pics- they look clearer now, hopefully it's clear enough.

2023-06-30 19:26 UTC, samueljlieber approved these changes
Hi @larm-odoo thank you for retaking the images, they are definitely better 🙂

Passing to @StraubCreative for final review– this should be a quick one!

2023-06-30 19:31 UTC, StraubCreative approved these changes
@robodoo r+

2023-06-30 20:39 UTC, closed without merging