[ADD] Thailand localisation Documentation
odoo/documentation pull request #5483
Opened 2023-08-14 09:00 UTC by tap-odoo

Added Thailand localisation documentation as it not exist before. Features were pushed to Odoo 16 already

2023-08-14 09:01 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5483).

2023-08-16 02:32 UTC, tong-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +     :align: center
```suggestion
.. image:: thailand/thailand-pnd3-pnd53.png
   :align: center
```

2023-08-16 02:32 UTC, tong-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +     :align: center
```suggestion
.. image:: thailand/thailand-tax-invoice.png
   :align: center
```

2023-08-16 02:32 UTC, tong-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +     :align: center
```suggestion
.. image:: thailand/thailand-tax-report.png
   :align: center
```

2023-08-16 02:32 UTC, tong-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +     :align: center
```suggestion
if the contact is identified as a branch.

.. image:: thailand/thailand-contact.png
   :align: center
```

2023-08-21 02:37 UTC, vin-odoo commented
@odoo/localizations-doc-review Hi team :pray: Could you please review this PR?
It would be perfect if it could be merged and available before September so that it can be shared during a webinar.

Sorry for the team ping and thank you in advance :pray:

2023-08-22 11:51 UTC, toaa-odoo requested changes
Hi, thank you for your great work!

Since you created it on your own repository, I couldn't push my commit on it. Instead, you can copy/paste this into your branch (which is my changes and recommendations in RST). Note there is also an (already compressed) new image to add in the configuration section:

========
Thailand
========

Configuration
=============

:ref:`Install <general/install>` the :guilabel:`🇹🇭 Thailand` localization package to get all the
features of the Thai localization:

.. list-table::
   :header-rows: 1

   * - Name
     - Technical name
     - Description
   * - :guilabel:`Thailand - Accounting`
     - `l10n_th`
     - Default :ref:`fiscal localization package <fiscal_localizations/packages>`
   * - :guilabel:`Thailand - Accounting Reports`
     - `l10n_th_reports`
     - Country-specific accounting reports

.. image:: thailand/thailand-modules.png
   :alt: Thailand localization modules

Chart of accounts and taxes
===========================

Odoo’s fiscal localization package for Thailand includes the following taxes:

- VAT 7%
- VAT-exempted
- Withholding tax
- Withholding income tax

Tax report
==========

Odoo allows users to generate Excel files to submit their VAT to the **Revenue Department** of
Thailand.

Sales and purchase tax report
-----------------------------

To generate a sales and purchase tax report, go to :menuselection:`Accounting --> Reporting --> Tax
Report`. Select a specific time or time range on the tax report, and click
:guilabel:`VAT-202-01 (xlsx)` for purchase tax, and :guilabel:`VAT-202-02 (xlsx)` for sales tax.

.. image:: thailand/thailand-tax-report.png
   :alt: Thai purchase and sales taxes reports

Withholding PND tax report
--------------------------

PND report data displays the summarized amounts of the applicable **withholding corporate income
tax returns (domestic)** from vendor bills under the :guilabel:`PND53 (TH)` and
:guilabel:`PND3 (TH)` tax reports, and is installed by default with the Thai localization.

.. image:: thailand/thailand-pnd-report.png
   :alt: PND tax reports

.. note::
   Withholding corporate income tax returns (domestic) is the tax used in case the company has
   withheld the tax from “**Personal (PND3)**” or “**Corporate (PND53)**” services provided such as
   rental, hiring, transportation, insurance, management fee, consulting, and etc.

The PND Tax report allows users to generate a CSV file for bills to upload on the
`RDprep for Thailand e-Filling application <https://efiling.rd.go.th/rd-cms/>`_.

To generate a PND CSV file, go to :menuselection:`Accounting --> Reporting --> Tax Report`, select a
specific time or time range on the tax report, and click :guilabel:`PND3` or :guilabel:`PND53`.

This generates the :file:`Tax Report PND3.csv` and :file:`Tax Report PND53.csv` file that lists all
the vendor bill lines with the applicable withholding tax.

.. image:: thailand/thailand-pnd3-pnd53.png
   :alt: PND3 and PND53 CSV files

.. warning::
   Odoo cannot generate the PND or PDF report or **withholding tax certificate** directly. The
   generated :file:`Tax Report PND3.csv` and :file:`Tax Report PND53.csv` files must be exported
   to an external tool to convert it into a **withholding PND** report or **PDF** format.

Tax invoice
===========

The **tax invoice PDF** report can be generated from Odoo through the **Invoicing** module. Users
have the  option to print PDF reports for normal invoices and tax invoices. To print out
**tax invoices**, users can click on :guilabel:`Print Invoices` in Odoo. Regular invoices can be
printed as **commercial invoice** by clicking on :menuselection:`⚙️ (Cog) --> Print --> Commercial
Invoice`.

.. image:: thailand/thailand-tax-invoice.png
   :alt: Commercial invoice printing

Headquarter/Branch number settings
-----------------------------------

You can inform the **Headquarters** and **Branch number** of a company in the **Contacts** app. Once
in the app, open the **contact form** of the company and under the :guilabel:`Sales & Purchase` tab:

- If the contact is identified as a branch, input the **Branch number** in the
  :guilabel:`Company ID` field.
- If the contact is a **Headquarters**, leave the :guilabel:`Company ID` field **blank**.

.. image:: thailand/thailand-contact.png
   :alt: Company Headquarter/Branch number

.. tip::
   This information is used in the **tax invoice** PDF report and PND **tax report** export.

![thailand-modules](https://github.com/odoo/documentation/assets/104567387/74277818-f565-4887-b389-a0b671772d76)

2023-08-23 09:32 UTC, tong-odoo commented
@toaa-odoo Since this PR is quite urgent therefore I will help updating the PR. May I ask if we could finish the update within this week. Is it possible to deploy this to production before 7 Sep?

2023-08-23 11:13 UTC, toaa-odoo commented
> @toaa-odoo Since this PR is quite urgent therefore I will help updating the PR. May I ask if we could finish the update within this week. Is it possible to deploy this to production before 7 Sep?

Passed on the message to somebody with R+ rights

2023-08-23 12:12 UTC, xpl-odoo reviewed
Very minor spelling suggestions. I haven't tested the described flow, though.

2023-08-23 12:12 UTC, xpl-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +This generates the :file:`Tax Report PND3.csv` and :file:`Tax Report PND53.csv` file that lists all
```suggestion
This generates the :file:`Tax Report PND3.csv` and :file:`Tax Report PND53.csv` files that list all
```

2023-08-23 12:12 UTC, xpl-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +The PND Tax report allows users to generate a CSV file for bills to upload on the
```suggestion
The PND tax report allows users to generate a CSV file for bills to upload on the
```

2023-08-23 12:12 UTC, xpl-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +   to an external tool to convert it into a **withholding PND** report or **PDF** format.
```suggestion
   to an external tool to convert them into a **withholding PND** report or a **PDF** file.
```

2023-08-23 12:12 UTC, xpl-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +printed as **commercial invoice** by clicking on :menuselection:`⚙️ (Cog) --> Print --> Commercial
```suggestion
printed as **commercial invoices** by clicking on :menuselection:`Cog button (⚙️) --> Print --> Commercial
```

2023-08-23 12:12 UTC, xpl-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +You can inform the **Headquarters** and **Branch number** of a company in the **Contacts** app. Once
```suggestion
You can inform a company's **Headquarters** and **Branch number** in the **Contacts** app. Once
```

2023-08-23 17:32 UTC, tong-odoo commented
> Very minor spelling suggestions. I haven't tested the described flow, though.

@xpl-odoo Thanks for the review! I updated the spelling mistake. Please feel free to let me know once you tested the described flow. Thanks again!

2023-08-23 19:21 UTC, xpl-odoo commented
> > Very minor spelling suggestions. I haven't tested the described flow, though.
> 
> @xpl-odoo Thanks for the review! I updated the spelling mistake. Please feel free to let me know once you tested the described flow. Thanks again! 

@toaa-odoo did you test the flow? If yes, the PR should be ready to be merged. If not, could you? :)

2023-08-24 08:13 UTC, toaa-odoo commented
> > > Very minor spelling suggestions. I haven't tested the described flow, though.
> > 
> > 
> > @xpl-odoo Thanks for the review! I updated the spelling mistake. Please feel free to let me know once you tested the described flow. Thanks again!
> 
> @toaa-odoo did you test the flow? If yes, the PR should be ready to be merged. If not, could you? :)

It was, you can r+ it

2023-08-24 11:37 UTC, xpl-odoo commented
@robodoo r+

2023-08-24 16:43 UTC, closed without merging