[IMP] Discuss Team Communication edits
odoo/documentation pull request #5497
Opened 2023-08-15 19:50 UTC by tiku-odoo

Changes to complete documentation requests: 

[Discuss] team communication
https://www.odoo.com/web#id=3464452&menu_id=4720&cids=3&action=333&active_id=3835&model=project.task&view_type=form

[Discuss] team communication
https://www.odoo.com/web#id=3425894&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2023-08-15 20:02 UTC, tiku-odoo commented
@StraubCreative 

This doc update for Discuss Team Communication is ready for your fast-track review. Thanks. 

:+1: 

Tim

2023-08-15 20:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5497).

2023-08-21 20:10 UTC, StraubCreative requested changes
Bunch of things here that need changes before we merge...
Pausing my review here, and will push up all of the changes shortly so we can get this merged in. Please take note on some of the comments below, especially around formatting, thanks.

2023-08-25 01:43 UTC, StraubCreative approved these changes
@robodoo r+

2023-08-25 02:50 UTC, closed without merging