[IMP] Mercado Pago: documentation and images update
odoo/documentation pull request #5525
Opened 2023-08-17 20:52 UTC by masi-odoo

This commit will add important clarifications to use and test the Mercado Pago payment provider and add visual documentation similar to other provider's documentation

2023-08-17 20:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5525).

2023-09-01 21:34 UTC, masi-odoo commented
Hello @samueljlieber thanks for that! Linking Google Drive folder with images: 

https://drive.google.com/drive/folders/1CuOVMkXwREj_H5yuKdJ1oPksQWoDJ6Nk?usp=sharing

2023-11-08 17:31 UTC, samueljlieber commented
Hi @masi-odoo I've implemented your images and updated the formatting for your changes in https://github.com/odoo/documentation/commit/1d92f29c1e20564cff28216af3553a0bffbb2866.

2023-11-13 11:25 UTC, AntoineVDV requested changes
Hello, I left some review comments below :)

2023-11-13 11:25 UTC, AntoineVDV commented on content/applications/finance/payment_providers/mercado_pago.rst
> +   an error message.
I was not aware of this but it's not normal. Please create a support ticket so we can fix it instead :)

2024-01-03 14:54 UTC, samueljlieber commented
Thank you for your review @AntoineVDV! I implemented your changes in https://github.com/odoo/documentation/commit/c00e36cbe06dbd290c146ececbc4d4bd5e3598bd and https://github.com/odoo/documentation/commit/b8dff5505f0ba63d08f3e2df567225a8881f96d0. I also added a seealso link to the latest [Mercado Pago Odoo webinar](https://www.youtube.com/watch?v=CX8vPHMb1ic) for @masi-odoo.

2024-01-09 07:57 UTC, auva-odoo requested changes
Hey @masi-odoo thank you for you work! I just added 2 suggestions, let me know if you have any questions!

2024-01-09 07:57 UTC, auva-odoo commented on content/applications/finance/payment_providers/mercado_pago.rst
> +   :align: center
We are moving away from center-aligned images so you can remove this.

2024-01-09 07:57 UTC, auva-odoo commented on content/applications/finance/payment_providers/mercado_pago.rst
> +   `Mercado Pago Odoo webinar <https://www.youtube.com/watch?v=CX8vPHMb1ic>`_
I would move this at the end of the page and merge it with the other seealso (and have 2 bullet points in there).

2024-01-09 08:15 UTC, AntoineVDV approved these changes

2024-01-09 14:51 UTC, auva-odoo approved these changes
Thanks @samueljlieber ! :)

@robodoo r+

2024-01-09 16:11 UTC, closed without merging