[IMP] website: Google Analytics
odoo/documentation pull request #5594
Opened 2023-08-24 07:23 UTC by auva-odoo

task-2790245

2023-08-24 07:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5594).

2023-08-28 14:15 UTC, LoredanaLrpz requested changes
Hey @auva-odoo , great work! Unfortunately, I didn't have a lot to say :/ buuuuut I managed to leave two comments <3 
Have a great day!! =D

2023-08-28 14:15 UTC, LoredanaLrpz commented on content/applications/websites/website/reporting/google_analytics.rst
> +   **Website settings**, make sure to select the website in the :guilabel:`Settings of Website`
The "Settings of Website" field isn't available yet in 15.0, it's only for versions 16.0 and above
![image](https://github.com/odoo/documentation/assets/95279628/71f131e6-a983-4f85-9d1f-b37d4e0bb3d7)

2023-08-28 14:15 UTC, LoredanaLrpz commented on content/applications/websites/website/reporting/google_analytics.rst
>  <https://support.google.com/analytics/answer/1008015?hl=en/>`_.
I think this link could be in the :seealso: since it's an additional link but not a step

2023-08-29 07:35 UTC, LoredanaLrpz approved these changes

2023-08-31 09:36 UTC, xpl-odoo requested changes
Hi @auva-odoo
Good job on the PR!
I did an in-depth review, trying to explain my thought process in detail. I feel it's useful as you are still relatively new. But don't worry, I'm not always that nitpicky😄

2023-08-31 10:58 UTC, auva-odoo commented on content/applications/websites/website/reporting/google_analytics.rst
> +   **Website settings**, make sure to select the website in the :guilabel:`Website` field before
I don't think so, I think I prefer without in this case :)

2023-08-31 10:58 UTC, auva-odoo commented on content/applications/websites/website/reporting/google_analytics.rst
> +   **Website settings**, make sure to select the website in the :guilabel:`Website` field before
I don't think so, I think I prefer without in this case :)

2023-09-01 12:17 UTC, xpl-odoo commented
@robodoo delegate+

2023-09-01 12:56 UTC, auva-odoo commented
@robodoo r+

2023-09-01 14:51 UTC, closed without merging