[IMP] howtos/translations: text & tips
odoo/documentation pull request #5653
Opened 2023-08-25 17:22 UTC by odoostan

Remove parenthesis around a term that's fairly straightforward to understand and later used as a title
Add a much-needed point (comma would be fine as well)
Correct an improper plural form

2023-08-25 17:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5653).

2023-08-25 17:26 UTC, odoostan commented
I would like to have methods `get_field_string` and `get_field_help` mentioned somewhere in the docs, what are your thoughts on using this page ?

2023-08-28 11:21 UTC, odoostan commented
I don't see it anywhere that it's possible to translate hardcoded strings from the code. I think it would be a great addition to this page as well.
@brinkflew 
![image](https://github.com/odoo/documentation/assets/92587669/8074de2b-92cc-4028-8760-30a86595eba9)

2023-09-04 12:21 UTC, AntoineVDV requested changes

2023-09-04 12:21 UTC, AntoineVDV commented on content/developer/howtos/translations.rst
> +      msg = _("You have %(count) invoices", count=invoice_count)
The format for labeled placeholders is `%(placeholder)s`. This change is not correct.

2023-10-05 11:32 UTC, odoostan commented
@AntoineVDV sorry for the wait, I forgot about this PR.
Adapted following your suggestion and corrections.
I would like to see some of the stuff I mentioned (and much more) in the docs, right now there's no docs at all on the "ir.translation" model.
However it seems that's very common, only [two standard modules](https://www.odoo.com/documentation/16.0/developer/reference/standard_modules.html) have their documentation in the reference.
Any plans to expand on that ?

2023-10-13 16:47 UTC, AntoineVDV approved these changes
@robodoo r+

2023-10-13 16:51 UTC, AntoineVDV commented
>I would like to see some of the stuff I mentioned (and much more) in the docs, right now there's no docs at all on the "ir.translation" model.
However it seems that's very common, only [two standard modules](https://www.odoo.com/documentation/16.0/developer/reference/standard_modules.html) have their documentation in the reference.
Any plans to expand on that ?

The developer documentation is a collaborative effort and only a few teams and developers invest time in maintaining that doc, so the best way to see something being added to the documentation is to create the PR ;)

2023-10-13 17:57 UTC, closed without merging