[IMP] Website: Unsplash documentation updated
odoo/documentation pull request #5823
Opened 2023-09-12 13:38 UTC by Donapi

[taskid: 3498880](https://www.odoo.com/web#id=3498880&cids=1&model=project.task&view_type=form)

2023-09-13 10:16 UTC, auva-odoo requested changes
@Donapi Thank you for your work! Since I will be gone when you see this and we therefore won't be able to discuss this IRL until I get back, I wrote down my general thoughts so you're not completely stuck while I'm gone. I also *tried* to explain my suggestions for the same reason (these might be "to-the-point" because I'm a bit short on time before my holiday). I hope this all makes sense to you :-) 

1) I think there are some issues with your images:
- It seems you deleted the "unsplash" folder (with your images) in /home/odoo/documentation/content/applications/websites/website/configuration, which I think is the reason why the PR failed the ci/documentation check.
- After discussing this with jcs when I took over the website documentation, we decided that images would not be centered throughout the website doc and instead aligned on the left (you can just remove  `:align: center` for all images; images are aligned on the left by default)
- I think you forgot to add the alt text for your images ( :alt: )

2) I would remove all of the subtitles and instead have one big list (a numbered list) of steps (I also think we could group some of those steps together so we don't have as many - see my suggestions) like we did for the Website analytics page (Plausible and Google Analytics) https://www.odoo.com/documentation/16.0/applications/websites/website/reporting/analytics.html 
I feel like all of the steps actually go together, especially in the first two sections; in the second section, you re-explain how to access the applications details page, when we were exactly there at the previous step, in the previous section. Removing the sub-titles would allow you to remove the confusion and unnecessary steps, IMO.

2023-09-18 08:49 UTC, Donapi commented on content/applications/websites/website/configuration/unsplash.rst
> +  browser's URL.
yes, it is, not sure why you can't see the screenshot...

2023-10-03 10:28 UTC, auva-odoo requested changes
Hey @Donapi you did a great job there :) I know it seems like I still have a lot of comments but really it's just a few minor changes (commas, image alignment) and 1 suggestion :) let me know if you want to talk about it :)

2023-10-03 10:28 UTC, auva-odoo commented on content/applications/websites/website/configuration/unsplash.rst
> +   add a :guilabel:`Description`, and click :guilabel:`Create application`.
```suggestion
   prefix `Odoo:` (e.g., `Odoo: connection`), so Unsplash recognizes it as an Odoo instance. Then,
   add a :guilabel:`Description` and click :guilabel:`Create application`.
```

2023-10-03 10:28 UTC, auva-odoo commented on content/applications/websites/website/configuration/unsplash.rst
> +   and click on the application you just created.
```suggestion
#. To **generate an Unsplash application ID**, go to your `applications dashboard <https://unsplash.com/oauth/applications>`_
   and click on the application you just created.
```

2023-10-03 11:10 UTC, Donapi commented on content/applications/websites/website/configuration/unsplash.rst
> +   enter your :guilabel:`Access Key` and :guilabel:`Application ID`.
I think it was ok as it was but I updated it...

2023-10-03 11:57 UTC, auva-odoo approved these changes

2023-12-05 12:51 UTC, xpl-odoo commented
@robodoo r+

2023-12-05 16:32 UTC, closed without merging