[IMP] sales: updated import products doc for 16
odoo/documentation pull request #5861
Opened 2023-09-14 20:06 UTC by ksc-odoo

Updated the current sales doc - for import doc - to adhere to recent RST formatting guidelines that we're decided upon in most recent Writer's Workshop meeting - and to adjust the workflow for accuracy reasons - aimed at 16.0, but can be back-ported to 15 (and minor adjustments and image updates will be made in the future to comply with those versions, but the RST formatting and workflow will, essentially, be the same - and are a major upgrade from the current doc)

PROJECT TASK: https://www.odoo.com/web#id=3496197&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2023-09-14 20:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5861).

2023-11-16 21:05 UTC, jero-odoo requested changes
@ksc-odoo Great work! Just a few comments, let me know if you have any questions! 👍

2023-11-16 21:05 UTC, jero-odoo commented on content/applications/sales/sales/products_prices/products/import.rst
> +imported and uploaded, that new information can be found on that product's product page.
```suggestion
imported and uploaded, that new information can be found on the :guilabel:`Products` page.
```
I understand you are trying to refer to an individual product record (page) here, so I do not know if this is the best wording, but I don't think "product's product page" works. Maybe just "Product record"?

2023-11-16 21:05 UTC, jero-odoo commented on content/applications/sales/sales/products_prices/products/import.rst
> +To import attributes and values, a separate Excel or CSV file dedicated to attributes and values
```suggestion
To import attributes and values, a separate spreadsheet or CSV file dedicated to attributes and values
```

2023-11-16 21:05 UTC, jero-odoo commented on content/applications/sales/sales/products_prices/products/import.rst
> +product attributes and variants can be found and modified, if necessary.
```suggestion
To view and modify the attributes and variants on any products, select the desired product from the
:guilabel:`Products` page, and click the :guilabel:`Attributes & Variants` tab.
```

2023-11-20 20:34 UTC, ksc-odoo commented
Thanks for all your helpful comments/feedback, @jero-odoo -- made all the suggested edits, and once you give this your approval, I'll then tag the materials team, so they can conduct a 2nd round of peer review for this PR... 👍

2023-11-20 21:14 UTC, jero-odoo approved these changes

2023-11-20 21:14 UTC, jero-odoo commented
Hey @ksc-odoo this looks good to me 👍

2023-11-21 17:21 UTC, ksc-odoo commented
Thanks, @jero-odoo ! Alrighty, Materials Team -- This one is ready for a 2nd Round of Peer Review (@hojo-odoo @Felicious @brse-odoo ) 👍

2023-11-29 15:04 UTC, brse-odoo reviewed
@ksc-odoo Just finished reviewing this PR. Great job! Once again, I didn't have many suggestions outside of grammatical suggestions and the potential for additional information, for you to accept/reject as you see fit.

Feel free to ping me with any questions, thanks!

2023-11-29 16:24 UTC, brse-odoo approved these changes

2023-11-29 21:11 UTC, ksc-odoo commented
Thanks for the helpful feedback @brse-odoo - made all the suggested edits! So now this one is ready for Final Review @odoo/us-doc-review 👍

2023-12-08 15:54 UTC, samueljlieber commented
Hi @StraubCreative this PR is good to go 👍

### FWP up to master

2023-12-21 17:50 UTC, StraubCreative approved these changes
@robodoo r+

2023-12-21 22:26 UTC, closed without merging