[IMP] accounting: update thailand localisations for PromptPay
odoo/documentation pull request #5862
Opened 2023-09-15 09:37 UTC by tong-odoo

Impacted Version:

- 17.0 and above

This commit improve below features:

- PromptPay QR code documentation

task-3506522

2023-09-15 09:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5862).

2023-09-15 13:53 UTC, chiaraprattico requested changes

2023-09-19 02:40 UTC, tong-odoo commented
@chiaraprattico Thanks for the review. I have fixed the comments above. Please take a look! :smile:

2023-09-20 06:46 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/thailand.rst
> +`Proxy Value` field depending on the chosen type.
the guilabel Proxy Value is not working

2023-09-20 06:48 UTC, chiaraprattico reviewed
Hi @tong-odoo just one guilabel is not working, but I'm sending it over already to my colleague for finalizing and pushing it.

2023-09-20 07:45 UTC, tong-odoo commented
@chiaraprattico Thanks for checking! I have fixed the guilabel as well. Please take a look :smile:

2023-09-20 09:47 UTC, jcs-odoo requested changes
Hello @tong-odoo 

Can you update the file names? See my suggestions below. I'll merge this afterward :)

Thanks!

2023-09-20 09:47 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +.. image:: thailand/thailand-promptpay-bank-setting.png
No need for the prefix "thailand" in the filename, as it is already in the path with the name of the folder. Rather, I suggest a prefix about the topic
```suggestion
.. image:: thailand/qr-promptpay-bank.png
```

2023-09-20 09:47 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +.. image:: thailand/thailand-bank-account-journal-setting.png
For example here, this name could apply to other topics than the QR code section.
```suggestion
.. image:: thailand/qr-bank-journal.png
```

2023-09-20 09:47 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +.. image:: thailand/thailand-qr-code-invoice-setting.png
```suggestion
.. image:: thailand/qr-code-invoice-emv.png
```

2023-09-20 09:47 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/thailand.rst
> +the **invoice amount** and one of the following **merchant information**:
```suggestion
The **PromptPay QR code** is a QR code that can be added to invoices to allow customers to pay their
bills using the PromptPay-supported bank mobile application. The QR code is generated based on the
**invoice amount** and one of the following **merchant information**:
```

2023-09-22 03:20 UTC, tong-odoo commented
@jcs-odoo Thanks for the review! I have updated the file names and your suggestions. Please take a look. :smile:

2023-09-22 06:46 UTC, jcs-odoo approved these changes
Thanks @tong-odoo 

Usually, it's best not to mix different types of changes if they can be applied to older versions as well (here --> changing existing filenames)
Otherwise, it becomes harder to maintain the doc across different versions.

But no worries, I created another PR to backport these changes to older versions of the doc :)
https://github.com/odoo/documentation/pull/5891

Thank you for your work!

@robodoo r+

2023-09-22 06:48 UTC, tong-odoo commented
> Thanks @tong-odoo
> 
> Usually, it's best not to mix different types of changes if they can be applied to older versions as well (here --> changing existing filenames) Otherwise, it becomes harder to maintain the doc across different versions.
> 
> But no worries, I created another PR to backport these changes to older versions of the doc :) #5891
> 
> Thank you for your work!
> 
> @robodoo r+

Sure thank you!

2023-09-22 10:24 UTC, closed without merging