[REM] paypal: remove IPN
odoo/documentation pull request #5875
Opened 2023-09-19 11:40 UTC by anko-odoo

Removing IPN mentions from documentation.

2023-09-19 11:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5875).

2023-10-03 13:45 UTC, jcs-odoo requested changes
Thanks for the update @anko-odoo :)
It's not required, but to help us double-check the content, it's good practice to explain the change (e.g., with a dev task, or the related community/enterprise PR)

Cheers!

2023-10-03 15:20 UTC, anko-odoo commented on content/applications/finance/payment_providers/paypal.rst
> +   :ref:`PDT <paypal/pdt>` **must** be enabled.
Yes, you str right, good catch.

2023-10-04 11:00 UTC, jcs-odoo commented
I just checked with @anko-odoo and the PR also needs to target saas-16.2 cc @toaa-odoo and @xpl-odoo ^^

2023-10-04 11:08 UTC, jcs-odoo approved these changes
@robodoo r+

2023-10-04 13:07 UTC, closed without merging