[ADD] Quality: Pass - Fail quality checks
odoo/documentation pull request #5884
Opened 2023-09-19 20:11 UTC by hojo-odoo

This PR adds a new doc detailing how to create and process Pass - Fail quality checks.

NOTE: One of the checks is failing because the PR contains a reference to the "Quality checks" doc, which is not yet live. That doc should be live before this one, at which point the ref tags in this doc will work as intended.

2023-09-19 20:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5884).

2023-11-14 00:16 UTC, StraubCreative commented
@odoo/us-doc-review 
Need #6454 to merge first, which includes the necessary toctree updates for the CI checks to pass

2023-11-17 01:27 UTC, Felicious approved these changes
This is a really really solid doc, @hojo-odoo :smile: 

It's concise and really easy to follow. I just had some minor typos I found and a VS Code tip I wanted to share. I think it'll be helpful for you while working on a lot of duplicate content :blush: 

Go ahead and pass this to the next reviewer after fixing the typos!

2023-11-17 01:27 UTC, Felicious commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +Once created, there are multiple ways that *Measure* quality checks can be processed. If a quality
```suggestion
Once created, there are multiple ways that *Pass - Fail* quality checks can be processed. If a quality
```

2023-11-17 01:27 UTC, Felicious commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +To process a *Measure* quality check from the check's page, begin by navigating to
```suggestion
To process a *Pass - Fail* quality check from the check's page, begin by navigating to
```

2023-11-17 01:27 UTC, Felicious commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +To process a *Measure* quality check from the check's page, begin by navigating to
John, I want to show you a neat lil trick in VS Code for finding and replacing instances of a word.

1. Click CTRL + F to open the word finder at the top right of your screen
![image](https://github.com/odoo/documentation/assets/23611711/056d5de0-c634-4b8f-966e-ed2bdfbe7a92)
2. Enter the word you'd like to find, i.e. "Measure" and it'll show u 
![image](https://github.com/odoo/documentation/assets/23611711/d1cc5af5-c543-4fad-881d-211ef294a73a)
3. You can manually modify it, but to automate it, click the little downwards arrow in the word finder window, and type the word you'd like to replace "Measure" with
![image](https://github.com/odoo/documentation/assets/23611711/305bfb39-5cb0-407f-90be-38a9122589f5)
4. Then, in the replace text field, type "Pass - Fail" right now, and click enter to replace the first instance of Measure, highlighted in bright colors
![image](https://github.com/odoo/documentation/assets/23611711/ca18a2fe-636e-445a-bc10-6c6ce0a4e067)

2023-11-17 01:27 UTC, Felicious commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +view, and selecting :guilabel:`Quality Alert` from the :guilabel:`Menu` pop-up window. A
```suggestion
If a quality alert must be created, do so by clicking the :guilabel:`☰ (hamburger)` button in the
tablet view, and selecting :guilabel:`Quality Alert` from the :guilabel:`Menu` pop-up window. A
```

2023-11-17 01:27 UTC, Felicious commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +   :alt: A Pass - Fail check for a manufacturing work order.
Yay! I appreciate that you applied my suggestion for a previous PR in this one too :smile:

2023-11-17 22:40 UTC, ksc-odoo approved these changes
@hojo-odoo great work on this doc! once you give these suggested edits a look, and implement the necessary adjustments, I think this one will be ready for the next stage. nicely done 👍

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +check.
```suggestion
field that allows the creator to specify a certain criteria that a product must meet in order to
pass the check.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +predetermined interval.
```suggestion
There are two distinct ways that *Pass - Fail* quality checks can be created.

A single check can be manually created, or a |QCP| can be configured that automatically creates
checks at a predetermined interval.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +<quality/quality_management/quality-control-points>`.
```suggestion
This documentation only details the configuration options that are unique to *Pass - Fail* quality
checks and |QCPs|.

For a full overview of all the configuration options available when creating a single check or a
|QCP|, see the documentation on :ref:`quality checks <quality/quality_management/quality-checks>`
and :ref:`quality control points <quality/quality_management/quality-control-points>`.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +  how to complete the quality check and the criteria that must be met for the check to pass.
```suggestion
  how to complete the quality check, along with the criteria that must be met for the check to pass.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +  check and the criteria that must be met for the check to pass.
```suggestion
  check, along with the criteria that must be met for the check to pass.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +selecting an order.
```suggestion
order (receipt, delivery, return, etc.), for which a check is required.

Manufacturing orders can be selected by navigating to :menuselection:`Manufacturing --> Operations
--> Manufacturing Orders`, and clicking on an order.

Inventory orders can be selected by navigating to :menuselection:`Inventory`, clicking the
:guilabel:`# To Process` button on an operation card, and selecting an order.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +<quality/quality_management/quality-alerts>`.
```suggestion
Alert` opens a quality alert form on a new page.

For a complete guide on how to fill out quality alert forms, view the documentation on :ref:`quality
alerts <quality/quality_management/quality-alerts>`.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +manufacturing order as a whole.
```suggestion
manufacturing order, as a whole.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +tab, and then clicking the :guilabel:`📱 (tablet)` button on the order's line.
```suggestion
*Pass - Fail* quality checks configured for work orders **must** be processed from the tablet view.

To do so, begin by navigating to :menuselection:`Manufacturing --> Operations --> Manufacturing
Orders`. Then, select a manufacturing order that includes a work order for which a quality
check is required.

Open the tablet view for that work order by selecting the :guilabel:`Work Orders` tab, and clicking
the :guilabel:`📱 (tablet)` button on the order's line.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +the top-right of the screen. If the criteria is not met, click the :guilabel:`Fail` button.
```suggestion
With the tablet view open, complete the steps listed on the left side of the screen until the *Pass
- Fail* quality check step is reached. Upon reaching the check, follow the instructions that appear
at the top of the screen.

If the criteria for the check is met, click the :guilabel:`Pass` button at the top-right of the
screen. If the criteria is not met, click the :guilabel:`Fail` button.
```

2023-11-17 22:40 UTC, ksc-odoo commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +alerts <quality/quality_management/quality-alerts>`.
```suggestion
:guilabel:`Quality Alerts` pop-up window appears, from which a quality alert can be created.

For a complete guide on how to fill out quality alert forms, view the documentation on :ref:`quality
alerts <quality/quality_management/quality-alerts>`.
```

2023-11-20 14:50 UTC, samueljlieber requested changes
Hi @hojo-odoo! Nice work on this PR 🙂 I have only one small change after my technical review. I will push up this change after this review to move this PR forward!

Thank you!

2023-11-20 14:50 UTC, samueljlieber commented on content/applications/inventory_and_mrp/quality/quality_check_types/pass_fail_check.rst
> +tab, and then clicking the :guilabel:`📱 (tablet)` button on the order's line.
Early line break
```suggestion
do so, begin by navigating to :menuselection:`Manufacturing --> Operations --> Manufacturing
Orders`. Select a manufacturing order that includes a work order for which a quality check is
required. Open the tablet view for that work order by selecting the :guilabel:`Work Orders` tab, and
then clicking the :guilabel:`📱 (tablet)` button on the order's line.
```

2023-11-20 15:08 UTC, samueljlieber commented
Implemented my change in https://github.com/odoo/documentation/commit/d2a4caa6c60ee9f1cc15a145b58482ba32c2b653. This PR is all set @StraubCreative 👍

2023-11-21 19:06 UTC, StraubCreative commented
@robodoo r+

2023-11-21 20:52 UTC, closed without merging