[IMP] Adding link to App Tour Ecuador
odoo/documentation pull request #5901
Opened 2023-09-22 22:07 UTC by rps-odoo

I'm adding the link for the App Tour for the Ecuatorian localization.

2023-09-22 22:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5901).

2023-09-25 14:40 UTC, samueljlieber requested changes
Hi @rps-odoo! Thank you for tagging me to review this improvement! Your changes look good, and I only have two small corrections:
- need to update the base branch to `16.0`.  Be sure that when you create a PR you are doing so on the correct base branch
![Screenshot 2023-09-25 at 10 41 05 AM](https://github.com/odoo/documentation/assets/36018073/1ff4f389-c3f0-44bb-afe7-c35ddffcbfe6)
![Screenshot 2023-09-25 at 10 41 49 AM](https://github.com/odoo/documentation/assets/36018073/e44315c7-19cd-4e9c-a0de-8253820d7317)
   
- update the commit tag to include the app/module: "[IMP] accounting/l10n_ec: adding link to app tour"

I will make these corrections now and push up my commit and approve my review.

2023-09-25 15:29 UTC, samueljlieber approved these changes
This improvement look good to me :)

2023-09-26 06:30 UTC, chiaraprattico approved these changes

2023-09-26 08:48 UTC, jcs-odoo reviewed
Hi @rps-odoo @samueljlieber and @chiaraprattico 

My issue here isn't that much with this PR's content, but it made me realize:
- The Smart Tutorial link isn't okay: it embeds the language string in the link `https://www.odoo.com/es_ES/slides/smart-tutorial-localizacion-de-ecuador-170`. We should avoid including the language string in links. It wasn't visible here because of the short link.
- Short links are not really necessary here since they don't take space: only the text is visible, not the URL. In this case, it is more transparent for the user to leave the full URL so they can know what they click when they hover over the link. (short links are, in my opinion, mainly useful to shorten longer links that include UTM parameters and that we have to copy-paste in full length (e.g., social media posts)).

I'll update the branch and change the other Latam localization docs as well (to remove the `es_ES` language string)

Cheers,

2023-09-26 08:48 UTC, jcs-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +   - `Smart Tutorial - Localización de Ecuador <https://www.odoo.com/r/TnE>`_
```suggestion
   - `App Tour - Localización de Ecuador <https://www.youtube.com/watch?v=BQOXVSDeeK8>`_
   - `Smart Tutorial - Localización de Ecuador <https://www.odoo.com/slides/smart-tutorial-localizacion-de-ecuador-170>`_
```

2023-09-26 08:56 UTC, jcs-odoo commented
@robodoo r+

2023-09-26 10:16 UTC, closed without merging

2023-09-26 20:41 UTC, rps-odoo commented
Hi @jcs-odoo ,

I used the short link (https://www.odoo.com/r/FWY) because this is a tracked link that helps our team (Localization Experts @and-Odoo) to know how many people clicked on that link. This helps us measure the impact of our work. Can tracked links be included?

2023-09-26 21:42 UTC, jcs-odoo commented
> Hi @jcs-odoo ,
> 
> I used the short link (https://www.odoo.com/r/FWY) because this is a tracked link that helps our team (Localization Experts @and-Odoo) to know how many people clicked on that link. This helps us measure the impact of our work. Can tracked links be included?
> 
> cc @samueljlieber
@rps-odoo 
Oh sorry!! I didn't see it! Sure!
Can you send me that link so I can fix it asap, or make a new pr?

2023-10-02 21:29 UTC, rps-odoo commented
Hi @jcs-odoo ,

Sorry about this, I did not see your reply. The tracked link is the following: https://www.odoo.com/r/FWY. Please let me know if this can be fixed. Thank you!

cc @and-Odoo