[ADD] Pos IoT Six module documentation added
odoo/documentation pull request #5912
Opened 2023-09-25 14:55 UTC by Ysoroko

This PR adds the documentation for a new Pos IoT Six module which will soon replace the old Six module.

Related PRs:
16.0 Enterprise: https://github.com/odoo/enterprise/pull/47086
16.0 Odoo: https://github.com/odoo/odoo/pull/13566
Worldline-lib: https://github.com/odoo/worldline-lib/pull/4

task-3031744

2023-09-25 14:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5912).

2023-10-02 14:55 UTC, jcs-odoo commented
Requesting a review from @odoo/be-doc-review since the team @odoo/pos-doc-review isn't available at the moment.

2023-10-24 09:07 UTC, LoredanaLrpz commented
Hey @Ysoroko , I've pushed the changes, thanks a lot for your work!

2023-10-24 12:21 UTC, dade-odoo requested changes
Hi @LoredanaLrpz and @Ysoroko ! Nice work on this doc. Overall it's really clear and will be super helpful. I made a few specific comments/edits for you. Feel free to discuss any of them if you have any questions :)

One point about the screenshots: I believe @jcs-odoo (feel free to correct me if I'm wrong here) had said that if we're updating/creating a doc from 16.0, we can go ahead and use 16.3 screenshots with the updated design so that the screenshots will have more longevity (provided that the layout isn't significantly different between 16.0 and 16.3).

2023-10-26 13:49 UTC, LoredanaLrpz commented on content/applications/sales/point_of_sale/payment_methods/terminals/six.rst
> +   - By default, the port used is `7784`.
"the port used by the Six terminal"

2023-10-31 11:21 UTC, LoredanaLrpz commented on content/applications/sales/point_of_sale/payment_methods/terminals/six.rst
>  .. image:: six/new-payment-method.png
note from the test day: the boolean field is for more recent versions

2023-11-02 08:00 UTC, dade-odoo approved these changes
Looks good :) @LoredanaLrpz

2023-11-09 12:10 UTC, xpl-odoo commented
@Ysoroko feel free to r+ whenever!
@robodoo delegate+

2023-11-13 15:13 UTC, Ysoroko commented
@robodoo r+

2023-11-13 16:58 UTC, closed without merging