[IMP] accounting/l10n_co: additional context
odoo/documentation pull request #5936
Opened 2023-09-26 17:32 UTC by samueljlieber

This PR improves the content of the Colombian localization documentation by adding additional context to most sections per https://github.com/odoo/documentation/pull/4425.

This PR can be FWP with small edits needed for 15.0 and 16.0.

2023-09-26 17:32 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5936).

2023-10-05 11:05 UTC, dade-odoo requested changes
Hey @samueljlieber - your updates look good. I made a few comments/edits to the doc in general. Feel free to reach out to discuss any of them if you want :)

2023-10-05 21:26 UTC, samueljlieber commented
Hi @dade-odoo thank you for your review and suggestions for improvement! I implemented them in https://github.com/odoo/documentation/commit/48ba2f857651f326d5efb04a80a84483c6623c83.

2023-10-06 08:08 UTC, dade-odoo commented
Hey @samueljlieber - I'll go ahead and approve this and pass it on to @odoo/be-doc-review, but I am still seeing a typo on line 89 - "modules **are** installed" or "module's installed" seem more appropriate to me :) I'll let you handle it

2023-10-06 08:08 UTC, dade-odoo approved these changes

2023-10-06 12:35 UTC, samueljlieber commented
Hi @dade-odoo you are right, thank you for catching that! I just pushed a commit changing line 89 to "modules are installed" in https://github.com/odoo/documentation/commit/b433243cf1d467bf40046d6f8ac94e54c1e34bbd

2023-10-17 19:59 UTC, samueljlieber commented
Hi @odoo/be-doc-review this PR is ready for your review 🙂

2023-11-14 22:52 UTC, larm-odoo requested changes
Not a lot of changes, but maybe that's because this was WAY shorter!

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
>       - This module includes the features that are required for the integration with Carvajal and
```suggestion
     - This module includes the features required for integration with Carvajal, and
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +       generates the electronic invoices and support document related to the vendor bills, based on
```suggestion
       generates the electronic invoices and support documents related to the vendor bills, based on
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +     - Includes Point of Sale receipt for Colombian localization.
```suggestion
     - Includes Point of Sale receipts for Colombian localization.
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +     - Includes Point of Sale receipt for Colombian localization.
"receipts" sounds better- UNLESS there is only a single receipt produced (but I doubt it).

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
>  form to configure the following information:
```suggestion
form and configure the following information:
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +  `No Aplica`)
```suggestion
 or  `No Aplica`)
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +Check the :guilabel:`Test mode` checkbox to connect with the Carvajal testing environment.
```suggestion
Enable the :guilabel:`Test mode` checkbox to connect with the Carvajal testing environment.
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +Once Odoo and Carvajal are fully configured and ready for production, uncheck the :guilabel:`Test
```suggestion
Once Odoo and Carvajal are fully configured and ready for production, deactivate the :guilabel:`Test
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +   :guilabel:`Test mode` must be used **only** on duplicated databases, **not** the production
```suggestion
   :guilabel:`Test mode` must **only** be used on duplicated databases, **not** the production
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +Partner contacts can be created in the *Contacts* app. To do so, navigate to
```suggestion
Partner contacts can be created in the *Contacts* application. To do so, navigate to
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +:guilabel:`Company` radio button.
```suggestion
Then, name the contact, and using the radio buttons, select the contact type, either :guilabel:`Individual` or :guilabel:`Company`.
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +:guilabel:`ZIP` code. Proceed to complete the identification and fiscal information.
```suggestion
:guilabel:`ZIP` code. Then, complete the identification and fiscal information.
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +  de tributación simple, `R-99-PN` No Aplica).
```suggestion
  de tributación simple, or `R-99-PN` No Aplica).
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +- :guilabel:`Fiscal Regimen`: Select the tribute name for the company (`IVA`, `INC`, `IVA e INC`,
```suggestion
- :guilabel:`Fiscal Regimen`: Select the tribute name for the company (`IVA`, `INC`, `IVA e INC`, or
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +to display taxes in the invoice PDF correctly.
```suggestion
to display taxes correctly in the invoice PDF.
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +The *electronic invoice status* could be checked in the :guilabel:`Action` menu, by selecting the
```suggestion
The *electronic invoice status* can be checked in the :guilabel:`Action` menu, by clicking the
```

2023-11-14 22:52 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/colombia.rst
> +:guilabel:`Add Debit Note` button, and complete the following information:
```suggestion
:guilabel:`Add Debit Note` button, and enter the following information:
```

2023-11-17 16:11 UTC, samueljlieber commented
Thank you @larm-odoo for your review! I implemented most of your suggestions in https://github.com/odoo/documentation/commit/a359dfefabe07cf2877fc389ad941d97ec49f31e. @StraubCreative this PR should be good to go. 👍

2023-11-21 14:58 UTC, larm-odoo approved these changes

2023-11-22 20:50 UTC, StraubCreative commented
@robodoo r+

2023-11-22 21:38 UTC, closed without merging