[REM] Accounting: Scrub Taxcloud
odoo/documentation pull request #5976
Opened 2023-10-02 19:53 UTC by tiku-odoo

Remove TaxCloud from master (16.5) and put admonition warning block in forwarding to Avatax: 

Task: https://www.odoo.com/web#id=3529514&cids=3&model=project.task&view_type=form

2023-10-02 19:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/5976).

2023-10-03 07:44 UTC, dade-odoo approved these changes
Hey @tiku-odoo ! Not sure if you were explicitly looking for a review from our side or if we just got pinged automatically because it affects accounting docs. Either way, it looks good to me.

2023-10-04 00:10 UTC, StraubCreative approved these changes
This looks good to me, Tim. Thanks!
I had one small suggestion for you below to help improve the warning, visually.

@samueljlieber can you do a technical review here please?
Specifically, since we're removing content I want to be sure there aren't any loose internal links or missing 301s. TIA! 🙏 

cc: @fhe-odoo 

@robodoo delegate=samueljlieber

2023-10-04 00:10 UTC, StraubCreative commented on content/applications/finance/accounting/taxes/taxcloud.rst
> +      :doc:`avatax`
Would separate the **seealso** from the **warning** so it's not embedded visually.
```suggestion
.. seealso::
   :doc:`avatax`
```

2023-10-04 13:11 UTC, tiku-odoo commented
@samueljlieber This doc is ready for your review. Thanks. 

Tim

2023-10-04 13:59 UTC, samueljlieber requested changes
Hi @tiku-odoo nice job! Your changes look good to me. I did not find any other `:doc:` or `:ref:` references to the `taxcloud.rst` doc. I did notice the image folder for `taxcloud.rst` still has images in it– these need to be removed since they are no longer needed in the doc 🙂

I will push up a commit removing the images after my review. Thanks @tiku-odoo!

2023-10-04 14:11 UTC, samueljlieber commented
Removed images from `taxcloud/` from [my review](https://github.com/odoo/documentation/pull/5976#pullrequestreview-1657615101) in https://github.com/odoo/documentation/commit/486b6274ced1c42080df5d8753c83e0bb78732a7. All set 🙂

2023-10-04 14:11 UTC, samueljlieber approved these changes

2023-10-04 14:12 UTC, samueljlieber commented
@robodoo r+

2023-10-04 14:12 UTC, robodoo commented
I'm sorry, @samueljlieber. I'm afraid I can't do that.

2023-10-04 16:18 UTC, StraubCreative commented
@robodoo r+

2023-10-04 20:53 UTC, closed without merging