[ADD] website: mailing lists
odoo/documentation pull request #6048
Opened 2023-10-06 13:50 UTC by auva-odoo

task-2845181

2023-10-06 13:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/6048).

2023-10-12 07:52 UTC, toaa-odoo approved these changes
Hey @auva-odoo, great work! I only moved a line, the rest was all good :)

2023-11-23 10:28 UTC, xpl-odoo requested changes
Great job @auva-odoo ! Almost all comments are nitpicks, as usual ;)

Note: do we really want to have this page at the level of the Pages/Configuration etc. sections? It feels like we give this feature too much importance maybe?

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +#. Go to :menuselection:`Website --> Groups --> Mailing list groups`, then click :guilabel:`Create`.
```suggestion
#. Go to :menuselection:`Website --> Groups --> Mailing List Groups`, then click :guilabel:`Create`.
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +#. Specify a :guilabel:`Group name`, the :guilabel:`Email alias`, and a :guilabel:`Description`.
```suggestion
#. Specify a :guilabel:`Group Name`, the :guilabel:`Email Alias`, and a :guilabel:`Description`.
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +   members` tab and writing the :guilabel:`Notification message`.
```suggestion
   Members` tab and writing the :guilabel:`Notification message`.
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +   particularly useful when the mail group is moderated.
```suggestion
#. If you wish to send out guidelines to new subscribers, enable :guilabel:`Send guidelines to new
   subscribers` and write them in the :guilabel:`Guidelines` tab. This is
   particularly useful when the mail group is moderated.
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +To moderate messages, go to :menuselection:`Website --> Groups --> Mailing list groups`, select the
```suggestion
To moderate messages, go to :menuselection:`Website --> Groups --> Mailing List Groups`, select the
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +The following buttons are available:
```suggestion
The following actions are available:
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +   --> Groups --> Mailing list groups`, select the mail group and click the :guilabel:`Emails` smart
```suggestion
   --> Groups --> Mailing List Groups`, select the mail group and click the :guilabel:`Emails` smart
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +:menuselection:`Website --> Groups --> List moderation rulings` and click :guilabel:`Create`. Then,
```suggestion
:menuselection:`Website --> Groups --> List Moderation Rulings` and click :guilabel:`Create`. Then,
```

2023-11-23 10:28 UTC, xpl-odoo commented on content/applications/websites/website/mail_groups.rst
> +   Groups --> Mailing list groups`, selecting the group, then clicking the :guilabel:`Moderations`
```suggestion
   Groups --> Mailing List Groups`, selecting the group, then clicking the :guilabel:`Moderations`
```

2023-11-27 14:28 UTC, auva-odoo commented
Hey @xpl-odoo thank you for the review! I implemented all of the suggested changes, except the one regarding weather we really want to have this page at the level of the Pages/Configuration etc. sections? I would argue that although I see your point, it's the solution that makes the most sense to me at this time. We can discuss this if you want :-)

2023-11-27 14:59 UTC, xpl-odoo commented
> Hey @xpl-odoo thank you for the review! I implemented all of the suggested changes, except the one regarding weather we really want to have this page at the level of the Pages/Configuration etc. sections? I would argue that although I see your point, it's the solution that makes the most sense to me at this time. We can discuss this if you want :-)

No need to discuss this, we can @robodoo r+ :)

2023-11-28 08:42 UTC, xpl-odoo commented
> @robodoo r+

2023-11-28 08:43 UTC, xpl-odoo commented
@robodoo r+

2023-11-28 09:59 UTC, closed without merging