[REM] crm: google spreadsheet integration
odoo/documentation pull request #6394
Opened 2023-11-09 16:31 UTC by jero-odoo

The information in this document is no longer relevant as of 16. Google Drive and Google Spreadsheet integrations are no longer supported. I added a redirect to existing documentation describing the features of Odoo Spreadsheets, including the CRM specific templates. 

Only a tech review needed, no content added.

2023-11-09 16:31 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/6394).

2023-11-09 16:36 UTC, ksc-odoo commented
> The information in this document is no longer relevant as of 16. Google Drive and Google Spreadsheet integrations are no longer supported. I added a redirect to existing documentation describing the features of Odoo Spreadsheets, including the CRM specific templates.
> 
> Only a tech review needed, no content added.

Gotcha! Looks good to me!

2023-11-09 16:37 UTC, ksc-odoo approved these changes
Understand this only needs a tech-review. Nicely done! @jero-odoo

2023-11-09 19:38 UTC, samueljlieber requested changes
Hi @jero-odoo nice job with this removal PR! I have a very small change that I will push up after this review, and then I will approve if all checks pass 🙂

2023-11-09 19:38 UTC, samueljlieber commented on redirects/16.0.txt
> +applications/sales/crm/performance/google_spreadsheets.rst applications/finance/spreadsheet/templates.rst                             # removed crm doc and directed to finance doc
Small change to follow the existing comment formatting, and lets move to the top of this section to maintain alphabetical order 🙂
```suggestion
applications/sales/crm/performance/google_spreadsheets.rst applications/finance/spreadsheet/templates.rst                             # /google_spreadsheets --> /spreadsheet/templates
```

2023-11-09 19:42 UTC, samueljlieber approved these changes
LGTM! @StraubCreative

2023-11-10 18:09 UTC, StraubCreative approved these changes
lgtm 👍 
on to you @odoo/user-docs-structure-review

2023-11-21 10:28 UTC, xpl-odoo commented
👍 
@robodoo r+

2023-11-21 13:05 UTC, closed without merging