[IMP] l10n_cl: Electronic Invoicing eCommerce feature added
odoo/documentation pull request #6408
Opened 2023-11-10 21:52 UTC by masi-odoo

Adding the new functionality for V17 which let's the end client to decide the electronic document to be generated for their eCommerce purchase.

Photo folder: https://drive.google.com/drive/folders/17zrIsuhZ2IAWX6X30IJ1HdFF0531gB3_?usp=drive_link

2023-11-10 21:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/6408).

2023-11-14 16:04 UTC, samueljlieber requested changes
Hi @masi-odoo, thanks for creating this PR! I have some corrections and suggestions for improvement for the sections you added. 

Regarding the images, it appears the folder you linked contains images for a different PR. I think this PR can suffice without screenshots. However, please link the correct images if you would like them to be included 🙂

I will push up a second commit with my changes so you can review.

2023-11-27 22:41 UTC, samueljlieber commented
Implemented my technical changes in https://github.com/odoo/documentation/commit/29219b32f12293af00571e6086de3245d4caddd7 and added images.

2023-12-07 17:45 UTC, larm-odoo reviewed
Hi @samueljlieber - I finished my review. I noticed I could only check on the green text/new text but could not make any edits or suggestions to the text above or below it, so I couldn't check that part. If you need me to, just let me know (and please show me how I can do that ). Otherwise- here you go!

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +automatically generated when the online payment is confirmed.
```suggestion
automatically generated when an online payment is confirmed.
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +   Review the :doc:`../payment_providers` documentation to know which are supported in Odoo and how
```suggestion
   Review the :doc:`../payment_providers` documentation for information on which payment providers are supported in Odoo, and how
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +online payment confirmation. To do so, go to :menuselection:`Website --> eCommerce --> Products` and
```suggestion
It is also recommended to configure your products so they are able to be invoiced when an online payment is confirmed. To do so, go to :menuselection:`Website --> eCommerce --> Products` and
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +Clients from Chile will be able to select if they need an invoice or a ballot for their purchase in
```suggestion
Clients from Chile will be able to select if they need an invoice or a ballot for their purchase with
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +an extra step added in the checkout process.
```suggestion
an extra step added during the checkout process.
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +be filled; such as the :guilabel:`Activity Description`, the :guilabel:`Identification Number` and
```suggestion
be filled out; such as the :guilabel:`Activity Description`, the :guilabel:`Identification Number` and
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +step and the electronic document will be generated for the *Consumidor Final Anónimo* contact.
```suggestion
step, and the electronic document will be generated for the *Consumidor Final Anónimo* contact.
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +To install the :guilabel:`Chilean Module for Point of Sale` go to :menuselection:`Apps` and search
```suggestion
To install the :guilabel:`Chilean Module for Point of Sale` go to the :menuselection:`Apps` application on the main Odoo dashboard, and search
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +- Effectively let the final client decide the type of electronic document to be generated for their
```suggestion
- Effectively lets the final client decide the type of electronic document to be generated for their
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +Sale --> Session --> Customers --> Details` to edit:
```suggestion
<chile/partner-information>` section, or directly modify a contact. Navigate to :menuselection:`Point of
Sale --> Session --> Customers --> Details`, and edit any of the following fields:
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +select a product record. On the :guilabel:`Sales` tab in the product form, it is necessary to mark
```suggestion
select a product record. In the :guilabel:`Sales` tab of the product form, it is necessary to mark
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +automatically selects the contact for the order as the :guilabel:`Consumidor Final Anónimo`, and
```suggestion
When a specific user making a purchase does not request an electronic invoice, Odoo
automatically selects the contact for the order as the :guilabel:`Consumidor Final Anónimo`, and
```

2023-12-07 17:45 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +Orders can be searched by status of the order or by contact and be selected for the refund to be
```suggestion
Orders can be searched by the order status or contact, and be selected for the refund to be
```

2023-12-08 14:40 UTC, samueljlieber commented
Thank you for your helpful review @larm-odoo! I implemented your suggestions in https://github.com/odoo/documentation/commit/64fb31d3e5be81c0a8d5a5db2977e55ec4dc6ae2.

2023-12-08 15:44 UTC, jero-odoo approved these changes
hey @samueljlieber great job! Only a few suggestions but otherwise everything looks good!

2023-12-08 15:44 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +and their :guilabel:`DTE Email`.
```suggestion
be filled out, including the :guilabel:`Activity Description`, the :guilabel:`Identification Number`
and their :guilabel:`DTE Email`.
```

2023-12-08 15:44 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +Clients from other countries (not Chile), will have their electronic receipts automatically
```suggestion
Clients from countries other than Chile will have their electronic receipts automatically
```

2023-12-08 15:44 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +- Support for required fiscal fields for contacts created in the *Point of Sale* application.
```suggestion
- Support the required fiscal fields for contacts created in the *Point of Sale* application.
```

2023-12-11 15:06 UTC, samueljlieber approved these changes
Thank you @jero-odoo, I implemented your suggestions in https://github.com/odoo/documentation/commit/6302aa53d503de7daec0b14947d9e5397714081c!

I am approving this PR now that it has two peer reviews, and a technical review by me.

@masi-odoo can you please [review the built documentation](https://runbot137.odoo.com/runbot/static/build/54947148-17-0/logs/build/html/applications/finance/fiscal_localizations/chile.html) one last time? Thank you!

2023-12-11 18:54 UTC, samueljlieber approved these changes
This PR is good to go @StraubCreative 👍

2023-12-14 12:16 UTC, toaa-odoo approved these changes
I changed a few words and cleaned up the screenshots (we don't do red arrows and squares). Sorry for the delay :)

2023-12-14 17:51 UTC, StraubCreative approved these changes
Seems good. Thanks everyone 👍 

@robodoo r+

2023-12-15 02:52 UTC, closed without merging