[IMP] l10n: Codabox for Belgium
odoo/documentation pull request #6425
Opened 2023-11-13 13:11 UTC by RicGR98

2023-11-13 13:12 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/6425).

2023-11-13 16:06 UTC, RicGR98 commented
Hello @odoo/localizations-doc-review
Could I have a review on this PR ?
Thanks :)

2023-11-16 12:29 UTC, chiaraprattico requested changes
Hi @RicGR98 thanks for this doc!
I've added a few comments to make it compliant to doc formats, if you have questions or certain things are unclear we can check it out together.

2023-11-16 12:29 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/belgium.rst
> +connection on Odoo's side only.
The connection between Odoo and Codabox can be revoked by using the
:guilabel:`Revoke` button in the Codabox settings, which will revoke the
link on Odoo's side only.

2023-11-16 12:29 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/belgium.rst
> +~~~~~~~~~~
I would add this as a :note:

2023-11-16 12:29 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/belgium.rst
> +~~~~~~~~~~
The whole revocation paragraph

2023-11-16 12:29 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/belgium.rst
> +~~~~~~~~~~~~~~~~
This whole section would be better using this format: 
error message 1
  Explanation

error message 2
  Explanation



Double spacing. It should look like this 
![example-doc](https://github.com/odoo/documentation/assets/95279572/caeefbc3-1624-4940-b126-821226ff38c5)

2023-11-16 12:29 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/belgium/configuration_connection_ok.png
Can this token be shown, if not better to blur it otherwise fine like this.

2023-11-17 12:05 UTC, RicGR98 reviewed
Thanks a lot for the review, everything has been corrected ! :)

2023-11-17 12:05 UTC, RicGR98 commented on content/applications/finance/fiscal_localizations/belgium/configuration_connection_ok.png
Yes it's a dummy one :)

2023-11-23 14:27 UTC, RicGR98 commented
Warning: please do not r+, we're still changing some things in Enterprise and we'll have to update this doc accordingly

2023-11-28 13:44 UTC, xpl-odoo commented
@RicGR98 re-request a review when done? :)

2023-12-29 10:26 UTC, chiaraprattico reviewed
All good just left a comment. For screenshots, we always advise avoiding the red highlighting as it should be clear enough without it. Up to you whether to keep them with the highlights or not.

2023-12-29 10:26 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/belgium.rst
> +By default, only the **Administrator** is part of this group.
:guilabel:`Allow to show and modify the CodaBox Connection Settings`. Add the users you want to this group.
By default, only the :guilabel:`Administrator` is part of this group.

2023-12-29 10:49 UTC, RicGR98 commented
> All good just left a comment. For screenshots, we always advise avoiding the red highlighting as it should be clear enough without it. Up to you whether to keep them with the highlights or not.

Done ! Thanks again for the review :)

2024-01-15 15:13 UTC, auva-odoo reviewed
I had a look at the PR (as @jcs-odoo asked) and added a few comments/suggestions :)

2024-01-15 15:13 UTC, auva-odoo commented on content/applications/finance/fiscal_localizations/belgium.rst
> +      Account (499000) will be used and a note will be left in the created journal entry.
```suggestion
      By default, if an account in the SODA is not mapped to an account in Odoo, the Suspense
      Account (499000) is used and a note is left in the created journal entry.
```

2024-01-15 15:13 UTC, auva-odoo commented on content/applications/finance/fiscal_localizations/belgium.rst
> +  In case you have lost your Access Token, you will have to go on the CodaBox platform, and revoke
```suggestion
  If you have lost your Access Token, you have to go on the CodaBox platform, and revoke
```

2024-01-15 15:13 UTC, auva-odoo commented on content/applications/finance/fiscal_localizations/belgium.rst
> +  company VAT after the connection was established for instance. For security reasons, you will have
```suggestion
  company VAT after the connection was established for instance. For security reasons, you have
```

2024-01-15 15:38 UTC, RicGR98 commented
Thanks for the review @auva-odoo, everything is fixed :)

2024-01-16 09:16 UTC, RicGR98 commented
@robodoo r+

2024-01-16 11:39 UTC, closed without merging