[IMP] l10n_br: include electronic invoicing flow
odoo/documentation pull request #6877
Opened 2023-12-07 14:42 UTC by vbe-odoo

With the addition of l10n_br_edi and l10n_br_edi_sale to the previous modules, now electronic invoices for goods can be created from Odoo.

This PR includes the necessary information to use these new modules - configuration and workflows.

G-Folder with images: https://drive.google.com/drive/folders/1rCkyiYnWslzlQ7Oxb3IJC0-TeiWrQOwb?usp=drive_link

2023-12-07 14:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/6877).

2023-12-07 14:47 UTC, vbe-odoo commented
Here is the PR @samueljlieber with the modifications for the e-invoicing documentation.
Please review it, and feel free to edit the content to improve it.

If you have any questions do not hesitate to ping me.
These modules with the new e-invoicing feature is not yet released but it will be pretty soon (1 to 2 weeks)

Thank you!
cc' @ren-odoo @fvz-odoo @cas-odoo

2023-12-07 22:32 UTC, vbe-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +Electronic documents
Hey @samueljlieber my bad here! This is wrong, it should be
```suggestion
Vendor Bills
```

Can you help me with this change?

All the rest looks good!
cc' @ren-odoo @fvz-odoo

2023-12-08 15:15 UTC, samueljlieber commented
Thank you @vbe-odoo, I've implemented [that change](https://github.com/odoo/documentation/pull/6877#discussion_r1419729699) in https://github.com/odoo/documentation/commit/293349c4855e2c1ee762ba56c0a95382f30450b1.

2023-12-08 20:07 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +
```suggestion
A correction letter ca be created and linked to an electronic invoice that was validated by
the government.

```

2023-12-08 20:08 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +customer via email, you can do so by selecting the :guilabel:`E-mail` checkbox.
```suggestion
:guilabel:`Reason` on the pop-up that appears. To send this correction reason to a customer via email, activate the :guilabel:`E-mail` checkbox.
```

2023-12-08 20:32 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +government, if those sequences are not used and are not going to be used. To do so, navigate to the
```suggestion
government, only if those sequences are not used **and** are not going to be used. To do so, navigate to the
```

2023-12-08 20:33 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +journal select the ::menuselection:`⚙️ (gear) icon --> Invalidate Number Range (BR)`. On the
```suggestion
journal select the ::menuselection:`⚙️ (gear) icon --> Invalidate Number Range (BR)`. On the
```
```suggestion
journal, and click the ::menuselection:`⚙️ (gear) icon --> Invalidate Number Range (BR)`. On the
```

2023-12-08 20:33 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +:guilabel:`Reason`.
```suggestion
:guilabel:`End Number` of the range that should be canceled, and enter an invalidation
:guilabel:`Reason`.
```

2023-12-08 20:34 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +   journal.
```suggestion
   The log of the canceled numbers along with the XML file are recorded in the chatter of the
   journal.
```

2023-12-08 20:34 UTC, larm-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +is recorded on :ref:`customer invoices <brazil/electronic-documents>`.
```suggestion
is recorded on the :ref:`customer invoices <brazil/electronic-documents>`.
```

2023-12-11 15:09 UTC, samueljlieber commented
Thank you @larm-odoo for your very thorough review! I implemented your suggestions in https://github.com/odoo/documentation/commit/f6f20eb81b090573888e6a417504c12805193b6b.

2023-12-11 15:57 UTC, jero-odoo approved these changes
Hey @samueljlieber nice work, just a few comments (mostly suggestions). Let me know if you have any questions 👍

2023-12-11 15:57 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +   Number` is displayed, allocated as  the first number to be used sequentially for subsequent
```suggestion
   Number` is displayed, allocated as the first number to be used sequentially for subsequent
```

2023-12-11 15:57 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +For the goods tax computation and electronic invoicing part, you need to configure the
```suggestion
For the goods tax computation and electronic invoicing process, you need to configure the
```

2023-12-11 15:57 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +   service, you **must** access the AvaTax portal and upload your certificate there.
```suggestion
   accessing the Avalara portal in the Odoo database. However, in order to use the electronic invoice
   service, you **must** access the AvaTax portal and upload your certificate there.
```

2023-12-11 15:57 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +In order to issue electronic invoices a certificate needs to be uploaded to the `AvaTax portal
```suggestion
In order to issue electronic invoices, a certificate needs to be uploaded to the `AvaTax portal
```

2023-12-11 15:57 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +identification number (CNPJ) matches with the CNPJ in AvaTax.
```suggestion
The certificate will be synchronized with Odoo, as long as the external identifier number in the AvaTax portal matches - without special characters - with the CNPJ number, and the identification number (CNPJ) in Odoo matches with the CNPJ in AvaTax.
```
I believe I was able to get the gist of this, but if I am wrong feel free to change it.

2023-12-11 15:57 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
> +     - In the :guilabel:`Street 2` field enter the neighborhood
```suggestion
     - In the :guilabel:`Street 2` field, enter the neighborhood
```

2023-12-11 15:57 UTC, jero-odoo commented on content/applications/finance/fiscal_localizations/brazil.rst
>     - :guilabel:`IM`: municipa tax identification number
```suggestion
   - :guilabel:`IM`: municipal tax identification number
```

2023-12-13 14:43 UTC, larm-odoo approved these changes
Looks great- approved!

2023-12-13 14:43 UTC, samueljlieber approved these changes
Thank you @jero-odoo for your review! I implemented your suggestions in https://github.com/odoo/documentation/commit/4d2ab9c690f673be58b6a4670d403ce37540abcf. 

@vbe-odoo let me know the feature this PR addresses was merged on Monday the 11th, so @StraubCreative this PR is good to go 👍

2023-12-15 16:47 UTC, vbe-odoo commented
> Thank you @jero-odoo for your review! I implemented your suggestions in [4d2ab9c](https://github.com/odoo/documentation/commit/4d2ab9c690f673be58b6a4670d403ce37540abcf).
> 
> @vbe-odoo let me know the feature this PR addresses was merged on Monday the 11th, so @StraubCreative this PR is good to go 👍

Hello! 
I've checked the last changes and it looks good.
Thanks for the changes and the review!

Do you think this can be merged soon? As the feature is already deployed.

Thanks!
cc' @ren-odoo @fvz-odoo

2023-12-15 19:03 UTC, StraubCreative commented
> Do you think this can be merged soon? As the feature is already deployed.

Once we get a ✅ from the @odoo/localizations-doc-review team we can merge. They were just pinged here and I will drop in doc channel as well. Hopefully by early next week we'll be g2g!

2023-12-18 12:35 UTC, chiaraprattico requested changes
Nice one, thanks. I added my review, we usually don't have highlights on screenshots so I noted that but it's up to you if you think that's useful but we try to be constant. Same for punctuation in bullet points.

2023-12-18 12:35 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/brazil.rst
> +Tax calculations on quotations / sales orders
Tax calculations on quotations and sales orders

2023-12-18 12:35 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/brazil.rst
> +This section provides an overview of the actions that trigger API calls for tax computation, and how
you might want to explain what API calls in a couple of words or only add a link to an explanation.

2023-12-18 12:35 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/brazil.rst
> +   :alt: Invoice information needed to process an electronic invoice.
no red highlights

2023-12-18 12:35 UTC, chiaraprattico commented on content/applications/finance/fiscal_localizations/brazil.rst
> +   :alt: Process electronic invoice pop-up in Odoo.
no red highlight needed

2023-12-19 21:04 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/brazil.rst
>     - :guilabel:`Main Activity Sector`: list of main activity sectors of the contact
Updated all bullets to use periods, thank you!

2023-12-19 21:56 UTC, samueljlieber commented
Thank you @chiaraprattico for your thorough review! I implemented all of your changes in https://github.com/odoo/documentation/commit/055ba821b5db45ebadd3bb398cd24341b4237475 except for updating the images, as I do feel the markup is helpful. That being said, this PR is ready for another look– thank you 🙏

2023-12-19 22:29 UTC, ren-odoo commented
Hi team 

Thank you for all the hard work on this PR, most of our Brazilian partners are already very eager to know in detail the feature we have released on BR, so the sooner we can publish this documentation the better. 

Thank you.

2023-12-20 21:46 UTC, StraubCreative commented
> Thank you @chiaraprattico for your thorough review! I implemented all of your changes in [055ba82](https://github.com/odoo/documentation/commit/055ba821b5db45ebadd3bb398cd24341b4237475) except for updating the images, as I do feel the markup is helpful. That being said, this PR is ready for another look– thank you 🙏

Since the items were addressed let's merge what we have for now so our translators can get started and so BR users can benefit from the content.

Any further issues we can address in another PR.

Thanks everyone for your hard work on this!

@robodoo r+

2023-12-20 23:58 UTC, closed without merging