[ADD] website: address autocomplete configuration
odoo/documentation pull request #6984
Opened 2023-12-19 13:09 UTC by masp-odoo

Task-3618264

2023-12-19 13:10 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/6984).

2023-12-22 10:19 UTC, Donapi requested changes
Hi Marion,
Congrats on your first PR; it's good work!
I made some comments but it would be best to discuss it IRL. I was not able to reproduce all the steps you described. Can we check together? And I will also explain some of my comments :)

2023-12-22 10:19 UTC, Donapi commented on content/applications/websites/website/configuration/address_autocomplete.rst
> +Step 3: Usage
I wouldn't put the info related to the "usage" in a Step 3. 
I would make a new section like "Using Google Places API"

2023-12-22 10:19 UTC, Donapi commented on content/applications/websites/website/configuration/address_autocomplete.rst
> +.. important::
I'm not sure it makes sens to mention this info in Odoo documentation. We can discuss it :)

2024-01-09 13:18 UTC, jcs-odoo approved these changes
@robodoo delegate+

2024-01-09 13:22 UTC, masp-odoo commented
@robodoo r+

2024-01-09 13:22 UTC, masp-odoo commented
@robodoo r+

2024-01-09 13:23 UTC, robodoo commented
I'm sorry, @masp-odoo: this PR is already reviewed, reviewing it again is useless.

2024-01-09 15:03 UTC, closed without merging