[IMP] Domain names: improve current doc
odoo/documentation pull request #7073
Opened 2023-12-21 14:17 UTC by Donapi

taskid-3595179

2023-12-21 14:17 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7073).

2023-12-28 14:29 UTC, chiaraprattico requested changes

2023-12-28 14:32 UTC, chiaraprattico commented on content/administration/maintain/domain_names.rst
> +icon, :guilabel:`Domain names`, and :guilabel:`DNS`.
You can configure your MX records to use your email server such as Google Workspace. To do so, create the required DNS records to use your domain name.
To manage DNS records, go to your Odoo portal, click :guilabel:`My Databases`, then click the gear
icon, :guilabel:`Domain names`, and :guilabel:`DNS`.

2023-12-28 14:57 UTC, Donapi commented on content/administration/maintain/domain_names.rst
> +registrar, and you will be charged at the renewal rates as indicated on `their site (renewal column)
I replaced "enjoy" by "get" as discussed

2023-12-28 14:59 UTC, Donapi commented on content/administration/maintain/domain_names.rst
> +     This process can take several days due to the success of the offer.
Rephrased: This process can take several days due to the high number of requests.

2023-12-28 15:09 UTC, Donapi commented on content/administration/maintain/domain_names.rst
> +   - `Bing Webmaster Tools - Add and Verify site <https://www.bing.com/webmasters/help/add-and-verify-site-12184f8b>`_
you're right!

2023-12-28 19:08 UTC, ksc-odoo reviewed
@Donapi Just finished reviewing this doc. Once the comments I left have been addressed, this PR will be ready for the next stage.

2023-12-28 19:08 UTC, ksc-odoo commented on content/administration/maintain/domain_names.rst
> +==========================================
```suggestion
Indexing domain names by search engines
=======================================
```

2023-12-28 19:08 UTC, ksc-odoo commented on content/administration/maintain/domain_names.rst
> +when their URLs are mentioned elsewhere online.
```suggestion
Search engines, like Google and Bing, rely on web crawlers (:dfn:`robots that explore and analyze
the web`) to discover and index websites, and their related domain names. These crawlers find new
website links through existing pages, enabling search engines to automatically index domain names
when their URLs are mentioned elsewhere online.
```

2023-12-28 19:08 UTC, ksc-odoo commented on content/administration/maintain/domain_names.rst
> +using the :guilabel:`Console Google Search` available in your website's configuration.
```suggestion
Some search engines provide tools for web admins, such as:

`Google Search Console <https://search.google.com/search-console>`_ and `Bing Webmaster Tools
<https://www.bing.com/webmasters>`_, to help users analyze and improve page ranking.

Users **must** prove themselves as the owner of the domain name to use these services.

One way to verify the ownership of the domain name is by adding a DNS record (users can do this for
:ref:`domain names registered with Odoo <domain-name/odoo-manage>` and for domain names managed by
other providers) or by using the :guilabel:`Console Google Search` available in the website's
configuration.
```

2023-12-28 19:08 UTC, ksc-odoo commented on content/administration/maintain/domain_names.rst
> +   configuration of your website.
```suggestion
   Users **cannot** remove the subdomain dbname.odoo.com if Odoo is the host. However, the subdomain
   dbname.odoo.com exploration by search engines is blocked when users add a custom domain name to
   the configuration of the website.
```

2023-12-28 19:08 UTC, ksc-odoo commented on content/applications/websites/website/pages/seo.rst
>  Search Engine Optimisation (SEO)
```suggestion
Search Engine Optimization (SEO)
```

2024-01-04 13:43 UTC, xpl-odoo commented
> @Donapi Just finished reviewing this doc. Once the comments I left have been addressed, this PR will be ready for the next stage.

Hi @ksc-odoo ! Thanks for the review and valuable suggestions.
FYI, you were automatically pinged because @Donapi modified a file under the Email Marketing team's responsibility (`content/applications/general/email_communication/email_servers.rst`). In such cases, you should only review files under your responsibility 😄

2024-02-26 14:10 UTC, xpl-odoo commented
@robodoo r+

2024-02-26 15:58 UTC, closed without merging