[IMP] accounting: checks
odoo/documentation pull request #7195
Opened 2023-12-28 09:38 UTC by toaa-odoo

Cleared up some confusion about path menu and feature

Forward to master

taskid-3644544

2023-12-28 09:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7195).

2024-01-04 13:08 UTC, xpl-odoo approved these changes
Just a suggestion!
@robodoo delegate +

2024-01-04 13:08 UTC, xpl-odoo commented on content/applications/finance/accounting/payments/pay_checks.rst
> +:guilabel:`Outgoing Payments` in **bank** journals.
```suggestion
:guilabel:`Outgoing Payments` tabs of **bank** journals.
```
Suggestion

2024-01-04 13:12 UTC, auva-odoo requested changes
Hi @toaa-odoo just a tiny little change :-)

2024-01-05 14:50 UTC, auva-odoo approved these changes

2024-01-05 14:55 UTC, robodoo commented
I'm sorry, @toaa-odoo: you can't review+.

2024-01-05 14:58 UTC, xpl-odoo commented
@robodoo r+

2024-01-05 16:59 UTC, closed without merging