[IMP] subscriptions: update renewals doc
odoo/documentation pull request #7239
Opened 2024-01-03 22:03 UTC by ksc-odoo

PROJECT TASK: https://www.odoo.com/web#id=3667181&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2024-01-03 22:10 UTC, ksc-odoo commented
Alrighty @meng-odoo this one is ready for its first round of Peer Review 👍

2024-01-05 21:17 UTC, StraubCreative requested changes
Hi @ksc-odoo 
Good rewrite.
Some quick changes to improve further, see below.

2024-01-05 21:17 UTC, StraubCreative commented on content/applications/sales/subscriptions/renewals.rst
> +who need to renew.
I think the previous instance of this paragraph was better in that it listed out, in a general way, what Odoo Subscriptions could do in regard to renewals. It didn't qualify with adjectives or pitch features.

Here is my suggestion to return back to that more neutral tone:

```suggestion
With the Odoo *Subscriptions* application, a company can manage all of their subscriptions in one
place. Renewals can be processed automatically or manually, include additional products or upsells
per renewal order, and be filtered in batch views to quickly locate customers who need to renew
their subscriptions.
```

2024-01-05 21:17 UTC, StraubCreative commented on content/applications/sales/subscriptions/renewals.rst
> +In order to renew a subscription, a quotation with a subscription product(s)/service(s) **must** be
List the necessary requirement only:
- Only a singular product is required
- A subscription service is still a product (albeit a digital + recurring one)

```suggestion
In order to renew a subscription, a quotation with a subscription product **must** be
```

2024-01-05 21:17 UTC, StraubCreative commented on content/applications/sales/subscriptions/renewals.rst
> +When the :guilabel:`Renew` is clicked, Odoo instantly presents a new renewal quotation, complete
```suggestion
When the :guilabel:`Renew` button is clicked, Odoo instantly presents a new renewal quotation, complete
```

2024-01-05 21:17 UTC, StraubCreative commented on content/applications/sales/subscriptions/renewals.rst
> +From here, a standard sales flow can occur, which is typically started by clicking :guilabel:`Send
optional suggestion around specificity
```suggestion
From here, a standard sales flow can occur in order to confirm the quotation. This is typically begins by clicking :guilabel:`Send
```

2024-01-05 21:17 UTC, StraubCreative commented on content/applications/sales/subscriptions/renewals.rst
> +by Email`. This sends a copy of the quotation to the customer for them to confirm, and eventually,
```suggestion
by Email`. This sends a copy of the quotation to the customer, by email, for them to confirm, and eventually,
```

2024-01-05 21:17 UTC, StraubCreative commented on content/applications/sales/subscriptions/renewals.rst
> +  :alt: Renewal quotation in the Odoo Subscriptions application.
I believe once a renewal is confirmed the **MRR** smartbutton becomes available too. Can we talk about this?

2024-01-09 17:11 UTC, ksc-odoo commented
@StraubCreative Hey There! 👋 Just finished making all your suggested edits and added a portion at the end to briefly discuss the MRR button (with an additional screenshot, as well). Please feel free to give this another quick review whenever you get a chance. If there's anything else that needs to be modified/adjusted, just let me know. Thanks again for all the super-helpful feedback 👍

2024-01-11 22:51 UTC, StraubCreative approved these changes
Looks good @ksc-odoo 

One item for your consideration: most of the screenshots are a bit small and hard to read. Zooming in on compressed images unfortunately doesn't help too much here, so maybe expand the widths a bit to the tablet breakpoint of 768px or low res desktop 933-1024px, if needed.

Up to you though, merge when ready 👍 

@robodoo delegate=ksc-odoo

2024-01-18 05:12 UTC, closed without merging