[IMP] subscriptions: update close subs doc for 17
odoo/documentation pull request #7327
Opened 2024-01-09 22:14 UTC by ksc-odoo

PROJECT TASK: https://www.odoo.com/web#id=3676411&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2024-01-09 22:15 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7327).

2024-01-09 22:29 UTC, ksc-odoo commented
@meng-odoo This one is ready for its first round of Peer Review - whenever you get a chance! 👍

2024-01-17 21:25 UTC, meng-odoo approved these changes
Hi @ksc-odoo! I just had small wording suggestions for this doc. Please go ahead and move it to the next review stage once you've gone through my suggestions. Thanks!

2024-01-22 17:47 UTC, ksc-odoo commented
Thanks for the awesome feedback @meng-odoo -- I made all the suggested edits, and believe this one is now ready for a 2nd Round of Peer Review from the materials team. So, whenever any of y'all get a chance to check this one out, I'd really appreciate it! 👍 @Felicious @hojo-odoo @brse-odoo

2024-02-07 03:06 UTC, Felicious reviewed
Hi @ksc-odoo ! I got through reviewing about half of this PR, I'll get to the rest tomorrow (:

Amazing job so far! I just had super minor rewording suggestions

2024-02-07 03:06 UTC, Felicious commented on content/applications/sales/subscriptions/closing.rst
> +   configure recurring plans.
Very minor thing, but I was once put on blast for linking to other docs this way. Apparently, we **must** link to other doc [this way](https://www.odoo.com/documentation/16.0/contributing/documentation/rst_cheat_sheet.html#see-also)...

```suggestion
   .. seealso::
   :doc:`Configure recurring plans <plans>`
```

2024-02-07 03:06 UTC, Felicious commented on content/applications/sales/subscriptions/closing.rst
> +After a quotation for a subscription product(s) has been confirmed, it becomes a sales order, and
```suggestion
After a quotation for a subscription product has been confirmed, it becomes a sales order, and
```

2024-02-07 03:06 UTC, Felicious commented on content/applications/sales/subscriptions/closing.rst
> +drop-down menu of options that appears when the :guilabel:`Reason` field is clicked.
```suggestion
Clicking the :guilabel:`Close` button prompts a :guilabel:`Close Reason` pop-up window to appear, allowing administrators to input the reason for closing the subscription, or choose from the drop-down menu of options in the :guilabel:`Reason` field.
```

2024-02-07 21:20 UTC, Felicious approved these changes
Amazing job with this doc, @ksc-odoo !

I only had a few minor rewording suggestions for brevity, so feel free to go through those and pick the ones you like (: 

The doc is already really clear and easy to follow, so after you go through the comments, feel free to pass this along to final review!

2024-02-07 21:20 UTC, Felicious commented on content/applications/sales/subscriptions/closing.rst
> +is located on the left side of the sales order.
```suggestion
  Administrators can use the :guilabel:`Preview` button at the top pf the subscriptions sales
  order to view the the customer's perspective, where the customer can find the :guilabel:`Close
  Subscription` button on the left side of the sales order in the customer portal.
```

2024-02-07 21:20 UTC, Felicious commented on content/applications/sales/subscriptions/closing.rst
> +in the customer portal.
```suggestion
Upon closure, the subscription order in the customer portal is tagged as 
:guilabel:`Closed` tag.
```

2024-02-09 23:03 UTC, ksc-odoo commented on content/applications/sales/sales/send_quotations/quote_template.rst
> +back-end of the *Sales* application. placeement   compleeete.
oh my gosh! that's when we were still testing out linter! haha guess it made its way onto the actual PR... oh boy!

2024-02-09 23:25 UTC, ksc-odoo commented
@Felicious Thanks for all your awesome feedback! I made all your suggested edits, and believe this one is now ready for Tech Review from @samueljlieber , whenever you get a chance! Thanks! 👍

2024-02-12 14:23 UTC, samueljlieber requested changes
Hi @ksc-odoo! Nice job on this PR, the improvements in this doc look pretty great. I have just a few corrections to get this PR ready for final, please see below. I only listed a couple of the indentation corrections, so please look out for others throughout the doc. 

Let me know when this PR is ready for another look, thank you!

2024-02-12 14:23 UTC, samueljlieber commented on content/applications/sales/subscriptions/closing.rst
>    :align: center
The image attributes need to be lined up with the `i` in `.. image::`.
```suggestion
.. image:: closing/recurring-plans-closable-option.png
   :align: center
   :alt: The Closable option on a recurring plan form in Odoo Subscriptions.
```

2024-02-12 14:23 UTC, samueljlieber commented on content/applications/sales/subscriptions/closing.rst
> +  Subscription` button on the left side of the sales order in the customer portal.
The text in an admonition need to be lined up with the first character in the admonition type title, `n` in `.. note::`:
```suggestion
.. note::
   As an administrator, the ability to visualize what customers see when managing their
   subscriptions is accessible via the :guilabel:`Preview` button, located at the top of the
   subscription sales order.
```

2024-02-12 14:23 UTC, samueljlieber commented on content/applications/sales/subscriptions/closing/close-subscriptions-administrator.png
This image is too wide at `1111px`, please retake so it is at or below 933px wide.

2024-02-12 14:23 UTC, samueljlieber commented on content/applications/sales/subscriptions/closing/churned-sales-order.png
This image could be retaken with a little more width and zoom, it is currently `661px` wide and the text is pretty small.

2024-02-12 23:41 UTC, ksc-odoo commented
Alrighty, @samueljlieber , I made all your suggested edits and believe this one is ready for another look from you, whenever you get a chance. Thanks! 👍

2024-02-13 14:50 UTC, samueljlieber approved these changes
Hi @ksc-odoo! Thank you for implementing my corrections, the PR looks good! I did catch a couple more line breaks and indentation corrections. Please make these before tagging for final. Approving now 👍

2024-02-13 14:50 UTC, samueljlieber commented on content/applications/sales/subscriptions/closing.rst
>  .. note::
This note admonition's content needs to be indented by a space
```suggestion
.. note::
   Customers can *only* chose a pre-configured reason why the subscription is being closed. They can
   *not* enter a custom reason from the customer portal.
```

2024-02-13 14:50 UTC, samueljlieber commented on content/applications/sales/subscriptions/closing.rst
> +business.
Early line break
```suggestion
While losing customers is not ideal, making it easy for customers to cancel subscriptions minimizes
the impact of losing them, fostering a positive experience for the customer *and* the business.
```

2024-02-13 14:50 UTC, samueljlieber commented on content/applications/sales/subscriptions/closing.rst
> +   :alt: Close subscription from an administration point of view with Odoo Subscriptions.
Line over 100 char
```suggestion
   :alt: The Close Reason pop-up that appears when the Close button is clicked in Odoo
         Subscriptions.
```

2024-02-13 20:34 UTC, ksc-odoo commented
Thanks for the feedback @samueljlieber -- made all your suggested edits, and will tag this one for FINAL review now. Ready for ya whenever you get a chance, @StraubCreative 👍

2024-02-16 02:20 UTC, StraubCreative approved these changes
Hi @ksc-odoo 
Approving with comments for your consideration.
Merge when ready, thanks! 👍 

@robodoo delegate=ksc-odoo

2024-02-16 02:20 UTC, StraubCreative commented on content/applications/sales/subscriptions/closing.rst
> +their subscriptions, or restrict that ability entirely.
What's here on lines 16-17, I'd argue, is the only part you need for the intro.
This sentence specifically (gh won't let me select):
```
Odoo *Subscriptions* provides flexibility for businesses to decide whether customers can self-manage
their subscriptions, or restrict that ability entirely.
```

The rest is borderline pre-sales expo or not needed.

2024-02-16 02:20 UTC, StraubCreative commented on content/applications/sales/subscriptions/closing.rst
> +To configure recurring plans offered, navigate to :menuselection:`Subscriptions app -->
First part not needed or seems forced. Suggestion to just tell the reader to go to the right dash.
```suggestion
Start by navigating to :menuselection:`Subscriptions app -->
```

2024-02-16 02:20 UTC, StraubCreative commented on content/applications/sales/subscriptions/closing.rst
> +subscription is officially :guilabel:`In Progress`.
specificity
```suggestion
subscription status changes to :guilabel:`In Progress`.
```

2024-02-16 02:20 UTC, StraubCreative commented on content/applications/sales/subscriptions/closing.rst
> +button at the top of the :guilabel:`In Progress` subscription order. This option is also available
"top of the **In Progress** subscription order" didn't make sense to me when I read it a couple times.
Here's a suggested rewrite: 

```suggestion
button at the top of the subscription order, near the row that contains :guilabel:`In Progress` and other stages. This option is also available
```

2024-02-16 02:20 UTC, StraubCreative commented on content/applications/sales/subscriptions/closing.rst
> +   *not* enter a custom reason from the customer portal.
Little more context.
```suggestion
   *not* enter a custom reason from the customer portal. These selections can be adjusted by
   navigating to :menuselection:`Subscriptions --> Configuration --> Close Reasons`.
```

2024-02-16 02:20 UTC, StraubCreative commented on content/applications/sales/subscriptions/closing.rst
> +Upon closure, the subscription order in the customer portal is tagged as :guilabel:`Closed` tag.
redundant
```suggestion
Upon closure, the subscription order in the customer portal is tagged as :guilabel:`Closed`.
```

2024-02-16 22:44 UTC, ksc-odoo commented on content/applications/sales/subscriptions/closing.rst
> +increase the level dissatisfaction amongst the leaving customer base, which can negatively impact
I'll just be keeping the lines of 16-17. Thanks for the advice. Removing the other lines in the intro.

2024-02-16 23:02 UTC, ksc-odoo commented
@robodoo r+

2024-02-17 01:58 UTC, closed without merging