[IMP] subscriptions: update automation rules doc for 17
odoo/documentation pull request #7338
Opened 2024-01-10 21:38 UTC by ksc-odoo

PROJECT TASK: https://www.odoo.com/web#id=3677982&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2024-01-10 21:39 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7338).

2024-01-10 21:41 UTC, ksc-odoo commented
@meng-odoo This one is ready for its first round of Peer Review, whenever you get a chance! 👍

2024-01-18 00:35 UTC, meng-odoo approved these changes
Hi @ksc-odoo, great job on this doc, I only had small suggestions for wording and formatting. Then this will be good to go! Thanks :)

2024-01-18 00:35 UTC, meng-odoo commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +- :guilabel:`Title`: enter a custom title for chosen activity.
```suggestion
- :guilabel:`Title`: enter a custom title for the chosen activity.
```

2024-01-22 18:59 UTC, ksc-odoo commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +- :guilabel:`Action To Do`: choose the action that will occur once the automated rule is triggered.
I encountered this, as well. I reformatted this lead-in portion to remedy that issue. Thanks for pointing it out! 👍

2024-01-22 19:02 UTC, ksc-odoo commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +     options: :guilabel:`Neutral`, :guilabel:`Good`, or :guilabel:`Bad`.
No longer a note. 👍

2024-01-22 19:14 UTC, ksc-odoo commented
Thanks for the always-helpful feedback @meng-odoo -- I made all those suggested edits, and this one is now ready for a 2nd Round of Peer Review from the Materials team... 👍 @Felicious @hojo-odoo @brse-odoo

2024-01-22 20:25 UTC, Felicious approved these changes
This is a really well-written and detailed explanation of automatic features, @ksc-odoo ! 
It seems like such a complicated feature, but your doc makes it really easy to understand. Great job explaining all the fields in great detail :blush: 

I had some super minor suggestions, feel free to pass this onto to final review after this!

2024-01-22 20:25 UTC, Felicious commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +  percentage of satisfaction.
```suggestion
- :guilabel:`Rating Satisfaction`: designate satisfaction as :guilabel:`greater than` or
  :guilabel:`less than` a percentage.
```

2024-01-22 20:25 UTC, Felicious commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +- :guilabel:`Over`: choose a period of time over which the designated KPIs are calculated.
possibly put KPI in an abbr tag and define what the acronym stands for?

2024-01-22 20:25 UTC, Felicious commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +~~~~~~~~~~~~~~~~
```suggestion
Apply on
~~~~~~~~
```
possibility for brevity and sentence case formatting. Feel free to reject this, as I know you have it written to match the section in the Automation Rule form (:

2024-01-22 20:25 UTC, Felicious commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +  action will be created at the creation of the subscription *and* when it is updated.
```suggestion
  action is created upon subscription creation *and* updates.
```
optional

2024-01-23 00:48 UTC, ksc-odoo commented
Thanks for the feedback, @Felicious ! I made all the suggested edits, and believe this one is now ready for Tech Review @samueljlieber 👍

2024-01-23 21:20 UTC, samueljlieber requested changes
Hi @ksc-odoo! Nice job on the improvements in this PR, the doc reads very well! I have a few corrections for you, please see below and tag me for another look when this PR is ready! 🙂

Also, this is a nitpick, the commit tag and PR title could be a little shorter/concise, something like:
```
[IMP] subscriptions: update automation rules doc
```

2024-01-23 21:20 UTC, samueljlieber commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +.. image:: automatic_alerts/automation-rules-page.png
Indent the `:align:` and `:alt:` image attributes please :)
```suggestion
.. image:: automatic_alerts/automation-rules-page.png
   :align: center
   :alt: The Automation Rules page in the Odoo Subscriptions application.
```

2024-01-23 21:20 UTC, samueljlieber commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +.. image:: automatic_alerts/automation-rules-form.png
Indent attributes here too please
```suggestion
.. image:: automatic_alerts/automation-rules-form.png
   :align: center
   :alt: A sample Automation Rules form in the Odoo Subscriptions application.
```

2024-01-23 21:20 UTC, samueljlieber commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +~~~~~~~~
Add "section" to the heading so it is consistent with the other headings
```suggestion
Apply On section
~~~~~~~~~~~~~~~~
```

2024-01-23 21:20 UTC, samueljlieber commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +  - :guilabel:`Set Contract Health value`: set the health value of the subscription contract.
No need for these bullets to be indented, please scoot them back :)
```suggestion
- :guilabel:`Create next activity`: creates the next activity to occur, which is configured in the
  :guilabel:`Activity` section that appears at the bottom of the automation rule form.
- :guilabel:`Send an email to the customer`: sends an email to the customer(s) who fit the specified
  criteria of the automation rule.
- :guilabel:`Send an SMS Text Message to the customer`: sends an SMS message to the customer(s) who
  fit the specified criteria of the automation rule.
- :guilabel:`Set Contract Health value`: set the health value of the subscription contract.
```

2024-01-23 21:20 UTC, samueljlieber commented on content/applications/sales/subscriptions/automatic_alerts.rst
> +    options: :guilabel:`Neutral`, :guilabel:`Good`, or :guilabel:`Bad`.
No need for these bullets to be indented either
```suggestion
- :guilabel:`Email Template`: create (and edit) a new email template *or* select from a list of
  pre-configured email templates to send to the customer(s).

If :guilabel:`Send an SMS Text Message to the customer` is selected in the :guilabel:`Action To Do`
field, the following field appears:

- :guilabel:`SMS Template`: create (and edit) a new SMS template *or* select from a list of
  pre-configured SMS templates to send to the customer(s).

If :guilabel:`Set Contract Health value` is selected in the :guilabel:`Action To Do` field, the
following field appears:

- :guilabel:`Health`: designate the health of the subscription by choosing one of the following
  options: :guilabel:`Neutral`, :guilabel:`Good`, or :guilabel:`Bad`.
```

2024-01-23 22:30 UTC, ksc-odoo commented
Alrighty @samueljlieber This one is ready for another look from ya, whenever you get a chance. Thanks! 👍

2024-01-23 22:38 UTC, samueljlieber approved these changes
Looks great @ksc-odoo, thank you! 

@StraubCreative this PR is good to go 👍

2024-02-04 02:52 UTC, StraubCreative approved these changes
@robodoo r+

2024-02-04 05:18 UTC, closed without merging