[FIX] Chile Documentation
odoo/documentation pull request #7339
Opened 2024-01-10 22:50 UTC by masi-odoo

Fixing typos and duplicates in the "Modules section"

2024-01-10 22:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7339).

2024-01-11 14:32 UTC, samueljlieber approved these changes
These edits look good to me, thank you @masi-odoo! 

I pushed up a commit to adjust the commit message and rebased to latest. This PR is all set for review 👍

2024-01-12 09:39 UTC, toaa-odoo approved these changes

2024-01-12 11:44 UTC, jcs-odoo requested changes
This should target 16.0, not 17.0

2024-01-12 14:39 UTC, jcs-odoo approved these changes
Thank you @samueljlieber :)

@robodoo r+

2024-01-12 16:45 UTC, closed without merging