[ADD] POS: page to configure and use product combos in retails and re…
odoo/documentation pull request #7341
Opened 2024-01-11 09:26 UTC by LoredanaLrpz

…staurants

Task-3604850

2024-01-11 09:26 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7341).

2024-01-11 13:34 UTC, masp-odoo requested changes
Hello Loredana, très contente de faire cette première review sur POS. Tout est clair, je n'ai rien à redire si ce n'est que les retours à la ligne apparaissent bizarrement chez moi donc je l'ai noté à chaque endroit. À dispo si besoin !

2024-01-11 13:34 UTC, masp-odoo commented on content/applications/sales/point_of_sale/configuration/combos.rst
> +      - The combo product price is only affected by the extra price optionally defined at the combo
Retour à la ligne après combo

2024-01-11 13:34 UTC, masp-odoo commented on content/applications/sales/point_of_sale/configuration/combos.rst
> +Once you have created and added the combo choices into a product, you can sell combos in your retail
Retour à la ligne après retail

2024-01-11 13:34 UTC, masp-odoo commented on content/applications/sales/point_of_sale/configuration/combos.rst
> +:ref:`Open a POS session <pos/session-start>` and select the combo product. Choose the options and
Retour à la ligne après "and"

2024-01-11 14:44 UTC, masp-odoo approved these changes

2024-01-15 11:14 UTC, auva-odoo requested changes
Hello my dear @LoredanaLrpz it was an honor for me to review this PR. 

Haha kidding aside, I added a few suggestions/comments; some can be discarded if you want, some (one) are a little forgetfullnessiness on your part and one is actually something I'd like to discuss with you if that's ok! Let me know when you're ready (tomorrow - Tuesday maybe?).

2024-01-16 12:32 UTC, jcs-odoo commented on content/applications/sales/point_of_sale/configuration/combos.rst
> +   :scale: 75%
😭

2024-01-17 08:59 UTC, LoredanaLrpz commented on content/applications/sales/point_of_sale/configuration/combos.rst
> +The "Product Combos" feature enables users to define and manage combination options within a
I've changed it, tell me what you think =D

2024-01-18 08:44 UTC, auva-odoo approved these changes
Nice job on the intro (and the rest of the PR as well of course), I think that clarifies it :) I just have one more tiny comment but since it's so small I'll go ahead and approve this already :) You can r+ whenever you're ready!
@robodoo delegate+

2024-01-18 08:44 UTC, auva-odoo commented on content/applications/sales/point_of_sale/configuration/combos.rst
> +        choice creation or if a variant of one of the items has a specified extra price.
Good job rephrasing this one :) I just think we can combine the two bullet points now (+ I'd replace "for" with "of"):
```suggestion
      The sales price of the combo product is fixed and does not vary based on the individual
       prices of included items or the quantity of items in the combo. It is only affected by the extra price optionally 
       defined at the combo choice creation or if a variant of one of the items has a specified extra price.
```

2024-01-18 08:44 UTC, auva-odoo commented on content/applications/sales/point_of_sale/configuration/combos.rst
> +        choice creation or if a variant of one of the items has a specified extra price.
I think we can combine the two bullet points (+ I'd replace "for" with "of"):
```suggestion
      The sales price of the combo product is fixed and does not vary based on the individual
       prices of included items or the quantity of items in the combo. It is only affected by the extra price optionally 
       defined at the combo choice creation or if a variant of one of the items has a specified extra price.
```

2024-01-22 12:07 UTC, LoredanaLrpz commented
@robodoo r+

2024-01-22 12:07 UTC, LoredanaLrpz commented
@robodoo r-

2024-01-22 12:35 UTC, LoredanaLrpz commented
@robodoo r+

2024-01-22 20:24 UTC, closed without merging