[IMP] Website: Updating seo documentation
odoo/documentation pull request #7386
Opened 2024-01-15 09:05 UTC by Donapi

[IMP] Website: Updating seo documentation

taskid-[3499195](https://www.odoo.com/web#id=3499195&cids=1&model=project.task&view_type=form)

2024-01-15 09:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7386).

2024-01-15 14:07 UTC, zulu-odoo requested changes
Hi Dona,
Please see my review comments. As always, feel free to ignore anything that you disagree with, and I'm available whenever if you want to discuss in person :)
Thank you!

2024-01-16 08:39 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +update the title tag of your webpage or keep it empty to use the default value.
updated

2024-01-16 09:11 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +results below the title. It is essential for encouraging click-through. You can update the
updated and simplified

2024-01-16 09:40 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +   The :guilabel:`Preview` card overviews how the title and description tags should appear in search
How they "should", as per JQU ...

2024-01-16 09:41 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +engines to find what they're looking for. Creating a list of relevant keywords is essential in any
I have been asked by the PO to delete this paragraph

2024-01-16 12:21 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +Odoo ``<keyword>`` finder helps you see how your keywords are used at the different levels of your
It's the context and not the field. I think we could debate about it :)

2024-01-16 13:19 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +.PNG and .GIF and lossy compression for .JPG). All images used in Odoo official themes have been
I discussed it with cwa and updated the sentence

2024-01-16 13:24 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +   shown when the image cannot be displayed.
the image right above shows the description field to add the alt tag, that's why it's here

2024-01-16 13:28 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +Businesses, Events and Organizations.
By default. Clarified in the sentence

2024-01-16 13:38 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +have dozens of thousands of products.
makes sense!

2024-01-17 08:16 UTC, zulu-odoo approved these changes
Hi Dona,
Looks good to me :)
Thank you!

2024-01-29 11:31 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +search engines.
Good idea!

2024-01-29 14:35 UTC, Donapi commented on content/applications/websites/website/pages/seo.rst
> +robots.txt
We speak about it in the tip in the sitemap section.

2024-02-06 11:52 UTC, auva-odoo approved these changes
@robodoo r+

2024-02-06 12:00 UTC, robodoo commented
@donapi @auva-odoo because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2024-02-06 12:38 UTC, auva-odoo commented
@robodoo r-

2024-02-06 13:55 UTC, Donapi commented
@robodoo r+

2024-02-06 13:56 UTC, robodoo commented
I'm sorry, @donapi: you can't review+.

2024-02-06 14:05 UTC, auva-odoo commented
@robodoo r+

2024-02-06 15:53 UTC, closed without merging