[IMP] payment_providers: payment methods + restructure doc page
odoo/documentation pull request #7414
Opened 2024-01-16 15:20 UTC by auva-odoo

task-3570280

2024-01-16 15:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7414).

2024-01-19 10:20 UTC, masp-odoo reviewed
Hello @auva-odoo, c'est bien structuré ! J'ai juste mis des commentaires sur la forme car parfois les alignements sont étranges sur la vue GitHub et une suggestion de texte. A dispo pour en discuter lundi si tu préfères.

2024-01-19 17:30 UTC, AntoineVDV requested changes
I like it! :star_struck:

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +.. warning::
?
```suggestion
.. danger::
```

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +.. _payment_providers/features/tokenization:
```suggestion
.. _payment_providers/tokenization:
```

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +can choose to save their card details for later. To enable this feature, go to the
It's less and less about cards only.
```suggestion
can choose to save their payment method details for later. To enable this feature, go to the
```

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +cancellation. Capturing payments manually is useful in many situations:
Cancellations are more of a customer action than a vendor action. Vendors typically have to refund payments that they want to revert when they have already been captured. The difference with a void is that a void releases the funds by canceling the authorization before the capture moves any money. In practice, you don't have to pay expensive (several percent) refund fees.

https://support.stripe.com/questions/understanding-fees-for-refunded-payments

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +cancellation. Capturing payments manually is useful in many situations:
See third bullet point.

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +- Avoid potentially high processing fees for cancelled payments: payment providers will not charge
refund fees; refunded payments

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> -again later.
Was this dropped on purpose?

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +allow customers to use the :guilabel:`Google Pay` and :guilabel:`Apple Pay` buttons and pay their
Not sure if it's worth mentioning but there is also Stripe's Link now (quite anecdotic).

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +To enable this feature, go to the :guilabel:`Configuration` tab of the selected payment provider and
For Stripe, they should also hit the "Enable Apple Pay" button.

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
> +Refunds
I think you forgot this one; it should be right after manual capture.

2024-01-19 17:30 UTC, AntoineVDV commented on content/applications/finance/payment_providers.rst
>  Payment journal
Do what you want with this information: payment journals must be configured only if Invoicing/Accounting is installed, since Odoo 17.

2024-01-23 15:02 UTC, AntoineVDV approved these changes

2024-01-23 22:57 UTC, StraubCreative approved these changes
Commenting just for `subscriptions.rst` as part of Subscriptions Doc Review.
Change looks good to me! 👍

2024-01-24 07:22 UTC, auva-odoo commented on content/applications/finance/payment_providers.rst
> +Payment providers and payment methods
Ok then, I changed the title but will keep the file name as is for now.

2024-01-24 09:18 UTC, auva-odoo commented
@robodoo r+

2024-01-24 12:29 UTC, closed without merging