[IMP] helpdesk: update helpcenter doc
odoo/documentation pull request #7710
Opened 2024-02-12 21:07 UTC by jero-odoo

Work in progress
Updating the Helpdesk- Help center documentation for V17. This includes updating the content and (all) screenshots to reflect changes for 17.

2024-02-12 21:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7710).

2024-02-20 19:10 UTC, larm-odoo requested changes
Hey Jess- great doc, not much to add, just a few things that you might want to double-check  against my testing!

2024-02-20 19:10 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +Knowing this, it may be beneficial to publish the course first if the course contents are intended
This could be in an example block?

2024-02-20 19:10 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +Click the :guilabel:`≣ (bars)` icon in the upper-right corner, directly beneath the search bar to
```suggestion
Click the :guilabel:`≣ (horizontal bars)` icon in the upper-right corner, directly beneath the search bar to
```

2024-02-20 19:10 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  With all the course content selected, double click any of the boxes in the :guilabel:`Is Published`
I just had to click, not double click. Maybe that's because when testing, all my items were published already? Might want to check this.

2024-02-20 19:10 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  column. This reveals a pop-up window, asking for confirmation that all selected records are intended
Line 326 - I see a "confirm'" button not an "OK" button here.

2024-02-21 16:25 UTC, jero-odoo commented
Thanks @larm-odoo ready for another look 👍

2024-02-21 17:16 UTC, larm-odoo approved these changes
Hey Jess- looks great! I only had a couple small things I didn't catch in the first go-around, which is that in the config menu, it's now called "Helpdesk Teams" instead of just "Teams". I am approving since that's just a tiny issue

2024-02-21 17:16 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +internal users`.
```suggestion
internal users (public)`.
```

2024-02-21 17:16 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  When a team has been selected or created, Odoo displays that team's detail form.
in line 49, it's called 'Helpdesk Teams' instead of just 'Teams' in the menu.

2024-02-21 17:16 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  :menuselection:`Helpdesk app --> Configuration --> Teams` and select a team, or create a :doc:`new
```suggestion
:menuselection:`Helpdesk app --> Configuration --> Helpdesk Teams` and select a team, or create a :doc:`new
```

2024-02-21 17:16 UTC, larm-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  --> Teams` and select a team, or create a :doc:`new one
```suggestion
--> Helpdesk Teams` and select a team, or create a :doc:`new one
```

I'd just search to make sure al instances of the config menu has "Helpdesk Teams"

2024-02-21 20:15 UTC, jero-odoo commented
@ksc-odoo This is ready for final review. Thanks!

2024-02-22 19:19 UTC, ksc-odoo requested changes
Hey @jero-odoo 👋 Just finished my Final Review on this doc -- AWESOME JOB! Once you address the comments I left, feel free to tag me for another quick look. Then, once everything's ready to go, we can pass this on to the next stage. Thanks!

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  adjustments have been made, click :guilabel:`Create and View Post`.
```suggestion
When clicked, a pop-up window appears. Here, the :guilabel:`Forum` post and :guilabel:`Title` can be
edited to correct any typos, or modified to remove any proprietary or client information.

:guilabel:`Tags` can also be added to help organize the post in the forum, making it easier for
users to locate during a search. When all adjustments have been made, click :guilabel:`Create and
View Post`.
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  To enable *eLearning* courses on a *Helpdesk* team, go to :menuselection:`Helpdesk --> Configuration
```suggestion
To enable *eLearning* courses on a *Helpdesk* team, go to :menuselection:`Helpdesk app --> Configuration
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  to :guilabel:`eLearning`. A new field will appear below, labeled :guilabel:`Courses`.
```suggestion
to :guilabel:`eLearning`. A new field will appear below, labeled, :guilabel:`Courses`.
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +Under :guilabel:`Access Rights`, select what users will be able to view and enroll in the course.
```suggestion
Under :guilabel:`Access Rights`, select which users are able to view and enroll in the course.
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +Under :guilabel:`Display`, choose the course :guilabel:`Type`.
```suggestion
Under :guilabel:`Display`, choose the preferred course :guilabel:`Type`.
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  To allow customers to enroll in a course, both the course and the contents need to be published.
```suggestion
To allow customers to enroll in a course, both the course and the contents **must** be published.
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +   Knowing this, it may be beneficial to publish the course first if the course contents are
```suggestion
   Knowing this, it may be beneficial to publish the course first, if the course contents are
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +While in list view, there is a checkbox on the far left of the screen, above the listed courses, to
```suggestion
While in list view, there is a checkbox on the far-left of the screen, above the listed courses, to
```

2024-02-22 19:19 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +selected at once.
```suggestion
the left of the :guilabel:`Title` column title. When that checkbox is clicked, all the course
contents are selected at once.
```

2024-02-22 20:20 UTC, jero-odoo commented
Thanks @ksc-odoo, ready for another look!

2024-02-22 21:39 UTC, ksc-odoo approved these changes
@jero-odoo great work making all those changes so quickly. nicely done. there are two other, super-minor suggestions that require your attention, but I'm approving now. So, once you make those modifications, feel free to tag this for Tech Review. Awesome job!!! 👍

2024-02-22 21:39 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
> +:guilabel:`Knowledge (bookmark)`.
```suggestion
:guilabel:`Knowledge (bookmark)` icon.
```

2024-02-22 21:39 UTC, ksc-odoo commented on content/applications/services/helpdesk/overview/help_center.rst
>  to :guilabel:`eLearning`. A new field will appear below, labeled :guilabel:`Courses`.
```suggestion
to :guilabel:`eLearning`. A new field appears below, labeled :guilabel:`Courses`.
```

2024-02-23 13:15 UTC, jero-odoo commented
@samueljlieber This is ready for technical review. Thanks!

2024-03-04 18:26 UTC, samueljlieber requested changes
Hi @jero-odoo, nice job on the 17.0 improvements in this PR! I have only a few technical corrections to be made, please see below.

Also the image `help-center-forum-settings.png` does not seem to be used, can you please remove this from the media directory?

Tag me for another quick look once these have been addressed, thank you!

2024-03-04 18:26 UTC, samueljlieber commented on content/applications/services/helpdesk/overview/help_center.rst
> +   :doc:`Getting Started </applications/services/helpdesk/overview/getting_started>`
Update to be a relative doc path please :)
```suggestion
   :doc:`Getting Started <getting_started>`
```

2024-03-04 18:26 UTC, samueljlieber commented on content/applications/services/helpdesk/overview/help_center.rst
>  </applications/services/helpdesk/overview/getting_started>`.
```suggestion
Configuration --> Helpdesk Teams` and select a team, or create a :doc:`new one <getting_started>`.
```

2024-03-04 18:26 UTC, samueljlieber commented on content/applications/services/helpdesk/overview/help_center.rst
Update to be a relative doc path please :)
```suggestion
   :doc:`Editing Knowledge articles <../../../productivity/knowledge/articles_editing>`
```

2024-03-04 18:26 UTC, samueljlieber commented on content/applications/services/helpdesk/overview/help_center.rst
> +is then added to the page. Add any necessary content to this block.
Update to relative path please :)
```suggestion
<../../../productivity/knowledge/articles_editing>`. Select or type `clipboard`. A gray block is
then added to the page. Add any necessary content to this block.
```

2024-03-04 18:26 UTC, samueljlieber commented on content/applications/services/helpdesk/overview/help_center.rst
> +:doc:`new one </applications/services/helpdesk/overview/getting_started>`.
```suggestion
:doc:`new one <getting_started>`.
```

2024-03-04 18:26 UTC, samueljlieber commented on content/applications/services/helpdesk/overview/help_center.rst
>  </applications/services/helpdesk/overview/getting_started>`.
```suggestion
Configuration --> Helpdesk Teams` and select a team, or create a :doc:`new one <getting_started>`.
```

2024-03-04 19:20 UTC, jero-odoo commented
Hey @samueljlieber ready for another look. Thanks!

2024-03-04 20:35 UTC, jero-odoo commented
@StraubCreative This one is ready for final review/merge. Thanks!

2024-03-05 22:51 UTC, StraubCreative approved these changes
Looks good, thanks @jero-odoo 
..
@robodoo r+

2024-03-06 01:28 UTC, closed without merging