[IMP] subscriptions: corrected error about recurring products tip
odoo/documentation pull request #7748
Opened 2024-02-15 16:07 UTC by ksc-odoo

Fixed error re: tip on the products.rst of Subscriptions to adhere to suggestion in this PROJECT TASK: https://www.odoo.com/web#id=3744972&cids=3&model=project.task&view_type=form

2024-02-15 16:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7748).

2024-02-16 16:46 UTC, StraubCreative requested changes
Hi @ksc-odoo 
Couple comments for you below.
I'm not sure we need either of these content changes— can just simply remove what's there and that solves the issues outlined in the Task. Wdyt?

2024-02-16 16:46 UTC, StraubCreative commented on content/applications/sales/subscriptions/products.rst
> +   without a recurrence.
Don't think we need this?
```suggestion
```

2024-02-16 16:46 UTC, StraubCreative commented on content/applications/sales/subscriptions/products.rst
> +   A recurrence is **required** for recurring products.
Don't think we need this either, honestly?
```suggestion
```

2024-02-16 17:14 UTC, ksc-odoo commented
Made all your suggested adjustments @StraubCreative -- ready for another quick look from you whenever you get a chance. Thanks! 👍

2024-02-16 17:27 UTC, StraubCreative approved these changes
@robodoo r+

2024-02-17 01:58 UTC, closed without merging