[IMP] email marketing: updated unsubscription/blacklist doc for 17
odoo/documentation pull request #7809
Opened 2024-02-22 16:40 UTC by ksc-odoo

PROJECT TASK: https://www.odoo.com/web#id=3763346&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2024-02-22 16:40 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7809).

2024-02-22 17:05 UTC, hojo-odoo commented
Hey @ksc-odoo,

I can take a look at this.

Thanks,
hojo

2024-02-22 18:02 UTC, hojo-odoo approved these changes
Hey @ksc-odoo,

Nice job on this doc. I just had a few suggestions. Feel free to move it to the next round of review after you take a look.

Thanks,
hojo

2024-02-22 18:02 UTC, hojo-odoo commented on content/applications/marketing/email_marketing/unsubscriptions.rst
> +when that recipient blacklisted themselves (via a :guilabel:`Mail Blacklist created` log note).
```suggestion
In the *chatter* of the blacklisted record page, there's a time-stamped message, informing the user
when the recipient blacklisted themselves (via a :guilabel:`Mail Blacklist created` log note).

```

2024-02-22 18:02 UTC, hojo-odoo commented on content/applications/marketing/email_marketing/unsubscriptions.rst
> +When :guilabel:`Unblacklist` is clicked, a :guilabel:`Are you sure you want to unblacklist this
```suggestion
When :guilabel:`Unblacklist` is clicked, an :guilabel:`Are you sure you want to unblacklist this

```

2024-03-04 16:07 UTC, samueljlieber requested changes
Hi @ksc-odoo! Awesome job on the improvements in this PR, your changes are looking pretty great! I have a few suggestions for greater clarity and to correct a few points. Please see below, tag me for another quick look once these have been addressed. Thank you!

2024-03-04 16:07 UTC, samueljlieber commented on content/applications/marketing/email_marketing/unsubscriptions.rst
Add a note for more context on what blacklisted emails mean for the database as a whole
```suggestion
.. note::
   Blacklisted emails are excluded from all marketing mailings, however, these emails can still
   receive transactional emails, such as order confirmations, shipping notifications, etc.

```

2024-03-07 20:42 UTC, ksc-odoo commented
Alrighty, @samueljlieber -- just made all your suggested changes, and it's ready for another look from you whenever you get a chance. Thanks!

2024-03-07 21:54 UTC, samueljlieber approved these changes
Hi @ksc-odoo! Thanks for implementing my suggestions, this doc is looking good to me! There is one small nitpick I have, if you don't mind addressing:

Update the seealso: doc paths to be relative 🙏
```
.. seealso::
   - :doc:`../email_marketing`
   - :doc:`mailing_lists`
```

I am approving now, and you can tag ZST whenever you are ready. Thank you!

2024-03-08 17:33 UTC, ksc-odoo commented
Thanks for the always-helpful feedback, @samueljlieber -- I made that last adjustment, and believe this one is now ready for @StraubCreative 👍

2024-03-21 23:55 UTC, StraubCreative approved these changes
Approved, thanks @ksc-odoo 👍 
...
@robodoo r+

2024-03-22 03:11 UTC, closed without merging