[IMP] accounting/l10n_cl: adding and improving electronic purchase in…
odoo/documentation pull request #7893
Opened 2024-02-27 00:36 UTC by masi-odoo

…voice

Google Drive image folder: https://drive.google.com/drive/folders/12OaeDvzn-u5Nf_AjhIzrWaZWEb7smlTL?usp=drive_link

2024-02-27 00:37 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/7893).

2024-03-07 22:10 UTC, samueljlieber approved these changes
Hi @masi-odoo, nice job on getting this PR started, please see the suggestions and corrections I made to your changes. I will push up a commit after this review!

2024-03-07 22:10 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/chile.rst
> +
```suggestion
Generate an electronic purchase invoice
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

2024-03-07 22:10 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/chile.rst
> +:menuselection:`Accounting --> Vendors --> Bills`, and click the :guilabel:`New` button.
```suggestion
To generate this type of document, it is necessary to create a vendor bill in Odoo. To do so,
navigate to :menuselection:`Accounting --> Vendors --> Bills`, and click the :guilabel:`New` button.
```

2024-03-07 22:10 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/chile.rst
> +Purchase Invoice* in the :guilabel:`Document Type` field:
```suggestion
When all of the electronic purchase invoice information is filled, select the option :guilabel:`(46)
Electronic Purchase Invoice` in the :guilabel:`Document Type` field:
```

2024-03-07 22:10 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/chile.rst
> +- The DTE SII Status is set as Pending to be sent.
```suggestion
- The :abbr:`DTE (Documentos Tributarios Electrónicos)` file (Electronic Tax Document) is
  automatically created and added to the chatter.
- The :guilabel:`DTE SII Status` is set as :guilabel:`Pending to be sent`.
```

2024-03-07 22:10 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/chile.rst
> +To get a response from the SII immediately, press the :guilabel:`Send now to SII` button.
```suggestion
The *DTE Status* is automatically updated by Odoo with a scheduled action that runs every day at
night. To get a response from the :abbr:`SII (Servicio de Impuestos Internos)` immediately, press
the :guilabel:`Send now to SII` button.
```

2024-03-07 22:10 UTC, samueljlieber commented on content/applications/finance/fiscal_localizations/chile.rst
> +   :alt: Selecting document type 46 in a vendor bill
I dont think that this image is needed since the instructions are descriptive enough :)
```suggestion
```

2024-03-11 12:48 UTC, dade-odoo requested changes
Hi @masi-odoo and @samueljlieber ! Thanks for your addition to the Chilean localization! Overall it looks great - just a few comments from me before we pass it on to the final review :) Let me know if you have any questions!

2024-03-11 12:48 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +When all of the electronic purchase invoice information is filled, select the option :guilabel:`(46)
I suggest mentioning that this field is found in the Cross Reference Documents tab. Also, in the runbot that I looked at, the field is called `SII Doc Type Selector`, not just `Document Type`

2024-03-12 09:37 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +When all of the electronic purchase invoice information is filled, select the option :guilabel:`(46)
Ah, my mistake. Thanks :)

2024-03-12 09:43 UTC, dade-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +To create a purchase journal, navigate to :menuselection:`Accounting --> Configuration -->
Make sure to respect the 100 character limit per line and otherwise this looks great :)

2024-03-12 13:38 UTC, samueljlieber commented
Thank you so much @dade-odoo, @masi-odoo and I implemented your suggestions in bb0c6d2. Ready for another look, thank you! :)

2024-03-12 15:46 UTC, dade-odoo commented
@samueljlieber @masi-odoo Looks good to me, thanks! I'll request a final review and it should be good to go :)

2024-03-19 15:10 UTC, xpl-odoo reviewed
@robodoo delegate+
Just two minor suggestions ;)

2024-03-19 15:10 UTC, xpl-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +- :guilabel:`Use Documents`: check this field for the journal to be able to generate electronic
```suggestion
- :guilabel:`Use Documents`: check this field so the journal can generate electronic
```
Suggestion to make it easier to read

2024-03-19 15:10 UTC, xpl-odoo commented on content/applications/finance/fiscal_localizations/chile.rst
> +get a response from the :abbr:`SII (Servicio de Impuestos Internos)` immediately, click the
```suggestion
Odoo automatically updates the DTE Status every night using a scheduled action. To
get a response from the :abbr:`SII (Servicio de Impuestos Internos)` immediately, click the
```
Suggestion to make it easier to read.

2024-03-19 16:24 UTC, samueljlieber commented
Thank you @xpl-odoo, I implemented your suggestions in 7de2359, and will merge after the CI checks pass! :)

2024-03-20 15:57 UTC, masi-odoo commented
@robodoo r+

2024-03-20 17:50 UTC, closed without merging