[IMP] accounting: add extra taxes
odoo/documentation pull request #8076
Opened 2024-03-08 13:50 UTC by toaa-odoo

Extra taxes (ecotax, luxury, etc) are currently missing from doc

Forward to master.

taskid-3794931

2024-03-08 13:50 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8076).

2024-03-12 09:14 UTC, Donapi commented on content/applications/finance/accounting/taxes.rst
> +   check your country's regulations to know how to compute them for your business.
```suggestion
   The method of computing these taxes varies across different countries. We recommend consulting your country's regulations to understand how to calculate them for your business.

2024-03-12 09:18 UTC, Donapi commented on content/applications/finance/accounting/taxes.rst
> +imposed by governments. These extra taxes can be **luxury** taxes, **environmental** taxes,
Below, you speak about ecotax; is it another name for the environmental tax? Should we always use the same name to refer to this tax?

2024-03-12 09:21 UTC, Donapi commented on content/applications/finance/accounting/taxes.rst
> +Therefore, our ecotax has to come *before* the sales tax in the computation sequence.
I understand what you mean by *before*, but I'm not sure how it is explained is 100% clear... we can discuss IRL

2024-03-12 09:29 UTC, Donapi commented on content/applications/finance/accounting/taxes.rst
> +Therefore, our ecotax has to come *before* the sales tax in the computation sequence.
Would it makes sens to move this paragraph below (or even in the example section?): 
First, we explain how to do it in Odoo, in general, and then we give an example of how we do it in Belgium?

2024-03-12 09:30 UTC, Donapi commented on content/applications/finance/accounting/taxes.rst
> +To do so, :ref:`create a tax <taxes/configuration>`, enter a tax name, select a
```suggestion
To compute an extra tax in Odoo, :ref:`create a tax <taxes/configuration>`, enter a tax name, select a
```

2024-03-12 14:59 UTC, Donapi approved these changes
Excellent work, son!

2024-03-14 10:48 UTC, jcs-odoo requested changes
A small improvement, then it will be good to go.

Thanks!

2024-03-14 10:48 UTC, jcs-odoo commented on content/applications/finance/accounting/taxes.rst
> +order the tax according to the computation order of your country.
This last sentence is super important but not clear enough, in my opinion.

It's worth explaining that the sequence order of the taxes as they are listed in the taxes list view is what is going to define the computation order. The example below then reinforces super well the info.

2024-03-21 09:51 UTC, jcs-odoo approved these changes
@robodoo r+

2024-03-21 23:02 UTC, closed without merging