[IMP] Link trackers: updating content
odoo/documentation pull request #8170
Opened 2024-03-15 13:07 UTC by Donapi

[taskid-3754778](https://www.odoo.com/web#id=3754778&cids=1&model=project.task&view_type=form)

2024-03-15 13:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8170).

2024-03-19 09:37 UTC, masp-odoo reviewed
Hello @Donapi, une toute petite suggestion :)
Beau travail sinon !

2024-03-19 09:37 UTC, masp-odoo commented on content/applications/websites/website/reporting/link_tracker.rst
> +   :doc:`Building blocks <../web_design/building_blocks>`
Hello, je mettrais peut-être juste le lien avec l'ancre qui emmène directement à la visibility des building blocks :)
https://www.odoo.com/documentation/17.0/applications/websites/website/web_design/building_blocks.html#visibility

2024-03-19 13:00 UTC, Donapi commented on content/applications/websites/website/reporting/link_tracker.rst
> +   :doc:`Building blocks <../web_design/building_blocks>`
J'ai mis le lien sur "visibilty" dans le paragraphe juste avant, bonne suggestion :)

2024-03-25 13:27 UTC, xpl-odoo requested changes

2024-03-25 13:27 UTC, xpl-odoo commented on content/applications/websites/website/reporting/link_tracker.rst
> +The :abbr:`UTM (Urchin Tracking Module)` parameters allow you to display some site elements only for
I wouldn't say it's the UTM parameters that _allow you_ to do something.
I would say that you can hide/show elements according to the UTM parameters.

2024-03-25 13:27 UTC, xpl-odoo commented on content/applications/websites/website/reporting/link_tracker.rst
> +Your tracked links
```suggestion
Tracked links overview
```

2024-03-25 13:27 UTC, xpl-odoo commented on content/applications/websites/website/reporting/link_tracker.rst
> +website through the tracked link.
```suggestion
```
Already mentioned in the intro, maybe just add "To measure the performance of the tracked links,..."

2024-03-28 10:11 UTC, Donapi commented on content/applications/websites/website/reporting/link_tracker.rst
> +channels bring you the most visitors and make informed decisions.
updated

2024-03-28 11:27 UTC, Donapi commented on content/applications/websites/website/reporting/link_tracker.rst
> +Create a traceable URL
updated

2024-03-28 11:37 UTC, Donapi commented on content/applications/websites/website/reporting/link_tracker.rst
> +#. :guilabel:`Medium`: The channel to share your link, such as an email or a social media ad.
updated

2024-04-03 14:17 UTC, xpl-odoo commented
@robodoo r+

2024-04-03 16:25 UTC, closed without merging