[IMP] email comms: feedback loop edit
odoo/documentation pull request #8171
Opened 2024-03-15 14:03 UTC by tiku-odoo

Task: https://www.odoo.com/web#id=3714944&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

2024-03-15 14:04 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8171).

2024-03-15 14:12 UTC, tiku-odoo commented
@StraubCreative 

This is a small change, brought to my attention by a consultant in BE. The original system parameters given to me for this change were incorrect.

Confirmed with mail expert.

CC: @lma-odoo

2024-03-18 23:21 UTC, StraubCreative requested changes

2024-03-18 23:21 UTC, StraubCreative commented on content/applications/general/email_communication/email_servers.rst
> +this alias is allowed to create in the given period of time (value of `mail.gateway.loop.minutes`).
early line breaks
```suggestion
`mail.gateway.loop.minutes`. If the received email was sent to an alias then Odoo will reference the
`mail.gateway.loop.threshold` system parameter and determine the value as the number of records this
alias is allowed to create in the given period of time (value of `mail.gateway.loop.minutes`).
```

2024-03-19 14:11 UTC, tiku-odoo commented
@StraubCreative 

This PR is now ready for merge. 

Thanks. Tim :+1:

2024-03-20 20:39 UTC, StraubCreative approved these changes
Thanks @tiku-odoo 👍 
...
@robodoo r+

2024-03-20 21:56 UTC, closed without merging