[ADD] Website: features blocks
odoo/documentation pull request #8173
Opened 2024-03-15 15:21 UTC by Donapi

taskid-3733828

2024-03-15 15:22 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8173).

2024-03-21 10:17 UTC, chiaraprattico requested changes
Hi @Donapi it seems like you have a conflict, the branch might not be up to date. 

![image](https://github.com/odoo/documentation/assets/95279572/f09ea72a-a924-4d33-b628-13673f3a5678)

2024-03-21 10:17 UTC, chiaraprattico commented on content/applications/websites/website/web_design/building_blocks/features_blocks.rst
> +content. This documentation presents the :guilabel:`Table of content` building block.
This documentation presents the :guilabel:`Table of content` building block.


Presenting it this way it's not typical documentation style. Instead I would say: among different feature blocks, there is the :guilabel:`Table of content` building block --> Explain a little what it does and why we mention it here (one line)

2024-03-21 10:17 UTC, chiaraprattico commented on content/applications/websites/website/web_design/building_blocks/features_blocks.rst
> +You can add a :guilabel:`Table of content` building block to your website by dragging and dropping
I would link this page here so they can know the more general setting on how to add blocks https://runbot137.odoo.com/runbot/static/build/59908338-17-0/logs/build/html/applications/websites/website/web_design/building_blocks.html

2024-03-21 10:17 UTC, chiaraprattico commented on content/applications/websites/website/web_design/building_blocks/features_blocks.rst
> +   :alt: Displaying the table of content building block
do you think we need to see the whole screen, maybe the edit options on the right are not useful, not sure, but I feel like it's not focusing on the H titles on the left

2024-03-29 12:31 UTC, Donapi reviewed
Thanks for your review, let's discuss IRL if you want :)

2024-05-03 11:46 UTC, xpl-odoo commented
@robodoo r+

2024-05-03 15:27 UTC, closed without merging