[ADD] website: dynamic content
odoo/documentation pull request #8205
Opened 2024-03-19 12:32 UTC by Donapi

taskid-3733885

2024-03-19 12:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8205).

2024-04-09 13:01 UTC, xpl-odoo requested changes
We can through my review together if you would like :)

2024-04-15 12:57 UTC, Donapi commented on content/applications/websites/website/web_design/building_blocks/dynamic_content.rst
> +:guilabel:`Custom Field`, or scroll down to choose an :guilabel:`Existing Field`.
It was explained in the note right below, I removed the note and explained it directly in the text :)

2024-04-16 11:59 UTC, xpl-odoo commented
@robodoo r+

2024-04-16 14:12 UTC, closed without merging