[ADD] surveys: created survey analysis doc for 17
odoo/documentation pull request #8398
Opened 2024-03-27 16:34 UTC by ksc-odoo

PROJECT TASK: https://www.odoo.com/web#id=3835022&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

- This is a brand new, from-scratch doc to cover Survey Analysis in the Surveys application.

2024-03-27 16:36 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8398).

2024-03-28 18:03 UTC, jero-odoo requested changes
Hey @ksc-odoo great job on this doc! I had a few comments, a few are grammar/spelling corrections but a lot are suggestions so you can do with them what you choose! Let me know when you are ready for me to take another look :+1:

2024-03-28 18:03 UTC, jero-odoo commented on content/applications/marketing/surveys/analysis.rst
> +details, along with their submitted answers.
```suggestion
Here, users can view information related to individual participants who took that specific survey.
If they desire to see a more detailed breakdown of their various answers and responses, they can
click on any participant, and Odoo reveals a separate page showing that participant's survey
details, along with their submitted answers.
```

2024-03-28 18:03 UTC, jero-odoo commented on content/applications/marketing/surveys/analysis.rst
> +participants, along with their response-related data for that survey appears on the page.
```suggestion
participants, along with their response-related data for that survey, appear on the page.
```

2024-04-08 22:04 UTC, ksc-odoo commented on content/applications/marketing/surveys/analysis.rst
> +(checkmark)` icon next to the right answer option, in the legend above the graph.
That's a GREAT point! Thanks for the suggestion!

2024-04-08 22:12 UTC, ksc-odoo commented
Thanks for all the awesome suggestions, @jero-odoo -- I implemented all your edits, and think this is ready for another look from you, whenever you get a chance. Thanks again! 👍

2024-04-09 12:19 UTC, jero-odoo commented
@ksc-odoo Looks good to me! ready for the next round :+1:

2024-04-09 15:23 UTC, ksc-odoo commented
Thanks, @jero-odoo -- This one's ready for Tech Review @samueljlieber 👍

2024-04-09 21:19 UTC, samueljlieber approved these changes
Nice job @ksc-odoo, Im approving and pushing up a commit quickly resolving a merge conflict on `surveys.rst` from #8381. 👍
.....

2024-04-10 00:46 UTC, closed without merging