[IMP] marketing automation: workflow activities
odoo/documentation pull request #8527
Opened 2024-04-03 19:47 UTC by samueljlieber

Task: [#3699212](https://www.odoo.com/web#id=3699212&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form)

This PR improves the content of the `workflow_activities.rst` doc for 17.0 updates and expanded details for creating activities.

`marketing_automation.rst` was also updated to include references to `workflow_activities.rst` and a small correction.

2024-04-03 19:48 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8527).

2024-04-03 19:49 UTC, samueljlieber commented
Hi @ksc-odoo this doc is ready for a peer/content review whenever you get a chance, thank you! :)

2024-04-05 21:17 UTC, ksc-odoo requested changes
Hey @samueljlieber -- just finished my Final Review of this doc. Great job. Super detailed and in-depth! Once you implement the necessary changes, feel free to tag me agianf or another quick look. Thanks! 👍 

REMEMBER: fix all modal mentions and add 'app' when necessary to menuselections

2024-04-05 21:17 UTC, ksc-odoo commented on content/applications/marketing/marketing_automation/workflow_activities.rst
> +to the :guilabel:`Create Activities` modal and continue to configure the :ref:`trigger
```suggestion
to the :guilabel:`Create Activities` modal, in order to configure the :ref:`trigger
```

2024-04-05 21:17 UTC, ksc-odoo commented on content/applications/marketing/marketing_automation/workflow_activities.rst
> +(e.g., `2` is valid, `0` is also valid, and `1.5` is not).
```suggestion
(e.g. `2` is valid, `0` is also valid, and `1.5` is not).
```

2024-04-05 21:17 UTC, ksc-odoo commented on content/applications/marketing/marketing_automation/workflow_activities.rst
> +pre-filled with the selected trigger type and the and :guilabel:`Activity` field has the parent
```suggestion
pre-filled with the selected trigger type, and the :guilabel:`Activity` field has the parent
```

2024-04-09 14:40 UTC, StraubCreative commented on content/applications/marketing/marketing_automation/workflow_activities.rst
> +Automation --> Campaigns` dashboard, then clicking the :guilabel:`Add new activity` button. Doing so
I don't recall this being a strict guideline? IIRC this is up to the writer whether or not they want to do this.

2024-04-10 12:57 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/workflow_activities.rst
> +Automation --> Campaigns` dashboard, then clicking the :guilabel:`Add new activity` button. Doing so
That is how I recall [the conversation](https://docs.google.com/document/d/1laiWC9ow0IjXPuQp5h8L_Tj98HbE8ymGn9v-FFOwlYM/edit) as well, that it is up to the writer. However, I do like being precise so I will change every instance to include 'app' like KSC is suggesting :)

2024-04-10 13:02 UTC, samueljlieber commented on content/applications/marketing/marketing_automation/workflow_activities.rst
> +Create a Template...` in the :guilabel:`Mail Template` field is available.
I totally agree, I got carried away with the create flow 😄 I will modify this to be exact 👍

2024-04-10 13:59 UTC, samueljlieber commented
Thank you so much @ksc-odoo for your review, your suggestions were very helpful and I'm happy with the direction this doc is heading. This PR should be ready for another look when you have a chance. Thanks again!

2024-04-10 20:42 UTC, ksc-odoo approved these changes
Looking good, @samueljlieber 👍 just one, super minor adjustment needed. But, once that's taken care of, feel free to move this to the next stage! Nicely done 👏

2024-04-10 20:42 UTC, ksc-odoo commented on content/applications/marketing/marketing_automation/workflow_activities.rst
> +The activity that triggers a child activity is known as it's *parent activity*.
```suggestion
The activity that triggers a child activity is known as its *parent activity*.
```

2024-04-13 01:25 UTC, StraubCreative commented
Remaining CR implemented on [6a45381](https://github.com/odoo/documentation/pull/8527/commits/6a4538139c684c697b336613a75a97dea72efac0).

2024-04-18 19:31 UTC, StraubCreative approved these changes
Looks good, thanks @samueljlieber 
@robodoo r+

2024-04-18 22:45 UTC, closed without merging