[IMP] accounting/l10n_ec: point of sale invoicing
odoo/documentation pull request #8962
Opened 2024-04-24 17:52 UTC by rps-odoo

Task: [#3864339](https://www.odoo.com/web?debug=1#id=3864339&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form)
Link to GDrive images folder: https://drive.google.com/drive/folders/1S5XmaPh2vnTgJAXB26PgBpnuvVgaxOL9?usp=drive_link

2024-04-24 17:53 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/8962).

2024-04-24 21:26 UTC, samueljlieber approved these changes
Hi @rps-odoo, thanks again for the PR! I implemented 2/4 of your images and made a few small RST syntax edits in 5d25f4d. This PR should now be ready for review. :)

2024-05-13 18:52 UTC, samueljlieber commented
b3de21d Rebased to resolve a conflict due to #8522 adding the **eCommerce** section to `ecuador.rst`

2024-05-14 08:28 UTC, dade-odoo approved these changes
I'm passing this on to the PoS master @LoredanaLrpz since she handles PoS documentation, but if you need anything from the accounting team, feel free to reach out!

2024-05-28 20:18 UTC, rps-odoo commented
Hi @LoredanaLrpz hope you are doing good! Do you got any updates/comments on this document PR? Thanks! cc @samueljlieber

2024-06-27 12:36 UTC, LoredanaLrpz requested changes
Hey @rps-odoo, thank you for your work, and sorry for the delay.
Here's my review and suggestions :)
Have a nice day!

2024-06-27 12:36 UTC, LoredanaLrpz commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +   configurations are all set, this feature will cover the next invoicing flows.
A verification exists to verify sounds weird to me; you also mention a feature: do you mean a feature checks the identification number length? 
Also, I get that Cédula and RUC are mentioned as examples? It looks like a very short list. Or maybe the verification feature only covers these two?

2024-06-27 12:36 UTC, LoredanaLrpz commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +contact for the order as the *Consumidor Final* and generates an electronic invoice.
```suggestion
When clients do not request an electronic invoice for their purchase, Odoo automatically sets the
customer as :guilabel:`Consumidor Final` and generates an electronic invoice anyway.
```

2024-06-27 12:36 UTC, LoredanaLrpz commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +   configurations are all set, this feature will cover the next invoicing flows.
```suggestion
As the identification number length differs depending on the identification type, Odoo automatically checks the :guilabel:`Tax ID` field upon saving the customer form. To manually ensure the length is correct, know that the :guilabel:`RUC` and :guilabel:`Citizenship` types require 13 and 10 digits respectively.

```

2024-06-27 12:36 UTC, LoredanaLrpz commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +information.
```suggestion
contact with their fiscal information. This ensures the invoice is generated with accurate customer details.
```

2024-06-27 12:36 UTC, LoredanaLrpz commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +If a customer requests an invoice during the sales, it is possible to select or create the required
```suggestion
If a customer requests an invoice during the sales, it is possible to select or create a
```

2024-07-02 16:09 UTC, samueljlieber commented
Thank you @LoredanaLrpz for your helpful review! I implemented most of your suggestions in e158e73. 

@rps-odoo can you help me with this remaining one: https://github.com/odoo/documentation/pull/8962#discussion_r1656948762

2024-07-08 16:16 UTC, rps-odoo commented on content/applications/finance/fiscal_localizations/ecuador.rst
> +identification and identification number.
Thanks for the suggestion @LoredanaLrpz . Identificación type is the field called 'Tax ID'. We can implement the following:

The POS cashier will be able to create a new contact for a customer who requests an invoice from an open session. Please refer to this documentation.

.. documentation: https://www.odoo.com/documentation/17.0/applications/sales/point_of_sale.html#set-customers

The *Ecuadorian Module for Point of Sale* adds two new fields to the contact creation form: :guilabel:`Identification Type` and :guilabel:`Tax ID`.

@samueljlieber let me know if my comment is clear :)

2024-07-09 14:30 UTC, samueljlieber commented
Thank you @rps-odoo, I implemented [your change](https://github.com/odoo/documentation/pull/8962#discussion_r1668931106) in b679428 as well as added a seealso to link to the POS documentation on receipts and invoices in the QR code section. 

@LoredanaLrpz this PR is ready for another look, TIA 🙏

2024-07-12 07:43 UTC, auva-odoo approved these changes
Since @LoredanaLrpz is currently off, I reviewed her comments and made some changes accordingly. I also took the opportunity to fix a few minor issues in the eCommerce workflow section just above. I hope you don't mind.

If you’re okay with my changes, you can r+ whenever you're ready. Thanks again!

@robodoo delegate+

2024-07-25 18:40 UTC, samueljlieber commented
@robodoo r+

2024-07-25 21:15 UTC, closed without merging