[ADD] email marketing: analyze metrics
odoo/documentation pull request #9025
Opened 2024-04-26 15:21 UTC by jero-odoo

Creating a new doc to outline how to analyze metrics in the email marketing app
Docs task: https://www.odoo.com/mail/view?model=project.task&res_id=3894022&access_token=d13dbf1e-c5cd-4052-92ec-c8031481e5b9

2024-04-26 15:21 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9025).

2024-05-01 20:00 UTC, jero-odoo commented
Hey @larm-odoo this one is ready for your review. Thanks!

2024-05-02 16:05 UTC, larm-odoo reviewed
Nice new doc! I love it- it's great info to share. I had just a general suggestion, and then some questions on the app itself/what can be included. Might be worth a suggestion to the product owner as well (I didn't see any 'unsubscribe' numbers, or 'report as spam'- which I think is important). Ping me again when you're done, just because I am curious to the answers, and would love to read it again.

2024-05-02 16:30 UTC, jero-odoo commented on content/applications/marketing/email_marketing/analyze_metrics.rst
> +
There is another doc that handles that (https://www.odoo.com/documentation/17.0/applications/marketing/email_marketing/unsubscriptions.html)

2024-05-02 16:39 UTC, jero-odoo commented on content/applications/marketing/email_marketing/analyze_metrics.rst
> +Combining metrics
again, there is another doc on the unsubscribe/blacklisting. I will add a seealso link to it :+1:

2024-05-02 19:25 UTC, jero-odoo commented
This is ready for tech/final. Thanks!

2024-05-03 15:47 UTC, samueljlieber requested changes
Hi @jero-odoo, thank you for this addition to the email marketing documentation! I am excited to see more content being added here, especially in regards to reporting/analyzing mass mailings. 

While this is a great start on analyzing email marketing metrics, there is some duplicate content in this doc, some strong assumptions made about mailings, and some missing information.

I also ended up with several suggestions around restructuring the content in this doc and found it easier to just make a commit with these changes. So please find the second commit with my changes for your consideration.

Here is a brief summery of my changes and suggestions:
- Remove the **Key metrics** section and combine the metric definitions with each in the **Analyze metrics** section. 
- Remove **Individual metrics** heading and move each metric heading up a heading level.
- Make less definite assumptions as to why an email may have a specific open, replied, clicked, received, or bounced rate as there are many reasons for each. Instead, I suggest using terms like "may indicate" or "could suggest".
- Add a **Deliverability issues** section to detail technical reasons for a high bounce rate or low received rate.
- Add sections for the following metrics that are missing: Sent, Ignored, and Link Tracker. (Bonus probably in another PR in the future: Opportunities, Quotations, and Invoiced?)
- I think the **Combining metrics** is a cool idea, but due to the many possible reasons for each combination– I think it is best to not include this section, sticking to the individual metric definitions instead.

I understand these are a lot of changes, but I don't feel that this doc in it's current state is ready to go live for my reasons above. Please let me know your thoughts and if you want to workshop anything, I'm more than happy to!

Please tag me for another look once you revise this PR, thanks for your continued hard work on this 🙏

2024-05-03 18:44 UTC, jero-odoo commented
Hey @samueljlieber thank you for all the work you did on this, I just had to make a few tweaks.
I understand wanting to limit the content to the barest essentials. However, I was hoping to include a few samples of the combined metrics to show how the varied results can be interpreted. And while yes, it is obviously based on assumptions more than hard facts, I don't think that would be out of line. I am fine merging it the way it is now, but I would like to consider expanding it in the future if there is a way to demonstrate that and focus on more potential real-life use cases. I would be happy to workshop that further. For now, I am ok with going forward as is.

Also:
-Add sections for the following metrics that are missing: Sent, Ignored, and Link Tracker. (Bonus probably in another PR in the future: Opportunities, Quotations, and Invoiced?)
Sent I don't know that I would consider this a metric perse, since it is simply a data point.
Ignored would be interesting to include, but I am not sure the best place to utilize it in the app
Link tracker specifically, I think, would be interesting on its own since there are a lot of avenues to explore with it.

2024-05-03 19:45 UTC, samueljlieber approved these changes
Thank you @jero-odoo for taking my suggestions into consideration, this PR is looking great! I am also comfortable merging as-is, but I agree with you there are a lot of opportunities here to improve and expand, especially with use-cases.

> I was hoping to include a few samples of the combined metrics to show how the varied results can be interpreted. And while yes, it is obviously based on assumptions more than hard facts, I don't think that would be out of line.

I completely agree, I think some assumptions have to be made. I just think we need to workshop framing the use-cases a little more in order to provide relevant examples. This should be a fun [IMP] to make in the near future 🙂

> Add sections for the following metrics that are missing: Sent, Ignored, and Link Tracker.

I believe **Sent** and **Ignored** are important to include since it defines the _total_ at which the other metrics are measured by, as well the **Ignored** smart button takes you to the Mailing Traces which show **Status** and **Failure Type** reasons for why a contact wasnt included in the mailing. See [this code](https://github.com/odoo/odoo/blob/855dc878a2c8abc594fc01d244bac10139b61702/addons/mass_mailing/models/mailing.py#L338) for how _total_ is calculated. 

I suppose **Link Tracker** could be its own doc possibly?

Either way, lets merge as is and note this for improvements down the road 🙂 👍
.....
@robodoo r+

2024-05-03 21:34 UTC, closed without merging