[IMP] sales: amazon connector add disclaimer block
odoo/documentation pull request #9055
Opened 2024-04-29 16:42 UTC by tiku-odoo

Task: 

https://www.odoo.com/web#id=3861792&cids=3&model=project.task&view_type=form

2024-04-29 16:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9055).

2024-04-29 16:47 UTC, tiku-odoo commented
@StraubCreative 

This PR is ready for your review/merge. 

It's the addition of a short warning block advising sellers that customer information will no longer be transmitted to Odoo on orders fulfilled by Amazon. 

Thanks, 
Tim :+1:

2024-04-30 17:43 UTC, tiku-odoo commented
@ksc-odoo 

When you have a moment, can you review this very short paragraph PR?

Thanks,
Tim

2024-04-30 18:42 UTC, ksc-odoo approved these changes
Alrighty, @tiku-odoo -- just finished my Review. Only a few suggestions that require your attention. Approving now, though. Once you implement the necessary changes, feel free to tag this for the next step. Thanks! 👍

2024-04-30 18:42 UTC, ksc-odoo commented on content/applications/sales/sales/amazon_connector/features.rst
> +   created with the *Amazon connector*, do not get the customer name anymore. This is due to the
```suggestion
   created with the *Amazon Connector*, do **not** get the customer name anymore. This is due to the
```

2024-04-30 18:42 UTC, ksc-odoo commented on content/applications/sales/sales/amazon_connector/features.rst
> +   fact that Amazon now calculates and remits sales tax on behalf of sellers. In other words,
```suggestion
   fact that Amazon now calculates, and remits, sales tax on behalf of sellers. In other words,
```

2024-04-30 18:42 UTC, ksc-odoo commented on content/applications/sales/sales/amazon_connector/features.rst
> +The Amazon Connector currently supports 9 marketplaces. If a marketplace is not listed below, it may
```suggestion
The *Amazon Connector* currently supports 9 marketplaces. If a marketplace is not listed below, it may
```

2024-04-30 20:20 UTC, tiku-odoo commented
@StraubCreative 

This PR is ready for your review/merge.

Thanks,
Tim :+1:

2024-04-30 20:42 UTC, StraubCreative requested changes
Hi @tiku-odoo 

This looks like an important warning, thank you for adding it!

Given the gravity of the change with FBA, I want to make sure we're being as detailed as possible for our users here, so I left a couple comments for you to consider when you have time.

Please tag me again when it's ready for another look, thanks!

2024-04-30 20:42 UTC, StraubCreative commented on content/applications/sales/sales/amazon_connector/features.rst
> +   On February 19, 2024, in North American marketplaces, :abbr:`FBA (fulfilled by Amazon)` orders
Capitalization for the Amazon product, according to the [product overview](https://sell.amazon.com/fulfillment-by-amazon)
```suggestion
   On February 19, 2024, in North American marketplaces, :abbr:`FBA (Fulfilled by Amazon)` orders
```

2024-04-30 20:42 UTC, StraubCreative commented on content/applications/sales/sales/amazon_connector/features.rst
> +   created with the *Amazon Connector*, do not get the customer name anymore. This is due to the
Is it possible to be more specific here?

When we say orders "do not get the customer name anymore," does this mean Amazon does not pass the customer's name over to Sales/Delivery in Odoo anymore? What specifically is impacted from the user's perspective? Are there any changes or workarounds the user should know about?

2024-05-01 12:57 UTC, tiku-odoo commented
@Demesmaeker 

Hi Morgane, 

Can you review these changes? Is there anything we are missing? Is it just the name that is scrubbed? 

Thanks,
Tim :+1:

2024-05-01 14:21 UTC, tiku-odoo commented
@dalaOdoo 

When you have a moment can you review this change on the FBA orders using the Amazon Connector? 

Do you have any other details on this change?

2024-05-06 15:33 UTC, tiku-odoo commented
@StraubCreative 

I've confirmed with (edm) that the customer name is the information that won't be conveyed. 

This PR is ready for your review. 

Thanks, 
Tim

2024-05-06 18:47 UTC, StraubCreative approved these changes
looks good, thanks @tiku-odoo 
i'll push up remaining change(s) in a moment and merge

2024-05-06 18:47 UTC, StraubCreative commented on content/applications/sales/sales/amazon_connector/features.rst
> +   not transmitted to the seller any longer, after a :abbr:`FBA (fulfilled by Amazon)` order.
missed a capitalization
```suggestion
   not transmitted to the seller any longer, after a :abbr:`FBA (Fulfilled by Amazon)` order.
```

2024-05-06 19:18 UTC, StraubCreative commented
..
@robodoo r+

2024-05-06 20:52 UTC, closed without merging