[IMP] Rewrote sentences in the introduction portion for both sections
odoo/documentation pull request #923
Opened 2021-03-31 20:22 UTC by sdr-odoo

2021-04-09 08:17 UTC, xpl-odoo commented
When you write the commit message, don't forget to add the app name. i.e. **[IMP] Helpdesk:** _(this commit will)_ **fix the grammar in the introduction**
Don't forget to follow the instructions in the commit_template.txt which pops up when you do `git commit`

2021-04-09 09:16 UTC, xpl-odoo requested changes

2021-04-09 09:16 UTC, xpl-odoo commented on helpdesk/overview/forum_and_elearning.rst
>  ------
General comment: you should also seize the opportunity to add more content/be more in-depth or precise - if it seems necessary of course. For example, here you could add, after _Helpdesk --> Configuration --> Helpdesk Team_**, select a Helpdesk Team, and** enable Help Center.

2021-04-09 09:16 UTC, xpl-odoo commented on helpdesk/overview/forum_and_elearning.rst
>  ------
General comment: you should use the opportunity to update screenshots whenever visual differences are introduced. It seems to be the case here for the first screenshot (i.e. "The related forum is:" has been changed to "Related forum:" - I know, small difference, but still). Could you check all screenshots and take new ones where necessary?

2021-04-09 09:21 UTC, xpl-odoo commented
Note, if you only want to fix grammar/spelling issues, you should work on v13 (or even v12) - then we will forward port to v14 all the changes. Here I requested to update screenshots etc, so that wouldn't work, but if changes can apply across several versions, it's best to work on the oldest one.

2021-06-04 13:27 UTC, xpl-odoo requested changes
Good job Sammy!

I believe I understand why you didn't present the Forum and eLearning features in detail: they should be described (at some point) under their 'own' apps' documentation.
Your documentation would really benefit from having links to such docs, because as it is, it doesn't give much information on how to fully use the features.

Also, I will need you to take new screenshots (except the 1st one): most aren't really readable, especially on a smaller screen, but the problem persists on a large screen as well. I have made a relatively long comment about that on the rst's second screenshot.

Additionally:

- You should include the Odoo task number in the commit message (the .txt file you edit on PyCharm). [Here is where you can find it in the task URL](https://i.imgur.com/ICO6RN5.png). Yours for this task is: `2496840`
- And include a link to the Odoo task on GitHub (i.e. when you submit the PR message on GitHub, which uses your commit message as a basis)

2021-06-04 13:27 UTC, xpl-odoo commented on content/applications/services/helpdesk/overview/forum_and_elearning.rst
> +Click on the external link to create or edit an eLearning channel.
I had to select a "Related channel" first.

2021-06-04 13:27 UTC, xpl-odoo commented on content/applications/services/helpdesk/overview/forum_and_elearning.rst
> +Once the structure and content of your course are ready, *Publish* by clicking on *Unpublished*.
```suggestion
Once the structure and content of your course are ready, switch the page to *Published* by clicking on the *Unpublished* toggle button.
```

2021-06-04 13:27 UTC, xpl-odoo commented on content/applications/services/helpdesk/overview/forum_and_elearning.rst
> +.. image:: forum_and_elearning/eLearning-course-published.png
New screenshot needed.

2021-06-04 13:27 UTC, xpl-odoo commented on content/applications/services/helpdesk/overview/forum_and_elearning.rst
> +.. image:: forum_and_elearning/eLearning-app-statistics.png
New screenshot needed.

2021-06-04 13:27 UTC, xpl-odoo commented on content/applications/services/helpdesk/overview/forum_and_elearning.rst
>     :alt: View of the elearning applications dashboard for Odoo Helpdesk
```suggestion
   :alt: View of the eLearning applications dashboard for Odoo Helpdesk
```

2021-06-04 13:27 UTC, xpl-odoo commented on content/applications/services/helpdesk/overview/forum_and_elearning.rst
>           Odoo Helpdesk
```suggestion
   :alt: Overview of the settings page of a customer care team emphasizing the eLearning feature in
         Odoo Helpdesk
```

2021-06-04 13:27 UTC, xpl-odoo commented on content/applications/services/helpdesk/overview/forum_and_elearning.rst
> +statistics, attendees, views, reviews, and more.
```suggestion
Use the *eLearning app* for an overview of all your courses and to keep track of course
statistics, such as the number of attendees, views, reviews, and more.
```

2022-04-29 18:23 UTC, mivu-odoo commented
Hi @xpl-odoo I'm Michelle, the new writer in charge of Helpdesk docs. Sammy is no longer with Odoo. I noticed you said new screenshots are needed for this. Would you like to just close this PR? I can take the changes that Sammy was trying to make and carry it on a new PR.

2022-04-30 08:28 UTC, xpl-odoo commented
Hi @mivu-odoo !  Indeed, it's probably better to just close this PR and start from scratch :) I wouldn't focus too much on the changes introduced by Sammy though, but instead have your own mind on what could be improved globally, starting from the structure of the app's documentation.

2022-04-30 08:28 UTC, closed without merging

2022-04-30 08:30 UTC, robodoo commented
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

2022-04-30 08:30 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/923).