[IMP] Documents: share section to be improved
odoo/documentation pull request #9288
Opened 2024-05-10 09:57 UTC by Donapi

taskid-[3898917](https://www.odoo.com/web#id=3898917&cids=1&model=project.task&view_type=form)

Applicable  from 17 to 17.1

2024-05-10 09:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9288).

2024-05-10 11:27 UTC, toaa-odoo approved these changes

2024-05-17 06:33 UTC, auva-odoo requested changes
Hello @Donapi thank you for your work! I have a few comments and questions so let me know if you want to go through them together.
One general comment I also have regarding this whole doc page is that we could add the icons directly in the text instead of only describing them, now that it's possible https://www.odoo.com/documentation/master/contributing/documentation/rst_cheat_sheet.html#icons . I don't think this should be done in this PR, though, but it might be worth creating a task to do this (e.g., when we say "ellipsis icon", "plus icon", "scissors icon", etc.), possibly from 16.0? We can talk about it!

2024-05-17 06:33 UTC, auva-odoo commented on content/applications/productivity/documents.rst
> +You can check the :guilabel:`Create a new activity` box to automatically create an activity when a
```suggestion
Enable :guilabel:`Create a new activity` to automatically create an activity when a
```
for the sake of simplifying the sentence

2024-05-23 11:44 UTC, Donapi commented on content/applications/productivity/documents.rst
> +     dropdown list of the :guilabel:`Owner` field.
Thank you for the suggestion, it makes sense to me, I will keep it in mind :)

2024-05-23 12:30 UTC, Donapi commented on content/applications/productivity/documents.rst
> +:guilabel:`Contact`.
The requested person can indeed upload the document; however, I double-checked, and they do not become the Contact person for the document.

2024-05-23 12:40 UTC, Donapi commented on content/applications/productivity/documents.rst
> +:guilabel:`Contact`.
I tried to simplify the sentence.

2024-05-23 13:30 UTC, Donapi commented on content/applications/productivity/documents.rst
> +using the chosen tags to the workspace.
I absolutely agree. Updated accordingly.

2024-06-11 12:07 UTC, Donapi commented on content/applications/productivity/documents.rst
> +   An employee must be owner of a document to be able to see it in **My Profile**.
Feedback from FRGI: employees must be users to see a document.

2024-06-25 10:37 UTC, auva-odoo approved these changes
@Donapi I force-pushed 3 minor corrections, I hope that's okay :slightly_smiling_face: 
@robodoo r+

2024-06-25 13:25 UTC, closed without merging