[IMP] accounting: employment hero added taxes mapping descriptions
odoo/documentation pull request #9340
Opened 2024-05-14 10:11 UTC by tong-odoo

Impacted Versions:

- 17.0 and above

2024-05-14 14:23 UTC, dade-odoo approved these changes
Hey @tong-odoo thanks for forward porting to keep all the versions up to date! We're trying to reduce the number of screenshots where it's possible for a few reasons (they increase the load on the documentation site and they necessitate more frequent updates as there are minor UI changes).

If it is a necessary screenshot, that's okay! In that case, we're trying to minimize the red markups on screenshots as they are unnecessary, and emphasis on fields can be accomplished through effective cropping, and the explanation should be clear enough even without the screenshot.

I'll go ahead and approve and request the final review :) thanks!

2024-05-16 03:49 UTC, tong-odoo commented
@dade-odoo Thanks for the review! I will remove the screenshot then.

2024-05-16 08:40 UTC, auva-odoo requested changes
Hi @tong-odoo, just one small change. Thank you for your work!

2024-05-16 08:40 UTC, auva-odoo commented on content/applications/finance/fiscal_localizations/employment_hero.rst
> +   **Employment Hero** to :guilabel:`Matching Employment Hero Tax`.
```suggestion
   **Employment Hero** in the :guilabel:`Matching Employment Hero Tax` field.
```

2024-05-16 09:19 UTC, auva-odoo approved these changes
Thanks @tong-odoo! You can r+ whenever you're ready :slightly_smiling_face: 
@robodoo delegate+

2024-05-16 09:27 UTC, tong-odoo commented
@robodoo r+

2024-05-16 09:33 UTC, tong-odoo commented
Thank you @auva-odoo for your review. Could you take a look at this PR as well? This is basically the same but older version is using Australia to show the employment hero information.
https://github.com/odoo/documentation/pull/9339

2024-05-27 05:28 UTC, vin-odoo commented
Note: had to rebase

2024-06-06 09:55 UTC, tong-odoo commented
@robodoo r+

2024-06-06 15:41 UTC, closed without merging