[IMP] payment_xendit: tokenization
odoo/documentation pull request #9394
Opened 2024-05-17 02:19 UTC by nni-odoo

Tokenization is introduced in https://github.com/odoo/odoo/pull/158445 and needs extra configuration to setup for credit card payment. We require optional 3DS to be enabled and dynamic 3DS to be disabled

2024-05-17 02:20 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9394).

2024-05-17 07:38 UTC, auva-odoo requested changes
Hello @nni-odoo I suggested a small change to reflect the actual name of the page :slightly_smiling_face:

2024-05-17 07:38 UTC, auva-odoo commented on content/applications/finance/payment_providers/xendit.rst
> +   page and ensure that :guilabel:`Optional 3DS` is enabled while :guilabel:`Dynamic 3DS` is disabled
```suggestion
#. Navigate to the `Card Settings page <https://dashboard.xendit.co/settings/payment-methods/cards-configuration>`_
   and ensure that :guilabel:`Optional 3DS` is enabled while :guilabel:`Dynamic 3DS` is disabled.
```

2024-06-07 14:19 UTC, AntoineVDV commented
Hello @nni-odoo, if I'm not mistaken, we need to guide the user through configuring their webhooks now that we must listen to additional events. cc @auva-odoo

2024-06-18 08:02 UTC, nni-odoo commented
Hello @auva-odoo thank you for the feedback on this!

@AntoineVDV actually, there's no additional config from Xendit dashboard with the newly added feature (or at least I'm not using it)

2024-06-18 09:24 UTC, AntoineVDV commented
@nni-odoo I enabled a bunch of them now, so it's hard to say for sure, but I think I had to enable at least these webhooks to receive feedback on card payments. Could you please double-check so we make sure not to miss on anything?
![image](https://github.com/odoo/documentation/assets/15896813/d5de5392-8b40-4eed-843d-32da088626e2)

2024-06-19 03:04 UTC, nni-odoo commented
@AntoineVDV I've retested again on runbot (https://64109170-master-all.runbot148.odoo.com/) and I've cleared all the webhook config except "Invoices paid", it is still able to carry out all the flows as expected!

2024-07-12 07:55 UTC, auva-odoo commented
Hey @nni-odoo I noticed this hasn't been merged yet. @AntoineVDV  should it be rebased in 17.4 first?

2024-07-18 07:20 UTC, nni-odoo commented
apologies to those who got mentioned, I forgot to re-target the PR to 17.4 before rebasing it :cold_sweat:

2024-07-18 09:05 UTC, auva-odoo approved these changes
@robodoo r+

2024-07-18 11:03 UTC, closed without merging