[IMP] conf: automatically generate the sitemap.xml for SEO
odoo/documentation pull request #9441
Opened 2024-05-22 17:12 UTC by lse-odoo

WIP

Heavily inspired by:
https://github.com/jdillard/sphinx-sitemap/blob/master/sphinx_sitemap/__init__.py

2024-05-22 17:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9441).

2024-05-22 17:14 UTC, lse-odoo commented
TODO: check how odoo.com handle documentation generation. 
- How many times is it ran ? (avoid creating one sitemap per language for instance).
- Do they `make clean` before? (otherwise only the new links will be in the sitemap, thus losing the previous ones)

2024-05-23 13:46 UTC, Feyensv commented
@AntoineVDV I don't have access to the script anymore I think, but it'd probably be difficult to handle a sitemap of all versions and languages we build the doc for no?

2024-05-23 15:13 UTC, AntoineVDV commented
@Feyensv @lse-odoo to check with internal (MAT, JDE or JKE) for the details, but it runs every night for every version and for every language in each version.

2024-05-24 12:54 UTC, lse-odoo commented
thanks for the info @AntoineVDV :) would you mind reviewing the PR please ? maybe @Feyensv you would be interested as well if you have some time

2024-06-05 10:06 UTC, lse-odoo commented
@odoo/doc-review would you have some time to review it please ? :)

2024-06-24 09:36 UTC, lse-odoo commented
@Feyensv would you have some time to review it please ? :)

2024-06-24 09:40 UTC, Feyensv commented
Started reviewing it, but other priorities came up :c.
I'm keeping it in my todo list but dunno exactly when we'll be able to focus on it, probably not before the 17.4 freeze

2024-11-19 15:11 UTC, Feyensv reviewed
fixup commit to only build the sitemap when requested (is_remote_build), and to drop language-specific urls.
I'll go see with internal how they handle their sitemaps, and how we could integrate the documentation sitemaps.

2024-11-20 11:16 UTC, lse-odoo commented
@Feyensv ok! LGTM thanks for the review :)

2024-11-21 16:25 UTC, Feyensv requested changes
After some investigation with JKE, we don't think that this sitemap would be useful right now, at least not in its current state.

A sitemap is mostly a way to inform search engines of new entry points they are not aware of, for a given domain name.  Considering (nearly) all the links are already referenced on `odoo.com/documentation`, itself being referenced on `odoo.com`, a sitemap wouldn't help much (and looking for stuff on google already points to odoo documentation, in the latest version most of the time).

The biggest improvement a sitemap could bring would be to inform the search engines of the pages last modification date (`lastmod`), so that modified pages are prioritized when crawling content, so that it's refreshed in priority.  But this feature is not included in the current version of this PR, nor guaranteed to work (i suppose we'd have to rely on the file last modification date but it doesn't seem like github propagates that information).

2025-01-23 09:37 UTC, closed without merging