[IMP] Spreadsheets: updating main doc to add filter doc
odoo/documentation pull request #9522
Opened 2024-05-29 15:10 UTC by larm-odoo

Updating the main doc to streamline the links and update the image.  After updatng the main doc, a new FIlters doc is needed (Pr coming after this one).

2024-05-29 15:11 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9522).

2024-05-29 16:25 UTC, larm-odoo commented
Hi @brse-odoo - this is a super short PR, and is ready for a first round review. I am adding a new doc about filters specifically (I didn't realize I was oging to add a new doc till this was opened/started- which is why the eits are so minimal).

2024-05-29 16:55 UTC, brse-odoo approved these changes
@larm-odoo I've finished my review of this PR, great job! Approving with very few suggestions for you to accept/reject as you see fit. Let me know if you have any questions, thanks!

2024-05-29 16:55 UTC, brse-odoo commented on content/applications/productivity/spreadsheet.rst
> +Various functions that can be performed within a spreadsheet are:
```suggestion
Spreadsheets allow users to organize, analyze, and visualize data by compiling data sets into tables.
Various functions that can be performed within a spreadsheet are:
```

2024-05-29 16:55 UTC, brse-odoo commented on content/applications/productivity/spreadsheet.rst
> +Various functions that can be performed within a spreadsheet are:
Optional rewording for clarity!

2024-05-29 16:55 UTC, brse-odoo commented on content/applications/productivity/spreadsheet.rst
> +- Insert and :doc:`link Odoo data <spreadsheet/insert>` (pivots, graphs, lists, and menus) .
```suggestion
- Insert and :doc:`link Odoo data <spreadsheet/insert>` (pivots, graphs, lists, and menus).
```

2024-05-29 19:34 UTC, ksc-odoo approved these changes
Hey there, @larm-odoo -- just finished my Final Review. Only have a small comment that requires your feedback, other than that, this one is ready for Tech Review.

I fully understand, as you've communicated with me (via Discord), that this is the first part of a larger PR to come -- and that Fabrice, himself, personally requested this from you. Taking that into account, I'd say this one is good to go.

However, if I've mistaken that explanation, I'd suggest making this a bit more detailed/complex, and include some relevant use cases (as suggested in the 'Essentials' related email we all received from JUB recently). Also, I'd suggest (somehow) relating this to the 'Documents' application, as not every spreadsheet is built the *exact* same, so that sort of attention to detail may prove beneficial here for the reader.

Other than that, if you have any questions, don't hesitate to reach out. Thanks! 👍

2024-05-29 19:34 UTC, ksc-odoo commented on content/applications/productivity/spreadsheet.rst
> +Spreadsheets allow users to organize, analyze, and visualize data by compiling data sets into
```suggestion
Spreadsheets help organize, analyze, and visualize data by compiling data sets into
```

2024-06-04 19:49 UTC, larm-odoo commented
Hi @samueljlieber - this is ready for a tech review!

2024-06-04 20:47 UTC, samueljlieber requested changes
Hi @larm-odoo 👋 Thank you for your work, however I do have some critical feedback for you–
This changes in this PR, in its current state, are really not worth merging because the improvements are pretty much replacing pronoun use and an image— there really isnt any value added to the doc in this PR. And with this being a BE scope, pronoun use *is okay*. That being said– I'd like to see more value being added in these improvements, or feel free to close this PR if you dont plan on making these improvements yourself

2024-06-04 21:24 UTC, closed without merging