[ADD] IoT: New doc about how to connect a scale using the IoT box.
odoo/documentation pull request #958
Opened 2021-05-07 08:53 UTC by Lau-Odoo

Here is new documentation about connecting a [electronic] scale to the PoS app using an IoT box. 
The doc is good for 12.0 and after. Some new pieces of information could be added later to the latest version only.

2021-05-07 11:16 UTC, jcs-odoo requested changes
really nice :)

a few suggestions then it's good to go

2021-05-07 11:16 UTC, jcs-odoo commented on content/applications/productivity/iot/devices/scale.rst
> +and open a *Point of Sale* in the list. Once opened, edit it and check the *IoT Box* feature.
```suggestion
To use the scale in your *Point of Sale* app, go to :menuselection:`Point of Sale --> Configuration
--> Point of Sale`, open the one you want to configure, then click on *Edit* and enable the *IoT
Box* feature.

```

2021-05-07 11:16 UTC, jcs-odoo commented on content/applications/productivity/iot/devices/scale.rst
> +product and add the correct price to the cart.
nitpicking:
I know it's obvious that it's only the sessions of the configured PoS but you wxrite "all" pos sessions.

+

```suggestion
The scale is now available in all your *PoS* sessions. Then, if a product has a price per weight
set, clicking on it on the *PoS* screen opens the scale screen, where the cashier can weigh the
product and add the correct price to the cart.
```

2021-05-07 12:46 UTC, Lau-Odoo commented on content/applications/productivity/iot/devices/scale.rst
> +.. image:: scale/choix-iot.png
Pouahaha, sorry... 😆

2021-05-10 08:43 UTC, jcs-odoo approved these changes
lgtm 👍

2021-05-10 08:54 UTC, AntoineVDV approved these changes

2021-05-10 08:54 UTC, merged