[IMP] General: Change language
odoo/documentation pull request #9670
Opened 2024-06-06 12:06 UTC by Donapi

taskid-3964562

2024-06-06 12:07 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9670).

2024-06-20 10:51 UTC, auva-odoo requested changes
Hello @Donapi, thanks a lot for taking on this task, this doc really needed a refresh. I've left a few comments and suggestions :slightly_smiling_face: Let me know if you'd like to discuss them.

2024-06-21 09:08 UTC, Donapi commented on content/applications/general/users/language.rst
> +Your database's language is selected upon its creation. However, you can :ref:`add <language/add>`
Slightly updated, "You can select..." sounds to me like it's optional.

2024-06-21 09:51 UTC, Donapi commented on content/applications/general/users/language.rst
>  ===============
I updated as you suggested, but I would have used the singular since we can only switch to one language at a time.

2024-06-21 14:10 UTC, auva-odoo approved these changes
@Donapi you can r+ when all the checks have passed :slightly_smiling_face: 
@robodoo delegate+

2024-06-24 08:16 UTC, Donapi commented
@robodoo r+

2024-06-24 10:27 UTC, closed without merging