[FIX] point_of_sale: replace receipt image
odoo/documentation pull request #9703
Opened 2024-06-07 12:33 UTC by guga-odoo

task-3834714

2024-06-07 12:34 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9703).

2024-06-07 12:39 UTC, guga-odoo commented
@LoredanaLrpz Hi! For the sake of gaining experience in github I've just replaced the receipt. Can you check if everything's alright to you? Thank you!

2024-06-10 08:02 UTC, LoredanaLrpz requested changes
Hey @guga-odoo, the new screenshot looks great, but it appears larger. Could you make it about 75%? 
To do so, just add a line under `.. image::` with  `:scale: 75%` (like an `:alt:` for example) 
I'm not sure if 75% would be best, you'll have to try different percentages until you think it's good =)
Thank you! :)

2024-06-11 11:32 UTC, LoredanaLrpz approved these changes
Splendid

2024-06-11 14:39 UTC, closed without merging