[IMP] eCommerce: update digital files section + remove screenshots al…
odoo/documentation pull request #9848
Opened 2024-06-18 13:46 UTC by masp-odoo

…ignment

task:3997287

2024-06-18 13:47 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/documentation/pull/9848.png)](https://mergebot.odoo.com/odoo/documentation/pull/9848)

2024-06-28 09:03 UTC, masp-odoo commented
@masp-odoo il faut changer la version pour 17.2 + 17.3 + Master (task à part pour Master). 
17.0 + 17.1 sont identiques.

2024-07-09 14:00 UTC, auva-odoo requested changes
Dear @masp-odoo, here's my review after testing this more extensively. We should also definitely wait for feedback before we finalize this of course!
Also, I don't think we need to mention the MRP field in 17.2 + 17.3; it's not there unless Manufacturing is installed so shouldn't be mentioned here :slightly_smiling_face: 

Also, side note, but ideally, we try to keep the PR title under 50 characters if possible, could you please change it? Thank you!

2024-07-18 12:32 UTC, auva-odoo commented
Will be addressed in the ongoing restructure of the Products page; closing this for better management.

2024-07-18 12:32 UTC, closed without merging