[FIX] mail: how to choose allowed "From" addresses
odoo/documentation pull request #987
Opened 2021-05-25 07:21 UTC by Yajo

- Document changes from https://github.com/odoo/odoo/pull/69218.
- Explain that Office365 is now usable.

@Tecnativa TT29842

2021-05-25 12:44 UTC, std-odoo commented
@Yajo Good explanation :)

Note that this feature will be removed in master
(see https://www.odoo.com/web#id=2367946&action=333&active_id=965&model=project.task&view_type=form&cids=1&menu_id=4720 )

And a "smarter" behavior will be implemented

2021-05-25 15:21 UTC, AntoineVDV requested changes
Hello, please find below the few (nitpicking) comments that concern the technical aspect of your PR. Your line size limit of 80 chars is a bit overkill IMO ([100 is recommended for this repo](https://www.odoo.com/documentation/master/contributing/documentation/rst_guidelines.html#start-a-new-line-before-the-100th-character)) but it's fine as is. Pretty good RST apart from that ;)

2021-05-25 15:21 UTC, AntoineVDV commented on content/applications/productivity/discuss/email_servers.rst
> +<https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme>`__, you can enable it
```suggestion
<https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme>`_, you can enable it
```
See https://www.odoo.com/documentation/master/contributing/documentation/rst_guidelines.html#use-single-underscore-suffixes-for-hyperlink-references

2021-05-25 15:21 UTC, AntoineVDV commented on content/applications/productivity/discuss/email_servers.rst
> +      :align: center
```suggestion
       :align: center
```
Nitpicking: https://www.odoo.com/documentation/master/contributing/documentation/rst_guidelines.html#be-consistent-with-indentation

2021-05-26 09:36 UTC, Yajo commented
> Your line size limit of 80 chars is a bit overkill IMO ([100 is recommended for this repo](https://www.odoo.com/documentation/master/contributing/documentation/rst_guidelines.html#start-a-new-line-before-the-100th-character)) but it's fine as is.

You should consider adopting https://editorconfig.org/ (even better if combined with https://pre-commit.com) if you really care about this.

> Pretty good RST apart from that ;)

Thanks... RST is though. 😅

2021-05-26 09:42 UTC, AntoineVDV commented
> You should consider adopting https://editorconfig.org/ (even better if combined with https://pre-commit.com) if you really care about this.
@Yajo We'll soon integrate this repository with Odoo's runbot ;)

2021-05-26 09:48 UTC, AntoineVDV approved these changes

2021-05-26 09:49 UTC, merged

2021-05-26 09:49 UTC, AntoineVDV commented
Thank you for your contribution ;)

2021-06-15 09:28 UTC, Yajo commented
I don't see this change deployed, nor migrated to newer branches... is there something else to do?

2021-06-15 09:34 UTC, AntoineVDV commented
> I don't see this change deployed, nor migrated to newer branches... is there something else to do?

Hello, this change had indeed been deployed. See [here](https://www.odoo.com/documentation/14.0/applications/productivity/discuss/advanced/email_servers.html#choose-allowed-from-email-addresses) for example.

2021-06-16 08:08 UTC, Yajo commented
🤦🏼‍♂️ I don't know how I searched then. Thanks, sorry.